/* MS SQL Server Migration script from 3.1.0 to 3.2.0 */
/* $Id: migrate310to320.sql 658 2009-01-02 10:48:52Z friedj $ */

ALTER TABLE [TATTRIBUTEOPTION] ADD [SORTORDER] [int] NULL ;

DROP TABLE [TREPORTLAYOUT]
GO

CREATE TABLE [TREPORTLAYOUT] (
	[OBJECTID] [int] NOT NULL ,
	[PROJECTTYPE] [int] NULL ,
	[PROJECT] [int] NULL ,
	[PERSON] [int] NULL ,
	[REPORTFIELD] [int] NOT NULL ,
	[FPOSITION] [int] NOT NULL ,
	[FWIDTH] [int] NOT NULL ,
	[FSORTORDER] [int] NULL ,
	[FSORTDIR] [varchar] (1)  NULL 
) ON [PRIMARY]
GO


ALTER TABLE [TREPORTLAYOUT] ADD 
	CONSTRAINT [TREPORTLAYOUT_FK_1] FOREIGN KEY 
	(
		[PROJECTTYPE]
	) REFERENCES [TPROJECTTYPE] (
		[OBJECTID]
	),
	CONSTRAINT [TREPORTLAYOUT_FK_2] FOREIGN KEY 
	(
		[PROJECT]
	) REFERENCES [TPROJECT] (
		[PKEY]
	),
	CONSTRAINT [TREPORTLAYOUT_FK_3] FOREIGN KEY 
	(
		[PERSON]
	) REFERENCES [TPERSON] (
		[PKEY]
	),
	CONSTRAINT [TREPORTLAYOUT_FK_4] FOREIGN KEY 
	(
		[REPORTFIELD]
	) REFERENCES [TATTRIBUTE] (
		[OBJECTID]
	)
GO

/* Additional changes from 3.2.0 B1 to 3.2.0 B2 */

ALTER TABLE [TNOTIFY] ADD [RACIROLE] [varchar] (1) NULL ;
ALTER TABLE [TNOTIFY] ADD [THEGROUP] [INT] NULL ;

ALTER TABLE [TPERSON] ADD [EMPLOYEEID] [varchar] (30) NULL ;

ALTER TABLE TACCOUNT DROP CONSTRAINT TACCOUNT_FK_1;
ALTER TABLE TACCOUNT DROP COLUMN PROJECT;

ALTER TABLE TACCOUNT ADD ACCOUNTNAME VARCHAR (80);
ALTER TABLE TACCOUNT ADD ACTIVE VARCHAR (1);
ALTER TABLE TACCOUNT ADD COSTCENTER VARCHAR (20);

GO

ALTER TABLE TSITE ALTER COLUMN ALLOWEDEMAILPATTERN varchar(150) NULL;
GO
ALTER TABLE [TSITE] ADD [PREFERENCES] [varchar] (2000) NULL ;
GO

CREATE TABLE TPROJECTACCOUNT
(
                    ACCOUNT INT NOT NULL,
                    PROJECT INT NOT NULL,

    CONSTRAINT TPROJECTACCOUNT_PK PRIMARY KEY(ACCOUNT,PROJECT));

CREATE TABLE TGROUP
(
                    OBJECTID INT NOT NULL,
                    EMAIL VARCHAR (60) NULL,
                    PREFERENCES VARCHAR(7000) NULL,

    CONSTRAINT TGROUP_PK PRIMARY KEY(OBJECTID));

CREATE TABLE TGROUPMEMBER
(
                    OBJECTID INT NOT NULL,
                    THEGROUP INT NOT NULL,
                    PERSON INT NOT NULL,

    CONSTRAINT TGROUPMEMBER_PK PRIMARY KEY(OBJECTID));

BEGIN
ALTER TABLE TPROJECTACCOUNT
    ADD CONSTRAINT TPROJECTACCOUNT_FK_1 FOREIGN KEY (PROJECT)
    REFERENCES TPROJECT (PKEY)
END    
;

BEGIN
ALTER TABLE TPROJECTACCOUNT
    ADD CONSTRAINT TPROJECTACCOUNT_FK_2 FOREIGN KEY (ACCOUNT)
    REFERENCES TACCOUNT (OBJECTID)
END    
;

BEGIN
ALTER TABLE TGROUPMEMBER
    ADD CONSTRAINT TGROUPMEMBER_FK_1 FOREIGN KEY (THEGROUP)
    REFERENCES TGROUP (OBJECTID)
END    
;

BEGIN
ALTER TABLE TGROUPMEMBER
    ADD CONSTRAINT TGROUPMEMBER_FK_2 FOREIGN KEY (PERSON)
    REFERENCES TPERSON (PKEY)
END
;

BEGIN
ALTER TABLE TNOTIFY
    ADD CONSTRAINT TNOTIFY_FK_5 FOREIGN KEY (THEGROUP)
    REFERENCES TGROUP (OBJECTID)
END    
;


INSERT INTO ID_TABLE (ID_TABLE_ID, TABLE_NAME, NEXT_ID, QUANTITY) VALUES
			(47, 'TGROUP', 1, 1); 

INSERT INTO ID_TABLE (ID_TABLE_ID, TABLE_NAME, NEXT_ID, QUANTITY) VALUES
			(48, 'TGROUPMEMBER', 1, 1); 

UPDATE ID_TABLE SET NEXT_ID=14 WHERE TABLE_NAME='TCATEGORY';

GO


