CREATE  INDEX TPERSINDEX3 ON TPERSON (FIRSTNAME);
CREATE  INDEX TPERSINDEX4 ON TPERSON (LASTNAME);
CREATE  INDEX TPERSINDEX5 ON TPERSON (LOGINNAME);
CREATE  INDEX TPERSINDEX6 ON TPERSON (ISGROUP);

CREATE  INDEX TPROJECTINDEX1 ON TPROJECT (STATUS);

CREATE  INDEX TWIINDEX22 ON TWORKITEM (CREATED);
CREATE  INDEX TWIINDEX23 ON TWORKITEM (WBSONLEVEL);
CREATE  INDEX TWIINDEX24 ON TWORKITEM (TOPDOWNSTARTDATE);
CREATE  INDEX TWIINDEX25 ON TWORKITEM (TOPDOWNENDDATE);
CREATE  INDEX TWIINDEX26 ON TWORKITEM (PROJECTKEY);

CREATE  INDEX TCOSTINDEX2 ON TCOST (LASTEDIT);
CREATE  INDEX TCOSTINDEX3 ON TCOST (EFFORTDATE);
    
CREATE  INDEX TBUDGETINDEX4 ON TBUDGET (LASTEDIT);

DROP TABLE TENTITYCHANGES;
CREATE TABLE TENTITYCHANGES
(
    OBJECTID INT NOT NULL,
    ENTITYKEY INT NULL,
    ENTITYTYPE INT NOT NULL,
    CLUSTERNODE INT NULL,
    LIST INT NULL,
    CHANGETYPE INT NULL,

    CONSTRAINT TENTITYCHANGES_PK PRIMARY KEY(OBJECTID));

CREATE  INDEX ENTITYCHANGESINDEX1 ON TENTITYCHANGES (ENTITYTYPE);
CREATE  INDEX ENTITYCHANGESINDEX2 ON TENTITYCHANGES (CLUSTERNODE);

BEGIN
ALTER TABLE TENTITYCHANGES
    ADD CONSTRAINT TENTITYCHANGES_FK_1 FOREIGN KEY (CLUSTERNODE)
    REFERENCES CLUSTERNODE (OBJECTID)
END;

GO