CREATE TABLE [TATTRIBUTE] (
	[OBJECTID] [int] NOT NULL ,
	[ATTRIBUTENAME] [varchar] (255)  NOT NULL ,
	[ATTRIBUTETYPE] [int] NOT NULL ,
	[DELETED] [int] NULL ,
	[DESCRIPTION] [varchar] (64)  NULL ,
	[PERMISSION] [varchar] (255)  NULL ,
	[REQUIREDOPTION] [int] NULL 
) ON [PRIMARY]
GO

CREATE TABLE [TATTRIBUTECLASS] (
	[OBJECTID] [int] NOT NULL ,
	[ATTRIBUTECLASSNAME] [varchar] (255)  NOT NULL ,
	[ATTRIBUTECLASSDESC] [varchar] (64)  NULL ,
	[JAVACLASSNAME] [varchar] (255)  NULL 
) ON [PRIMARY]
GO

CREATE TABLE [TATTRIBUTEOPTION] (
	[OBJECTID] [int] NOT NULL ,
	[ATTRIBUTEID] [int] NOT NULL ,
	[PARENTOPTION] [int] NULL ,
	[OPTIONNAME] [varchar] (255)  NOT NULL ,
	[DELETED] [int] NULL 
) ON [PRIMARY]
GO

CREATE TABLE [TATTRIBUTETYPE] (
	[OBJECTID] [int] NOT NULL ,
	[ATTRIBUTETYPENAME] [varchar] (255)  NOT NULL ,
	[ATTRIBUTECLASS] [int] NOT NULL ,
	[JAVACLASSNAME] [varchar] (255)  NULL ,
	[VALIDATIONKEY] [varchar] (25)  NULL 
) ON [PRIMARY]
GO

CREATE TABLE [TISSUEATTRIBUTEVALUE] (
	[OBJECTID] [int] NOT NULL ,
	[ATTRIBUTEID] [int] NOT NULL ,
	[DELETED] [int] NULL ,
	[ISSUE] [int] NOT NULL ,
	[NUMERICVALUE] [int] NULL ,
	[TIMESTAMPVALUE] [datetime] NULL ,
	[LONGTEXTVALUE] [varchar] (7000)  NULL ,
	[OPTIONID] [int] NULL ,
	[PERSON] [int] NULL ,
	[CHARVALUE] [varchar] (255)  NULL ,
	[DISPLAYVALUE] [varchar] (255)  NULL 
) ON [PRIMARY]
GO

ALTER TABLE TPERSON	ADD [REMINDMEASORIGINATOR] [char] (1) default 'N'  NULL;
ALTER TABLE TPERSON	ADD [REMINDMEASMANAGER] [char] (1) default 'Y'  NULL;
ALTER TABLE TPERSON	ADD [REMINDMEASRESPONSIBLE] [char] (1) default 'Y'  NULL;
ALTER TABLE TPERSON	ADD [EMAILREMINDPLEVEL] [int] NULL;
ALTER TABLE TPERSON	ADD [EMAILREMINDSLEVEL] [int] NULL;

CREATE TABLE [TPPRIORITY] (
	[OBJECTID] [int] NOT NULL ,
	[PRIORITY] [int] NULL ,
	[PROJECTTYPE] [int] NULL ,
	[LISTTYPE] [int] NULL 
) ON [PRIMARY]
GO

ALTER TABLE [TPRIORITY] ADD [WLEVEL] [int] NULL; 


ALTER TABLE [TPROJECT] ADD [VERSIONSYSTEMFIELD0] [varchar] (255)  NULL;
ALTER TABLE [TPROJECT] ADD [VERSIONSYSTEMFIELD1] [varchar] (255)  NULL;
ALTER TABLE [TPROJECT] ADD [VERSIONSYSTEMFIELD2] [varchar] (255)  NULL;
ALTER TABLE [TPROJECT] ADD [VERSIONSYSTEMFIELD3] [varchar] (255)  NULL;
ALTER TABLE [TPROJECT] ADD [DELETED] [varchar] (1)  DEFAULT 'N' NOT NULL; 

CREATE TABLE [TPSEVERITY] (
	[OBJECTID] [int] NOT NULL ,
	[SEVERITY] [int] NULL ,
	[PROJECTTYPE] [int] NULL ,
	[LISTTYPE] [int] NULL 
) ON [PRIMARY]
GO

CREATE TABLE [TREPORTLAYOUT] (
	[OBJECTID] [int] NOT NULL ,
	[PROJECTTYPE] [int] NULL ,
	[PROJECT] [int] NULL ,
	[PERSON] [int] NULL ,
	[REPORTFIELD] [int] NOT NULL ,
	[FPOSITION] [int] NOT NULL ,
	[FWIDTH] [int] NOT NULL ,
	[FSORTORDER] [int] NULL ,
	[FSORTDIR] [varchar] (1)  NULL 
) ON [PRIMARY]
GO

CREATE TABLE [TSCHEDULER] (
	[OBJECTID] [int] NOT NULL ,
	[CRONWHEN] [varchar] (64)  NOT NULL ,
	[JAVACLASSNAME] [varchar] (255)  NULL ,
	[EXTERNALEXE] [varchar] (255)  NULL ,
	[PERSON] [int] NOT NULL 
) ON [PRIMARY]
GO

ALTER TABLE [TSEVERITY] ADD [WLEVEL] [int] NULL ;


ALTER TABLE [TSITE] ADD [LICENSEEXT] [varchar] (255)  NULL ;
ALTER TABLE [TSITE] ADD [EXECUTABLE1] [varchar] (255)  NULL ;
ALTER TABLE [TSITE] ADD [EXECUTABLE2] [varchar] (255)  NULL ;
ALTER TABLE [TSITE] ADD [LDAPBINDDN] [varchar] (255)  NULL ;
ALTER TABLE [TSITE] ADD [LDAPBINDPASSW] [varchar] (20)  NULL; 

DROP TABLE TWORKFLOW;

CREATE TABLE [TWORKFLOW] (
	[OBJECTID] [int] NOT NULL ,
	[STATEFROM] [int] NULL ,
	[STATETO] [int] NULL ,
	[PROJECTTYPE] [int] NULL 
) ON [PRIMARY]
GO

CREATE TABLE [TWORKFLOWCATEGORY] (
	[OBJECTID] [int] NOT NULL ,
	[WORKFLOW] [int] NULL ,
	[CATEGORY] [int] NULL 
) ON [PRIMARY]
GO

CREATE TABLE [TWORKFLOWROLE] (
	[OBJECTID] [int] NOT NULL ,
	[WORKFLOW] [int] NULL ,
	[MAYCHANGEROLE] [int] NULL 
) ON [PRIMARY]
GO

ALTER TABLE [TWORKITEM] ADD [WLEVEL] [varchar] (14)  NULL; 


ALTER TABLE [TATTRIBUTE] WITH NOCHECK ADD 
	CONSTRAINT [TATTRIBUTE_PK] PRIMARY KEY  CLUSTERED 
	(
		[OBJECTID]
	)  ON [PRIMARY] 
GO

ALTER TABLE [TATTRIBUTECLASS] WITH NOCHECK ADD 
	CONSTRAINT [TATTRIBUTECLASS_PK] PRIMARY KEY  CLUSTERED 
	(
		[OBJECTID]
	)  ON [PRIMARY] 
GO

ALTER TABLE [TATTRIBUTEOPTION] WITH NOCHECK ADD 
	CONSTRAINT [TATTRIBUTEOPTION_PK] PRIMARY KEY  CLUSTERED 
	(
		[OBJECTID]
	)  ON [PRIMARY] 
GO

ALTER TABLE [TATTRIBUTETYPE] WITH NOCHECK ADD 
	CONSTRAINT [TATTRIBUTETYPE_PK] PRIMARY KEY  CLUSTERED 
	(
		[OBJECTID]
	)  ON [PRIMARY] 
GO

ALTER TABLE [TISSUEATTRIBUTEVALUE] WITH NOCHECK ADD 
	CONSTRAINT [TISSUEATTRIBUTEVALUE_PK] PRIMARY KEY  CLUSTERED 
	(
		[OBJECTID]
	)  ON [PRIMARY] 
GO

ALTER TABLE [TPPRIORITY] WITH NOCHECK ADD 
	CONSTRAINT [TPPRIORITY_PK] PRIMARY KEY  CLUSTERED 
	(
		[OBJECTID]
	)  ON [PRIMARY] 
GO

ALTER TABLE [TPSEVERITY] WITH NOCHECK ADD 
	CONSTRAINT [TPSEVERITY_PK] PRIMARY KEY  CLUSTERED 
	(
		[OBJECTID]
	)  ON [PRIMARY] 
GO

ALTER TABLE [TREPORTLAYOUT] WITH NOCHECK ADD 
	CONSTRAINT [TREPORTLAYOUT_PK] PRIMARY KEY  CLUSTERED 
	(
		[OBJECTID]
	)  ON [PRIMARY] 
GO

ALTER TABLE [TSCHEDULER] WITH NOCHECK ADD 
	CONSTRAINT [TSCHEDULER_PK] PRIMARY KEY  CLUSTERED 
	(
		[OBJECTID]
	)  ON [PRIMARY] 
GO

ALTER TABLE [TWORKFLOW] WITH NOCHECK ADD 
	CONSTRAINT [TWORKFLOW_PK] PRIMARY KEY  CLUSTERED 
	(
		[OBJECTID]
	)  ON [PRIMARY] 
GO

ALTER TABLE [TWORKFLOWCATEGORY] WITH NOCHECK ADD 
	CONSTRAINT [TWORKFLOWCATEGORY_PK] PRIMARY KEY  CLUSTERED 
	(
		[OBJECTID]
	)  ON [PRIMARY] 
GO

ALTER TABLE [TWORKFLOWROLE] WITH NOCHECK ADD 
	CONSTRAINT [TWORKFLOWROLE_PK] PRIMARY KEY  CLUSTERED 
	(
		[OBJECTID]
	)  ON [PRIMARY] 
GO

 CREATE  INDEX [TWIINDEX17] ON [TWORKITEM]([WLEVEL]) ON [PRIMARY]
GO

ALTER TABLE [TATTRIBUTE] ADD 
	CONSTRAINT [TATTRIBUTE_FK_1] FOREIGN KEY 
	(
		[REQUIREDOPTION]
	) REFERENCES [TATTRIBUTEOPTION] (
		[OBJECTID]
	)
GO

ALTER TABLE [TATTRIBUTEOPTION] ADD 
	CONSTRAINT [TATTRIBUTEOPTION_FK_1] FOREIGN KEY 
	(
		[ATTRIBUTEID]
	) REFERENCES [TATTRIBUTE] (
		[OBJECTID]
	)
GO

ALTER TABLE [TATTRIBUTETYPE] ADD 
	CONSTRAINT [TATTRIBUTETYPE_FK_1] FOREIGN KEY 
	(
		[ATTRIBUTECLASS]
	) REFERENCES [TATTRIBUTECLASS] (
		[OBJECTID]
	)
GO

ALTER TABLE [TISSUEATTRIBUTEVALUE] ADD 
	CONSTRAINT [TISSUEATTRIBUTEVALUE_FK_1] FOREIGN KEY 
	(
		[PERSON]
	) REFERENCES [TPERSON] (
		[PKEY]
	),
	CONSTRAINT [TISSUEATTRIBUTEVALUE_FK_2] FOREIGN KEY 
	(
		[ISSUE]
	) REFERENCES [TWORKITEM] (
		[WORKITEMKEY]
	),
	CONSTRAINT [TISSUEATTRIBUTEVALUE_FK_3] FOREIGN KEY 
	(
		[ATTRIBUTEID]
	) REFERENCES [TATTRIBUTE] (
		[OBJECTID]
	),
	CONSTRAINT [TISSUEATTRIBUTEVALUE_FK_4] FOREIGN KEY 
	(
		[OPTIONID]
	) REFERENCES [TATTRIBUTEOPTION] (
		[OBJECTID]
	)
GO

ALTER TABLE [TPPRIORITY] ADD 
	CONSTRAINT [TPPRIORITY_FK_1] FOREIGN KEY 
	(
		[PRIORITY]
	) REFERENCES [TPRIORITY] (
		[PKEY]
	),
	CONSTRAINT [TPPRIORITY_FK_2] FOREIGN KEY 
	(
		[PROJECTTYPE]
	) REFERENCES [TPROJECTTYPE] (
		[OBJECTID]
	),
	CONSTRAINT [TPPRIORITY_FK_3] FOREIGN KEY 
	(
		[LISTTYPE]
	) REFERENCES [TCATEGORY] (
		[PKEY]
	)
GO

ALTER TABLE [TPSEVERITY] ADD 
	CONSTRAINT [TPSEVERITY_FK_1] FOREIGN KEY 
	(
		[SEVERITY]
	) REFERENCES [TSEVERITY] (
		[PKEY]
	),
	CONSTRAINT [TPSEVERITY_FK_2] FOREIGN KEY 
	(
		[PROJECTTYPE]
	) REFERENCES [TPROJECTTYPE] (
		[OBJECTID]
	),
	CONSTRAINT [TPSEVERITY_FK_3] FOREIGN KEY 
	(
		[LISTTYPE]
	) REFERENCES [TCATEGORY] (
		[PKEY]
	)
GO


ALTER TABLE [TREPORTLAYOUT] ADD 
	CONSTRAINT [TREPORTLAYOUT_FK_1] FOREIGN KEY 
	(
		[PROJECTTYPE]
	) REFERENCES [TPROJECTTYPE] (
		[OBJECTID]
	),
	CONSTRAINT [TREPORTLAYOUT_FK_2] FOREIGN KEY 
	(
		[PROJECT]
	) REFERENCES [TPROJECT] (
		[PKEY]
	),
	CONSTRAINT [TREPORTLAYOUT_FK_3] FOREIGN KEY 
	(
		[PERSON]
	) REFERENCES [TPERSON] (
		[PKEY]
	),
	CONSTRAINT [TREPORTLAYOUT_FK_4] FOREIGN KEY 
	(
		[REPORTFIELD]
	) REFERENCES [TISSUEATTRIBUTEVALUE] (
		[OBJECTID]
	)
GO

ALTER TABLE [TSCHEDULER] ADD 
	CONSTRAINT [TSCHEDULER_FK_1] FOREIGN KEY 
	(
		[PERSON]
	) REFERENCES [TPERSON] (
		[PKEY]
	)
GO

ALTER TABLE [TWORKFLOW] ADD 
	CONSTRAINT [TWORKFLOW_FK_1] FOREIGN KEY 
	(
		[STATEFROM]
	) REFERENCES [TSTATE] (
		[PKEY]
	),
	CONSTRAINT [TWORKFLOW_FK_2] FOREIGN KEY 
	(
		[STATETO]
	) REFERENCES [TSTATE] (
		[PKEY]
	),
	CONSTRAINT [TWORKFLOW_FK_3] FOREIGN KEY 
	(
		[PROJECTTYPE]
	) REFERENCES [TPROJECTTYPE] (
		[OBJECTID]
	)
GO

ALTER TABLE [TWORKFLOWCATEGORY] ADD 
	CONSTRAINT [TWORKFLOWCATEGORY_FK_1] FOREIGN KEY 
	(
		[WORKFLOW]
	) REFERENCES [TWORKFLOW] (
		[OBJECTID]
	),
	CONSTRAINT [TWORKFLOWCATEGORY_FK_2] FOREIGN KEY 
	(
		[CATEGORY]
	) REFERENCES [TCATEGORY] (
		[PKEY]
	)
GO

ALTER TABLE [TWORKFLOWROLE] ADD 
	CONSTRAINT [TWORKFLOWROLE_FK_1] FOREIGN KEY 
	(
		[WORKFLOW]
	) REFERENCES [TWORKFLOW] (
		[OBJECTID]
	),
	CONSTRAINT [TWORKFLOWROLE_FK_2] FOREIGN KEY 
	(
		[MAYCHANGEROLE]
	) REFERENCES [TROLE] (
		[PKEY]
	)
GO

INSERT INTO ID_TABLE (ID_TABLE_ID, TABLE_NAME, NEXT_ID, QUANTITY) VALUES
			(36, 'TWORKFLOWCATEGORY', 1, 1);

INSERT INTO ID_TABLE (ID_TABLE_ID, TABLE_NAME, NEXT_ID, QUANTITY) VALUES
			(37, 'TWORKFLOWROLE', 1, 1);

INSERT INTO ID_TABLE (ID_TABLE_ID, TABLE_NAME, NEXT_ID, QUANTITY) VALUES
			(38, 'TPPRIORITY', 1, 1);

INSERT INTO ID_TABLE (ID_TABLE_ID, TABLE_NAME, NEXT_ID, QUANTITY) VALUES
			(39, 'TPSEVERITY', 1, 1);

INSERT INTO ID_TABLE (ID_TABLE_ID, TABLE_NAME, NEXT_ID, QUANTITY) VALUES
			(40, 'TISSUEATTRIBUTEVALUE', 1, 1);

INSERT INTO ID_TABLE (ID_TABLE_ID, TABLE_NAME, NEXT_ID, QUANTITY) VALUES
			(41, 'TATTRIBUTEOPTION', 1, 1);

INSERT INTO ID_TABLE (ID_TABLE_ID, TABLE_NAME, NEXT_ID, QUANTITY) VALUES
			(42, 'TATTRIBUTECLASS', 1, 1);

INSERT INTO ID_TABLE (ID_TABLE_ID, TABLE_NAME, NEXT_ID, QUANTITY) VALUES
			(43, 'TATTRIBUTETYPE', 1, 1);

INSERT INTO ID_TABLE (ID_TABLE_ID, TABLE_NAME, NEXT_ID, QUANTITY) VALUES
			(44, 'TATTRIBUTE', 1, 1);

INSERT INTO ID_TABLE (ID_TABLE_ID, TABLE_NAME, NEXT_ID, QUANTITY) VALUES
			(45, 'TREPORTLAYOUT', 1, 1);

INSERT INTO ID_TABLE (ID_TABLE_ID, TABLE_NAME, NEXT_ID, QUANTITY) VALUES
			(46, 'TSCHEDULER', 1, 1);