ALTER TABLE TCATEGORY ALTER COLUMN LABEL VARCHAR(255) NOT NULL;
ALTER TABLE TDEPARTMENT ALTER COLUMN LABEL VARCHAR(255) NOT NULL;
ALTER TABLE TPERSON ADD SUBSTITUTEKEY INTEGER;
ALTER TABLE TPERSON ADD SUBSTITUTEACTIVE CHAR (1) default 'N';
ALTER TABLE TPRIORITY ALTER COLUMN LABEL VARCHAR(255) NULL;
ALTER TABLE TPROJECT ALTER COLUMN LABEL VARCHAR(255) NULL;
ALTER TABLE TRELEASE ALTER COLUMN LABEL VARCHAR(255) NULL;
ALTER TABLE TROLE ALTER COLUMN LABEL VARCHAR(255) NOT NULL;
ALTER TABLE TSEVERITY ALTER COLUMN LABEL VARCHAR(255) NULL;
ALTER TABLE TSTATE ALTER COLUMN LABEL VARCHAR(255) NOT NULL;
ALTER TABLE TWORKITEM ALTER COLUMN PACKAGESYNOPSYS VARCHAR (255) NOT NULL;
ALTER TABLE TPROJECTTYPE ALTER COLUMN LABEL VARCHAR(255) NULL;
ALTER TABLE TSITE DROP COLUMN LICENSEKEY;
ALTER TABLE TSITE DROP COLUMN EXECUTABLE1;
ALTER TABLE TSITE DROP COLUMN EXECUTABLE2;
ALTER TABLE TSITE ALTER COLUMN LICENSEEXT VARCHAR(512);
ALTER TABLE TSCREENFIELD ADD HIDELABEL CHAR (1) default 'N';
ALTER TABLE TPERSON
    ADD CONSTRAINT TPERSON_FK_4 FOREIGN KEY (SUBSTITUTEKEY)
    REFERENCES TPERSON (PKEY);
GO