/* MS SQL Server migration script from 3.2.0 to 3.3.0 */
/* $Id: migrate320to330.sql 658 2009-01-02 10:48:52Z friedj $ */

ALTER TABLE TBASELINE DROP CONSTRAINT TBASELINE_FK_3;            
ALTER TABLE TNOTIFY DROP CONSTRAINT TNOTIFY_FK_5;
ALTER TABLE TWORKITEM DROP CONSTRAINT TWORKITEM_FK_13;
ALTER TABLE TCOST DROP CONSTRAINT TCOST_FK_4;    
ALTER TABLE TPCURRENCY DROP CONSTRAINT TPCURRENCY_FK_1;
ALTER TABLE TPCURRENCY DROP CONSTRAINT TPCURRENCY_FK_2;
ALTER TABLE TGROUPMEMBER DROP CONSTRAINT TGROUPMEMBER_FK_1;            

ALTER TABLE [TBASELINE] DROP COLUMN [EFFORT];
ALTER TABLE [TBASELINE] DROP COLUMN [ESTIMATEDHOURS];
ALTER TABLE [TBASELINE] DROP COLUMN [ESTIMATEDCOST];
ALTER TABLE [TBASELINE] DROP COLUMN [CURRENCY];

ALTER TABLE TDEPARTMENT ADD COSTCENTER [INT] NULL;

ALTER TABLE TNOTIFY DROP COLUMN THEGROUP;

ALTER TABLE TPERSON ADD HOURSPERWORKDAY FLOAT NULL;
ALTER TABLE TPERSON ADD [ISGROUP] CHAR (1) default 'N' NULL;

ALTER TABLE TPRIORITY ADD SYMBOL [VARCHAR] (255) NULL;

ALTER TABLE TPROJECT ADD [STATUS] [INT] NULL;
ALTER TABLE TPROJECT ADD CURRENCYNAME [VARCHAR] (255) NULL;
ALTER TABLE TPROJECT ADD CURRENCYSYMBOL [VARCHAR] (255) NULL;
ALTER TABLE TPROJECT ADD HOURSPERWORKDAY FLOAT NULL;
ALTER TABLE TPROJECT ADD MOREPROPS [VARCHAR] (3000) NULL;
ALTER TABLE TPROJECT ADD DESCRIPTION [VARCHAR] (255) NULL;


ALTER TABLE TRELEASE ADD STATUS [INT] NULL;
ALTER TABLE TRELEASE ADD SORTORDER [INT] NULL;
ALTER TABLE TRELEASE ADD MOREPROPS [VARCHAR] (3000) NULL;
ALTER TABLE TRELEASE ADD DESCRIPTION [VARCHAR] (255) NULL;
ALTER TABLE TRELEASE ADD DUEDATE DATETIME NULL;

ALTER TABLE TSEVERITY ADD SYMBOL [VARCHAR] (255) NULL;

ALTER TABLE TSTATE ADD SYMBOL [VARCHAR] (255) NULL;

ALTER TABLE TWORKITEM ADD SUBMITTEREMAIL [VARCHAR] (60) NULL;
ALTER TABLE TWORKITEM ADD ACCESSLEVEL [INT] NULL;
ALTER TABLE TWORKITEM DROP COLUMN ESTIMATEDHOURS; 
ALTER TABLE TWORKITEM DROP COLUMN ESTIMATEDCOST;
ALTER TABLE TWORKITEM DROP COLUMN CURRENCY;

CREATE  INDEX TWIINDEX18 ON TWORKITEM (ACCESSLEVEL);

ALTER TABLE TACCOUNT DROP COLUMN [ACTIVE];
ALTER TABLE TACCOUNT DROP COLUMN [COSTCENTER];
ALTER TABLE TACCOUNT ADD COSTCENTER [INT] NULL;
ALTER TABLE TACCOUNT ADD STATUS [INT] NULL;
ALTER TABLE TACCOUNT ADD DESCRIPTION [VARCHAR] (255) NULL;
ALTER TABLE TACCOUNT ADD MOREPROPS [VARCHAR] (3000) NULL;

ALTER TABLE TCOST DROP COLUMN CURRENCY;
ALTER TABLE TCOST ADD SUBJECT [VARCHAR] (255) NULL;
ALTER TABLE TCOST ADD DESCRIPTION [VARCHAR] (255) NULL;
ALTER TABLE TCOST ADD MOREPROPS [VARCHAR] (3000) NULL;
ALTER TABLE TCOST ADD LASTEDIT DATETIME NULL;

DROP TABLE [TPCURRENCY];
DROP TABLE [TCURRENCY];


ALTER TABLE TPROJECTTYPE ADD HOURSPERWORKDAY FLOAT NULL;
ALTER TABLE TPROJECTTYPE ADD MOREPROPS [VARCHAR] (3000) NULL;

DROP TABLE TGROUP;

CREATE TABLE TBUDGET
(
            OBJECTID INT NOT NULL,
            WORKITEMKEY INT NOT NULL,
            ESTIMATEDHOURS FLOAT NULL,
            TIMEUNIT INT NULL,
            ESTIMATEDCOST FLOAT NULL,
            CHANGEDESCRIPTION VARCHAR (255) NULL,
            MOREPROPS VARCHAR (3000) NULL,
            CHANGEDBY INT NULL,
            LASTEDIT DATETIME NULL,

    CONSTRAINT TBUDGET_PK PRIMARY KEY(OBJECTID));

CREATE  INDEX TBUDGETINDEX1 ON TBUDGET (WORKITEMKEY);
CREATE  INDEX TBUDGETINDEX2 ON TBUDGET (CHANGEDBY);


CREATE TABLE TACTUALESTIMATEDBUDGET
(
            OBJECTID INT NOT NULL,
            WORKITEMKEY INT NOT NULL,
            ESTIMATEDHOURS FLOAT NULL,
            TIMEUNIT INT NULL,
            ESTIMATEDCOST FLOAT NULL,
            CHANGEDBY INT NULL,
            LASTEDIT DATETIME NULL,

    CONSTRAINT TACTUALESTIMATEDBUDGET_PK PRIMARY KEY(OBJECTID));

CREATE  INDEX TACTUALESTINDEX1 ON TACTUALESTIMATEDBUDGET (WORKITEMKEY);
CREATE  INDEX TACTUALESTINDEX2 ON TACTUALESTIMATEDBUDGET (CHANGEDBY);


CREATE TABLE TSYSTEMSTATE
(
            OBJECTID INT NOT NULL,
            LABEL VARCHAR (255) NULL,
            STATEFLAG INT NULL,
            SYMBOL VARCHAR (255) NULL,
            ENTITYFLAG INT NULL,
            SORTORDER INT NULL,

    CONSTRAINT TSYSTEMSTATE_PK PRIMARY KEY(OBJECTID));



CREATE TABLE TCOSTCENTER
(
            OBJECTID INT NOT NULL,
            COSTCENTERNUMBER VARCHAR (30) NOT NULL,
            COSTCENTERNAME VARCHAR (80) NULL,
            MOREPROPS VARCHAR (3000) NULL,

    CONSTRAINT TCOSTCENTER_PK PRIMARY KEY(OBJECTID));



CREATE TABLE TMOTD
(
            OBJECTID INT NOT NULL,
            THELOCALE VARCHAR (2) NULL,
            THEMESSAGE VARCHAR (7000) NULL,

    CONSTRAINT TMOTD_PK PRIMARY KEY(OBJECTID));


ALTER TABLE TDEPARTMENT ADD CONSTRAINT TDEPARTMENT_FK_1 FOREIGN KEY (COSTCENTER) REFERENCES TCOSTCENTER (OBJECTID);
ALTER TABLE TPROJECT ADD CONSTRAINT TPROJECT_FK_5 FOREIGN KEY (STATUS) REFERENCES TSYSTEMSTATE (OBJECTID);
ALTER TABLE TRELEASE ADD CONSTRAINT TRELEASE_FK_2 FOREIGN KEY (STATUS) REFERENCES TSYSTEMSTATE (OBJECTID);        
ALTER TABLE TACCOUNT ADD CONSTRAINT TACCOUNT_FK_1 FOREIGN KEY (STATUS) REFERENCES TSYSTEMSTATE (OBJECTID);
ALTER TABLE TACCOUNT ADD CONSTRAINT TACCOUNT_FK_2 FOREIGN KEY (COSTCENTER) REFERENCES TCOSTCENTER (OBJECTID);
ALTER TABLE TGROUPMEMBER ADD CONSTRAINT TGROUPMEMBER_FK_1 FOREIGN KEY (THEGROUP) REFERENCES TPERSON (PKEY);    
ALTER TABLE TBUDGET ADD CONSTRAINT TBUDGET_FK_1 FOREIGN KEY (WORKITEMKEY) REFERENCES TWORKITEM (WORKITEMKEY);
ALTER TABLE TBUDGET ADD CONSTRAINT TBUDGET_FK_2 FOREIGN KEY (CHANGEDBY) REFERENCES TPERSON (PKEY);    
ALTER TABLE TACTUALESTIMATEDBUDGET ADD CONSTRAINT TACTUALESTIMATEDBUDGET_FK_1 FOREIGN KEY (WORKITEMKEY) REFERENCES TWORKITEM (WORKITEMKEY);
ALTER TABLE TACTUALESTIMATEDBUDGET ADD CONSTRAINT TACTUALESTIMATEDBUDGET_FK_2 FOREIGN KEY (CHANGEDBY) REFERENCES TPERSON (PKEY);

GO

/*
DML statements
*/

INSERT INTO ID_TABLE (ID_TABLE_ID, TABLE_NAME, NEXT_ID, QUANTITY) VALUES
			(49, 'TBUDGET', 1, 1);
INSERT INTO ID_TABLE (ID_TABLE_ID, TABLE_NAME, NEXT_ID, QUANTITY) VALUES
			(50, 'TACTUALESTIMATEDBUDGET', 1, 1);
INSERT INTO ID_TABLE (ID_TABLE_ID, TABLE_NAME, NEXT_ID, QUANTITY) VALUES
			(51, 'TSYSTEMSTATE', 100, 1);
INSERT INTO ID_TABLE (ID_TABLE_ID, TABLE_NAME, NEXT_ID, QUANTITY) VALUES
			(52, 'TCOSTCENTER', 1, 1);
INSERT INTO ID_TABLE (ID_TABLE_ID, TABLE_NAME, NEXT_ID, QUANTITY) VALUES
			(53, 'TMOTD', 1, 1);

INSERT INTO TSYSTEMSTATE (OBJECTID, LABEL, STATEFLAG, ENTITYFLAG, SORTORDER)
       VALUES (1,'proposed', 0, 1, 1);
INSERT INTO TSYSTEMSTATE (OBJECTID, LABEL, STATEFLAG, ENTITYFLAG, SORTORDER) 
       VALUES (2,'in planning', 0, 1, 2);
INSERT INTO TSYSTEMSTATE (OBJECTID, LABEL, STATEFLAG, ENTITYFLAG, SORTORDER) 
       VALUES (3,'in progress', 0, 1, 3);
INSERT INTO TSYSTEMSTATE (OBJECTID, LABEL, STATEFLAG, ENTITYFLAG, SORTORDER) 
       VALUES (4,'on hold', 1, 1, 4);
INSERT INTO TSYSTEMSTATE (OBJECTID, LABEL, STATEFLAG, ENTITYFLAG, SORTORDER) 
       VALUES (5,'released', 1, 1, 5);
INSERT INTO TSYSTEMSTATE (OBJECTID, LABEL, STATEFLAG, ENTITYFLAG, SORTORDER) 
       VALUES (6,'archived', 2, 1, 6);

INSERT INTO TSYSTEMSTATE (OBJECTID, LABEL, STATEFLAG, ENTITYFLAG, SORTORDER)
       VALUES (7,'proposed', 0, 2, 1);
INSERT INTO TSYSTEMSTATE (OBJECTID, LABEL, STATEFLAG, ENTITYFLAG, SORTORDER) 
       VALUES (8,'in planning', 0, 2, 2);
INSERT INTO TSYSTEMSTATE (OBJECTID, LABEL, STATEFLAG, ENTITYFLAG, SORTORDER) 
       VALUES (9,'in progress', 0, 2, 3);
INSERT INTO TSYSTEMSTATE (OBJECTID, LABEL, STATEFLAG, ENTITYFLAG, SORTORDER) 
       VALUES (10,'on hold', 1, 2, 4);
INSERT INTO TSYSTEMSTATE (OBJECTID, LABEL, STATEFLAG, ENTITYFLAG, SORTORDER) 
       VALUES (11,'released', 1, 2, 5);
INSERT INTO TSYSTEMSTATE (OBJECTID, LABEL, STATEFLAG, ENTITYFLAG, SORTORDER) 
       VALUES (12,'archived', 2, 2, 6);

INSERT INTO TSYSTEMSTATE (OBJECTID, LABEL, STATEFLAG, ENTITYFLAG, SORTORDER)
       VALUES (13,'opened', 0, 3, 1);
INSERT INTO TSYSTEMSTATE (OBJECTID, LABEL, STATEFLAG, ENTITYFLAG, SORTORDER) 
       VALUES (14,'closed', 2, 3, 3);

UPDATE TPERSON SET ISGROUP = 'N' WHERE ISGROUP IS NULL;

UPDATE TPROJECT SET STATUS = 3 WHERE STATUS IS NULL AND (DELETED IS NULL OR DELETED = 'N');
UPDATE TPROJECT SET STATUS = 6 WHERE STATUS IS NULL AND DELETED = 'Y';

UPDATE TRELEASE SET STATUS = 9 WHERE STATUS IS NULL;

UPDATE TACCOUNT SET STATUS = 13 WHERE STATUS IS NULL;

GO
