ALTER TABLE TCATEGORY MODIFY LABEL VARCHAR2(255);
ALTER TABLE TDEPARTMENT MODIFY LABEL VARCHAR2(255);
ALTER TABLE TPERSON ADD SUBSTITUTEKEY NUMBER(10,0);
ALTER TABLE TPERSON ADD SUBSTITUTEACTIVE CHAR (1) default 'N';
ALTER TABLE TPRIORITY MODIFY LABEL VARCHAR2(255);
ALTER TABLE TPROJECT MODIFY LABEL VARCHAR2(255);
ALTER TABLE TRELEASE MODIFY LABEL VARCHAR2(255);
ALTER TABLE TROLE MODIFY LABEL VARCHAR2(255);
ALTER TABLE TSEVERITY MODIFY LABEL VARCHAR(255);
ALTER TABLE TSTATE MODIFY LABEL VARCHAR2(255);
ALTER TABLE TWORKITEM MODIFY PACKAGESYNOPSYS VARCHAR (255);
ALTER TABLE TPROJECTTYPE MODIFY LABEL VARCHAR2(255);
ALTER TABLE TSITE DROP COLUMN LICENSEKEY;
ALTER TABLE TSITE DROP COLUMN EXECUTABLE1;
ALTER TABLE TSITE DROP COLUMN EXECUTABLE2;
ALTER TABLE TSITE MODIFY LICENSEEXT VARCHAR(512);
ALTER TABLE TSCREENFIELD ADD HIDELABEL CHAR (1) default 'N';
ALTER TABLE TPERSON
    ADD CONSTRAINT TPERSON_FK_4 FOREIGN KEY (SUBSTITUTEKEY)
    REFERENCES TPERSON (PKEY);
COMMIT;