ALTER TABLE TCATEGORY ADD TYPEFLAG NUMBER(10,0);
ALTER TABLE TSTATE ADD PERCENTCOMPLETE NUMBER(10,0);
ALTER TABLE TWORKFLOW ADD RESPONSIBLE NUMBER(10,0);
ALTER TABLE TREPORTLAYOUT ADD QUERYID NUMBER(10,0); 
ALTER TABLE TREPORTLAYOUT ADD QUERYTYPE NUMBER(10,0); 

CREATE INDEX TREPORTLAYOUTINDEX4 ON TREPORTLAYOUT (QUERYID);

ALTER TABLE TDASHBOARDSCREEN ADD PROJECT NUMBER(10,0);

ALTER TABLE TDASHBOARDSCREEN ADD ENTITYTYPE NUMBER(10,0);

-----------------------------------------------------------------------------
-- TRECURRENCEPATTERN
-----------------------------------------------------------------------------
--DROP TABLE TRECURRENCEPATTERN CASCADE CONSTRAINTS;

CREATE TABLE TRECURRENCEPATTERN
(
    OBJECTID NUMBER(10,0) NOT NULL,
    RECURRENCEPERIOD NUMBER(10,0) NOT NULL,
    PARAM1 NUMBER(10,0),
    PARAM2 NUMBER(10,0),
    PARAM3 NUMBER(10,0),
    DAYS VARCHAR2(255),
    DATEISABSOLUTE CHAR(1) default 'Y',
    STARTDATE TIMESTAMP,
    ENDDATE TIMESTAMP,
    OCCURENCETYPE NUMBER(10,0),
    NOOFOCCURENCES NUMBER(10,0),
    TPUUID VARCHAR2(36)
);

ALTER TABLE TRECURRENCEPATTERN
    ADD CONSTRAINT TRECURRENCEPATTERN_PK
PRIMARY KEY (OBJECTID);

CREATE INDEX TRECURRENCEPATTERNINDEX1 ON TRECURRENCEPATTERN (TPUUID);


-----------------------------------------------------------------------------
-- TREPORTPERSONSETTINGS
-----------------------------------------------------------------------------
--DROP TABLE TREPORTPERSONSETTINGS CASCADE CONSTRAINTS;

CREATE TABLE TREPORTPERSONSETTINGS
(
    OBJECTID NUMBER(10,0) NOT NULL,
    PERSON NUMBER(10,0) NOT NULL,
    RECURRENCEPATTERN NUMBER(10,0),
    REPORTTEMPLATE NUMBER(10,0) NOT NULL,
    TPUUID VARCHAR2(36)
);

ALTER TABLE TREPORTPERSONSETTINGS
    ADD CONSTRAINT TREPORTPERSONSETTINGS_PK
PRIMARY KEY (OBJECTID);

CREATE INDEX TREPORTPERSONSETTINGSINDEX1 ON TREPORTPERSONSETTINGS (TPUUID);


-----------------------------------------------------------------------------
-- TREPORTPARAMETER
-----------------------------------------------------------------------------
--DROP TABLE TREPORTPARAMETER CASCADE CONSTRAINTS;

CREATE TABLE TREPORTPARAMETER
(
    OBJECTID NUMBER(10,0) NOT NULL,
    NAME VARCHAR2(255) NOT NULL,
    PARAMVALUE VARCHAR2(4000),
    REPORTPERSONSETTINGS NUMBER(10,0) NOT NULL,
    TPUUID VARCHAR2(36)
);

ALTER TABLE TREPORTPARAMETER
    ADD CONSTRAINT TREPORTPARAMETER_PK
PRIMARY KEY (OBJECTID);

CREATE INDEX TREPORTPARAMETERINDEX1 ON TREPORTPARAMETER (TPUUID);



-----------------------------------------------------------------------------
-- TMSPROJECTTASK
-----------------------------------------------------------------------------
--DROP TABLE TMSPROJECTTASK CASCADE CONSTRAINTS;

CREATE TABLE TMSPROJECTTASK
(
    OBJECTID NUMBER(10,0) NOT NULL,
    WORKITEM NUMBER(10,0) NOT NULL,
    UNIQUEID NUMBER(10,0) NOT NULL,
    TASKTYPE NUMBER(10,0) NOT NULL,
    CONTACT VARCHAR2(100),
    WBS VARCHAR2(100),
    OUTLINENUMBER VARCHAR2(100),
    DURATION VARCHAR2(100),
    DURATIONFORMAT NUMBER(10,0),
    ESTIMATED CHAR(1) default 'N',
    MILESTONE CHAR(1) default 'N',
    SUMMARY CHAR(1) default 'N',
    ACTUALDURATION VARCHAR2(100),
    REMAININGDURATION VARCHAR2(100),
    CONSTRAINTTYPE NUMBER(10,0),
    CONSTRAINTDATE TIMESTAMP,
    DEADLINE TIMESTAMP,
    TPUUID VARCHAR2(36)
);

ALTER TABLE TMSPROJECTTASK
    ADD CONSTRAINT TMSPROJECTTASK_PK
PRIMARY KEY (OBJECTID);

CREATE INDEX TMSPROJECTTASKINDEX1 ON TMSPROJECTTASK (TPUUID);





-----------------------------------------------------------------------------
-- TMSPROJECTEXCHANGE
-----------------------------------------------------------------------------
--DROP TABLE TMSPROJECTEXCHANGE CASCADE CONSTRAINTS;

CREATE TABLE TMSPROJECTEXCHANGE
(
    OBJECTID NUMBER(10,0) NOT NULL,
    EXCHANGEDIRECTION NUMBER(10,0) NOT NULL,
    ENTITYID NUMBER(10,0) NOT NULL,
    ENTITYTYPE NUMBER(10,0) NOT NULL,
    FILENAME VARCHAR2(255),
    FILECONTENT CLOB,
    CHANGEDBY NUMBER(10,0),
    LASTEDIT TIMESTAMP,
    TPUUID VARCHAR2(36)
);

ALTER TABLE TMSPROJECTEXCHANGE
    ADD CONSTRAINT TMSPROJECTEXCHANGE_PK
PRIMARY KEY (OBJECTID);

CREATE INDEX TMSPROJECTEXCHANGEINDEX1 ON TMSPROJECTEXCHANGE (TPUUID);

ALTER TABLE TWORKFLOW
    ADD CONSTRAINT TWORKFLOW_FK_4 FOREIGN KEY (RESPONSIBLE)
    REFERENCES TPERSON (PKEY)
;


ALTER TABLE TDASHBOARDSCREEN
    ADD CONSTRAINT TDASHBOARDSCREEN_FK_2 FOREIGN KEY (PROJECT)
    REFERENCES TPROJECT (PKEY)
;

ALTER TABLE TREPORTPERSONSETTINGS
    ADD CONSTRAINT TREPORTPERSONSETTINGS_FK_1 FOREIGN KEY (PERSON)
    REFERENCES TPERSON (PKEY)
;

ALTER TABLE TREPORTPERSONSETTINGS
    ADD CONSTRAINT TREPORTPERSONSETTINGS_FK_2 FOREIGN KEY (RECURRENCEPATTERN)
    REFERENCES TRECURRENCEPATTERN (OBJECTID)
;

ALTER TABLE TREPORTPERSONSETTINGS
    ADD CONSTRAINT TREPORTPERSONSETTINGS_FK_3 FOREIGN KEY (REPORTTEMPLATE)
    REFERENCES TEXPORTTEMPLATE (OBJECTID)
;



ALTER TABLE TREPORTPARAMETER
    ADD CONSTRAINT TREPORTPARAMETER_FK_1 FOREIGN KEY (REPORTPERSONSETTINGS)
    REFERENCES TREPORTPERSONSETTINGS (OBJECTID)
;



ALTER TABLE TMSPROJECTTASK
    ADD CONSTRAINT TMSPROJECTTASK_FK_1 FOREIGN KEY (WORKITEM)
    REFERENCES TWORKITEM (WORKITEMKEY)
;



ALTER TABLE TMSPROJECTEXCHANGE
    ADD CONSTRAINT TMSPROJECTEXCHANGE_FK_1 FOREIGN KEY (CHANGEDBY)
    REFERENCES TPERSON (PKEY)
;
INSERT INTO ID_TABLE (ID_TABLE_ID, TABLE_NAME, NEXT_ID, QUANTITY) VALUES(106, 'TRECURRENCEPATTERN', 1, 1);
INSERT INTO ID_TABLE (ID_TABLE_ID, TABLE_NAME, NEXT_ID, QUANTITY) VALUES(107, 'TREPORTPERSONSETTINGS', 1, 1);
INSERT INTO ID_TABLE (ID_TABLE_ID, TABLE_NAME, NEXT_ID, QUANTITY) VALUES(108, 'TREPORTPARAMETER', 1, 1);
INSERT INTO ID_TABLE (ID_TABLE_ID, TABLE_NAME, NEXT_ID, QUANTITY) VALUES(109, 'TMSPROJECTTASK', 1, 1);
INSERT INTO ID_TABLE (ID_TABLE_ID, TABLE_NAME, NEXT_ID, QUANTITY) VALUES(110, 'TMSPROJECTEXCHANGE', 1, 1);

INSERT INTO TCATEGORY (PKEY, LABEL, TYPEFLAG, SORTORDER, SYMBOL, TPUUID) VALUES (-1,'Task',1,-3,'task.gif','8e2216df-370c-446e-9348-a20936854b49');
INSERT INTO TCATEGORY (PKEY, LABEL, TYPEFLAG, SORTORDER, SYMBOL, TPUUID) VALUES (-2,'Sprint',2,-2,'sprint.gif','f150b9e8-55da-4ab7-95bd-0d19e8cceb46');
INSERT INTO TCATEGORY (PKEY, LABEL, TYPEFLAG, SORTORDER, SYMBOL, TPUUID) VALUES (-3,'Meeting',3,-1,'meeting.gif', '9ca87dc7-cf62-41a3-bce1-e13d0f5046e1');

