-- Oracle update script 310 to 320
-- $Id: migrate310to320.sql 658 2009-01-02 10:48:52Z friedj $


-- TATTRIBUTEOPTION
ALTER TABLE TATTRIBUTEOPTION ADD SORTORDER NUMBER;

-----------------------------------------------------------------------------
-- TREPORTLAYOUT
-----------------------------------------------------------------------------
DROP TABLE TREPORTLAYOUT CASCADE CONSTRAINTS;

CREATE TABLE TREPORTLAYOUT
(
    OBJECTID NUMBER NOT NULL,
    PROJECTTYPE NUMBER,
    PROJECT NUMBER,
    PERSON NUMBER,
    REPORTFIELD NUMBER NOT NULL,
    FPOSITION NUMBER NOT NULL,
    FWIDTH NUMBER NOT NULL,
    FSORTORDER NUMBER,
    FSORTDIR VARCHAR2 (1)
);

ALTER TABLE TREPORTLAYOUT
    ADD CONSTRAINT TREPORTLAYOUT_PK
PRIMARY KEY (OBJECTID);

ALTER TABLE TSITE ADD PREFERENCES VARCHAR2 (4000);

/* ******************************************** */
/* Additional changes from 3.2.0 B1 to 3.2.0 B2 */

ALTER TABLE TNOTIFY ADD RACIROLE VARCHAR2 (1);
ALTER TABLE TNOTIFY ADD THEGROUP NUMBER;
ALTER TABLE TPERSON ADD EMPLOYEEID VARCHAR2 (30);

DROP TABLE TACCOUNT CASCADE CONSTRAINTS;

CREATE TABLE TACCOUNT
(
    OBJECTID NUMBER NOT NULL,
    ACCOUNTNUMBER VARCHAR2 (30) NOT NULL,
    ACCOUNTNAME VARCHAR2 (80),
    ACTIVE VARCHAR2 (1),
    COSTCENTER VARCHAR2 (20)
);

ALTER TABLE TACCOUNT
    ADD CONSTRAINT TACCOUNT_PK
PRIMARY KEY (OBJECTID);



-----------------------------------------------------------------------------
-- TPROJECTACCOUNT
-----------------------------------------------------------------------------
-- DROP TABLE TPROJECTACCOUNT CASCADE CONSTRAINTS;

CREATE TABLE TPROJECTACCOUNT
(
    ACCOUNT NUMBER NOT NULL,
    PROJECT NUMBER NOT NULL
);

ALTER TABLE TPROJECTACCOUNT
    ADD CONSTRAINT TPROJECTACCOUNT_PK
PRIMARY KEY (ACCOUNT,PROJECT);



-----------------------------------------------------------------------------
-- TGROUP
-----------------------------------------------------------------------------
-- DROP TABLE TGROUP CASCADE CONSTRAINTS;

CREATE TABLE TGROUP
(
    OBJECTID NUMBER NOT NULL,
    EMAIL VARCHAR2 (60),
    PREFERENCES VARCHAR2(4000)
);

ALTER TABLE TGROUP
    ADD CONSTRAINT TGROUP_PK
PRIMARY KEY (OBJECTID);



-----------------------------------------------------------------------------
-- TGROUPMEMBER
-----------------------------------------------------------------------------
-- DROP TABLE TGROUPMEMBER CASCADE CONSTRAINTS;

CREATE TABLE TGROUPMEMBER
(
    ObjectID NUMBER NOT NULL,
    THEGROUP NUMBER NOT NULL,
    PERSON NUMBER NOT NULL
);

ALTER TABLE TGROUPMEMBER
    ADD CONSTRAINT TGROUPMEMBER_PK
PRIMARY KEY (OBJECTID);

ALTER TABLE TPROJECTACCOUNT
    ADD CONSTRAINT TPROJECTACCOUNT_FK_1 FOREIGN KEY (PROJECT)
    REFERENCES TPROJECT (PKEY)
;

ALTER TABLE TPROJECTACCOUNT
    ADD CONSTRAINT TPROJECTACCOUNT_FK_2 FOREIGN KEY (ACCOUNT)
    REFERENCES TACCOUNT (OBJECTID)
;


ALTER TABLE TGROUPMEMBER
    ADD CONSTRAINT TGROUPMEMBER_FK_1 FOREIGN KEY (THEGROUP)
    REFERENCES TGROUP (OBJECTID)
;

ALTER TABLE TGROUPMEMBER
    ADD CONSTRAINT TGROUPMEMBER_FK_2 FOREIGN KEY (PERSON)
    REFERENCES TPERSON (PKEY)
;



INSERT INTO ID_TABLE (ID_TABLE_ID, TABLE_NAME, NEXT_ID, QUANTITY) VALUES
			(47, 'TGROUP', 1, 1); 

INSERT INTO ID_TABLE (ID_TABLE_ID, TABLE_NAME, NEXT_ID, QUANTITY) VALUES
			(48, 'TGROUPMEMBER', 1, 1);   
            
UPDATE ID_TABLE SET NEXT_ID=14 WHERE TABLE_NAME='TCATEGORY';
            
COMMIT;










