-- ALTER TABLE `TCARDFIELD` ADD `HIDELABEL` char(1) DEFAULT 'Y';
ALTER TABLE `TCARDFIELD` ADD `ICONRENDERING` NUMBER(10,0) DEFAULT NULL;
  

ALTER TABLE `TITEMLINKHISTORY` ADD `SORTORDER` NUMBER(10,0) DEFAULT NULL;
ALTER TABLE `TPROJECT` ADD  `ISTEMPLATE` char(1) DEFAULT 'N';

ALTER TABLE `TSCREENFIELD` ADD `ICONRENDERING` NUMBER(10,0) DEFAULT NULL;

DROP TABLE IF EXISTS `TWFACTIVITYCONTEXTPARAMS`;
CREATE TABLE `TWFACTIVITYCONTEXTPARAMS` (
  `OBJECTID` NUMBER(10,0) NOT NULL,
  `WORKFLOWACTIVITY` NUMBER(10,0) NOT NULL,
  `ISSUETYPE` NUMBER(10,0) DEFAULT NULL,
  `PROJECTTYPE` NUMBER(10,0) DEFAULT NULL,
  `PROJECT` NUMBER(10,0) DEFAULT NULL,
  `SETTERORPARTID` NUMBER(10,0) DEFAULT NULL,
  `ACTIVITYPARAMS` VARCHAR2(4000),
  `TPUUID` VARCHAR2(36) DEFAULT NULL,
  PRIMARY KEY (`OBJECTID`),
  KEY `TWFACTIVITYCONTEXTPARAMSINDEX1` (`WORKFLOWACTIVITY`),
  KEY `TWFACTIVITYCONTEXTPARAMSINDEX2` (`ISSUETYPE`),
  KEY `TWFACTIVITYCONTEXTPARAMSINDEX3` (`PROJECTTYPE`),
  KEY `TWFACTIVITYCONTEXTPARAMSINDEX4` (`PROJECT`),
  KEY `TWFACTIVITYCONTEXTPARAMSINDEX5` (`TPUUID`),
  CONSTRAINT `TWFACTIVITYCONTEXTPARAMS_FK_4` FOREIGN KEY (`PROJECT`) REFERENCES `TPROJECT` (`PKEY`),
  CONSTRAINT `TWFACTIVITYCONTEXTPARAMS_FK_1` FOREIGN KEY (`WORKFLOWACTIVITY`) REFERENCES `TWORKFLOWACTIVITY` (`OBJECTID`),
  CONSTRAINT `TWFACTIVITYCONTEXTPARAMS_FK_2` FOREIGN KEY (`ISSUETYPE`) REFERENCES `TCATEGORY` (`PKEY`),
  CONSTRAINT `TWFACTIVITYCONTEXTPARAMS_FK_3` FOREIGN KEY (`PROJECTTYPE`) REFERENCES `TPROJECTTYPE` (`OBJECTID`)

) 


DROP TABLE IF EXISTS `TWORKFLOWCOMMENT`;

CREATE TABLE `TWORKFLOWCOMMENT` (
  `OBJECTID` NUMBER(10,0) NOT NULL,
  `DESCRIPTION` VARCHAR2(4000),
  `WORKFLOW` NUMBER(10,0) DEFAULT NULL,
  `NODEX` NUMBER(10,0) DEFAULT NULL,
  `NODEY` NUMBER(10,0) DEFAULT NULL,
  `TPUUID` VARCHAR2(36) DEFAULT NULL,
  PRIMARY KEY (`OBJECTID`),
  KEY `TWORKFLOWCOMMENTINDEX1` (`WORKFLOW`),
  KEY `TWORKFLOWCOMMENTINDEX2` (`TPUUID`),
  CONSTRAINT `TWORKFLOWCOMMENT_FK_1` FOREIGN KEY (`WORKFLOW`) REFERENCES `TWORKFLOWDEF` (`OBJECTID`)
)

ALTER TABLE `TWORKITEM` ADD `OVERBUDGET` char(1) DEFAULT 'N';
  
  
ALTER TABLE `TWORKITEMLINK` ADD `SORTORDER` NUMBER(10,0) DEFAULT NULL;






