ALTER TABLE TMAILTEMPLATEDEF DROP COLUMN MAILBODY;
ALTER TABLE TMAILTEMPLATEDEF ADD MAILBODY CLOB;
UPDATE TWORKITEM x  set x.SUPERIORWORKITEM=null where x.WORKITEMKEY in
(SELECT a.WORKITEMKEY FROM TWORKITEM a left join TWORKITEM b on a.SUPERIORWORKITEM=b.WORKITEMKEY where a.SUPERIORWORKITEM is not null and b.WORKITEMKEY is null);
ALTER TABLE TWORKITEM
    ADD CONSTRAINT TWORKITEM_FK_14 FOREIGN KEY (SUPERIORWORKITEM)
    REFERENCES TWORKITEM (WORKITEMKEY);