ALTER TABLE TACL ADD TPUUID VARCHAR2(36);
CREATE  INDEX TACLINDEX1 ON TACL (TPUUID);

ALTER TABLE TBASELINE ADD TPUUID VARCHAR2(36);
CREATE  INDEX TBASINDEX3 ON TBASELINE (TPUUID);

ALTER TABLE TCATEGORY ADD TPUUID VARCHAR2(36);
CREATE  INDEX TCATEGORYINDEX1 ON TCATEGORY (TPUUID);

ALTER TABLE TCLASS ADD TPUUID VARCHAR2(36);
CREATE  INDEX TCLASSINDEX1 ON TCLASS (TPUUID);

ALTER TABLE TDEPARTMENT ADD TPUUID VARCHAR2(36);
CREATE  INDEX TDEPARTMENTINDEX1 ON TDEPARTMENT (TPUUID);

ALTER TABLE TNOTIFY ADD TPUUID VARCHAR2(36);
CREATE  INDEX TNOTIFYINDEX1 ON TNOTIFY (TPUUID);

ALTER TABLE TPERSON ADD USERLEVEL NUMBER(10,0);
ALTER TABLE TPERSON ADD TPUUID VARCHAR2(36);
CREATE  INDEX TPERSINDEX2 ON TPERSON (TPUUID);

ALTER TABLE TPRIORITY ADD TPUUID VARCHAR2(36);
CREATE  INDEX TPRIOINDEX1 ON TPRIORITY (TPUUID);

ALTER TABLE TPPRIORITY ADD TPUUID VARCHAR2(36);
CREATE  INDEX TPPRIOINDEX1 ON TPPRIORITY (TPUUID);

ALTER TABLE TPROJCAT ADD TPUUID VARCHAR2(36);
CREATE  INDEX TPROJCATINDEX2 ON TPROJCAT (TPUUID);

ALTER TABLE TPROJECT ADD TPUUID VARCHAR2(36);
CREATE  INDEX TPROJECTINDEX ON TPROJECT (TPUUID);

ALTER TABLE TRELEASE ADD TPUUID VARCHAR2(36);
CREATE  INDEX TRELINDEX2 ON TRELEASE (TPUUID);

ALTER TABLE TROLE ADD TPUUID VARCHAR2(36);
CREATE  INDEX TROLEINDEX1 ON TROLE (TPUUID);

ALTER TABLE TSEVERITY ADD TPUUID VARCHAR2(36);
CREATE  INDEX TSEVINDEX1 ON TSEVERITY (TPUUID);

ALTER TABLE TPSEVERITY ADD TPUUID VARCHAR2(36);
CREATE  INDEX TPSEVINDEX1 ON TPSEVERITY (TPUUID);

ALTER TABLE TSTATE ADD TPUUID VARCHAR2(36);
CREATE  INDEX TSTATEINDEX1 ON TSTATE (TPUUID);

ALTER TABLE TSTATECHANGE ADD TPUUID VARCHAR2(36);
CREATE  INDEX TSTATECHANGEINDEX4 ON TSTATECHANGE (TPUUID);

ALTER TABLE TTRAIL ADD TPUUID VARCHAR2(36);
CREATE  INDEX TTRAILINDEX3 ON TTRAIL (TPUUID);

ALTER TABLE TWORKITEM ADD ARCHIVELEVEL NUMBER(10,0);
ALTER TABLE TWORKITEM ADD TPUUID VARCHAR2(36);
CREATE  INDEX TWIINDEX19 ON TWORKITEM (ARCHIVELEVEL);
CREATE  INDEX TWIINDEX20 ON TWORKITEM (TPUUID);

ALTER TABLE TCOMPUTEDVALUES ADD TPUUID VARCHAR2(36);
CREATE  INDEX TCVINDEX1 ON TCOMPUTEDVALUES (TPUUID);

ALTER TABLE TPRIVATEREPORTREPOSITORY ADD TPUUID VARCHAR2(36);
CREATE  INDEX TPRIVREPREPINDEX1 ON TPRIVATEREPORTREPOSITORY (TPUUID);

ALTER TABLE TPUBLICREPORTREPOSITORY ADD TPUUID VARCHAR2(36);
CREATE  INDEX TPUBREPREPINDEX1 ON TPUBLICREPORTREPOSITORY (TPUUID);

ALTER TABLE TPROJECTREPORTREPOSITORY ADD TPUUID VARCHAR2(36);
CREATE  INDEX TPROJREPREPINDEX1 ON TPROJECTREPORTREPOSITORY (TPUUID);

ALTER TABLE TACCOUNT ADD TPUUID VARCHAR2(36);
CREATE  INDEX TACCOUNTINDEX1 ON TACCOUNT (TPUUID);

ALTER TABLE TATTACHMENT ADD TPUUID VARCHAR2(36);
CREATE  INDEX TATTACHINDEX1 ON TATTACHMENT (TPUUID);

ALTER TABLE TCOST ADD TPUUID VARCHAR2(36);
CREATE  INDEX TCOSTINDEX1 ON TCOST (TPUUID);

ALTER TABLE TEFFORTTYPE ADD TPUUID VARCHAR2(36);
CREATE  INDEX TEFFORTTYPEINDEX1 ON TEFFORTTYPE (TPUUID);

ALTER TABLE TEFFORTUNIT ADD TPUUID VARCHAR2(36);
CREATE  INDEX TEFFORTUNITINDEX1 ON TEFFORTUNIT (TPUUID);

ALTER TABLE TDOCSTATE ADD TPUUID VARCHAR2(36);
CREATE  INDEX TDOCSTATEINDEX1 ON TDOCSTATE (TPUUID);

ALTER TABLE TDISABLEFIELD ADD TPUUID VARCHAR2(36);
CREATE  INDEX TDISABLEFINDEX1 ON TDISABLEFIELD (TPUUID);

ALTER TABLE TPLISTTYPE ADD TPUUID VARCHAR2(36);
CREATE  INDEX TPLISTTYPEINDEX1 ON TPLISTTYPE (TPUUID);

ALTER TABLE TPROJECTTYPE ADD TPUUID VARCHAR2(36);
CREATE  INDEX TPROJTYPEINDEX1 ON TPROJECTTYPE (TPUUID);

ALTER TABLE TPSTATE ADD TPUUID VARCHAR2(36);
CREATE  INDEX TPSTATEINDEX1 ON TPSTATE (TPUUID);

ALTER TABLE TSITE ADD TPUUID VARCHAR2(36);
CREATE  INDEX TSITEINDEX1 ON TSITE (TPUUID);

ALTER TABLE TWORKFLOW ADD TPUUID VARCHAR2(36);
CREATE  INDEX TWORKFLOWINDEX1 ON TWORKFLOW (TPUUID);

ALTER TABLE TWORKFLOWROLE ADD TPUUID VARCHAR2(36);
CREATE  INDEX TWORKFLOWROLEINDEX1 ON TWORKFLOWROLE (TPUUID);

ALTER TABLE TWORKFLOWCATEGORY ADD TPUUID VARCHAR2(36);
CREATE  INDEX TWORKFLOWCATINDEX1 ON TWORKFLOWCATEGORY (TPUUID);

ALTER TABLE TROLELISTTYPE ADD TPUUID VARCHAR2(36);
CREATE  INDEX TROLELISTTINDEX1 ON TROLELISTTYPE (TPUUID);

ALTER TABLE TISSUEATTRIBUTEVALUE ADD TPUUID VARCHAR2(36);
CREATE  INDEX TISSUEATTINDEX1 ON TISSUEATTRIBUTEVALUE (TPUUID);

ALTER TABLE TATTRIBUTEOPTION ADD TPUUID VARCHAR2(36);
CREATE  INDEX TATTOPTINDEX1 ON TATTRIBUTEOPTION (TPUUID);

ALTER TABLE TATTRIBUTECLASS ADD TPUUID VARCHAR2(36);
CREATE  INDEX TATTCLASSINDEX1 ON TATTRIBUTECLASS (TPUUID);

ALTER TABLE TATTRIBUTETYPE ADD TPUUID VARCHAR2(36);
CREATE  INDEX TATTTYPEINDEX1 ON TATTRIBUTETYPE (TPUUID);

ALTER TABLE TATTRIBUTE ADD TPUUID VARCHAR2(36);
CREATE  INDEX TATTRIBUTEINDEX1 ON TATTRIBUTE (TPUUID);

ALTER TABLE TREPORTLAYOUT ADD EXPANDING VARCHAR2(1);
ALTER TABLE TREPORTLAYOUT ADD LAYOUTKEY NUMBER(10,0);
ALTER TABLE TREPORTLAYOUT ADD TPUUID VARCHAR2(36);
CREATE  INDEX TREPORTLAYOUTINDEX1 ON TREPORTLAYOUT (FIELDTYPE);
CREATE  INDEX TREPORTLAYOUTINDEX2 ON TREPORTLAYOUT (LAYOUTKEY);
CREATE  INDEX TREPORTLAYOUTINDEX3 ON TREPORTLAYOUT (TPUUID);

ALTER TABLE TSCHEDULER ADD TPUUID VARCHAR2(36);
CREATE  INDEX TSCHEDULERINDEX1 ON TSCHEDULER (TPUUID);

ALTER TABLE TPROJECTACCOUNT ADD TPUUID VARCHAR2(36);
CREATE  INDEX TPROJACCINDEX1 ON TPROJECTACCOUNT (TPUUID);

ALTER TABLE TGROUPMEMBER ADD TPUUID VARCHAR2(36);
CREATE  INDEX TGROUPMEMINDEX1 ON TGROUPMEMBER (TPUUID);

ALTER TABLE TBUDGET ADD TPUUID VARCHAR2(36);
CREATE  INDEX TBUDGETINDEX3 ON TBUDGET (TPUUID);

ALTER TABLE TACTUALESTIMATEDBUDGET ADD TPUUID VARCHAR2(36);
CREATE  INDEX TACTUALESTINDEX3 ON TACTUALESTIMATEDBUDGET (TPUUID);

ALTER TABLE TSYSTEMSTATE ADD TPUUID VARCHAR2(36);
CREATE  INDEX TSYSTEMSTATEINDEX1 ON TSYSTEMSTATE (TPUUID);

ALTER TABLE TCOSTCENTER ADD TPUUID VARCHAR2(36);
CREATE  INDEX TCOSTCENTERINDEX1 ON TCOSTCENTER (TPUUID);

ALTER TABLE TMOTD ADD TPUUID VARCHAR2(36);
CREATE  INDEX TMOTDINDEX1 ON TMOTD (TPUUID);

ALTER TABLE TDASHBOARDSCREEN ADD TPUUID VARCHAR2(36);
CREATE  INDEX TDBSCREENINDEX1 ON TDASHBOARDSCREEN (TPUUID);

ALTER TABLE TDASHBOARDTAB ADD TPUUID VARCHAR2(36);
CREATE  INDEX TDBTABINDEX1 ON TDASHBOARDTAB (TPUUID);

ALTER TABLE TDASHBOARDPANEL ADD TPUUID VARCHAR2(36);
CREATE  INDEX TDBPANELINDEX1 ON TDASHBOARDPANEL (TPUUID);

ALTER TABLE TDASHBOARDFIELD ADD TPUUID VARCHAR2(36);
CREATE  INDEX TDBFIELDINDEX1 ON TDASHBOARDFIELD (TPUUID);

ALTER TABLE TDASHBOARDPARAMETER ADD TPUUID VARCHAR2(36);
CREATE  INDEX TDBPARAMINDEX1 ON TDASHBOARDPARAMETER (TPUUID);

ALTER TABLE TVERSIONCONTROLPARAMETER ADD TPUUID VARCHAR2(36);
CREATE  INDEX TVCPARAMINDEX1 ON TVERSIONCONTROLPARAMETER (TPUUID);

ALTER TABLE TFIELD ADD TPUUID VARCHAR2(36);
CREATE  INDEX TFIELDINDEX1 ON TFIELD (TPUUID);

ALTER TABLE TFIELDCONFIG ADD TPUUID VARCHAR2(36);
CREATE  INDEX TFIELDCONFIGINDEX1 ON TFIELDCONFIG (TPUUID);

ALTER TABLE TROLEFIELD ADD TPUUID VARCHAR2(36);
CREATE  INDEX TROLEFIELDINDEX1 ON TROLEFIELD (TPUUID);

ALTER TABLE TCONFIGOPTIONSROLE ADD TPUUID VARCHAR2(36);
CREATE  INDEX TCONFIGOPTINDEX1 ON TCONFIGOPTIONSROLE (TPUUID);

ALTER TABLE TTEXTBOXSETTINGS ADD TPUUID VARCHAR2(36);
CREATE  INDEX TTEXTBOXCONFINDEX1 ON TTEXTBOXSETTINGS (TPUUID);

ALTER TABLE TGENERALSETTINGS ADD TPUUID VARCHAR2(36);
CREATE  INDEX TGENERALCONFINDEX1 ON TGENERALSETTINGS (TPUUID);

ALTER TABLE TLIST ADD TPUUID VARCHAR2(36);
CREATE  INDEX TLISTINDEX1 ON TLIST (TPUUID);

ALTER TABLE TOPTION ADD TPUUID VARCHAR2(36);
CREATE  INDEX TOPTIONINDEX1 ON TOPTION (TPUUID);

ALTER TABLE TOPTIONSETTINGS ADD TPUUID VARCHAR2(36);
CREATE  INDEX TOPTIONCONFINDEX1 ON TOPTIONSETTINGS (TPUUID);

ALTER TABLE TATTRIBUTEVALUE ADD TPUUID VARCHAR2(36);
CREATE  INDEX TATTVALUEINDEX1 ON TATTRIBUTEVALUE (TPUUID);

ALTER TABLE TSCREEN ADD TPUUID VARCHAR2(36);
CREATE  INDEX TSCREENINDEX1 ON TSCREEN (TPUUID);

ALTER TABLE TSCREENTAB ADD TPUUID VARCHAR2(36);
CREATE  INDEX TSCREENTABINDEX1 ON TSCREENTAB (TPUUID);

ALTER TABLE TSCREENPANEL ADD TPUUID VARCHAR2(36);
CREATE  INDEX TSCREENPANELINDEX1 ON TSCREENPANEL (TPUUID);

ALTER TABLE TSCREENFIELD ADD TPUUID VARCHAR2(36);
CREATE  INDEX TSCREENFIELDINDEX1 ON TSCREENFIELD (TPUUID);

ALTER TABLE TACTION ADD TPUUID VARCHAR2(36);
CREATE  INDEX TACTIONINDEX1 ON TACTION (TPUUID);

ALTER TABLE TSCREENCONFIG ADD TPUUID VARCHAR2(36);
CREATE  INDEX TSCREENCONFINDEX1 ON TSCREENCONFIG (TPUUID);

ALTER TABLE TINITSTATE ADD TPUUID VARCHAR2(36);
CREATE  INDEX TINITSTATEINDEX1 ON TINITSTATE (TPUUID);

ALTER TABLE TEVENT ADD TPUUID VARCHAR2(36);
CREATE  INDEX TEVENTINDEX1 ON TEVENT (TPUUID);

ALTER TABLE TCLOB ADD TPUUID VARCHAR2(36);
CREATE  INDEX TCLOBINDEX1 ON TCLOB (TPUUID);

ALTER TABLE TNOTIFYFIELD ADD TPUUID VARCHAR2(36);
CREATE  INDEX TNOTIFYFIELDINDEX1 ON TNOTIFYFIELD (TPUUID);

ALTER TABLE TNOTIFYTRIGGER ADD TPUUID VARCHAR2(36);
CREATE  INDEX TNOTIFYTRIGGERINDEX1 ON TNOTIFYTRIGGER (TPUUID);

ALTER TABLE TNOTIFYSETTINGS ADD TPUUID VARCHAR2(36);
CREATE  INDEX TNOTIFYCONFINDEX1 ON TNOTIFYSETTINGS (TPUUID);

ALTER TABLE TQUERYREPOSITORY ADD TPUUID VARCHAR2(36);
CREATE  INDEX TQUERYREPINDEX1 ON TQUERYREPOSITORY (TPUUID);

ALTER TABLE TLOCALIZEDRESOURCES ADD TPUUID VARCHAR2(36);
CREATE  INDEX TLOCALRESINDEX1 ON TLOCALIZEDRESOURCES (TPUUID);

DROP TABLE TWORKITEMLINK;
CREATE TABLE TWORKITEMLINK
(
    OBJECTID NUMBER(10,0) NOT NULL,
    LINKISCROSSPROJECT CHAR(1) default 'N',
    LINKPRED NUMBER(10,0) NOT NULL,
    LINKSUCC NUMBER(10,0),
    LINKTYPE NUMBER(10,0) NOT NULL,
	LINKDIRECTION NUMBER(10,0),
    LINKLAG FLOAT,
    LINKLAGFORMAT NUMBER(10,0),
    STRINGVALUE1 VARCHAR2(255),
    STRINGVALUE2 VARCHAR2(255),
    STRINGVALUE3 VARCHAR2(255),
    INTEGERVALUE1 NUMBER(10,0),
    INTEGERVALUE2 NUMBER(10,0),
    INTEGERVALUE3 NUMBER(10,0),
    DATEVALUE TIMESTAMP,
    DESCRIPTION VARCHAR2(4000),
    EXTERNALLINK VARCHAR2(255),
    CHANGEDBY NUMBER(10,0),
    LASTEDIT TIMESTAMP,
    TPUUID VARCHAR2(36)
);

ALTER TABLE TWORKITEMLINK
    ADD CONSTRAINT TWORKITEMLINK_PK
PRIMARY KEY (OBJECTID);

CREATE INDEX TWORKITEMLINKINDEX1 ON TWORKITEMLINK (TPUUID);

DROP TABLE TLINKTYPE;

CREATE TABLE TLINKTYPE
(
    OBJECTID NUMBER(10,0) NOT NULL,
    NAME VARCHAR2(255) NOT NULL,
    REVERSENAME VARCHAR2(255),
    LEFTTORIGHTFIRST VARCHAR2(255),
    LEFTTORIGHTLEVEL VARCHAR2(255),
    LEFTTORIGHTALL VARCHAR2(255),
    RIGHTTOLEFTFIRST VARCHAR2(255),
    RIGHTTOLEFTLEVEL VARCHAR2(255),
    RIGHTTOLEFTALL VARCHAR2(255),
    LINKDIRECTION NUMBER(10,0),
    LINKTYPEPLUGIN VARCHAR2(255),
    MOREPROPS VARCHAR2(4000),
    TPUUID VARCHAR2(36)
);

ALTER TABLE TLINKTYPE
    ADD CONSTRAINT TLINKTYPE_PK
PRIMARY KEY (OBJECTID);

CREATE INDEX TLINKTYPEINDEX1 ON TLINKTYPE (TPUUID);



COMMENT ON COLUMN TLINKTYPE.MOREPROPS IS 'This is a multi-purpose field. It contains a text in .properties format with a number of additional attributes.';



ALTER TABLE TLOGGINGLEVEL ADD TPUUID VARCHAR2(36);
CREATE  INDEX TLOGLEVELINDEX1 ON TLOGGINGLEVEL (TPUUID);

ALTER TABLE TWORKITEMLOCK ADD TPUUID VARCHAR2(36);
CREATE  INDEX TWORKITEMLOCKINDEX1 ON TWORKITEMLOCK (TPUUID);

ALTER TABLE TEXPORTTEMPLATE ADD TPUUID VARCHAR2(36);
CREATE  INDEX TEXPOPRTTEMPINDEX1 ON TEXPORTTEMPLATE (TPUUID);

ALTER TABLE TEMAILPROCESSED ADD TPUUID VARCHAR2(36);
CREATE  INDEX TEMAILPROCINDEX1 ON TEMAILPROCESSED (TPUUID);

-----------------------------------------------------------------------------
-- TAPPLICATIONCONTEXT
-----------------------------------------------------------------------------
--DROP TABLE TAPPLICATIONCONTEXT CASCADE CONSTRAINTS;

CREATE TABLE TAPPLICATIONCONTEXT
(
    OBJECTID NUMBER(10,0) NOT NULL,
    LOGGEDFULLUSERS NUMBER(10,0),
    LOGGEDLIMITEDUSERS NUMBER(10,0),
    REFRESHCONFIGURATION NUMBER(10,0) default 0 NOT NULL,
    FIRSTTIME NUMBER(10,0) default 0 NOT NULL,
    MOREPROPS VARCHAR2(4000)
);

ALTER TABLE TAPPLICATIONCONTEXT
    ADD CONSTRAINT TAPPLICATIONCONTEXT_PK
PRIMARY KEY (OBJECTID);




COMMENT ON COLUMN TAPPLICATIONCONTEXT.REFRESHCONFIGURATION IS 'In case of configuration change, this is set to the number of nodes. As each node updates its configuration, the count is decremented.';
COMMENT ON COLUMN TAPPLICATIONCONTEXT.FIRSTTIME IS 'When this is the first start after a version upgrade, go to site configuration';
COMMENT ON COLUMN TAPPLICATIONCONTEXT.MOREPROPS IS 'This is a multi-purpose field. It contains a text in .properties format with a number of additional attributes.';


-----------------------------------------------------------------------------
-- TLOGGEDINUSERS
-----------------------------------------------------------------------------
--DROP TABLE TLOGGEDINUSERS CASCADE CONSTRAINTS;

CREATE TABLE TLOGGEDINUSERS
(
    OBJECTID NUMBER(10,0) NOT NULL,
    NODEADDRESS NUMBER(10,0),
    SESSIONID VARCHAR2(255),
    LOGGEDUSER NUMBER(10,0) NOT NULL,
    USERLEVEL NUMBER(10,0),
    LASTUPDATE TIMESTAMP,
    MOREPROPS VARCHAR2(4000)
);

ALTER TABLE TLOGGEDINUSERS
    ADD CONSTRAINT TLOGGEDINUSERS_PK
PRIMARY KEY (OBJECTID);




COMMENT ON COLUMN TLOGGEDINUSERS.OBJECTID IS 'This helps with the bookkeeping of logged in users';
COMMENT ON COLUMN TLOGGEDINUSERS.NODEADDRESS IS 'The ip address of the node which counts these numbers';
COMMENT ON COLUMN TLOGGEDINUSERS.SESSIONID IS 'The session id under which this user was logged';
COMMENT ON COLUMN TLOGGEDINUSERS.LOGGEDUSER IS 'Foreign key reference to TPERSON';
COMMENT ON COLUMN TLOGGEDINUSERS.USERLEVEL IS 'Indicates a full or limited user';
COMMENT ON COLUMN TLOGGEDINUSERS.LASTUPDATE IS 'This enables to clean the table in case of a crash';
COMMENT ON COLUMN TLOGGEDINUSERS.MOREPROPS IS 'This is a multi-purpose field. It contains a text in .properties format with a number of additional attributes.';


-----------------------------------------------------------------------------
-- CLUSTERNODE
-----------------------------------------------------------------------------
--DROP TABLE CLUSTERNODE CASCADE CONSTRAINTS;

CREATE TABLE CLUSTERNODE
(
    OBJECTID NUMBER(10,0) NOT NULL,
    NODEADDRESS VARCHAR2(40),
    NODEURL VARCHAR2(255),
    LASTUPDATE TIMESTAMP,
    MASTERNODE NUMBER(10,0) default 0,
    RELOADCONFIG NUMBER(10,0) default 0
);

ALTER TABLE CLUSTERNODE
    ADD CONSTRAINT CLUSTERNODE_PK
PRIMARY KEY (OBJECTID);



COMMENT ON TABLE CLUSTERNODE IS 'This table holds properties for each node in the cluster';

COMMENT ON COLUMN CLUSTERNODE.NODEADDRESS IS 'The ip address of this node';
COMMENT ON COLUMN CLUSTERNODE.NODEURL IS 'The URL where the managing instance of this node can be reached';
COMMENT ON COLUMN CLUSTERNODE.LASTUPDATE IS 'This enables to clean the table in case of a crash';
COMMENT ON COLUMN CLUSTERNODE.MASTERNODE IS 'If this is the master node, this value is > 0';
COMMENT ON COLUMN CLUSTERNODE.RELOADCONFIG IS 'If this is not 0, reload the configuration from TSITE';


-----------------------------------------------------------------------------
-- TENTITYCHANGES
-----------------------------------------------------------------------------
--DROP TABLE TENTITYCHANGES CASCADE CONSTRAINTS;

CREATE TABLE TENTITYCHANGES
(
    OBJECTID NUMBER(10,0) NOT NULL,
    ENTITYKEY NUMBER(10,0) NOT NULL,
    ENTITYTYPE NUMBER(10,0) NOT NULL,
    CLUSTERNODE NUMBER(10,0)
);

ALTER TABLE TENTITYCHANGES
    ADD CONSTRAINT TENTITYCHANGES_PK
PRIMARY KEY (OBJECTID);

CREATE INDEX ENTITYCHANGESINDEX1 ON TENTITYCHANGES (ENTITYTYPE);
CREATE INDEX ENTITYCHANGESINDEX2 ON TENTITYCHANGES (CLUSTERNODE);


COMMENT ON TABLE TENTITYCHANGES IS 'This table holds the changed entities for updating the full text search index in each clusternode';



-----------------------------------------------------------------------------
-- TSUMMARYMAIL
-----------------------------------------------------------------------------
--DROP TABLE TSUMMARYMAIL CASCADE CONSTRAINTS;

CREATE TABLE TSUMMARYMAIL
(
    OBJECTID NUMBER(10,0) NOT NULL,
    WORKITEM NUMBER(10,0) NOT NULL,
    PERSONFROM NUMBER(10,0) NOT NULL,
    FROMADDRESS VARCHAR2(255),
    MAILSUBJECT VARCHAR2(255),
    WORKITEMLINK VARCHAR2(255),
    PERSONTO NUMBER(10,0) NOT NULL,
    LASTEDIT TIMESTAMP,
    TPUUID VARCHAR2(36)
);

ALTER TABLE TSUMMARYMAIL
    ADD CONSTRAINT TSUMMARYMAIL_PK
PRIMARY KEY (OBJECTID);

CREATE INDEX TSUMMARYMAILINDEX1 ON TSUMMARYMAIL (WORKITEM);
CREATE INDEX TSUMMARYMAILINDEX2 ON TSUMMARYMAIL (PERSONFROM);
CREATE INDEX TSUMMARYMAILINDEX3 ON TSUMMARYMAIL (PERSONTO);
CREATE INDEX TSUMMARYMAILINDEX4 ON TSUMMARYMAIL (TPUUID);


COMMENT ON TABLE TSUMMARYMAIL IS 'This table holds the summary mail parts before they are sent';



-----------------------------------------------------------------------------
-- TOUTLINECODE
-----------------------------------------------------------------------------
--DROP TABLE TOUTLINECODE CASCADE CONSTRAINTS;

CREATE TABLE TOUTLINECODE
(
    OBJECTID NUMBER(10,0) NOT NULL,
    PARENTID NUMBER(10,0),
    LEVELNO NUMBER(10,0) NOT NULL,
    LEVELCODE VARCHAR2(50) NOT NULL,
    FULLCODE VARCHAR2(255) NOT NULL,
    ENTITYID NUMBER(10,0) NOT NULL,
    OUTLINETEMPLATE NUMBER(10,0) NOT NULL,
    TPUUID VARCHAR2(36)
);

ALTER TABLE TOUTLINECODE
    ADD CONSTRAINT TOUTLINECODE_PK
PRIMARY KEY (OBJECTID);

CREATE INDEX TOUTLINECODEINDEX1 ON TOUTLINECODE (PARENTID);
CREATE INDEX TOUTLINECODEINDEX2 ON TOUTLINECODE (ENTITYID);
CREATE INDEX TOUTLINECODEINDEX3 ON TOUTLINECODE (TPUUID);


COMMENT ON TABLE TOUTLINECODE IS 'Holds the outline codes';



-----------------------------------------------------------------------------
-- TOUTLINETEMPLATEDEF
-----------------------------------------------------------------------------
--DROP TABLE TOUTLINETEMPLATEDEF CASCADE CONSTRAINTS;

CREATE TABLE TOUTLINETEMPLATEDEF
(
    OBJECTID NUMBER(10,0) NOT NULL,
    LEVELNO NUMBER(10,0) NOT NULL,
    SEQUENCETYPE NUMBER(10,0) NOT NULL,
    LISTID NUMBER(10,0),
    SEQUENCELENGTH NUMBER(10,0) NOT NULL,
    SEPARATORCHAR VARCHAR2(10) NOT NULL,
    OUTLINETEMPLATE NUMBER(10,0) NOT NULL,
    TPUUID VARCHAR2(36)
);

ALTER TABLE TOUTLINETEMPLATEDEF
    ADD CONSTRAINT TOUTLINETEMPLATEDEF_PK
PRIMARY KEY (OBJECTID);

CREATE INDEX TOUTLINETEMPLATEDEFINDEX1 ON TOUTLINETEMPLATEDEF (TPUUID);


COMMENT ON TABLE TOUTLINETEMPLATEDEF IS 'defines the parts of an outline code';



-----------------------------------------------------------------------------
-- TOUTLINETEMPLATE
-----------------------------------------------------------------------------
--DROP TABLE TOUTLINETEMPLATE CASCADE CONSTRAINTS;

CREATE TABLE TOUTLINETEMPLATE
(
    OBJECTID NUMBER(10,0) NOT NULL,
    LABEL VARCHAR2(255) NOT NULL,
    ENTITYTYPE NUMBER(10,0) NOT NULL,
    TPUUID VARCHAR2(36)
);

ALTER TABLE TOUTLINETEMPLATE
    ADD CONSTRAINT TOUTLINETEMPLATE_PK
PRIMARY KEY (OBJECTID);

CREATE INDEX TOUTLINETEMPLATEINDEX1 ON TOUTLINETEMPLATE (TPUUID);


COMMENT ON TABLE TOUTLINETEMPLATE IS 'Holds the association between the entity and the outline template';



-----------------------------------------------------------------------------
-- THISTORYTRANSACTION
-----------------------------------------------------------------------------
--DROP TABLE THISTORYTRANSACTION CASCADE CONSTRAINTS;

CREATE TABLE THISTORYTRANSACTION
(
    OBJECTID NUMBER(10,0) NOT NULL,
    WORKITEM NUMBER(10,0) NOT NULL,
    CHANGEDBY NUMBER(10,0) NOT NULL,
    LASTEDIT TIMESTAMP,
    TPUUID VARCHAR2(36)
);

ALTER TABLE THISTORYTRANSACTION
    ADD CONSTRAINT THISTORYTRANSACTION_PK
PRIMARY KEY (OBJECTID);

CREATE INDEX THISTORYTRANSINDEX1 ON THISTORYTRANSACTION (WORKITEM);
CREATE INDEX THISTORYTRANSINDEX2 ON THISTORYTRANSACTION (CHANGEDBY);
CREATE INDEX THISTORYTRANSINDEX3 ON THISTORYTRANSACTION (TPUUID);





-----------------------------------------------------------------------------
-- TFIELDCHANGE
-----------------------------------------------------------------------------
--DROP TABLE TFIELDCHANGE CASCADE CONSTRAINTS;

CREATE TABLE TFIELDCHANGE
(
    OBJECTID NUMBER(10,0) NOT NULL,
    FIELDKEY NUMBER(10,0) NOT NULL,
    HISTORYTRANSACTION NUMBER(10,0) NOT NULL,
    NEWTEXTVALUE VARCHAR2(255),
    OLDTEXTVALUE VARCHAR2(255),
    NEWINTEGERVALUE NUMBER(10,0),
    OLDINTEGERVALUE NUMBER(10,0),
    NEWDOUBLEVALUE FLOAT,
    OLDDOUBLEVALUE FLOAT,
    NEWDATEVALUE TIMESTAMP,
    OLDDATEVALUE TIMESTAMP,
    NEWCHARACTERVALUE CHAR(1),
    OLDCHARACTERVALUE CHAR(1),
    NEWLONGTEXTVALUE VARCHAR2(4000),
    OLDLONGTEXTVALUE VARCHAR2(4000),
    NEWSYSTEMOPTIONID NUMBER(10,0),
    OLDSYSTEMOPTIONID NUMBER(10,0),
    SYSTEMOPTIONTYPE NUMBER(10,0),
    NEWCUSTOMOPTIONID NUMBER(10,0),
    OLDCUSTOMOPTIONID NUMBER(10,0),
    PARAMETERCODE NUMBER(10,0),
    VALIDVALUE NUMBER(10,0),
    PARENTCOMMENT NUMBER(10,0),
    TIMESEDITED NUMBER(10,0),
    TPUUID VARCHAR2(36)
);

ALTER TABLE TFIELDCHANGE
    ADD CONSTRAINT TFIELDCHANGE_PK
PRIMARY KEY (OBJECTID);

CREATE INDEX TFIELDCHANGE1 ON TFIELDCHANGE (FIELDKEY);
CREATE INDEX TFIELDCHANGE2 ON TFIELDCHANGE (HISTORYTRANSACTION);
CREATE INDEX TFIELDCHANGE3 ON TFIELDCHANGE (VALIDVALUE);
CREATE INDEX TFIELDCHANGE4 ON TFIELDCHANGE (TPUUID);





-----------------------------------------------------------------------------
-- TSCRIPTS
-----------------------------------------------------------------------------
--DROP TABLE TSCRIPTS CASCADE CONSTRAINTS;

CREATE TABLE TSCRIPTS
(
    OBJECTID NUMBER(10,0) NOT NULL,
    CHANGEDBY NUMBER(10,0),
    LASTEDIT TIMESTAMP,
    SCRIPTVERSION NUMBER(10,0),
    ORIGINALVERSION NUMBER(10,0),
    PROJECTTYPE NUMBER(10,0),
    PROJECT NUMBER(10,0),
    SCRIPTTYPE NUMBER(10,0),
    CLAZZNAME VARCHAR2(253),
    SOURCECODE VARCHAR2(4000),
    TPUUID VARCHAR2(36)
);

ALTER TABLE TSCRIPTS
    ADD CONSTRAINT TSCRIPTS_PK
PRIMARY KEY (OBJECTID);

CREATE INDEX TSCRIPTINDEX1 ON TSCRIPTS (CLAZZNAME);
CREATE INDEX TSCRIPTINDEX2 ON TSCRIPTS (PROJECTTYPE);
CREATE INDEX TSCRIPTINDEX3 ON TSCRIPTS (PROJECT);
CREATE INDEX TSCRIPTINDEX4 ON TSCRIPTS (TPUUID);


COMMENT ON TABLE TSCRIPTS IS 'Contains Groovy scripts';



-----------------------------------------------------------------------------
-- TREVISION
-----------------------------------------------------------------------------
--DROP TABLE TREVISION CASCADE CONSTRAINTS;

CREATE TABLE TREVISION
(
    OBJECTID NUMBER(10,0) NOT NULL,
    FILENAME VARCHAR2(255) NOT NULL,
    AUTHORNAME VARCHAR2(255) NOT NULL,
    CHANGEDESCRIPTION VARCHAR2(4000),
    REVISIONDATE TIMESTAMP NOT NULL,
    REVISIONNUMBR VARCHAR2(255) NOT NULL,
    REPOSITORYKEY NUMBER(10,0) NOT NULL,
    TPUUID VARCHAR2(36)
);

ALTER TABLE TREVISION
    ADD CONSTRAINT TREVISION_PK
PRIMARY KEY (OBJECTID);

CREATE INDEX TREVISIONINDEX1 ON TREVISION (TPUUID);


COMMENT ON TABLE TREVISION IS 'Comments from the version control system';



-----------------------------------------------------------------------------
-- TREVISIONWORKITEMS
-----------------------------------------------------------------------------
--DROP TABLE TREVISIONWORKITEMS CASCADE CONSTRAINTS;

CREATE TABLE TREVISIONWORKITEMS
(
    OBJECTID NUMBER(10,0) NOT NULL,
    WORKITEMKEY NUMBER(10,0) NOT NULL,
    REVISIONKEY NUMBER(10,0) NOT NULL,
    TPUUID VARCHAR2(36)
);

ALTER TABLE TREVISIONWORKITEMS
    ADD CONSTRAINT TREVISIONWORKITEMS_PK
PRIMARY KEY (OBJECTID);

CREATE INDEX TREVISIONWORKITEMSINDEX1 ON TREVISIONWORKITEMS (WORKITEMKEY);
CREATE INDEX TREVISIONWORKITEMSINDEX2 ON TREVISIONWORKITEMS (TPUUID);


COMMENT ON TABLE TREVISIONWORKITEMS IS 'Comments from the version control system';



-----------------------------------------------------------------------------
-- TREPOSITORY
-----------------------------------------------------------------------------
--DROP TABLE TREPOSITORY CASCADE CONSTRAINTS;

CREATE TABLE TREPOSITORY
(
    OBJECTID NUMBER(10,0) NOT NULL,
    REPOSITORYTYPE VARCHAR2(255) NOT NULL,
    REPOSITORYURL VARCHAR2(255) NOT NULL,
    STARTDATE TIMESTAMP,
    ENDDATE TIMESTAMP,
    STATUSKEY NUMBER(10,0) NOT NULL,
    TPUUID VARCHAR2(36)
);

ALTER TABLE TREPOSITORY
    ADD CONSTRAINT TREPOSITORY_PK
PRIMARY KEY (OBJECTID);

CREATE INDEX TREPOSITORYINDEX1 ON TREPOSITORY (TPUUID);


COMMENT ON TABLE TREPOSITORY IS 'Version control repositiories defined';


-----------------------------------------------------------------------------
-- TTEMPLATEPERSON
-----------------------------------------------------------------------------
--DROP TABLE TTEMPLATEPERSON CASCADE CONSTRAINTS;

CREATE TABLE TTEMPLATEPERSON
(
    OBJECTID NUMBER(10,0) NOT NULL,
    REPORTTEMPLATE NUMBER(10,0) NOT NULL,
    PERSON NUMBER(10,0) NOT NULL,
    RIGHTFLAG NUMBER(10,0),
    TPUUID VARCHAR2(36)
);

ALTER TABLE TTEMPLATEPERSON
    ADD CONSTRAINT TTEMPLATEPERSON_PK
PRIMARY KEY (OBJECTID);

CREATE INDEX TTEMPLATEPERSONINDEX1 ON TTEMPLATEPERSON (TPUUID);


COMMENT ON TABLE TTEMPLATEPERSON IS 'The persons who can or can not run a report template';

COMMENT ON COLUMN TTEMPLATEPERSON.RIGHTFLAG IS 'whether the right is added or revoked';

ALTER TABLE TWORKITEMLINK
    ADD CONSTRAINT TWORKITEMLINK_FK_1 FOREIGN KEY (LINKPRED)
    REFERENCES TWORKITEM (WORKITEMKEY)
;

ALTER TABLE TWORKITEMLINK
    ADD CONSTRAINT TWORKITEMLINK_FK_2 FOREIGN KEY (LINKSUCC)
    REFERENCES TWORKITEM (WORKITEMKEY)
;

ALTER TABLE TWORKITEMLINK
    ADD CONSTRAINT TWORKITEMLINK_FK_3 FOREIGN KEY (LINKTYPE)
    REFERENCES TLINKTYPE (OBJECTID)
;

ALTER TABLE TWORKITEMLINK
    ADD CONSTRAINT TWORKITEMLINK_FK_4 FOREIGN KEY (CHANGEDBY)
    REFERENCES TPERSON (PKEY)
;


ALTER TABLE TLOGGEDINUSERS
    ADD CONSTRAINT TLOGGEDINUSERS_FK_1 FOREIGN KEY (LOGGEDUSER)
    REFERENCES TPERSON (PKEY);

ALTER TABLE TLOGGEDINUSERS
    ADD CONSTRAINT TLOGGEDINUSERS_FK_2 FOREIGN KEY (NODEADDRESS)
    REFERENCES CLUSTERNODE (OBJECTID);

ALTER TABLE TENTITYCHANGES
    ADD CONSTRAINT TENTITYCHANGES_FK_1 FOREIGN KEY (CLUSTERNODE)
    REFERENCES CLUSTERNODE (OBJECTID);

ALTER TABLE TSUMMARYMAIL
    ADD CONSTRAINT TSUMMARYMAIL_FK_1 FOREIGN KEY (WORKITEM)
    REFERENCES TWORKITEM (WORKITEMKEY);

ALTER TABLE TSUMMARYMAIL
    ADD CONSTRAINT TSUMMARYMAIL_FK_2 FOREIGN KEY (PERSONFROM)
    REFERENCES TPERSON (PKEY);

ALTER TABLE TSUMMARYMAIL
    ADD CONSTRAINT TSUMMARYMAIL_FK_3 FOREIGN KEY (PERSONTO)
    REFERENCES TPERSON (PKEY);

ALTER TABLE TOUTLINECODE
    ADD CONSTRAINT TOUTLINECODE_FK_1 FOREIGN KEY (OUTLINETEMPLATE)
    REFERENCES TOUTLINETEMPLATE (OBJECTID);

ALTER TABLE TOUTLINETEMPLATEDEF
    ADD CONSTRAINT TOUTLINETEMPLATEDEF_FK_1 FOREIGN KEY (OUTLINETEMPLATE)
    REFERENCES TOUTLINETEMPLATE (OBJECTID);

ALTER TABLE THISTORYTRANSACTION
    ADD CONSTRAINT THISTORYTRANSACTION_FK_1 FOREIGN KEY (WORKITEM)
    REFERENCES TWORKITEM (WORKITEMKEY)
;

ALTER TABLE THISTORYTRANSACTION
    ADD CONSTRAINT THISTORYTRANSACTION_FK_2 FOREIGN KEY (CHANGEDBY)
    REFERENCES TPERSON (PKEY)
;

ALTER TABLE TFIELDCHANGE
    ADD CONSTRAINT TFIELDCHANGE_FK_1 FOREIGN KEY (HISTORYTRANSACTION)
    REFERENCES THISTORYTRANSACTION (OBJECTID)
;

ALTER TABLE TFIELDCHANGE
    ADD CONSTRAINT TFIELDCHANGE_FK_2 FOREIGN KEY (PARENTCOMMENT)
    REFERENCES TFIELDCHANGE (OBJECTID)
;

ALTER TABLE TFIELDCHANGE
    ADD CONSTRAINT TFIELDCHANGE_FK_3 FOREIGN KEY (NEWCUSTOMOPTIONID)
    REFERENCES TOPTION (OBJECTID)
;

ALTER TABLE TFIELDCHANGE
    ADD CONSTRAINT TFIELDCHANGE_FK_4 FOREIGN KEY (OLDCUSTOMOPTIONID)
    REFERENCES TOPTION (OBJECTID)
;

ALTER TABLE TSCRIPTS
    ADD CONSTRAINT TSCRIPTS_FK_1 FOREIGN KEY (CHANGEDBY)
    REFERENCES TPERSON (PKEY)
;

ALTER TABLE TSCRIPTS
    ADD CONSTRAINT TSCRIPTS_FK_2 FOREIGN KEY (PROJECTTYPE)
    REFERENCES TPROJECTTYPE (OBJECTID)
;

ALTER TABLE TSCRIPTS
    ADD CONSTRAINT TSCRIPTS_FK_3 FOREIGN KEY (PROJECT)
    REFERENCES TPROJECT (PKEY)
;

ALTER TABLE TREVISION
    ADD CONSTRAINT TREVISION_FK_1 FOREIGN KEY (REPOSITORYKEY)
    REFERENCES TREPOSITORY (OBJECTID)
;

ALTER TABLE TREVISIONWORKITEMS
    ADD CONSTRAINT TREVISIONWORKITEMS_FK_1 FOREIGN KEY (REVISIONKEY)
    REFERENCES TREVISION (OBJECTID)
;

ALTER TABLE TTEMPLATEPERSON
    ADD CONSTRAINT TTEMPLATEPERSON_FK_1 FOREIGN KEY (PERSON)
    REFERENCES TPERSON (PKEY)
;

ALTER TABLE TTEMPLATEPERSON
    ADD CONSTRAINT TTEMPLATEPERSON_FK_2 FOREIGN KEY (REPORTTEMPLATE)
    REFERENCES TEXPORTTEMPLATE (OBJECTID)
;

ALTER TABLE TCATEGORY ADD ICONKEY NUMBER(10,0);
ALTER TABLE TPRIORITY ADD ICONKEY NUMBER(10,0);
ALTER TABLE TSEVERITY ADD ICONKEY NUMBER(10,0);
ALTER TABLE TSTATE ADD ICONKEY NUMBER(10,0);
ALTER TABLE TOPTION ADD ICONKEY NUMBER(10,0);
ALTER TABLE TLINKTYPE ADD OUTWARDICONKEY NUMBER(10,0);
ALTER TABLE TLINKTYPE ADD INWARDICONKEY NUMBER(10,0);
-----------------------------------------------------------------------------
-- TBLOB
-----------------------------------------------------------------------------
--DROP TABLE TBLOB CASCADE CONSTRAINTS;

CREATE TABLE TBLOB
(
    OBJECTID NUMBER(10,0) NOT NULL,
    BLOBVALUE BLOB,
    TPUUID VARCHAR2(36)
);

ALTER TABLE TBLOB
    ADD CONSTRAINT TBLOB_PK
PRIMARY KEY (OBJECTID);

CREATE INDEX TBLOBINDEX1 ON TBLOB (TPUUID);



ALTER TABLE TCATEGORY
    ADD CONSTRAINT TCATEGORY_FK_1 FOREIGN KEY (ICONKEY)
    REFERENCES TBLOB (OBJECTID)
;

ALTER TABLE TPRIORITY
    ADD CONSTRAINT TPRIORITY_FK_1 FOREIGN KEY (ICONKEY)
    REFERENCES TBLOB (OBJECTID)
;

ALTER TABLE TSEVERITY
    ADD CONSTRAINT TSEVERITY_FK_1 FOREIGN KEY (ICONKEY)
    REFERENCES TBLOB (OBJECTID)
;

ALTER TABLE TSTATE
    ADD CONSTRAINT TSTATE_FK_1 FOREIGN KEY (ICONKEY)
    REFERENCES TBLOB (OBJECTID)
;

ALTER TABLE TOPTION
    ADD CONSTRAINT TOPTION_FK_2 FOREIGN KEY (ICONKEY)
    REFERENCES TBLOB (OBJECTID)
;

ALTER TABLE TLINKTYPE
    ADD CONSTRAINT TLINKTYPE_FK_1 FOREIGN KEY (OUTWARDICONKEY)
    REFERENCES TBLOB (OBJECTID)
;

ALTER TABLE TLINKTYPE
    ADD CONSTRAINT TLINKTYPE_FK_2 FOREIGN KEY (INWARDICONKEY)
    REFERENCES TBLOB (OBJECTID)
;


ALTER TABLE TPROJECT ADD PREFIX VARCHAR2(10);
ALTER TABLE TPROJECT ADD LASTID NUMBER(10,0);

CREATE  INDEX TPROJECTINDEXIDPF ON TPROJECT (PREFIX);

ALTER TABLE TWORKITEM ADD IDNUMBER NUMBER(10,0);

CREATE  INDEX TWIINDEX21 ON TWORKITEM (IDNUMBER);

INSERT INTO ID_TABLE (ID_TABLE_ID, TABLE_NAME, NEXT_ID, QUANTITY) VALUES(90, 'TAPPLICATIONCONTEXT', 1, 1);
INSERT INTO ID_TABLE (ID_TABLE_ID, TABLE_NAME, NEXT_ID, QUANTITY) VALUES(91, 'TLOGGEDINUSERS', 1, 1);
INSERT INTO ID_TABLE (ID_TABLE_ID, TABLE_NAME, NEXT_ID, QUANTITY) VALUES(92, 'TEMAILCONNECTIONPOINT', 1, 1);
INSERT INTO ID_TABLE (ID_TABLE_ID, TABLE_NAME, NEXT_ID, QUANTITY) VALUES(93, 'CLUSTERNODE', 1, 1);
INSERT INTO ID_TABLE (ID_TABLE_ID, TABLE_NAME, NEXT_ID, QUANTITY) VALUES(94, 'TSUMMARYMAIL', 1, 1);
INSERT INTO ID_TABLE (ID_TABLE_ID, TABLE_NAME, NEXT_ID, QUANTITY) VALUES(95, 'TOUTLINECODE', 1, 1);
INSERT INTO ID_TABLE (ID_TABLE_ID, TABLE_NAME, NEXT_ID, QUANTITY) VALUES(96, 'TOUTLINETEMPLATEDEF', 1, 1);
INSERT INTO ID_TABLE (ID_TABLE_ID, TABLE_NAME, NEXT_ID, QUANTITY) VALUES(97, 'TOUTLINETEMPLATE', 1, 1);
INSERT INTO ID_TABLE (ID_TABLE_ID, TABLE_NAME, NEXT_ID, QUANTITY) VALUES(98, 'THISTORYTRANSACTION', 1, 1);
INSERT INTO ID_TABLE (ID_TABLE_ID, TABLE_NAME, NEXT_ID, QUANTITY) VALUES(99, 'TFIELDCHANGE', 1, 1);
INSERT INTO ID_TABLE (ID_TABLE_ID, TABLE_NAME, NEXT_ID, QUANTITY) VALUES(100, 'TSCRIPTS', 1, 1);
INSERT INTO ID_TABLE (ID_TABLE_ID, TABLE_NAME, NEXT_ID, QUANTITY) VALUES(101, 'TREVISION', 1, 1);
INSERT INTO ID_TABLE (ID_TABLE_ID, TABLE_NAME, NEXT_ID, QUANTITY) VALUES(102, 'TREVISIONWORKITEMS', 1, 1);
INSERT INTO ID_TABLE (ID_TABLE_ID, TABLE_NAME, NEXT_ID, QUANTITY) VALUES(103, 'TREPOSITORY', 1, 1);
INSERT INTO ID_TABLE (ID_TABLE_ID, TABLE_NAME, NEXT_ID, QUANTITY) VALUES(104, 'TTEMPLATEPERSON', 1, 1);
INSERT INTO ID_TABLE (ID_TABLE_ID, TABLE_NAME, NEXT_ID, QUANTITY) VALUES(105, 'TBLOB', 1, 1);

INSERT INTO TFIELD (OBJECTID, NAME, FIELDTYPE, DEPRECATED, ISCUSTOM, REQUIRED)
			VALUES (25, 'ArchiveLevel', 'com.aurel.track.fieldType.types.system.text.SystemArchiveLevel', 'N', 'N', 'N');
INSERT INTO TFIELDCONFIG(OBJECTID, FIELDKEY, LABEL, TOOLTIP, REQUIRED)
			VALUES (25, 25, 'ArchiveLevel', 'ArchiveLevel', 'N');
INSERT INTO TFIELD (OBJECTID, NAME, FIELDTYPE, DEPRECATED, ISCUSTOM, REQUIRED)
			VALUES (26, 'SubmitterEmail', 'com.aurel.track.fieldType.types.system.text.SystemSubmitterEmail', 'N', 'N', 'N');
INSERT INTO TFIELDCONFIG(OBJECTID, FIELDKEY, LABEL, TOOLTIP, REQUIRED)
			VALUES (26, 26, 'SubmitterEmail', 'SubmitterEmail', 'N');

INSERT INTO TLINKTYPE (OBJECTID, NAME, REVERSENAME, LEFTTORIGHTFIRST, RIGHTTOLEFTFIRST, LINKDIRECTION, LINKTYPEPLUGIN) 
	VALUES	(1, 'duplicate of', 'duplicated by', 'duplicates of these issues', 'duplicated by these issues', 3, 'com.aurel.track.linkType.GenericLinkType');
INSERT INTO TLINKTYPE (OBJECTID, NAME, REVERSENAME, LEFTTORIGHTFIRST, RIGHTTOLEFTFIRST, LINKDIRECTION, LINKTYPEPLUGIN) 
	VALUES	(2, 'test case for', 'verified by', 'test cases for these issues', 'verified by these issues', 3, 'com.aurel.track.linkType.GenericLinkType');
commit;