-----------------------------------------------------------------------------
-- TDOMAIN
-----------------------------------------------------------------------------
--DROP TABLE TDOMAIN CASCADE CONSTRAINTS;

CREATE TABLE TDOMAIN
(
    OBJECTID NUMBER(10,0) NOT NULL,
    LABEL VARCHAR2(255),
    DESCRIPTION VARCHAR2(4000),
    TPUUID VARCHAR2(36)
);

ALTER TABLE TDOMAIN
    ADD CONSTRAINT TDOMAIN_PK
PRIMARY KEY (OBJECTID);

CREATE INDEX TDOMAININDEX1 ON TDOMAIN (TPUUID);

ALTER TABLE TPERSON ADD HOURLYWAGE FLOAT;
ALTER TABLE TPERSON ADD EXTRAHOURWAGE FLOAT;
ALTER TABLE TWORKITEM ADD OVERBUDGET CHAR(1) default 'N';
ALTER TABLE TSCREENFIELD ADD ICONRENDERING NUMBER(10,0);
ALTER TABLE TWORKITEMLINK ADD SORTORDER NUMBER(10,0);

ALTER TABLE TCATEGORY ADD TOOLTIP VARCHAR2(255);
ALTER TABLE TDEPARTMENT ADD DOMAINKEY NUMBER(10,0);
ALTER TABLE TDEPARTMENT
    ADD CONSTRAINT TDEPARTMENT_FK_2 FOREIGN KEY (DOMAINKEY)
    REFERENCES TDOMAIN (OBJECTID)
;
ALTER TABLE TPRIORITY ADD TOOLTIP VARCHAR2(255);
ALTER TABLE TPROJECT ADD SORTORDER NUMBER(10,0);
ALTER TABLE TPROJECT ADD ISTEMPLATE CHAR(1) default 'N';
ALTER TABLE TPROJECT ADD DOMAINKEY NUMBER(10,0);
CREATE INDEX TPROJECTINDEX2 ON TPROJECT (SORTORDER);
ALTER TABLE TPROJECT
    ADD CONSTRAINT TPROJECT_FK_7 FOREIGN KEY (DOMAINKEY)
    REFERENCES TDOMAIN (OBJECTID)
;
ALTER TABLE TSEVERITY ADD TOOLTIP VARCHAR2(255);
ALTER TABLE TSTATE ADD TOOLTIP VARCHAR2(255);
ALTER TABLE TATTACHMENT ADD ISURL CHAR(1) default 'N';
ALTER TABLE TFIELD ADD PROJECTTYPE NUMBER(10,0);
ALTER TABLE TFIELD ADD PROJECT NUMBER(10,0);
ALTER TABLE TFIELD
    ADD CONSTRAINT TFIELD_FK_2 FOREIGN KEY (PROJECTTYPE)
    REFERENCES TPROJECTTYPE (OBJECTID)
;
ALTER TABLE TFIELD
    ADD CONSTRAINT TFIELD_FK_3 FOREIGN KEY (PROJECT)
    REFERENCES TPROJECT (PKEY)
;
ALTER TABLE TOPTION ADD TOOLTIP VARCHAR2(255);
ALTER TABLE TSCREEN ADD PROJECTTYPE NUMBER(10,0);
ALTER TABLE TSCREEN ADD PROJECT NUMBER(10,0);
ALTER TABLE TSCREEN
    ADD CONSTRAINT TSCREEN_FK_2 FOREIGN KEY (PROJECTTYPE)
    REFERENCES TPROJECTTYPE (OBJECTID)
;
ALTER TABLE TSCREEN
    ADD CONSTRAINT TSCREEN_FK_3 FOREIGN KEY (PROJECT)
    REFERENCES TPROJECT (PKEY)
;

ALTER TABLE TDASHBOARDSCREEN ADD OWNER NUMBER(10,0);
ALTER TABLE TDASHBOARDSCREEN
    ADD CONSTRAINT TDASHBOARDSCREEN_FK_3 FOREIGN KEY (OWNER)
    REFERENCES TPERSON (PKEY)
;

ALTER TABLE TQUERYREPOSITORY ADD SORTORDER NUMBER(10,0);
ALTER TABLE TQUERYREPOSITORY ADD VIEWID VARCHAR2(255);
CREATE INDEX TQUERYREPINDEX2 ON TQUERYREPOSITORY (SORTORDER);
ALTER TABLE TEXPORTTEMPLATE ADD PARENT NUMBER(10,0);
ALTER TABLE TEXPORTTEMPLATE ADD SORTORDER NUMBER(10,0);
CREATE INDEX TEXPOPRTTEMPINDEX2 ON TEXPORTTEMPLATE (SORTORDER);
ALTER TABLE TEXPORTTEMPLATE
    ADD CONSTRAINT TEXPORTTEMPLATE_FK_4 FOREIGN KEY (PARENT)
    REFERENCES TEXPORTTEMPLATE (OBJECTID)
;
ALTER TABLE TREPORTPERSONSETTINGS DROP CONSTRAINT TREPORTPERSONSETTINGS_FK_2;
ALTER TABLE TREPORTPERSONSETTINGS DROP CONSTRAINT TREPORTPERSONSETTINGS_FK_3;
ALTER TABLE TREPORTPERSONSETTINGS
    ADD CONSTRAINT TREPORTPERSONSETTINGS_FK_2 FOREIGN KEY (REPORTTEMPLATE)
    REFERENCES TEXPORTTEMPLATE (OBJECTID)
;
ALTER TABLE TREPORTPERSONSETTINGS DROP COLUMN RECURRENCEPATTERN;
ALTER TABLE TFILTERCATEGORY ADD SORTORDER NUMBER(10,0);
CREATE INDEX TFILTERCATEGORYINDEX2 ON TFILTERCATEGORY (SORTORDER);
ALTER TABLE TREPORTCATEGORY ADD SORTORDER NUMBER(10,0);
CREATE INDEX TREPORTCATEGORYINDEX2 ON TREPORTCATEGORY (SORTORDER);
ALTER TABLE TWORKFLOWTRANSITION ADD ELAPSEDTIME NUMBER(10,0);
ALTER TABLE TWORKFLOWTRANSITION ADD TIMEUNIT NUMBER(10,0);
ALTER TABLE TWORKFLOWACTIVITY ADD FIELDSETTERRELATION NUMBER(10,0);
ALTER TABLE TWORKFLOWACTIVITY ADD PARAMNAME VARCHAR2(255);
ALTER TABLE TWORKFLOWACTIVITY ADD FIELDSETMODE NUMBER(10,0);
ALTER TABLE TWORKFLOWACTIVITY ADD SORTORDER NUMBER(10,0);
ALTER TABLE TREADISSUE ADD FIELDKEY NUMBER(10,0);
ALTER TABLE TREADISSUE ADD LASTEDIT TIMESTAMP;
CREATE INDEX TREADISSUEINDEX4 ON TREADISSUE (FIELDKEY);

-----------------------------------------------------------------------------
-- TWFACTIVITYCONTEXTPARAMS
-----------------------------------------------------------------------------
--DROP TABLE TWFACTIVITYCONTEXTPARAMS CASCADE CONSTRAINTS;

CREATE TABLE TWFACTIVITYCONTEXTPARAMS
(
    OBJECTID NUMBER(10,0) NOT NULL,
    WORKFLOWACTIVITY NUMBER(10,0) NOT NULL,
    ISSUETYPE NUMBER(10,0),
    PROJECTTYPE NUMBER(10,0),
    PROJECT NUMBER(10,0),
    SETTERORPARTID NUMBER(10,0),
    ACTIVITYPARAMS VARCHAR2(4000),
    TPUUID VARCHAR2(36)
);

ALTER TABLE TWFACTIVITYCONTEXTPARAMS
    ADD CONSTRAINT TWFACTIVITYCONTEXTPARAMS_PK
PRIMARY KEY (OBJECTID);

CREATE INDEX TWFACTIVITYCONTEXTPARAMSINDEX1 ON TWFACTIVITYCONTEXTPARAMS (WORKFLOWACTIVITY);
CREATE INDEX TWFACTIVITYCONTEXTPARAMSINDEX2 ON TWFACTIVITYCONTEXTPARAMS (ISSUETYPE);
CREATE INDEX TWFACTIVITYCONTEXTPARAMSINDEX3 ON TWFACTIVITYCONTEXTPARAMS (PROJECTTYPE);
CREATE INDEX TWFACTIVITYCONTEXTPARAMSINDEX4 ON TWFACTIVITYCONTEXTPARAMS (PROJECT);
CREATE INDEX TWFACTIVITYCONTEXTPARAMSINDEX5 ON TWFACTIVITYCONTEXTPARAMS (TPUUID);

-----------------------------------------------------------------------------
-- TWORKFLOWCOMMENT
-----------------------------------------------------------------------------
--DROP TABLE TWORKFLOWCOMMENT CASCADE CONSTRAINTS;

CREATE TABLE TWORKFLOWCOMMENT
(
    OBJECTID NUMBER(10,0) NOT NULL,
    DESCRIPTION VARCHAR2(4000),
    WORKFLOW NUMBER(10,0),
    NODEX NUMBER(10,0),
    NODEY NUMBER(10,0),
    TPUUID VARCHAR2(36)
);

ALTER TABLE TWORKFLOWCOMMENT
    ADD CONSTRAINT TWORKFLOWCOMMENT_PK
PRIMARY KEY (OBJECTID);

CREATE INDEX TWORKFLOWCOMMENTINDEX1 ON TWORKFLOWCOMMENT (WORKFLOW);
CREATE INDEX TWORKFLOWCOMMENTINDEX2 ON TWORKFLOWCOMMENT (TPUUID);


-----------------------------------------------------------------------------
-- TREPORTSUBSCRIBE
-----------------------------------------------------------------------------
--DROP TABLE TREPORTSUBSCRIBE CASCADE CONSTRAINTS;

CREATE TABLE TREPORTSUBSCRIBE
(
    OBJECTID NUMBER(10,0) NOT NULL,
    PERSON NUMBER(10,0) NOT NULL,
    RECURRENCEPATTERN NUMBER(10,0),
    REPORTTEMPLATE NUMBER(10,0) NOT NULL,
    TPUUID VARCHAR2(36)
);

ALTER TABLE TREPORTSUBSCRIBE
    ADD CONSTRAINT TREPORTSUBSCRIBE_PK
PRIMARY KEY (OBJECTID);

CREATE INDEX TREPORTSUBSCRIBEINDEX1 ON TREPORTSUBSCRIBE (TPUUID);





-----------------------------------------------------------------------------
-- TGRIDLAYOUT
-----------------------------------------------------------------------------
--DROP TABLE TGRIDLAYOUT CASCADE CONSTRAINTS;

CREATE TABLE TGRIDLAYOUT
(
    OBJECTID NUMBER(10,0) NOT NULL,
    PERSON NUMBER(10,0),
    LAYOUTKEY NUMBER(10,0) NOT NULL,
    TPUUID VARCHAR2(36)
);

ALTER TABLE TGRIDLAYOUT
    ADD CONSTRAINT TGRIDLAYOUT_PK
PRIMARY KEY (OBJECTID);

CREATE INDEX TGRIDLAYOUTINDEX1 ON TGRIDLAYOUT (PERSON);
CREATE INDEX TGRIDLAYOUTINDEX2 ON TGRIDLAYOUT (LAYOUTKEY);
CREATE INDEX TGRIDLAYOUTINDEX3 ON TGRIDLAYOUT (TPUUID);


COMMENT ON TABLE TGRIDLAYOUT IS 'layout for grids';

COMMENT ON COLUMN TGRIDLAYOUT.LAYOUTKEY IS 'a hardcoded key to identify the grid';


-----------------------------------------------------------------------------
-- TGRIDFIELD
-----------------------------------------------------------------------------
--DROP TABLE TGRIDFIELD CASCADE CONSTRAINTS;

CREATE TABLE TGRIDFIELD
(
    OBJECTID NUMBER(10,0) NOT NULL,
    GRIDLAYOUT NUMBER(10,0) NOT NULL,
    GRIDFIELD NUMBER(10,0) NOT NULL,
    FIELDPOSITION NUMBER(10,0) NOT NULL,
    FIELDWIDTH NUMBER(10,0) NOT NULL,
    FILTERSTRING VARCHAR2(255),
    TPUUID VARCHAR2(36)
);

ALTER TABLE TGRIDFIELD
    ADD CONSTRAINT TGRIDFIELD_PK
PRIMARY KEY (OBJECTID);

CREATE INDEX TGRIDFIELDINDEX1 ON TGRIDFIELD (GRIDLAYOUT);
CREATE INDEX TGRIDFIELDINDEX2 ON TGRIDFIELD (TPUUID);


COMMENT ON TABLE TGRIDFIELD IS 'fields in grids';



-----------------------------------------------------------------------------
-- TGRIDGROUPINGSORTING
-----------------------------------------------------------------------------
--DROP TABLE TGRIDGROUPINGSORTING CASCADE CONSTRAINTS;

CREATE TABLE TGRIDGROUPINGSORTING
(
    OBJECTID NUMBER(10,0) NOT NULL,
    GRIDLAYOUT NUMBER(10,0) NOT NULL,
    GRIDFIELD NUMBER(10,0) NOT NULL,
    SORTPOSITION NUMBER(10,0) NOT NULL,
    ISGROUPING CHAR(1) default 'N',
    ISDESCENDING CHAR(1) default 'N',
    ISCOLLAPSED CHAR(1) default 'N',
    TPUUID VARCHAR2(36)
);

ALTER TABLE TGRIDGROUPINGSORTING
    ADD CONSTRAINT TGRIDGROUPINGSORTING_PK
PRIMARY KEY (OBJECTID);

CREATE INDEX TGRIDGROUPINGSORTINGINDEX1 ON TGRIDGROUPINGSORTING (GRIDLAYOUT);
CREATE INDEX TGRIDGROUPINGSORTINGINDEX2 ON TGRIDGROUPINGSORTING (TPUUID);


COMMENT ON TABLE TGRIDGROUPINGSORTING IS 'grouping and sorting in grids';



-----------------------------------------------------------------------------
-- TNAVIGATORLAYOUT
-----------------------------------------------------------------------------
--DROP TABLE TNAVIGATORLAYOUT CASCADE CONSTRAINTS;

CREATE TABLE TNAVIGATORLAYOUT
(
    OBJECTID NUMBER(10,0) NOT NULL,
    PERSON NUMBER(10,0),
    FILTERID NUMBER(10,0),
    FILTERTYPE NUMBER(10,0),
    TPUUID VARCHAR2(36)
);

ALTER TABLE TNAVIGATORLAYOUT
    ADD CONSTRAINT TNAVIGATORLAYOUT_PK
PRIMARY KEY (OBJECTID);

CREATE INDEX TNAVIGATORLAYOUTINDEX1 ON TNAVIGATORLAYOUT (PERSON);
CREATE INDEX TNAVIGATORLAYOUTINDEX2 ON TNAVIGATORLAYOUT (TPUUID);


COMMENT ON TABLE TNAVIGATORLAYOUT IS 'layout for item navigator';

COMMENT ON COLUMN TNAVIGATORLAYOUT.PERSON IS 'person is null for the global default layout';
COMMENT ON COLUMN TNAVIGATORLAYOUT.FILTERID IS 'specified for filter specific layout, null for default layout';
COMMENT ON COLUMN TNAVIGATORLAYOUT.FILTERTYPE IS 'specifies the type of the filter: dashboard, tree filter, etc.';


-----------------------------------------------------------------------------
-- TNAVIGATORCOLUMN
-----------------------------------------------------------------------------
--DROP TABLE TNAVIGATORCOLUMN CASCADE CONSTRAINTS;

CREATE TABLE TNAVIGATORCOLUMN
(
    OBJECTID NUMBER(10,0) NOT NULL,
    NAVIGATORLAYOUT NUMBER(10,0) NOT NULL,
    FIELD NUMBER(10,0) NOT NULL,
    FIELDPOSITION NUMBER(10,0) NOT NULL,
    FIELDWIDTH NUMBER(10,0),
    TPUUID VARCHAR2(36)
);

ALTER TABLE TNAVIGATORCOLUMN
    ADD CONSTRAINT TNAVIGATORCOLUMN_PK
PRIMARY KEY (OBJECTID);

CREATE INDEX TNAVIGATORCOLUMNINDEX1 ON TNAVIGATORCOLUMN (NAVIGATORLAYOUT);
CREATE INDEX TNAVIGATORCOLUMNINDEX2 ON TNAVIGATORCOLUMN (TPUUID);


COMMENT ON TABLE TNAVIGATORCOLUMN IS 'column in item navigator';



-----------------------------------------------------------------------------
-- TNAVIGATORGROUPINGSORTING
-----------------------------------------------------------------------------
--DROP TABLE TNAVIGATORGROUPINGSORTING CASCADE CONSTRAINTS;

CREATE TABLE TNAVIGATORGROUPINGSORTING
(
    OBJECTID NUMBER(10,0) NOT NULL,
    NAVIGATORLAYOUT NUMBER(10,0) NOT NULL,
    FIELD NUMBER(10,0) NOT NULL,
    SORTPOSITION NUMBER(10,0),
    ISGROUPING CHAR(1) default 'N',
    ISDESCENDING CHAR(1) default 'N',
    ISCOLLAPSED CHAR(1) default 'N',
    TPUUID VARCHAR2(36)
);

ALTER TABLE TNAVIGATORGROUPINGSORTING
    ADD CONSTRAINT TNAVIGATORGROUPINGSORTING_PK
PRIMARY KEY (OBJECTID);

CREATE INDEX TNAVIGATORGROUPINGSORTINGIDX1 ON TNAVIGATORGROUPINGSORTING (NAVIGATORLAYOUT);
CREATE INDEX TNAVIGATORGROUPINGSORTINGIDX2 ON TNAVIGATORGROUPINGSORTING (TPUUID);


COMMENT ON TABLE TNAVIGATORGROUPINGSORTING IS 'grouping and sorting in item navigator';



-----------------------------------------------------------------------------
-- TCARDGROUPINGFIELD
-----------------------------------------------------------------------------
--DROP TABLE TCARDGROUPINGFIELD CASCADE CONSTRAINTS;

CREATE TABLE TCARDGROUPINGFIELD
(
    OBJECTID NUMBER(10,0) NOT NULL,
    NAVIGATORLAYOUT NUMBER(10,0) NOT NULL,
    CARDFIELD NUMBER(10,0) NOT NULL,
    ISACTIV CHAR(1) default 'N',
    SORTFIELD NUMBER(10,0),
    ISDESCENDING CHAR(1) default 'N',
    TPUUID VARCHAR2(36)
);

ALTER TABLE TCARDGROUPINGFIELD
    ADD CONSTRAINT TCARDGROUPINGFIELD_PK
PRIMARY KEY (OBJECTID);

CREATE INDEX TCARDGROUPINGFIELDINDEX1 ON TCARDGROUPINGFIELD (NAVIGATORLAYOUT);
CREATE INDEX TCARDGROUPINGFIELDINDEX2 ON TCARDGROUPINGFIELD (TPUUID);


COMMENT ON TABLE TCARDGROUPINGFIELD IS 'grouping field for card';



-----------------------------------------------------------------------------
-- TCARDFIELDOPTION
-----------------------------------------------------------------------------
--DROP TABLE TCARDFIELDOPTION CASCADE CONSTRAINTS;

CREATE TABLE TCARDFIELDOPTION
(
    OBJECTID NUMBER(10,0) NOT NULL,
    GROUPINGFIELD NUMBER(10,0) NOT NULL,
    OPTIONID NUMBER(10,0) NOT NULL,
    OPTIONPOSITION NUMBER(10,0) NOT NULL,
    OPTIONWIDTH NUMBER(10,0) NOT NULL,
    MAXNUMBER NUMBER(10,0),
    TPUUID VARCHAR2(36)
);

ALTER TABLE TCARDFIELDOPTION
    ADD CONSTRAINT TCARDFIELDOPTION_PK
PRIMARY KEY (OBJECTID);

CREATE INDEX TCARDFIELDOPTIONINDEX1 ON TCARDFIELDOPTION (GROUPINGFIELD);
CREATE INDEX TCARDFIELDOPTIONINDEX2 ON TCARDFIELDOPTION (TPUUID);


COMMENT ON TABLE TCARDFIELDOPTION IS 'fields for card';


-----------------------------------------------------------------------------
-- TCARDPANEL
-----------------------------------------------------------------------------
--DROP TABLE TCARDPANEL CASCADE CONSTRAINTS;

CREATE TABLE TCARDPANEL
(
    OBJECTID NUMBER(10,0) NOT NULL,
    PERSON NUMBER(10,0),
    ROWSNO NUMBER(10,0) NOT NULL,
    COLSNO NUMBER(10,0) NOT NULL,
    TPUUID VARCHAR2(36)
);

ALTER TABLE TCARDPANEL
    ADD CONSTRAINT TCARDPANEL_PK
PRIMARY KEY (OBJECTID);

CREATE INDEX TCARDPANELINDEX1 ON TCARDPANEL (TPUUID);





-----------------------------------------------------------------------------
-- TCARDFIELD
-----------------------------------------------------------------------------
--DROP TABLE TCARDFIELD CASCADE CONSTRAINTS;

CREATE TABLE TCARDFIELD
(
    OBJECTID NUMBER(10,0) NOT NULL,
    NAME VARCHAR2(255),
    COLINDEX NUMBER(10,0),
    ROWINDEX NUMBER(10,0),
    COLSPAN NUMBER(10,0),
    ROWSPAN NUMBER(10,0),
    LABELHALIGN NUMBER(10,0) NOT NULL,
    LABELVALIGN NUMBER(10,0) NOT NULL,
    VALUEHALIGN NUMBER(10,0) NOT NULL,
    VALUEVALIGN NUMBER(10,0) NOT NULL,
    CARDPANEL NUMBER(10,0) NOT NULL,
    FIELDKEY NUMBER(10,0),
   	HIDELABEL CHAR(1) default 'Y',
    ICONRENDERING NUMBER(10,0),
    TPUUID VARCHAR2(36)
);

ALTER TABLE TCARDFIELD
    ADD CONSTRAINT TCARDFIELD_PK
PRIMARY KEY (OBJECTID);

CREATE INDEX TCARDFIELDINDEX1 ON TCARDFIELD (TPUUID);





-----------------------------------------------------------------------------
-- TVIEWPARAM
-----------------------------------------------------------------------------
--DROP TABLE TVIEWPARAM CASCADE CONSTRAINTS;

CREATE TABLE TVIEWPARAM
(
    OBJECTID NUMBER(10,0) NOT NULL,
    NAVIGATORLAYOUT NUMBER(10,0) NOT NULL,
    PARAMNAME VARCHAR2(255) NOT NULL,
    PARAMVALUE VARCHAR2(4000),
    TPUUID VARCHAR2(36)
);

ALTER TABLE TVIEWPARAM
    ADD CONSTRAINT TVIEWPARAM_PK
PRIMARY KEY (OBJECTID);

CREATE INDEX TVIEWPARAMINDEX1 ON TVIEWPARAM (NAVIGATORLAYOUT);
CREATE INDEX TVIEWPARAMINDEX2 ON TVIEWPARAM (TPUUID);


COMMENT ON TABLE TVIEWPARAM IS 'general parameters for a view';



-----------------------------------------------------------------------------
-- TGENERALPARAM
-----------------------------------------------------------------------------
--DROP TABLE TGENERALPARAM CASCADE CONSTRAINTS;

CREATE TABLE TGENERALPARAM
(
    OBJECTID NUMBER(10,0) NOT NULL,
    PARAMNAME VARCHAR2(255) NOT NULL,
    PARAMVALUE VARCHAR2(4000),
    TPUUID VARCHAR2(36)
);

ALTER TABLE TGENERALPARAM
    ADD CONSTRAINT TGENERALPARAM_PK
PRIMARY KEY (OBJECTID);

CREATE INDEX TGENERALPARAMINDEX1 ON TGENERALPARAM (TPUUID);


COMMENT ON TABLE TGENERALPARAM IS 'general parameters for the system';



-----------------------------------------------------------------------------
-- TVERSIONCONTROL
-----------------------------------------------------------------------------
--DROP TABLE TVERSIONCONTROL CASCADE CONSTRAINTS;

CREATE TABLE TVERSIONCONTROL
(
    OBJECTID NUMBER(10,0) NOT NULL,
    VCTYPE NUMBER(10,0) NOT NULL,
    REPOSITORYBROWSER NUMBER(10,0) NOT NULL,
    CHANGESETLINK VARCHAR2(255),
    ADDEDFILESLINK VARCHAR2(255),
    MODIFIEDEDFILESLINK VARCHAR2(255),
    REPLACEDFILESLINK VARCHAR2(255),
    DELETEDFILESLINK VARCHAR2(255),
    CONNECTIONTYPE NUMBER(10,0) NOT NULL,
    SERVERNAME VARCHAR2(255) NOT NULL,
    REPOSITORYPATH VARCHAR2(255) NOT NULL,
    DEFAULTSEVERPORT CHAR(1) default 'Y',
    SEVERPORT NUMBER(10,0),
    AUTHENTICATIONMODE NUMBER(10,0) NOT NULL,
    USERNAME VARCHAR2(100),
    PASSWORD VARCHAR2(255),
    PRIVATEKEY VARCHAR2(4000),
    PASSPHRASE VARCHAR2(255),
    PARENT NUMBER(10,0),
    TPUUID VARCHAR2(36)
);

ALTER TABLE TVERSIONCONTROL
    ADD CONSTRAINT TVERSIONCONTROL_PK
PRIMARY KEY (OBJECTID);

CREATE INDEX TVERSIONCONTROLINDEX1 ON TVERSIONCONTROL (TPUUID);


COMMENT ON TABLE TVERSIONCONTROL IS 'configuration for version control server';



-----------------------------------------------------------------------------
-- TSHORTCUT
-----------------------------------------------------------------------------
--DROP TABLE TSHORTCUT CASCADE CONSTRAINTS;

CREATE TABLE TSHORTCUT
(
    OBJECTID NUMBER(10,0) NOT NULL,
    SHORTCUTKEY NUMBER(10,0),
    CTRLKEY CHAR(1) default 'N',
    SHIFTKEY CHAR(1) default 'N',
    ALTKEY CHAR(1) default 'N',
    MENUITEMKEY NUMBER(10,0),
    MENUCONTEXT NUMBER(10,0),
    TPUUID VARCHAR2(36)
);

ALTER TABLE TSHORTCUT
    ADD CONSTRAINT TSHORTCUT_PK
PRIMARY KEY (OBJECTID);

CREATE INDEX TSHORTCUTSINDEX1 ON TSHORTCUT (TPUUID);


COMMENT ON TABLE TSHORTCUT IS 'shortcut  definitions for menu items';

COMMENT ON COLUMN TSHORTCUT.MENUCONTEXT IS 'main menu, item navigator context menu etc.';


-----------------------------------------------------------------------------
-- TMAILTEXTBLOCK
-----------------------------------------------------------------------------
--DROP TABLE TMAILTEXTBLOCK CASCADE CONSTRAINTS;

CREATE TABLE TMAILTEXTBLOCK
(
    OBJECTID NUMBER(10,0) NOT NULL,
    PERSON NUMBER(10,0),
    BLOCKTITLE VARCHAR2(255),
    BLOCKCONTENT VARCHAR2(4000),
    TAGLABEL VARCHAR2(100),
    REPOSITORYTYPE NUMBER(10,0),
    PROJECT NUMBER(10,0),
    TPUUID VARCHAR2(36)
);

ALTER TABLE TMAILTEXTBLOCK
    ADD CONSTRAINT TMAILTEXTBLOCK_PK
PRIMARY KEY (OBJECTID);

CREATE INDEX TMAILTEXTBLOCKINDEX1 ON TMAILTEXTBLOCK (PERSON);
CREATE INDEX TMAILTEXTBLOCKINDEX2 ON TMAILTEXTBLOCK (TPUUID);


COMMENT ON TABLE TMAILTEXTBLOCK IS 'predefined text blocks to edit an mail';

COMMENT ON COLUMN TMAILTEXTBLOCK.TAGLABEL IS 'user defined tag/category used for filtering/grouping the blocks';


-----------------------------------------------------------------------------
-- TPROLE
-----------------------------------------------------------------------------
--DROP TABLE TPROLE CASCADE CONSTRAINTS;

CREATE TABLE TPROLE
(
    OBJECTID NUMBER(10,0) NOT NULL,
    PROJECTTYPE NUMBER(10,0),
    ROLEKEY NUMBER(10,0),
    TPUUID VARCHAR2(36)
);

ALTER TABLE TPROLE
    ADD CONSTRAINT TPROLE_PK
PRIMARY KEY (OBJECTID);

CREATE INDEX TPROLEINDEX1 ON TPROLE (TPUUID);





-----------------------------------------------------------------------------
-- TCHILDPROJECTTYPE
-----------------------------------------------------------------------------
--DROP TABLE TCHILDPROJECTTYPE CASCADE CONSTRAINTS;

CREATE TABLE TCHILDPROJECTTYPE
(
    OBJECTID NUMBER(10,0) NOT NULL,
    PROJECTTYPEPARENT NUMBER(10,0) NOT NULL,
    PROJECTTYPECHILD NUMBER(10,0) NOT NULL,
    TPUUID VARCHAR2(36)
);

ALTER TABLE TCHILDPROJECTTYPE
    ADD CONSTRAINT TCHILDPROJECTTYPE_PK
PRIMARY KEY (OBJECTID);

CREATE INDEX TCHILDPROJECTTYPEINDEX1 ON TCHILDPROJECTTYPE (TPUUID);


COMMENT ON TABLE TCHILDPROJECTTYPE IS 'Describes which project type can have a child project depending on the a project type of parent project';

-----------------------------------------------------------------------------
-- TPERSONINDOMAIN
-----------------------------------------------------------------------------
--DROP TABLE TPERSONINDOMAIN CASCADE CONSTRAINTS;

CREATE TABLE TPERSONINDOMAIN
(
    OBJECTID NUMBER(10,0) NOT NULL,
    PERSONKEY NUMBER(10,0) NOT NULL,
    DOMAINKEY NUMBER(10,0) NOT NULL,
    DESCRIPTION VARCHAR2(4000),
    TPUUID VARCHAR2(36)
);

ALTER TABLE TPERSONINDOMAIN
    ADD CONSTRAINT TPERSONINDOMAIN_PK
PRIMARY KEY (OBJECTID);

CREATE INDEX TPERSONINDOMAININDEX1 ON TPERSONINDOMAIN (TPUUID);





-----------------------------------------------------------------------------
-- TATTACHMENTVERSION
-----------------------------------------------------------------------------
--DROP TABLE TATTACHMENTVERSION CASCADE CONSTRAINTS;

CREATE TABLE TATTACHMENTVERSION
(
    OBJECTID NUMBER(10,0) NOT NULL,
    WORKITEM NUMBER(10,0) NOT NULL,
    CHANGEDBY NUMBER(10,0),
    DOCUMENTSTATE NUMBER(10,0),
    FILENAME VARCHAR2(256) NOT NULL,
    ISURL CHAR(1) default 'N',
    FILESIZE VARCHAR2(20),
    MIMETYPE VARCHAR2(15),
    LASTEDIT TIMESTAMP,
    VERSION VARCHAR2(20),
    DESCRIPTION VARCHAR2(4000),
    CRYPTKEY VARCHAR2(4000),
    ISENCRYPTED CHAR(1) default 'N',
    ISDELETED CHAR(1) default 'N',
    TPUUID VARCHAR2(36)
);

ALTER TABLE TATTACHMENTVERSION
    ADD CONSTRAINT TATTACHMENTVERSION_PK
PRIMARY KEY (OBJECTID);

CREATE INDEX TATTACHMENTVERSIONINDEX1 ON TATTACHMENTVERSION (TPUUID);

-----------------------------------------------------------------------------
-- TUSERLEVEL
-----------------------------------------------------------------------------
--DROP TABLE TUSERLEVEL CASCADE CONSTRAINTS;

CREATE TABLE TUSERLEVEL
(
    OBJECTID NUMBER(10,0) NOT NULL,
    LABEL VARCHAR2(255),
    DESCRIPTION VARCHAR2(4000),
    TPUUID VARCHAR2(36)
);

ALTER TABLE TUSERLEVEL
    ADD CONSTRAINT TUSERLEVEL_PK
PRIMARY KEY (OBJECTID);

CREATE INDEX TUSERLEVELINDEX1 ON TUSERLEVEL (TPUUID);





-----------------------------------------------------------------------------
-- TUSERLEVELSETTING
-----------------------------------------------------------------------------
--DROP TABLE TUSERLEVELSETTING CASCADE CONSTRAINTS;

CREATE TABLE TUSERLEVELSETTING
(
    OBJECTID NUMBER(10,0) NOT NULL,
    USERLEVEL NUMBER(10,0) NOT NULL,
    ACTIONKEY NUMBER(10,0) NOT NULL,
    ISACTIVE CHAR(1) default 'N',
    TPUUID VARCHAR2(36)
);

ALTER TABLE TUSERLEVELSETTING
    ADD CONSTRAINT TUSERLEVELSETTING_PK
PRIMARY KEY (OBJECTID);

CREATE INDEX TUSERLEVELSETTINGINDEX1 ON TUSERLEVELSETTING (TPUUID);




-----------------------------------------------------------------------------
-- TUSERFEATURE
-----------------------------------------------------------------------------
--DROP TABLE TUSERFEATURE CASCADE CONSTRAINTS;

CREATE TABLE TUSERFEATURE
(
    OBJECTID NUMBER(10,0) NOT NULL,
    FEATURENAME VARCHAR2(255) NOT NULL,
    PERSON NUMBER(10,0),
    ISACTIVE CHAR(1) default 'N',
    TPUUID VARCHAR2(36)
);

ALTER TABLE TUSERFEATURE
    ADD CONSTRAINT TUSERFEATURE_PK
PRIMARY KEY (OBJECTID);

CREATE INDEX TUSERFEATUREINDEX1 ON TUSERFEATURE (TPUUID);


-----------------------------------------------------------------------------
-- TITEMTRANSITION
-----------------------------------------------------------------------------
--DROP TABLE TITEMTRANSITION CASCADE CONSTRAINTS;

CREATE TABLE TITEMTRANSITION
(
    OBJECTID NUMBER(10,0) NOT NULL,
    WORKITEM NUMBER(10,0) NOT NULL,
    TRANSITION NUMBER(10,0) NOT NULL,
    TRANSITIONTIME TIMESTAMP,
    TPUUID VARCHAR2(36)
);

ALTER TABLE TITEMTRANSITION
    ADD CONSTRAINT TITEMTRANSITION_PK
PRIMARY KEY (OBJECTID);

CREATE INDEX TITEMTRANSITIONINDEX1 ON TITEMTRANSITION (WORKITEM);
CREATE INDEX TITEMTRANSITIONINDEX2 ON TITEMTRANSITION (TRANSITION);
CREATE INDEX TITEMTRANSITIONINDEX3 ON TITEMTRANSITION (TPUUID);

ALTER TABLE TWFACTIVITYCONTEXTPARAMS
    ADD CONSTRAINT TWFACTIVITYCONTEXTPARAMS_FK_1 FOREIGN KEY (WORKFLOWACTIVITY)
    REFERENCES TWORKFLOWACTIVITY (OBJECTID)
;

ALTER TABLE TWFACTIVITYCONTEXTPARAMS
    ADD CONSTRAINT TWFACTIVITYCONTEXTPARAMS_FK_2 FOREIGN KEY (ISSUETYPE)
    REFERENCES TCATEGORY (PKEY)
;

ALTER TABLE TWFACTIVITYCONTEXTPARAMS
    ADD CONSTRAINT TWFACTIVITYCONTEXTPARAMS_FK_3 FOREIGN KEY (PROJECTTYPE)
    REFERENCES TPROJECTTYPE (OBJECTID)
;

ALTER TABLE TWFACTIVITYCONTEXTPARAMS
    ADD CONSTRAINT TWFACTIVITYCONTEXTPARAMS_FK_4 FOREIGN KEY (PROJECT)
    REFERENCES TPROJECT (PKEY)
;

ALTER TABLE TWORKFLOWCOMMENT
    ADD CONSTRAINT TWORKFLOWCOMMENT_FK_1 FOREIGN KEY (WORKFLOW)
    REFERENCES TWORKFLOWDEF (OBJECTID)
;

ALTER TABLE TREPORTSUBSCRIBE
    ADD CONSTRAINT TREPORTSUBSCRIBE_FK_1 FOREIGN KEY (PERSON)
    REFERENCES TPERSON (PKEY)
;

ALTER TABLE TREPORTSUBSCRIBE
    ADD CONSTRAINT TREPORTSUBSCRIBE_FK_2 FOREIGN KEY (RECURRENCEPATTERN)
    REFERENCES TRECURRENCEPATTERN (OBJECTID)
;

ALTER TABLE TREPORTSUBSCRIBE
    ADD CONSTRAINT TREPORTSUBSCRIBE_FK_3 FOREIGN KEY (REPORTTEMPLATE)
    REFERENCES TEXPORTTEMPLATE (OBJECTID)
;



ALTER TABLE TGRIDLAYOUT
    ADD CONSTRAINT TGRIDLAYOUT_FK_1 FOREIGN KEY (PERSON)
    REFERENCES TPERSON (PKEY)
;



ALTER TABLE TGRIDFIELD
    ADD CONSTRAINT TGRIDFIELD_FK_1 FOREIGN KEY (GRIDLAYOUT)
    REFERENCES TGRIDLAYOUT (OBJECTID)
;



ALTER TABLE TGRIDGROUPINGSORTING
    ADD CONSTRAINT TGRIDGROUPINGSORTING_FK_1 FOREIGN KEY (GRIDLAYOUT)
    REFERENCES TGRIDLAYOUT (OBJECTID)
;



ALTER TABLE TNAVIGATORLAYOUT
    ADD CONSTRAINT TNAVIGATORLAYOUT_FK_1 FOREIGN KEY (PERSON)
    REFERENCES TPERSON (PKEY)
;



ALTER TABLE TNAVIGATORCOLUMN
    ADD CONSTRAINT TNAVIGATORCOLUMN_FK_1 FOREIGN KEY (NAVIGATORLAYOUT)
    REFERENCES TNAVIGATORLAYOUT (OBJECTID)
;



ALTER TABLE TNAVIGATORGROUPINGSORTING
    ADD CONSTRAINT TNAVIGATORGROUPINGSORTING_FK_1 FOREIGN KEY (NAVIGATORLAYOUT)
    REFERENCES TNAVIGATORLAYOUT (OBJECTID)
;



ALTER TABLE TCARDGROUPINGFIELD
    ADD CONSTRAINT TCARDGROUPINGFIELD_FK_1 FOREIGN KEY (NAVIGATORLAYOUT)
    REFERENCES TNAVIGATORLAYOUT (OBJECTID)
;



ALTER TABLE TCARDFIELDOPTION
    ADD CONSTRAINT TCARDFIELDOPTION_FK_1 FOREIGN KEY (GROUPINGFIELD)
    REFERENCES TCARDGROUPINGFIELD (OBJECTID)
;




ALTER TABLE TCARDFIELD
    ADD CONSTRAINT TCARDFIELD_FK_1 FOREIGN KEY (CARDPANEL)
    REFERENCES TCARDPANEL (OBJECTID)
;



ALTER TABLE TVIEWPARAM
    ADD CONSTRAINT TVIEWPARAM_FK_1 FOREIGN KEY (NAVIGATORLAYOUT)
    REFERENCES TNAVIGATORLAYOUT (OBJECTID)
;





ALTER TABLE TVERSIONCONTROL
    ADD CONSTRAINT TVERSIONCONTROL_FK_1 FOREIGN KEY (PARENT)
    REFERENCES TVERSIONCONTROL (OBJECTID)
;





ALTER TABLE TMAILTEXTBLOCK
    ADD CONSTRAINT TMAILTEXTBLOCK_FK_1 FOREIGN KEY (PERSON)
    REFERENCES TPERSON (PKEY)
;

ALTER TABLE TMAILTEXTBLOCK
    ADD CONSTRAINT TMAILTEXTBLOCK_FK_2 FOREIGN KEY (PROJECT)
    REFERENCES TPROJECT (PKEY)
;



ALTER TABLE TPROLE
    ADD CONSTRAINT TPROLE_FK_1 FOREIGN KEY (PROJECTTYPE)
    REFERENCES TPROJECTTYPE (OBJECTID)
;

ALTER TABLE TPROLE
    ADD CONSTRAINT TPROLE_FK_2 FOREIGN KEY (ROLEKEY)
    REFERENCES TROLE (PKEY)
;



ALTER TABLE TCHILDPROJECTTYPE
    ADD CONSTRAINT TCHILDPROJECTTYPE_FK_1 FOREIGN KEY (PROJECTTYPEPARENT)
    REFERENCES TPROJECTTYPE (OBJECTID)
;

ALTER TABLE TCHILDPROJECTTYPE
    ADD CONSTRAINT TCHILDPROJECTTYPE_FK_2 FOREIGN KEY (PROJECTTYPECHILD)
    REFERENCES TPROJECTTYPE (OBJECTID)
;

ALTER TABLE TPERSONINDOMAIN
    ADD CONSTRAINT TPERSONINDOMAIN_FK_1 FOREIGN KEY (PERSONKEY)
    REFERENCES TPERSON (PKEY)
;

ALTER TABLE TPERSONINDOMAIN
    ADD CONSTRAINT TPERSONINDOMAIN_FK_2 FOREIGN KEY (DOMAINKEY)
    REFERENCES TDOMAIN (OBJECTID)
;



ALTER TABLE TATTACHMENTVERSION
    ADD CONSTRAINT TATTACHMENTVERSION_FK_1 FOREIGN KEY (WORKITEM)
    REFERENCES TWORKITEM (WORKITEMKEY)
;

ALTER TABLE TATTACHMENTVERSION
    ADD CONSTRAINT TATTACHMENTVERSION_FK_2 FOREIGN KEY (CHANGEDBY)
    REFERENCES TPERSON (PKEY)
;

ALTER TABLE TATTACHMENTVERSION
    ADD CONSTRAINT TATTACHMENTVERSION_FK_3 FOREIGN KEY (DOCUMENTSTATE)
    REFERENCES TDOCSTATE (OBJECTID)
;

ALTER TABLE TUSERLEVELSETTING
    ADD CONSTRAINT TUSERLEVELSETTING_FK_1 FOREIGN KEY (USERLEVEL)
    REFERENCES TUSERLEVEL (OBJECTID)
;

ALTER TABLE TUSERFEATURE
    ADD CONSTRAINT TUSERFEATURE_FK_1 FOREIGN KEY (PERSON)
    REFERENCES TPERSON (PKEY)
;

ALTER TABLE TITEMTRANSITION
    ADD CONSTRAINT TITEMTRANSITION_FK_1 FOREIGN KEY (WORKITEM)
    REFERENCES TWORKITEM (WORKITEMKEY)
;

ALTER TABLE TITEMTRANSITION
    ADD CONSTRAINT TITEMTRANSITION_FK_2 FOREIGN KEY (TRANSITION)
    REFERENCES TWORKFLOWTRANSITION (OBJECTID)
;
