INSERT INTO ID_TABLE (ID_TABLE_ID, TABLE_NAME, NEXT_ID, QUANTITY) VALUES(88, 'TCOMPUTEDVALUES', 1, 1);
INSERT INTO ID_TABLE (ID_TABLE_ID, TABLE_NAME, NEXT_ID, QUANTITY) VALUES(89, 'TLINKTYPE', 1, 1);

ALTER TABLE TREPORTLAYOUT DROP CONSTRAINT TREPORTLAYOUT_FK_4;
ALTER TABLE TREPORTLAYOUT ADD FIELDTYPE NUMBER(10,0);

DROP TABLE TCOMPUTEDVALUES;
CREATE TABLE TCOMPUTEDVALUES
(
    PKEY NUMBER(10,0) NOT NULL,
    WORKITEMKEY NUMBER(10,0) NOT NULL,
    EFFORTTYPE NUMBER(10,0) NOT NULL,
    COMPUTEDVALUETYPE NUMBER(10,0) NOT NULL,
    COMPUTEDVALUE FLOAT,
    MEASUREMENTUNIT NUMBER(10,0),
    PERSON NUMBER(10,0)
);
ALTER TABLE TCOMPUTEDVALUES
    ADD CONSTRAINT TCOMPUTEDVALUES_PK
PRIMARY KEY (PKEY);

ALTER TABLE TCOMPUTEDVALUES
    ADD CONSTRAINT TCOMPUTEDVALUES_FK_1 FOREIGN KEY (WORKITEMKEY)
    REFERENCES TWORKITEM (WORKITEMKEY)
;
ALTER TABLE TCOMPUTEDVALUES
    ADD CONSTRAINT TCOMPUTEDVALUES_FK_2 FOREIGN KEY (PERSON)
    REFERENCES TPERSON (PKEY)
;

DROP TABLE TLOCALIZEDRESOURCES;
CREATE TABLE TLOCALIZEDRESOURCES
(
    OBJECTID NUMBER(10,0) NOT NULL,
    TABLENAME VARCHAR2(255),
    PRIMARYKEYVALUE NUMBER(10,0),
    FIELDNAME VARCHAR2(255) NOT NULL,
    LOCALIZEDTEXT VARCHAR2(255),
    LOCALE VARCHAR2(20)
);

ALTER TABLE TLOCALIZEDRESOURCES
    ADD CONSTRAINT TLOCALIZEDRESOURCES_PK
PRIMARY KEY (OBJECTID);

CREATE TABLE TLINKTYPE
(
    OBJECTID NUMBER(10,0) NOT NULL,
    NAME VARCHAR2(255) NOT NULL,
    MOREPROPS VARCHAR2(4000)
);

ALTER TABLE TLINKTYPE
    ADD CONSTRAINT TLINKTYPE_PK
PRIMARY KEY (OBJECTID);

ALTER TABLE TWORKITEMLINK
    ADD CONSTRAINT TWORKITEMLINK_FK_3 FOREIGN KEY (LINKTYPE)
    REFERENCES TLINKTYPE (OBJECTID);
	
update TSTATE set symbol='opened.gif' where pkey=1;
update TSTATE set symbol='analyzed.gif' where pkey=2;
update TSTATE set symbol='assigned.gif' where pkey=3;
update TSTATE set symbol='suspended.gif' where pkey=4;
update TSTATE set symbol='processing.gif' where pkey=5;
update TSTATE set symbol='implemented.gif' where pkey=6;
update TSTATE set symbol='integrated.gif' where pkey=7;
update TSTATE set symbol='closed.gif' where pkey=8;
update TSTATE set symbol='assessing.gif' where pkey=9;

update TPRIORITY set symbol='occasionally.gif' where pkey=1;
update TPRIORITY set symbol='soon.gif' where pkey=2;
update TPRIORITY set symbol='immediate.gif' where pkey=3;

update TSEVERITY set symbol='minor.gif' where pkey=1;
update TSEVERITY set symbol='major.gif' where pkey=2;
update TSEVERITY set symbol='blocker.gif' where pkey=3;
commit;