/*
 * Project:      Track+
 * Author:       Joerg Friedrich
 *
 * Date Created: Thursday, June 24, 2004
 *
 * Updates the database from previous database release 2.0 to 3.0
 * 
 *//*
 * Project:      Track+
 * Author:       Joerg Friedrich
 *
 * Date Created: Thursday, June 24, 2004
 *
 * Updates the database from previous database release 2.0 to 3.0
 * 
 */

-- TBASELINE
ALTER TABLE TBASELINE ADD ESTIMATEDHOURS FLOAT;
ALTER TABLE TBASELINE ADD ESTIMATEDCOST FLOAT;
ALTER TABLE TBASELINE ADD CURRENCY NUMBER;

-- TCATEGORY
ALTER TABLE TCATEGORY ADD SORTORDER NUMBER;

-- TNOTIFY
ALTER TABLE TNOTIFY ADD WORKITEM NUMBER;

-- TPERSON
ALTER TABLE TPERSON ADD TOKENPASSWD VARCHAR(80);
ALTER TABLE TPERSON ADD TOKENEXPDATE timestamp;
ALTER TABLE TPERSON ADD EMAILFREQUENCY NUMBER;
ALTER TABLE TPERSON ADD EMAILLEAD NUMBER;
ALTER TABLE TPERSON ADD EMAILLASTREMINDED timestamp;
ALTER TABLE TPERSON ADD EMAILREMINDME CHAR(1) default 'N';
ALTER TABLE TPERSON ADD PREFEMAILTYPE VARCHAR(15) default 'Plain';
ALTER TABLE TPERSON ADD PREFLOCALE VARCHAR(10);
ALTER TABLE TPERSON ADD MYDEFAULTREPORT NUMBER;
ALTER TABLE TPERSON ADD NOEMAILSPLEASE NUMBER;

-- TPRIORITY
ALTER TABLE TPRIORITY ADD SORTORDER NUMBER;

-- TPROJECT
ALTER TABLE TPROJECT ADD DEFMANAGER NUMBER;
ALTER TABLE TPROJECT ADD PROJECTTYPE NUMBER;

-- TROLE
ALTER TABLE TROLE ADD EXTENDEDACCESSKEY VARCHAR(30);
ALTER TABLE TROLE ADD PROJECTTYPE NUMBER;

-- TSEVERITY
ALTER TABLE TSEVERITY ADD SORTORDER NUMBER;

-- TSTATE
ALTER TABLE TSTATE ADD SORTORDER NUMBER;

-- TWORKITEM
ALTER TABLE TWORKITEM ADD ESTIMATEDHOURS FLOAT;
ALTER TABLE TWORKITEM ADD ESTIMATEDCOST FLOAT;
ALTER TABLE TWORKITEM ADD CURRENCY NUMBER;
ALTER TABLE TWORKITEM ADD ACTUALSTARTDATE timestamp;
ALTER TABLE TWORKITEM ADD ACTUALENDDATE timestamp;

CREATE INDEX TWIINDEX15 ON TWORKITEM (ACTUALSTARTDATE);
CREATE INDEX TWIINDEX16 ON TWORKITEM (ACTUALENDDATE);

-- TPRIVATEREPORTREPOSITORY
CREATE TABLE TPRIVATEREPORTREPOSITORY
(
	PKEY NUMBER NOT NULL,
	OWNER NUMBER NOT NULL,
	NAME VARCHAR(100) NOT NULL,
	QUERY VARCHAR(4000) NOT NULL
);

CREATE INDEX TPRIVREPINDEX1 ON TPRIVATEREPORTREPOSITORY (PKEY);
CREATE INDEX TPRIVREPINDEX2 ON TPRIVATEREPORTREPOSITORY (OWNER);

ALTER TABLE TPRIVATEREPORTREPOSITORY
    ADD CONSTRAINT TPRIVATEREPORTREPOSITORY_PK
PRIMARY KEY (PKEY);



-- TPUBLICREPORTREPOSITORY
CREATE TABLE TPUBLICREPORTREPOSITORY
(
	PKEY NUMBER NOT NULL,
	OWNER NUMBER NOT NULL,
	NAME VARCHAR(100) NOT NULL,
	QUERY VARCHAR(4000) NOT NULL
);

ALTER TABLE TPUBLICREPORTREPOSITORY
    ADD CONSTRAINT TPUBLICREPORTREPOSITORY_PK
PRIMARY KEY (PKEY);

CREATE INDEX TPUBREPINDEX2 ON TPUBLICREPORTREPOSITORY (OWNER);



-- TPROJECTREPORTREPOSITORY
CREATE TABLE TPROJECTREPORTREPOSITORY
(
	PKEY NUMBER NOT NULL,
	PROJECT NUMBER NOT NULL,
	NAME VARCHAR(100) NOT NULL,
	QUERY VARCHAR(4000) NOT NULL
);

ALTER TABLE TPROJECTREPORTREPOSITORY
    ADD CONSTRAINT TPROJECTREPORTREPOSITORY_PK
PRIMARY KEY (PKEY);

CREATE INDEX TPROJREPINDEX2 ON TPROJECTREPORTREPOSITORY (PROJECT);



-- TACCOUNT
CREATE TABLE TACCOUNT
(
	OBJECTID NUMBER NOT NULL,
	ACCOUNTNUMBER VARCHAR(30) NOT NULL,
	PROJECT NUMBER NOT NULL
);

ALTER TABLE TACCOUNT
    ADD CONSTRAINT TACCOUNT_PK
PRIMARY KEY (OBJECTID);

CREATE INDEX TACCOUNTINDEX2 ON TACCOUNT (PROJECT);



-- TATTACHMENT
CREATE TABLE TATTACHMENT
(
	OBJECTID NUMBER NOT NULL,
	WORKITEM NUMBER NOT NULL,
	CHANGEDBY NUMBER,
	DOCUMENTSTATE NUMBER,
	FILENAME VARCHAR(256) NOT NULL,
	FILESIZE VARCHAR(20),
	MIMETYPE VARCHAR(15),
	LASTEDIT timestamp,
	VERSION VARCHAR(20),
	DESCRIPTION VARCHAR(4000),
	CRYPTKEY VARCHAR(4000),
	ISENCRYPTED CHAR(1) default 'N',
	ISDELETED CHAR(1) default 'N'
);

ALTER TABLE TATTACHMENT
    ADD CONSTRAINT TATTACHMENT_PK 
PRIMARY KEY (OBJECTID);

CREATE INDEX TATTACHINDEX2 ON TATTACHMENT (WORKITEM);
CREATE INDEX TATTACHINDEX3 ON TATTACHMENT (CHANGEDBY);
CREATE INDEX TATTACHINDEX4 ON TATTACHMENT (DOCUMENTSTATE);


-- TCOST
CREATE TABLE TCOST
(
	OBJECTID NUMBER NOT NULL,
	ACCOUNT NUMBER,
	PERSON NUMBER,
	WORKITEM NUMBER,
	HOURS FLOAT,
	COST FLOAT,
	CURRENCY NUMBER
);

ALTER TABLE TCOST
    ADD CONSTRAINT TCOST_PK 
PRIMARY KEY (OBJECTID);

CREATE INDEX TCOSTINDEX2 ON TCOST (ACCOUNT);
CREATE INDEX TCOSTINDEX3 ON TCOST (PERSON);
CREATE INDEX TCOSTINDEX4 ON TCOST (WORKITEM);
CREATE INDEX TCOSTINDEX5 ON TCOST (CURRENCY);



-- TCURRENCY
CREATE TABLE TCURRENCY
(
	OBJECTID NUMBER NOT NULL,
	CURRENCY VARCHAR (10) NOT NULL,
	CONVERSIONFACTOR FLOAT NOT NULL
);

ALTER TABLE TCURRENCY
    ADD CONSTRAINT TCURRENCY_PK 
PRIMARY KEY (OBJECTID);




-- TDOCSTATE
CREATE TABLE TDOCSTATE
(
	OBJECTID NUMBER NOT NULL,
	LABEL VARCHAR (25) NOT NULL,
	STATEFLAG NUMBER,
	PROJECTTYPE NUMBER
);

ALTER TABLE TDOCSTATE
    ADD CONSTRAINT TDOCSTATE_PK 
PRIMARY KEY (OBJECTID);

CREATE INDEX TDOCSTATEINDEX2 ON TDOCSTATE (STATEFLAG);
CREATE INDEX TDOCSTATEINDEX3 ON TDOCSTATE (PROJECTTYPE);


-- TDISABLEFIELD
CREATE TABLE TDISABLEFIELD
(
	OBJECTID NUMBER NOT NULL,
	FIELDNAME VARCHAR(25) NOT NULL,
	LISTTYPE NUMBER,
	PROJECTTYPE NUMBER
);

ALTER TABLE TDISABLEFIELD
    ADD CONSTRAINT TDISABLEFIELD_PK 
PRIMARY KEY (OBJECTID);

CREATE INDEX TDISABLEFIELDINDEX2 ON TDISABLEFIELD (LISTTYPE);
CREATE INDEX TDISABLEFIELDINDEX3 ON TDISABLEFIELD (PROJECTTYPE);


-- TPCURRENCY
CREATE TABLE TPCURRENCY
(
	OBJECTID NUMBER NOT NULL,
	CURRENCY NUMBER,
	PROJECTTYPE NUMBER
);

ALTER TABLE TPCURRENCY
    ADD CONSTRAINT TPCURRENCY_PK 
PRIMARY KEY (OBJECTID);


CREATE INDEX TPCURRENCYINDEX2 ON TPCURRENCY (CURRENCY);
CREATE INDEX TPCURRENCYINDEX3 ON TPCURRENCY (PROJECTTYPE);


-- TPLISTTYPE
CREATE TABLE TPLISTTYPE
(
	OBJECTID NUMBER NOT NULL,
	PROJECTTYPE NUMBER,
	CATEGORY NUMBER
);

ALTER TABLE TPLISTTYPE
    ADD CONSTRAINT TPLISTTYPE_PK 
PRIMARY KEY (OBJECTID);

CREATE INDEX TPLISTTYPEINDEX2 ON TPLISTTYPE (PROJECTTYPE);
CREATE INDEX TPLISTTYPEINDEX3 ON TPLISTTYPE (CATEGORY);


-- TPROJECTTYPE
CREATE TABLE TPROJECTTYPE
(
	OBJECTID NUMBER NOT NULL,
	LABEL VARCHAR (35),
    NOTIFYOWNERLEVEL NUMBER,
    NOTIFYMANAGERLEVEL NUMBER
);

ALTER TABLE TPROJECTTYPE
    ADD CONSTRAINT TPROJECTTYPE_PK 
PRIMARY KEY (OBJECTID);




-- TPSTATE
CREATE TABLE TPSTATE
(
	OBJECTID NUMBER NOT NULL,
	STATE NUMBER,
	PROJECTTYPE NUMBER,
    LISTTYPE NUMBER NOT NULL
);

ALTER TABLE TPSTATE
    ADD CONSTRAINT TPSTATE_PK 
PRIMARY KEY (OBJECTID);

CREATE INDEX TPSTATEINDEX2 ON TPSTATE (STATE);
CREATE INDEX TPSTATEINDEX3 ON TPSTATE (PROJECTTYPE);
CREATE INDEX TPSTATEINDEX4 ON TPSTATE (LISTTYPE);


-- TSITE
CREATE TABLE TSITE
(
	OBJECTID NUMBER NOT NULL,
	TRACKVERSION VARCHAR (10),
	DBVERSION VARCHAR (10),
	LICENSEKEY VARCHAR (80),
	EXPDATE TIMESTAMP,
	NUMBEROFUSERS NUMBER,
	TRACKEMAIL VARCHAR (100),
	SMTPSERVERNAME VARCHAR (100),
	SMTPPORT NUMBER,
	MAILENCODING VARCHAR (20),
	SMTPUSER VARCHAR (100),
	SMTPPASSWORD VARCHAR (30),
	POPSERVERNAME VARCHAR (100),
	POPPORT NUMBER,
	POPUSER VARCHAR (100),
	POPPASSWORD VARCHAR (30),
	ALLOWEDEMAILPATTERN VARCHAR(4000),
	ISLDAPON CHAR(1),
	LDAPSERVERURL VARCHAR (100),
	LDAPATTRIBUTELOGINNAME VARCHAR (10),
	ATTACHMENTROOTDIR VARCHAR(512),
	SERVERURL VARCHAR (100),
	DESCRIPTIONLENGTH NUMBER,
	ISSELFREGISTERALLOWED CHAR(1) default 'Y',
	ISDEMOSITE CHAR(1) default 'N',
    USETRACKFROMADDRESS CHAR (1) default 'Y',
    RESERVEDUSE NUMBER
);

ALTER TABLE TSITE
    ADD CONSTRAINT TSITE_PK 
PRIMARY KEY (OBJECTID);


-- TWORKFLOW
CREATE TABLE TWORKFLOW
(
	OBJECTID NUMBER NOT NULL,
	STATEFROM NUMBER,
	STATETO NUMBER,
	MAYCHANGEROLE NUMBER,
	CHANGETOROLE NUMBER,
	PROJECTTYPE NUMBER,
    LISTTYPE NUMBER NOT NULL
);

ALTER TABLE TWORKFLOW
    ADD CONSTRAINT TWORKFLOW_PK 
PRIMARY KEY (OBJECTID);


CREATE INDEX TWORKFLOWINDEX2 ON TWORKFLOW (STATEFROM);
CREATE INDEX TWORKFLOWINDEX3 ON TWORKFLOW (STATETO);
CREATE INDEX TWORKFLOWINDEX4 ON TWORKFLOW (MAYCHANGEROLE);
CREATE INDEX TWORKFLOWINDEX5 ON TWORKFLOW (CHANGETOROLE);
CREATE INDEX TWORKFLOWINDEX6 ON TWORKFLOW (PROJECTTYPE);
CREATE INDEX TWORKFLOWINDEX7 ON TWORKFLOW (LISTTYPE);



/* --------------------------------------------------------------------------
TROLELISTTYPE
-------------------------------------------------------------------------- */
CREATE TABLE TROLELISTTYPE
(
    OBJECTID NUMBER NOT NULL,
    PROLE NUMBER NOT NULL,
    LISTTYPE NUMBER NOT NULL
);


CREATE INDEX TROLELISTTYPEINDEX2 ON TROLELISTTYPE (PROLE);
CREATE INDEX TROLELISTTYPEINDEX3 ON TROLELISTTYPE (LISTTYPE);

ALTER TABLE TROLELISTTYPE
    ADD CONSTRAINT TROLELISTTYPE_PK 
PRIMARY KEY (OBJECTID);



ALTER TABLE TBASELINE 
	ADD CONSTRAINT TBASELINE_FK_3 FOREIGN KEY (CURRENCY)
		REFERENCES TCURRENCY (OBJECTID);

ALTER TABLE TNOTIFY
	ADD CONSTRAINT TNOTIFY_FK_4 FOREIGN KEY (WORKITEM)
		REFERENCES TWORKITEM (WORKITEMKEY);

ALTER TABLE TPERSON
        ADD CONSTRAINT TPERSON_FK_2 FOREIGN KEY (MYDEFAULTREPORT)
            REFERENCES TPRIVATEREPORTREPOSITORY (PKEY);
                        
ALTER TABLE TPROJECT
	ADD CONSTRAINT TPROJECT_FK_3 FOREIGN KEY (DEFMANAGER)
		REFERENCES TPERSON (PKEY);
ALTER TABLE TPROJECT
	ADD CONSTRAINT TPROJECT_FK_4 FOREIGN KEY (PROJECTTYPE)
		REFERENCES TPROJECTTYPE (OBJECTID);

ALTER TABLE TROLE
	ADD CONSTRAINT TROLE_FK_1 FOREIGN KEY (PROJECTTYPE)
		REFERENCES TPROJECTTYPE (OBJECTID);
		
ALTER TABLE TWORKITEM
	ADD CONSTRAINT TWORKITEM_FK_13 FOREIGN KEY (CURRENCY)
		REFERENCES TCURRENCY (OBJECTID);
		
ALTER TABLE TPRIVATEREPORTREPOSITORY
	ADD CONSTRAINT TPRIVATEREPORTREPOSITORY_FK_1 FOREIGN KEY (OWNER)
		REFERENCES TPERSON (PKEY);


ALTER TABLE TPUBLICREPORTREPOSITORY
	ADD CONSTRAINT TPUBLICREPORTREPOSITORY_FK_1 FOREIGN KEY (OWNER)
		REFERENCES TPERSON (PKEY);


ALTER TABLE TPROJECTREPORTREPOSITORY
	ADD CONSTRAINT TPROJECTREPORTREPOSITORY_FK_1 FOREIGN KEY (PROJECT)
		REFERENCES TPROJECT (PKEY);

		
ALTER TABLE TACCOUNT
	ADD CONSTRAINT TACCOUNT_FK_1 FOREIGN KEY (PROJECT)
		REFERENCES TPROJECT (PKEY);

ALTER TABLE TATTACHMENT
	ADD CONSTRAINT TATTACHMENT_FK_1 FOREIGN KEY (WORKITEM)
		REFERENCES TWORKITEM (WORKITEMKEY);
ALTER TABLE TATTACHMENT
	ADD CONSTRAINT TATTACHMENT_FK_2 FOREIGN KEY (CHANGEDBY)
		REFERENCES TPERSON (PKEY);
ALTER TABLE TATTACHMENT
	ADD CONSTRAINT TATTACHMENT_FK_3 FOREIGN KEY (DOCUMENTSTATE)
		REFERENCES TDOCSTATE (OBJECTID);

ALTER TABLE TCOST
	ADD CONSTRAINT TCOST_FK_1 FOREIGN KEY (ACCOUNT)
		REFERENCES TACCOUNT (OBJECTID);
ALTER TABLE TCOST
	ADD CONSTRAINT TCOST_FK_2 FOREIGN KEY (PERSON)
		REFERENCES TPERSON (PKEY);
ALTER TABLE TCOST
	ADD CONSTRAINT TCOST_FK_3 FOREIGN KEY (WORKITEM)
		REFERENCES TWORKITEM (WORKITEMKEY);
ALTER TABLE TCOST
	ADD CONSTRAINT TCOST_FK_4 FOREIGN KEY (CURRENCY)
		REFERENCES TCURRENCY (OBJECTID);

ALTER TABLE TDOCSTATE
	ADD CONSTRAINT TDOCSTATE_FK_1 FOREIGN KEY (PROJECTTYPE)
		REFERENCES TPROJECTTYPE (OBJECTID);

ALTER TABLE TDISABLEFIELD
	ADD CONSTRAINT TDISABLEFIELD_FK_1 FOREIGN KEY (LISTTYPE)
		REFERENCES TCATEGORY (PKEY);
ALTER TABLE TDISABLEFIELD
	ADD CONSTRAINT TDISABLEFIELD_FK_2 FOREIGN KEY (PROJECTTYPE)
		REFERENCES TPROJECTTYPE (OBJECTID);

ALTER TABLE TPCURRENCY
	ADD CONSTRAINT TPCURRENCY_FK_1 FOREIGN KEY (CURRENCY)
		REFERENCES TCURRENCY (OBJECTID);
ALTER TABLE TPCURRENCY
	ADD CONSTRAINT TPCURRENCY_FK_2 FOREIGN KEY (PROJECTTYPE)
		REFERENCES TPROJECTTYPE (OBJECTID);

ALTER TABLE TPLISTTYPE
	ADD CONSTRAINT TPLISTTYPE_FK_1 FOREIGN KEY (PROJECTTYPE)
		REFERENCES TPROJECTTYPE (OBJECTID);
ALTER TABLE TPLISTTYPE
	ADD CONSTRAINT TPLISTTYPE_FK_2 FOREIGN KEY (CATEGORY)
		REFERENCES TCATEGORY (PKEY);

ALTER TABLE TPSTATE
	ADD CONSTRAINT TPSTATE_FK_1 FOREIGN KEY (STATE)
		REFERENCES TSTATE (PKEY);
ALTER TABLE TPSTATE
	ADD CONSTRAINT TPSTATE_FK_2 FOREIGN KEY (PROJECTTYPE)
		REFERENCES TPROJECTTYPE (OBJECTID);
ALTER TABLE TPSTATE
    ADD CONSTRAINT TPSTATE_FK_3 FOREIGN KEY (LISTTYPE) 
        REFERENCES TCATEGORY (PKEY);

ALTER TABLE TWORKFLOW
	ADD CONSTRAINT TWORKFLOW_FK_1 FOREIGN KEY (STATEFROM)
		REFERENCES TSTATE (PKEY);
ALTER TABLE TWORKFLOW
	ADD CONSTRAINT TWORKFLOW_FK_2 FOREIGN KEY (STATETO)
		REFERENCES TSTATE (PKEY);
ALTER TABLE TWORKFLOW
	ADD CONSTRAINT TWORKFLOW_FK_3 FOREIGN KEY (MAYCHANGEROLE)
		REFERENCES TROLE (PKEY);
ALTER TABLE TWORKFLOW
	ADD CONSTRAINT TWORKFLOW_FK_4 FOREIGN KEY (CHANGETOROLE)
		REFERENCES TROLE (PKEY);
ALTER TABLE TWORKFLOW
	ADD CONSTRAINT TWORKFLOW_FK_5 FOREIGN KEY (PROJECTTYPE)
		REFERENCES TPROJECTTYPE (OBJECTID);

ALTER TABLE TWORKFLOW
	ADD CONSTRAINT TWORKFLOW_FK_6 FOREIGN KEY (LISTTYPE) 
        REFERENCES TCATEGORY (PKEY);

ALTER TABLE TROLELISTTYPE
    ADD CONSTRAINT TROLELISTTYPE_FK_1 FOREIGN KEY (PROLE) 
        REFERENCES TROLE (PKEY);
ALTER TABLE TROLELISTTYPE
    ADD CONSTRAINT TROLELISTTYPE_FK_2 FOREIGN KEY (LISTTYPE) 
        REFERENCES TCATEGORY (PKEY);

COMMIT;

INSERT INTO ID_TABLE (ID_TABLE_ID, TABLE_NAME, NEXT_ID, QUANTITY) 
VALUES (21, 'TPRIVATEREPORTREPOSITORY', 1, 1);


INSERT INTO ID_TABLE (ID_TABLE_ID, TABLE_NAME, NEXT_ID, QUANTITY) 
VALUES (22, 'TPROJECTREPORTREPOSITORY', 1, 1);


INSERT INTO ID_TABLE (ID_TABLE_ID, TABLE_NAME, NEXT_ID, QUANTITY) 
VALUES (23, 'TPUBLICREPORTREPOSITORY', 1, 1);


INSERT INTO ID_TABLE (ID_TABLE_ID, TABLE_NAME, NEXT_ID, QUANTITY) VALUES
			(24, 'TPLISTTYPE', 1, 1);

INSERT INTO ID_TABLE (ID_TABLE_ID, TABLE_NAME, NEXT_ID, QUANTITY) VALUES
			(25, 'TPTDISABLEFIELD', 1, 1);

INSERT INTO ID_TABLE (ID_TABLE_ID, TABLE_NAME, NEXT_ID, QUANTITY) VALUES
			(26, 'TCOST', 1, 1);

INSERT INTO ID_TABLE (ID_TABLE_ID, TABLE_NAME, NEXT_ID, QUANTITY) VALUES
			(27, 'TACCOUNT', 1, 1);

INSERT INTO ID_TABLE (ID_TABLE_ID, TABLE_NAME, NEXT_ID, QUANTITY) VALUES
			(28, 'TCURRENCY', 3, 1);

INSERT INTO ID_TABLE (ID_TABLE_ID, TABLE_NAME, NEXT_ID, QUANTITY) VALUES
			(29, 'TPCURRENCY', 1, 1);

INSERT INTO ID_TABLE (ID_TABLE_ID, TABLE_NAME, NEXT_ID, QUANTITY) VALUES
			(30, 'TPROJECTTYPE', 1, 1);

INSERT INTO ID_TABLE (ID_TABLE_ID, TABLE_NAME, NEXT_ID, QUANTITY) VALUES
			(31, 'TPSTATE', 1, 1);

INSERT INTO ID_TABLE (ID_TABLE_ID, TABLE_NAME, NEXT_ID, QUANTITY) VALUES
			(32, 'TWORKFLOW', 1, 1);

INSERT INTO ID_TABLE (ID_TABLE_ID, TABLE_NAME, NEXT_ID, QUANTITY) VALUES
			(33, 'TDOCSTATE', 5, 1);

INSERT INTO ID_TABLE (ID_TABLE_ID, TABLE_NAME, NEXT_ID, QUANTITY) VALUES
			(34, 'TSITE', 1, 1);

INSERT INTO ID_TABLE (ID_TABLE_ID, TABLE_NAME, NEXT_ID, QUANTITY) VALUES
			(35, 'TROLELISTTYPE', 1, 1);
			






