/**
 * Genji Scrum Tool and Issue Tracker
 * Copyright (C) 2015 Steinbeis GmbH & Co. KG Task Management Solutions

 * <a href="http://www.trackplus.com">Genji Scrum Tool</a>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

/* $Id:$ */

package com.aurel.track.persist;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.Iterator;
import java.util.LinkedList;
import java.util.List;
import java.util.Map;

import org.apache.logging.log4j.Logger;
import org.apache.logging.log4j.LogManager;
import org.apache.torque.TorqueException;
import org.apache.torque.util.Criteria;

import com.aurel.track.beans.TPpriorityBean;
import com.aurel.track.dao.PPriorityDAO;
import com.workingdogs.village.DataSetException;
import com.workingdogs.village.Record;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Mon Feb 14 15:14:25 CET 2005]
 *
 *  You should add additional methods to this class to meet the
 *  application requirements.  This class will only be generated as
 *  long as it does not already exist in the output directory.
 */
public class TPpriorityPeer
	extends com.aurel.track.persist.BaseTPpriorityPeer
	implements PPriorityDAO
{

	private static final long serialVersionUID = -1047692715741783158L;

	private static final Logger LOGGER = LogManager.getLogger(TPpriorityPeer.class); 
	
	/**
	 * Loads all TPpriorityBeans 
	 * @return
	 */
	@Override
	public List<TPpriorityBean> loadAll() {
		Criteria crit = new Criteria();
		try {
			return convertTorqueListToBeanList(doSelect(crit));
		} catch (TorqueException e) {
			LOGGER.error("Loading all ppriorities failed with " + e.getMessage());
			return new LinkedList<TPpriorityBean>();
		}
	}
	
	/**
	 * Gets the number of valid priorities for issue types in a projectType
	 * @param projectTypeID
	 * @return
	 */
	@Override
	public Map<Integer, Integer> loadNumberOfPrioritiesForIssueTypesInProjectType(Integer projectTypeID) {
		Map<Integer, Integer> numberOfPrioritiesForIssueTypes = new HashMap<Integer, Integer>();
		Criteria crit = new Criteria();
		crit.add(PROJECTTYPE, projectTypeID);
		String countPriorities = "COUNT(" + PRIORITY + ")";
		crit.addSelectColumn(countPriorities);
		crit.addSelectColumn(LISTTYPE);
		crit.addGroupByColumn(LISTTYPE);
		List<Record> records = new LinkedList<Record>();
		try {
			records = doSelectVillageRecords(crit);
		} catch(Exception e) {
			LOGGER.error("Groupping the priorities by issueTypes in projectType " + projectTypeID + " failed with " + e.getMessage());
		}
		try {
			if (records!=null && !records.isEmpty()) {
				for (Record record : records) {
					Integer numberOfPersons = record.getValue(1).asIntegerObj();
					Integer roleID = record.getValue(2).asIntegerObj();
					numberOfPrioritiesForIssueTypes.put(roleID, numberOfPersons); 
				}
			}
		} catch (Exception e) {
			LOGGER.error("Getting the number of priorities by issueTypes in projectType " + projectTypeID + " failed with " + e.getMessage());
		}
		return numberOfPrioritiesForIssueTypes;
	}
	/**
	 * Gets the number of valid priorities for an issue type in a projectType
	 * @param projectTypeID
	 * @param issueTypeID
	 * @return
	 */
	@Override
	public Integer loadNumberOfPrioritiesForIssueTypeInProjectType(Integer projectTypeID, Integer issueTypeID) {
		Criteria crit = new Criteria();
		crit.add(PROJECTTYPE, projectTypeID);
		crit.add(LISTTYPE, issueTypeID);
		String countPriorities = "COUNT(" + PRIORITY + ")";
		crit.addSelectColumn(countPriorities);
		try {
			return ((Record) doSelectVillageRecords(crit).get(0)).getValue(1).asIntegerObj();
		} catch (TorqueException e) {
			LOGGER.error("Counting the priorities in projectTypeID " + projectTypeID + " and issueTypeID " +
					issueTypeID + " failed with TorqueException " + e.getMessage(), e);
		} catch (DataSetException e) {
			LOGGER.error("Counting the priorities in projectTypeID " + projectTypeID + " and issueTypeID " +
					issueTypeID + " failed with DataSetException " + e.getMessage(), e);
		}
		return Integer.valueOf(0);
	}
	
	/**
	 * Load TPpriorityBeans by project type
	 * @param projectType
	 * @return
	 */
	@Override
	public List<TPpriorityBean> loadByProjectType(Integer projectType) {
		Criteria crit = new Criteria();
		crit.add(PROJECTTYPE, projectType, Criteria.EQUAL); 
		try {
			return convertTorqueListToBeanList(doSelect(crit));
		}
		catch (Exception e) {
			LOGGER.error("Loading by project type " +  projectType + " failed with " + e.getMessage());
			return new ArrayList<TPpriorityBean>();
		}
	}
	
	/**
	 * Load TPpriorityBeans by project types and priorities
	 * @param projectType
	 * @param priorities
	 * @return
	 */
	@Override
	public List<TPpriorityBean> loadByProjectTypeAndPriorities(Integer projectType, List<Integer> priorities) {
		if (priorities==null || priorities.isEmpty() || projectType==null) {
			return new ArrayList<TPpriorityBean>();
		}
		Criteria crit = new Criteria();
		crit.add(PROJECTTYPE, projectType, Criteria.EQUAL); 
		crit.addIn(PRIORITY, priorities);
		try {
			return convertTorqueListToBeanList(doSelect(crit));
		}
		catch (Exception e) {
			LOGGER.error("Loading by project type " +  projectType + " and priorities " + priorities.size() + " failed with " + e.getMessage());
			return new ArrayList<TPpriorityBean>();
		}
	}
	
	/**
	 * Load TPpriorityBeans by project types and issueType
	 * @param projectType
	 * @param issueType
	 * @return
	 */
	@Override
	public List<TPpriorityBean> loadByProjectTypeAndIssueType(Integer projectType, Integer issueType) {		
		Criteria crit = new Criteria();
		crit.add(PROJECTTYPE, projectType);
		crit.add(LISTTYPE, issueType);
		crit.add(PRIORITY, 0, Criteria.NOT_EQUAL);
		try {
			return convertTorqueListToBeanList(doSelect(crit));
		} catch (TorqueException e) {
			LOGGER.error("Getting the priorities allowed by project type "+ projectType + 
					" and issue type " + issueType + " failed with " + e.getMessage(), e);
			 return new LinkedList<TPpriorityBean>();
		}
	}
	
	/**
	 * Load TPpriorityBeans by project types and issueTypes
	 * @param projectType
	 * @param issueTypes
	 * @return
	 */
	@Override
	public List<TPpriorityBean> loadByProjectTypeAndIssueTypes(Integer projectType, List<Integer> issueTypes) {
		if (issueTypes==null || issueTypes.isEmpty() || projectType==null) {
			return new LinkedList<TPpriorityBean>();
		}		
		Criteria crit = new Criteria();
		crit.add(PROJECTTYPE, projectType);
		crit.addIn(LISTTYPE, issueTypes);
		crit.add(PRIORITY, 0, Criteria.NOT_EQUAL);
		try {
			return convertTorqueListToBeanList(doSelect(crit));
		} catch (TorqueException e) {
			LOGGER.error("Getting the priorities allowed by project type "+ projectType + 
					" and issue types " + issueTypes.size() + " failed with " + e.getMessage(), e);
			 return new LinkedList<TPpriorityBean>();
		}
	}
	
	/**
	 * Save  TPpriorityBean in the TPpriority table
	 * @param ppriorityBean
	 * @return
	 */
	@Override
	public Integer save(TPpriorityBean ppriorityBean) {
		TPpriority tpPpriority;
		try {
			tpPpriority = BaseTPpriority.createTPpriority(ppriorityBean);
			tpPpriority.save();
			return tpPpriority.getObjectID();
			
		} catch (Exception e) {
			LOGGER.error("Saving of an ppriorityBean failed with " + e.getMessage());
			return null;
		}
	}
	
	/**
	 * Deletes a TPpriorityBean from the TPpriority table 
	 * @param objectID
	 * @return
	 */
	@Override
	public void delete(Integer objectID) {
		Criteria crit = new Criteria();
		crit.add(OBJECTID, objectID);
		try {
			doDelete(crit);
		} catch (TorqueException e) {
			LOGGER.error("Deleting the TPpriorityBean " + objectID + " failed with: " + e);
		}
	}
	
	/**
	 * Deletes TPpriorityBean(s) from the TPpriority table 
	 * @param projectTypeID
	 * @param itemTypeID
	 * @param priorityID
	 */
	@Override
	public void delete(Integer projectTypeID, Integer itemTypeID, List<Integer> priorityIDs) {
		if (projectTypeID==null || itemTypeID==null || priorityIDs==null || priorityIDs.isEmpty()) {
			return;
		}
		Criteria crit = new Criteria();
		crit.add(PROJECTTYPE, projectTypeID);
		crit.add(LISTTYPE, itemTypeID);
		crit.addIn(PRIORITY, priorityIDs);
		try {
			doDelete(crit);
		} catch (TorqueException e) {
			LOGGER.error("Deleting the TPstateBean by projectType " + projectTypeID +
					" and issueType " + itemTypeID + " and priorities " + priorityIDs.size() + " failed with: " + e);
		}
	}
	
	private List<TPpriorityBean> convertTorqueListToBeanList(List<TPpriority> torqueList) {
		List<TPpriorityBean> beanList = new LinkedList<TPpriorityBean>();
		if (torqueList!=null){
			Iterator<TPpriority> itrTorqueList = torqueList.iterator();
			while (itrTorqueList.hasNext()){
				beanList.add(itrTorqueList.next().getBean());
			}
		}
		return beanList;
	}
}
