/**
 * Genji Scrum Tool and Issue Tracker
 * Copyright (C) 2015 Steinbeis GmbH & Co. KG Task Management Solutions

 * <a href="http://www.trackplus.com">Genji Scrum Tool</a>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

/* $Id:$ */

package com.aurel.track.persist;

import java.util.ArrayList;
import java.util.List;

import org.apache.logging.log4j.Logger;
import org.apache.logging.log4j.LogManager;
import org.apache.torque.TorqueException;
import org.apache.torque.util.Criteria;

import com.aurel.track.beans.TPrivateReportRepositoryBean;
import com.aurel.track.dao.PrivateRepositoryDAO;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Fri Apr 30 10:33:48 CEST 2004]
 *
 *  You should add additional methods to this class to meet the
 *  application requirements.  This class will only be generated as
 *  long as it does not already exist in the output directory.
 */
public class TPrivateReportRepositoryPeer
	extends com.aurel.track.persist.BaseTPrivateReportRepositoryPeer
	implements PrivateRepositoryDAO
{

	private static final long serialVersionUID = 7003871634095827595L;
	
	private static final Logger LOGGER = LogManager.getLogger(TPrivateReportRepositoryPeer.class); 
	
	/**
	 * Load all private TQLs
	 * @return
	 */
	@Override
	public List<TPrivateReportRepositoryBean> loadAll() {
		try {
			Criteria criteria = new Criteria ();
			return convertTorqueListToBeanList(doSelect (criteria));
		} catch (TorqueException e) {
			LOGGER.error("Getting all TPrivateReportRepositories failed with " + e.getMessage());
			return null;
		}
	}
	
	/**
	 * Converts a list of TPrivateReportRepository torque objects 
	 * to a list of TPrivateReportRepositoryBean objects 
	 * @param torqueList
	 * @return
	 */
	private static List<TPrivateReportRepositoryBean> convertTorqueListToBeanList(
			List<TPrivateReportRepository> torqueList) {
		List<TPrivateReportRepositoryBean> beanList = new ArrayList<TPrivateReportRepositoryBean>();
		if (torqueList!=null) {
			for (TPrivateReportRepository privateReportRepository : torqueList) {
				beanList.add(privateReportRepository.getBean());
			}
		}
		return beanList;
	}

	
}
