/**
 * Genji Scrum Tool and Issue Tracker
 * Copyright (C) 2015 Steinbeis GmbH & Co. KG Task Management Solutions

 * <a href="http://www.trackplus.com">Genji Scrum Tool</a>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

/* $Id:$ */


package com.aurel.track.persist;

import java.util.ArrayList;
import java.util.List;

import org.apache.logging.log4j.Logger;
import org.apache.logging.log4j.LogManager;
import org.apache.torque.util.Criteria;

import com.aurel.track.beans.TWorkFlowRoleBean;
import com.aurel.track.dao.WorkflowRoleDAO;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Tue Jun 15 21:31:34 CEST 2004]
 *
 *  You should add additional methods to this class to meet the
 *  application requirements.  This class will only be generated as
 *  long as it does not already exist in the output directory.
 *
 * @author Sergej Redel <sergej@schoene-hochzeit.com>
 * @author Martin Bierkoch <martin.bierkoch@gmx.de>
 * @version $Revision: 1795 $ $Date: 2015-11-12 13:07:18 +0100 (Thu, 12 Nov 2015) $
 */
public class TWorkFlowRolePeer
    extends com.aurel.track.persist.BaseTWorkFlowRolePeer
    implements WorkflowRoleDAO
{
    private static final long serialVersionUID = 6244732857929601740L;
    private static final Logger LOGGER = LogManager.getLogger(TWorkFlowRolePeer.class);

    /**
	 * Load all workflow roles
	 * @return
	 */
	@Override
	public List<TWorkFlowRoleBean> loadAll() {
		try {
			Criteria crit = new Criteria();
			return convertTorqueListToBeanList(doSelect(crit));
		}
		catch (Exception e) {
			LOGGER.error("Loading all workflow roles for migration failed with " + e.getMessage());
			return null;
		}
	}

	/**
	 * Convert the torque objects to beans
	 * @param torqueList
	 * @return
	 */
	private static List<TWorkFlowRoleBean> convertTorqueListToBeanList(List<TWorkFlowRole> torqueList) {
		List<TWorkFlowRoleBean> beanList = new ArrayList<TWorkFlowRoleBean>();
		if (torqueList!=null){
			for (TWorkFlowRole tWorkFlowRole : torqueList) {
				beanList.add(tWorkFlowRole.getBean());
			}
		}
		return beanList;
	}

}
