--------------------------------------------------------------------------
-- TDOMAIN
--------------------------------------------------------------------------

CREATE TABLE TDOMAIN
(
    OBJECTID INTEGER NOT NULL,
    LABEL VARCHAR (255),
    DESCRIPTION VARCHAR (10000),
    TPUUID VARCHAR (36)
);

ALTER TABLE TDOMAIN
    ADD PRIMARY KEY (OBJECTID);


CREATE  INDEX TDOMAININDEX1 ON TDOMAIN (TPUUID);

ALTER TABLE TPERSON ADD HOURLYWAGE DOUBLE;
ALTER TABLE TPERSON ADD EXTRAHOURWAGE DOUBLE;
ALTER TABLE TWORKITEM ADD OVERBUDGET VARCHAR (1) default 'N';
ALTER TABLE TSCREENFIELD ADD ICONRENDERING INTEGER;
ALTER TABLE TWORKITEMLINK ADD SORTORDER INTEGER;

ALTER TABLE TCATEGORY ADD TOOLTIP VARCHAR (255);
ALTER TABLE TDEPARTMENT ADD DOMAINKEY INTEGER;
ALTER TABLE TDEPARTMENT
    ADD CONSTRAINT TDEPARTMENT_FK_2 FOREIGN KEY (DOMAINKEY)
    REFERENCES TDOMAIN (OBJECTID)
;
ALTER TABLE TPRIORITY ADD TOOLTIP VARCHAR (255);
ALTER TABLE TPROJECT ADD SORTORDER INTEGER;
ALTER TABLE TPROJECT ADD ISTEMPLATE VARCHAR (1) default 'N';
ALTER TABLE TPROJECT ADD DOMAINKEY INTEGER;
CREATE  INDEX TPROJECTINDEX2 ON TPROJECT (SORTORDER);
ALTER TABLE TPROJECT
    ADD CONSTRAINT TPROJECT_FK_7 FOREIGN KEY (DOMAINKEY)
    REFERENCES TDOMAIN (OBJECTID)
;
ALTER TABLE TSEVERITY ADD TOOLTIP VARCHAR (255);
ALTER TABLE TSTATE ADD TOOLTIP VARCHAR (255);
ALTER TABLE TATTACHMENT ADD ISURL VARCHAR (1) default 'N';
ALTER TABLE TFIELD ADD PROJECTTYPE INTEGER;
ALTER TABLE TFIELD ADD PROJECT INTEGER;
ALTER TABLE TFIELD
    ADD CONSTRAINT TFIELD_FK_2 FOREIGN KEY (PROJECTTYPE)
    REFERENCES TPROJECTTYPE (OBJECTID)
;
ALTER TABLE TFIELD
    ADD CONSTRAINT TFIELD_FK_3 FOREIGN KEY (PROJECT)
    REFERENCES TPROJECT (PKEY)
;
ALTER TABLE TOPTION ADD TOOLTIP VARCHAR (255);
ALTER TABLE TSCREEN ADD PROJECTTYPE INTEGER;
ALTER TABLE TSCREEN ADD PROJECT INTEGER;
ALTER TABLE TSCREEN
    ADD CONSTRAINT TSCREEN_FK_2 FOREIGN KEY (PROJECTTYPE)
    REFERENCES TPROJECTTYPE (OBJECTID)
;
ALTER TABLE TSCREEN
    ADD CONSTRAINT TSCREEN_FK_3 FOREIGN KEY (PROJECT)
    REFERENCES TPROJECT (PKEY)
;

ALTER TABLE TDASHBOARDSCREEN ADD OWNER INTEGER;
ALTER TABLE TDASHBOARDSCREEN
    ADD CONSTRAINT TDASHBOARDSCREEN_FK_3 FOREIGN KEY (OWNER)
    REFERENCES TPERSON (PKEY)
;

ALTER TABLE TQUERYREPOSITORY ADD SORTORDER INTEGER;
ALTER TABLE TQUERYREPOSITORY ADD VIEWID VARCHAR (255);
CREATE  INDEX TQUERYREPINDEX2 ON TQUERYREPOSITORY (SORTORDER);
ALTER TABLE TEXPORTTEMPLATE ADD PARENT INTEGER;
ALTER TABLE TEXPORTTEMPLATE ADD SORTORDER INTEGER;
CREATE  INDEX TEXPOPRTTEMPINDEX2 ON TEXPORTTEMPLATE (SORTORDER);
ALTER TABLE TEXPORTTEMPLATE
    ADD CONSTRAINT TEXPORTTEMPLATE_FK_4 FOREIGN KEY (PARENT)
    REFERENCES TEXPORTTEMPLATE (OBJECTID);
ALTER TABLE TREPORTPERSONSETTINGS DROP CONSTRAINT TREPORTPERSON_FK_2;
ALTER TABLE TREPORTPERSONSETTINGS DROP CONSTRAINT TREPORTPERSON_FK_3;
ALTER TABLE TREPORTPERSONSETTINGS
    ADD CONSTRAINT TREPORTPERSON_FK_2 FOREIGN KEY (REPORTTEMPLATE)
    REFERENCES TEXPORTTEMPLATE (OBJECTID);
ALTER TABLE TREPORTPERSONSETTINGS DROP RECURRENCEPATTERN;
ALTER TABLE TFILTERCATEGORY ADD SORTORDER INTEGER;
CREATE  INDEX TFILTERCATEGORYINDEX2 ON TFILTERCATEGORY (SORTORDER);
ALTER TABLE TREPORTCATEGORY ADD SORTORDER INTEGER;
CREATE  INDEX TREPORTCATEGORYINDEX2 ON TREPORTCATEGORY (SORTORDER);
ALTER TABLE TWORKFLOWTRANSITION ADD ELAPSEDTIME INTEGER;
ALTER TABLE TWORKFLOWTRANSITION ADD TIMEUNIT INTEGER;
ALTER TABLE TWORKFLOWACTIVITY ADD FIELDSETTERRELATION INTEGER;
ALTER TABLE TWORKFLOWACTIVITY ADD PARAMNAME VARCHAR (255);
ALTER TABLE TWORKFLOWACTIVITY ADD FIELDSETMODE INTEGER;
ALTER TABLE TWORKFLOWACTIVITY ADD SORTORDER INTEGER;
ALTER TABLE TREADISSUE ADD FIELDKEY INTEGER;
ALTER TABLE TREADISSUE ADD LASTEDIT TIMESTAMP;
CREATE INDEX TREADISSUEINDEX4 ON TREADISSUE (FIELDKEY);

-----------------------------------------------------------------------------
-- TWFACTIVITYCONTEXTPARAMS
-----------------------------------------------------------------------------
-- drop table TWFACTIVITYCONTEXTPARAMS;

CREATE TABLE TWFACTIVITYCONTEXTPARAMS
(
    OBJECTID INTEGER NOT NULL,
    WORKFLOWACTIVITY INTEGER NOT NULL,
    ISSUETYPE INTEGER,
    PROJECTTYPE INTEGER,
    PROJECT INTEGER,
    SETTERORPARTID INTEGER,
    ACTIVITYPARAMS VARCHAR (31000),
    TPUUID VARCHAR (36)
);

ALTER TABLE TWFACTIVITYCONTEXTPARAMS
    ADD PRIMARY KEY (OBJECTID);


CREATE  INDEX TWFACTIVITYCONTEXTPARAMSINDEX1 ON TWFACTIVITYCONTEXTPARAMS (WORKFLOWACTIVITY);
CREATE  INDEX TWFACTIVITYCONTEXTPARAMSINDEX2 ON TWFACTIVITYCONTEXTPARAMS (ISSUETYPE);
CREATE  INDEX TWFACTIVITYCONTEXTPARAMSINDEX3 ON TWFACTIVITYCONTEXTPARAMS (PROJECTTYPE);
CREATE  INDEX TWFACTIVITYCONTEXTPARAMSINDEX4 ON TWFACTIVITYCONTEXTPARAMS (PROJECT);
CREATE  INDEX TWFACTIVITYCONTEXTPARAMSINDEX5 ON TWFACTIVITYCONTEXTPARAMS (TPUUID);

-----------------------------------------------------------------------------
-- TWORKFLOWCOMMENT
-----------------------------------------------------------------------------
-- drop table TWORKFLOWCOMMENT;

CREATE TABLE TWORKFLOWCOMMENT
(
    OBJECTID INTEGER NOT NULL,
    DESCRIPTION VARCHAR (10000),
    WORKFLOW INTEGER,
    NODEX INTEGER,
    NODEY INTEGER,
    TPUUID VARCHAR (36)
);

ALTER TABLE TWORKFLOWCOMMENT
    ADD PRIMARY KEY (OBJECTID);


CREATE  INDEX TWORKFLOWCOMMENTINDEX1 ON TWORKFLOWCOMMENT (WORKFLOW);
CREATE  INDEX TWORKFLOWCOMMENTINDEX2 ON TWORKFLOWCOMMENT (TPUUID);

-----------------------------------------------------------------------------
-- TREPORTSUBSCRIBE
-----------------------------------------------------------------------------
-- drop table TREPORTSUBSCRIBE;

CREATE TABLE TREPORTSUBSCRIBE
(
    OBJECTID INTEGER NOT NULL,
    PERSON INTEGER NOT NULL,
    RECURRENCEPATTERN INTEGER,
    REPORTTEMPLATE INTEGER NOT NULL,
    TPUUID VARCHAR (36)
);

ALTER TABLE TREPORTSUBSCRIBE
    ADD PRIMARY KEY (OBJECTID);


CREATE  INDEX TREPORTSUBSCRIBEINDEX1 ON TREPORTSUBSCRIBE (TPUUID);





-----------------------------------------------------------------------------
-- TGRIDLAYOUT
-----------------------------------------------------------------------------
-- drop table TGRIDLAYOUT;

CREATE TABLE TGRIDLAYOUT
(
    OBJECTID INTEGER NOT NULL,
    PERSON INTEGER,
    LAYOUTKEY INTEGER NOT NULL,
    TPUUID VARCHAR (36)
);

ALTER TABLE TGRIDLAYOUT
    ADD PRIMARY KEY (OBJECTID);


CREATE  INDEX TGRIDLAYOUTINDEX1 ON TGRIDLAYOUT (PERSON);
CREATE  INDEX TGRIDLAYOUTINDEX2 ON TGRIDLAYOUT (LAYOUTKEY);
CREATE  INDEX TGRIDLAYOUTINDEX3 ON TGRIDLAYOUT (TPUUID);


COMMENT ON TABLE TGRIDLAYOUT IS 'layout for grids';

COMMENT ON COLUMN TGRIDLAYOUT.LAYOUTKEY IS 'a hardcoded key to identify the grid';


-----------------------------------------------------------------------------
-- TGRIDFIELD
-----------------------------------------------------------------------------
-- drop table TGRIDFIELD;

CREATE TABLE TGRIDFIELD
(
    OBJECTID INTEGER NOT NULL,
    GRIDLAYOUT INTEGER NOT NULL,
    GRIDFIELD INTEGER NOT NULL,
    FIELDPOSITION INTEGER NOT NULL,
    FIELDWIDTH INTEGER NOT NULL,
    FILTERSTRING VARCHAR (255),
    TPUUID VARCHAR (36)
);

ALTER TABLE TGRIDFIELD
    ADD PRIMARY KEY (OBJECTID);


CREATE  INDEX TGRIDFIELDINDEX1 ON TGRIDFIELD (GRIDLAYOUT);
CREATE  INDEX TGRIDFIELDINDEX2 ON TGRIDFIELD (TPUUID);


COMMENT ON TABLE TGRIDFIELD IS 'fields in grids';



-----------------------------------------------------------------------------
-- TGRIDGROUPINGSORTING
-----------------------------------------------------------------------------
-- drop table TGRIDGROUPINGSORTING;

CREATE TABLE TGRIDGROUPINGSORTING
(
    OBJECTID INTEGER NOT NULL,
    GRIDLAYOUT INTEGER NOT NULL,
    GRIDFIELD INTEGER NOT NULL,
    SORTPOSITION INTEGER NOT NULL,
    ISGROUPING VARCHAR (1) default 'N',
    ISDESCENDING VARCHAR (1) default 'N',
    ISCOLLAPSED VARCHAR (1) default 'N',
    TPUUID VARCHAR (36)
);

ALTER TABLE TGRIDGROUPINGSORTING
    ADD PRIMARY KEY (OBJECTID);


CREATE  INDEX TGRIDGROUPINGSORTINGINDEX1 ON TGRIDGROUPINGSORTING (GRIDLAYOUT);
CREATE  INDEX TGRIDGROUPINGSORTINGINDEX2 ON TGRIDGROUPINGSORTING (TPUUID);


COMMENT ON TABLE TGRIDGROUPINGSORTING IS 'grouping and sorting in grids';



-----------------------------------------------------------------------------
-- TNAVIGATORLAYOUT
-----------------------------------------------------------------------------
-- drop table TNAVIGATORLAYOUT;

CREATE TABLE TNAVIGATORLAYOUT
(
    OBJECTID INTEGER NOT NULL,
    PERSON INTEGER,
    FILTERID INTEGER,
    FILTERTYPE INTEGER,
    TPUUID VARCHAR (36)
);

ALTER TABLE TNAVIGATORLAYOUT
    ADD PRIMARY KEY (OBJECTID);


CREATE  INDEX TNAVIGATORLAYOUTINDEX1 ON TNAVIGATORLAYOUT (PERSON);
CREATE  INDEX TNAVIGATORLAYOUTINDEX2 ON TNAVIGATORLAYOUT (TPUUID);


COMMENT ON TABLE TNAVIGATORLAYOUT IS 'layout for item navigator';

COMMENT ON COLUMN TNAVIGATORLAYOUT.PERSON IS 'person is null for the global default layout';
COMMENT ON COLUMN TNAVIGATORLAYOUT.FILTERID IS 'specified for filter specific layout, null for default layout';
COMMENT ON COLUMN TNAVIGATORLAYOUT.FILTERTYPE IS 'specifies the type of the filter: dashboard, tree filter, etc.';


-----------------------------------------------------------------------------
-- TNAVIGATORCOLUMN
-----------------------------------------------------------------------------
-- drop table TNAVIGATORCOLUMN;

CREATE TABLE TNAVIGATORCOLUMN
(
    OBJECTID INTEGER NOT NULL,
    NAVIGATORLAYOUT INTEGER NOT NULL,
    FIELD INTEGER NOT NULL,
    FIELDPOSITION INTEGER NOT NULL,
    FIELDWIDTH INTEGER,
    TPUUID VARCHAR (36)
);

ALTER TABLE TNAVIGATORCOLUMN
    ADD PRIMARY KEY (OBJECTID);


CREATE  INDEX TNAVIGATORCOLUMNINDEX1 ON TNAVIGATORCOLUMN (NAVIGATORLAYOUT);
CREATE  INDEX TNAVIGATORCOLUMNINDEX2 ON TNAVIGATORCOLUMN (TPUUID);


COMMENT ON TABLE TNAVIGATORCOLUMN IS 'column in item navigator';



-----------------------------------------------------------------------------
-- TNAVIGATORGROUPINGSORTING
-----------------------------------------------------------------------------
-- drop table TNAVIGATORGROUPINGSORTING;

CREATE TABLE TNAVIGATORGROUPINGSORTING
(
    OBJECTID INTEGER NOT NULL,
    NAVIGATORLAYOUT INTEGER NOT NULL,
    FIELD INTEGER NOT NULL,
    SORTPOSITION INTEGER,
    ISGROUPING VARCHAR (1) default 'N',
    ISDESCENDING VARCHAR (1) default 'N',
    ISCOLLAPSED VARCHAR (1) default 'N',
    TPUUID VARCHAR (36)
);

ALTER TABLE TNAVIGATORGROUPINGSORTING
    ADD PRIMARY KEY (OBJECTID);


CREATE  INDEX TNAVIGATORGROUPINGSORTINGIDX1 ON TNAVIGATORGROUPINGSORTING (NAVIGATORLAYOUT);
CREATE  INDEX TNAVIGATORGROUPINGSORTINGIDX2 ON TNAVIGATORGROUPINGSORTING (TPUUID);


COMMENT ON TABLE TNAVIGATORGROUPINGSORTING IS 'grouping and sorting in item navigator';



-----------------------------------------------------------------------------
-- TCARDGROUPINGFIELD
-----------------------------------------------------------------------------
-- drop table TCARDGROUPINGFIELD;

CREATE TABLE TCARDGROUPINGFIELD
(
    OBJECTID INTEGER NOT NULL,
    NAVIGATORLAYOUT INTEGER NOT NULL,
    CARDFIELD INTEGER NOT NULL,
    ISACTIV VARCHAR (1) default 'N',
    SORTFIELD INTEGER,
    ISDESCENDING VARCHAR (1) default 'N',
    TPUUID VARCHAR (36)
);

ALTER TABLE TCARDGROUPINGFIELD
    ADD PRIMARY KEY (OBJECTID);


CREATE  INDEX TCARDGROUPINGFIELDINDEX1 ON TCARDGROUPINGFIELD (NAVIGATORLAYOUT);
CREATE  INDEX TCARDGROUPINGFIELDINDEX2 ON TCARDGROUPINGFIELD (TPUUID);


COMMENT ON TABLE TCARDGROUPINGFIELD IS 'grouping field for card';


-----------------------------------------------------------------------------
-- TCARDFIELDOPTION
-----------------------------------------------------------------------------
-- drop table TCARDFIELDOPTION;

CREATE TABLE TCARDFIELDOPTION
(
    OBJECTID INTEGER NOT NULL,
    GROUPINGFIELD INTEGER NOT NULL,
    OPTIONID INTEGER NOT NULL,
    OPTIONPOSITION INTEGER NOT NULL,
    OPTIONWIDTH INTEGER NOT NULL,
    MAXNUMBER INTEGER,
    TPUUID VARCHAR (36)
);

ALTER TABLE TCARDFIELDOPTION
    ADD PRIMARY KEY (OBJECTID);


CREATE  INDEX TCARDFIELDOPTIONINDEX1 ON TCARDFIELDOPTION (GROUPINGFIELD);
CREATE  INDEX TCARDFIELDOPTIONINDEX2 ON TCARDFIELDOPTION (TPUUID);


COMMENT ON TABLE TCARDFIELDOPTION IS 'fields for card';



-----------------------------------------------------------------------------
-- TCARDPANEL
-----------------------------------------------------------------------------
-- drop table TCARDPANEL;

CREATE TABLE TCARDPANEL
(
    OBJECTID INTEGER NOT NULL,
    PERSON INTEGER,
    ROWSNO INTEGER NOT NULL,
    COLSNO INTEGER NOT NULL,
    TPUUID VARCHAR (36)
);

ALTER TABLE TCARDPANEL
    ADD PRIMARY KEY (OBJECTID);


CREATE  INDEX TCARDPANELINDEX1 ON TCARDPANEL (TPUUID);





-----------------------------------------------------------------------------
-- TCARDFIELD
-----------------------------------------------------------------------------
-- drop table TCARDFIELD;

CREATE TABLE TCARDFIELD
(
    OBJECTID INTEGER NOT NULL,
    NAME VARCHAR (255),
    COLINDEX INTEGER,
    ROWINDEX INTEGER,
    COLSPAN INTEGER,
    ROWSPAN INTEGER,
    LABELHALIGN INTEGER NOT NULL,
    LABELVALIGN INTEGER NOT NULL,
    VALUEHALIGN INTEGER NOT NULL,
    VALUEVALIGN INTEGER NOT NULL,
    CARDPANEL INTEGER NOT NULL,
    FIELDKEY INTEGER,
    HIDELABEL VARCHAR (1) default 'Y',
    ICONRENDERING INTEGER,
    TPUUID VARCHAR (36)
);

ALTER TABLE TCARDFIELD
    ADD PRIMARY KEY (OBJECTID);


CREATE  INDEX TCARDFIELDINDEX1 ON TCARDFIELD (TPUUID);





-----------------------------------------------------------------------------
-- TVIEWPARAM
-----------------------------------------------------------------------------
-- drop table TVIEWPARAM;

CREATE TABLE TVIEWPARAM
(
    OBJECTID INTEGER NOT NULL,
    NAVIGATORLAYOUT INTEGER NOT NULL,
    PARAMNAME VARCHAR (255) NOT NULL,
    PARAMVALUE VARCHAR (10000),
    TPUUID VARCHAR (36)
);

ALTER TABLE TVIEWPARAM
    ADD PRIMARY KEY (OBJECTID);


CREATE  INDEX TVIEWPARAMINDEX1 ON TVIEWPARAM (NAVIGATORLAYOUT);
CREATE  INDEX TVIEWPARAMINDEX2 ON TVIEWPARAM (TPUUID);


COMMENT ON TABLE TVIEWPARAM IS 'general parameters for a view';



-----------------------------------------------------------------------------
-- TGENERALPARAM
-----------------------------------------------------------------------------
-- drop table TGENERALPARAM;

CREATE TABLE TGENERALPARAM
(
    OBJECTID INTEGER NOT NULL,
    PARAMNAME VARCHAR (255) NOT NULL,
    PARAMVALUE VARCHAR (10000),
    TPUUID VARCHAR (36)
);

ALTER TABLE TGENERALPARAM
    ADD PRIMARY KEY (OBJECTID);


CREATE  INDEX TGENERALPARAMINDEX1 ON TGENERALPARAM (TPUUID);


COMMENT ON TABLE TGENERALPARAM IS 'general parameters for the system';



-----------------------------------------------------------------------------
-- TVERSIONCONTROL
-----------------------------------------------------------------------------
-- drop table TVERSIONCONTROL;

CREATE TABLE TVERSIONCONTROL
(
    OBJECTID INTEGER NOT NULL,
    VCTYPE INTEGER NOT NULL,
    REPOSITORYBROWSER INTEGER NOT NULL,
    CHANGESETLINK VARCHAR (255),
    ADDEDFILESLINK VARCHAR (255),
    MODIFIEDEDFILESLINK VARCHAR (255),
    REPLACEDFILESLINK VARCHAR (255),
    DELETEDFILESLINK VARCHAR (255),
    CONNECTIONTYPE INTEGER NOT NULL,
    SERVERNAME VARCHAR (255) NOT NULL,
    REPOSITORYPATH VARCHAR (255) NOT NULL,
    DEFAULTSEVERPORT VARCHAR (1) default 'Y',
    SEVERPORT INTEGER,
    AUTHENTICATIONMODE INTEGER NOT NULL,
    USERNAME VARCHAR (100),
    PASSWORD VARCHAR (255),
    PRIVATEKEY VARCHAR (10000),
    PASSPHRASE VARCHAR (255),
    PARENT INTEGER,
    TPUUID VARCHAR (36)
);

ALTER TABLE TVERSIONCONTROL
    ADD PRIMARY KEY (OBJECTID);


CREATE  INDEX TVERSIONCONTROLINDEX1 ON TVERSIONCONTROL (TPUUID);


COMMENT ON TABLE TVERSIONCONTROL IS 'configuration for version control server';



-----------------------------------------------------------------------------
-- TSHORTCUT
-----------------------------------------------------------------------------
-- drop table TSHORTCUT;

CREATE TABLE TSHORTCUT
(
    OBJECTID INTEGER NOT NULL,
    SHORTCUTKEY INTEGER,
    CTRLKEY VARCHAR (1) default 'N',
    SHIFTKEY VARCHAR (1) default 'N',
    ALTKEY VARCHAR (1) default 'N',
    MENUITEMKEY INTEGER,
    MENUCONTEXT INTEGER,
    TPUUID VARCHAR (36)
);

ALTER TABLE TSHORTCUT
    ADD PRIMARY KEY (OBJECTID);


CREATE  INDEX TSHORTCUTSINDEX1 ON TSHORTCUT (TPUUID);


COMMENT ON TABLE TSHORTCUT IS 'shortcut  definitions for menu items';

COMMENT ON COLUMN TSHORTCUT.MENUCONTEXT IS 'main menu, item navigator context menu etc.';


-----------------------------------------------------------------------------
-- TMAILTEXTBLOCK
-----------------------------------------------------------------------------
-- drop table TMAILTEXTBLOCK;

CREATE TABLE TMAILTEXTBLOCK
(
    OBJECTID INTEGER NOT NULL,
    PERSON INTEGER,
    BLOCKTITLE VARCHAR (255),
    BLOCKCONTENT VARCHAR (10000),
    TAGLABEL VARCHAR (100),
    REPOSITORYTYPE INTEGER,
    PROJECT INTEGER,
    TPUUID VARCHAR (36)
);

ALTER TABLE TMAILTEXTBLOCK
    ADD PRIMARY KEY (OBJECTID);


CREATE  INDEX TMAILTEXTBLOCKINDEX1 ON TMAILTEXTBLOCK (PERSON);
CREATE  INDEX TMAILTEXTBLOCKINDEX2 ON TMAILTEXTBLOCK (TPUUID);


COMMENT ON TABLE TMAILTEXTBLOCK IS 'predefined text blocks to edit an mail';

COMMENT ON COLUMN TMAILTEXTBLOCK.TAGLABEL IS 'user defined tag/category used for filtering/grouping the blocks';


-----------------------------------------------------------------------------
-- TPROLE
-----------------------------------------------------------------------------
-- drop table TPROLE;

CREATE TABLE TPROLE
(
    OBJECTID INTEGER NOT NULL,
    PROJECTTYPE INTEGER,
    ROLEKEY INTEGER,
    TPUUID VARCHAR (36)
);

ALTER TABLE TPROLE
    ADD PRIMARY KEY (OBJECTID);


CREATE  INDEX TPROLEINDEX1 ON TPROLE (TPUUID);





-----------------------------------------------------------------------------
-- TCHILDPROJECTTYPE
-----------------------------------------------------------------------------
-- drop table TCHILDPROJECTTYPE;

CREATE TABLE TCHILDPROJECTTYPE
(
    OBJECTID INTEGER NOT NULL,
    PROJECTTYPEPARENT INTEGER NOT NULL,
    PROJECTTYPECHILD INTEGER NOT NULL,
    TPUUID VARCHAR (36)
);

ALTER TABLE TCHILDPROJECTTYPE
    ADD PRIMARY KEY (OBJECTID);


CREATE  INDEX TCHILDPROJECTTYPEINDEX1 ON TCHILDPROJECTTYPE (TPUUID);


COMMENT ON TABLE TCHILDPROJECTTYPE IS 'Describes which project type can have a child project depending on the a project type of parent project';

-----------------------------------------------------------------------------
-- TPERSONINDOMAIN
-----------------------------------------------------------------------------
-- drop table TPERSONINDOMAIN;

CREATE TABLE TPERSONINDOMAIN
(
    OBJECTID INTEGER NOT NULL,
    PERSONKEY INTEGER NOT NULL,
    DOMAINKEY INTEGER NOT NULL,
    DESCRIPTION VARCHAR (10000),
    TPUUID VARCHAR (36)
);

ALTER TABLE TPERSONINDOMAIN
    ADD PRIMARY KEY (OBJECTID);


CREATE  INDEX TPERSONINDOMAININDEX1 ON TPERSONINDOMAIN (TPUUID);





-----------------------------------------------------------------------------
-- TATTACHMENTVERSION
-----------------------------------------------------------------------------
-- drop table TATTACHMENTVERSION;

CREATE TABLE TATTACHMENTVERSION
(
    OBJECTID INTEGER NOT NULL,
    WORKITEM INTEGER NOT NULL,
    CHANGEDBY INTEGER,
    DOCUMENTSTATE INTEGER,
    FILENAME VARCHAR (256) NOT NULL,
    ISURL VARCHAR (1) default 'N',
    FILESIZE VARCHAR (20),
    MIMETYPE VARCHAR (15),
    LASTEDIT TIMESTAMP,
    VERSION VARCHAR (20),
    DESCRIPTION VARCHAR (10000),
    CRYPTKEY VARCHAR (4096),
    ISENCRYPTED VARCHAR (1) default 'N',
    ISDELETED VARCHAR (1) default 'N',
    TPUUID VARCHAR (36)
);

ALTER TABLE TATTACHMENTVERSION
    ADD PRIMARY KEY (OBJECTID);


CREATE  INDEX TATTACHMENTVERSIONINDEX1 ON TATTACHMENTVERSION (TPUUID);





-----------------------------------------------------------------------------
-- TUSERLEVEL
-----------------------------------------------------------------------------
-- drop table TUSERLEVEL;

CREATE TABLE TUSERLEVEL
(
    OBJECTID INTEGER NOT NULL,
    LABEL VARCHAR (255),
    DESCRIPTION VARCHAR (10000),
    TPUUID VARCHAR (36)
);

ALTER TABLE TUSERLEVEL
    ADD PRIMARY KEY (OBJECTID);


CREATE  INDEX TUSERLEVELINDEX1 ON TUSERLEVEL (TPUUID);





-----------------------------------------------------------------------------
-- TUSERLEVELSETTING
-----------------------------------------------------------------------------
-- drop table TUSERLEVELSETTING;

CREATE TABLE TUSERLEVELSETTING
(
    OBJECTID INTEGER NOT NULL,
    USERLEVEL INTEGER NOT NULL,
    ACTIONKEY INTEGER NOT NULL,
    ISACTIVE VARCHAR (1) default 'N',
    TPUUID VARCHAR (36)
);

ALTER TABLE TUSERLEVELSETTING
    ADD PRIMARY KEY (OBJECTID);


CREATE  INDEX TUSERLEVELSETTINGINDEX1 ON TUSERLEVELSETTING (TPUUID);

-----------------------------------------------------------------------------
-- TUSERFEATURE
-----------------------------------------------------------------------------
-- drop table TUSERFEATURE;

CREATE TABLE TUSERFEATURE
(
    OBJECTID INTEGER NOT NULL,
    FEATURENAME VARCHAR (255) NOT NULL,
    PERSON INTEGER,
    ISACTIVE VARCHAR (1) default 'N',
    TPUUID VARCHAR (36)
);

ALTER TABLE TUSERFEATURE
    ADD PRIMARY KEY (OBJECTID);


CREATE  INDEX TUSERFEATUREINDEX1 ON TUSERFEATURE (TPUUID);

-----------------------------------------------------------------------------
-- TITEMTRANSITION
-----------------------------------------------------------------------------
-- drop table TITEMTRANSITION;

CREATE TABLE TITEMTRANSITION
(
    OBJECTID INTEGER NOT NULL,
    WORKITEM INTEGER NOT NULL,
    TRANSITION INTEGER NOT NULL,
    TRANSITIONTIME TIMESTAMP,
    TPUUID VARCHAR (36)
);

ALTER TABLE TITEMTRANSITION
    ADD PRIMARY KEY (OBJECTID);

CREATE  INDEX TITEMTRANSITIONINDEX1 ON TITEMTRANSITION (WORKITEM);
CREATE  INDEX TITEMTRANSITIONINDEX2 ON TITEMTRANSITION (TRANSITION);
CREATE  INDEX TITEMTRANSITIONINDEX3 ON TITEMTRANSITION (TPUUID);

ALTER TABLE TWFACTIVITYCONTEXTPARAMS
    ADD CONSTRAINT TWFACTIVITYCO_FK_1 FOREIGN KEY (WORKFLOWACTIVITY)
    REFERENCES TWORKFLOWACTIVITY (OBJECTID)
;
ALTER TABLE TWFACTIVITYCONTEXTPARAMS
    ADD CONSTRAINT TWFACTIVITYCO_FK_2 FOREIGN KEY (ISSUETYPE)
    REFERENCES TCATEGORY (PKEY)
;
ALTER TABLE TWFACTIVITYCONTEXTPARAMS
    ADD CONSTRAINT TWFACTIVITYCO_FK_3 FOREIGN KEY (PROJECTTYPE)
    REFERENCES TPROJECTTYPE (OBJECTID)
;
ALTER TABLE TWFACTIVITYCONTEXTPARAMS
    ADD CONSTRAINT TWFACTIVITYCO_FK_4 FOREIGN KEY (PROJECT)
    REFERENCES TPROJECT (PKEY)
;

ALTER TABLE TWORKFLOWCOMMENT
    ADD CONSTRAINT TWORKFLOWCOMM_FK_1 FOREIGN KEY (WORKFLOW)
    REFERENCES TWORKFLOWDEF (OBJECTID)
;

ALTER TABLE TREPORTSUBSCRIBE
    ADD CONSTRAINT TREPORTSUBSCRIBE_FK_1 FOREIGN KEY (PERSON)
    REFERENCES TPERSON (PKEY)
;

ALTER TABLE TREPORTSUBSCRIBE
    ADD CONSTRAINT TREPORTSUBSCRIBE_FK_2 FOREIGN KEY (RECURRENCEPATTERN)
    REFERENCES TRECURRENCEPATTERN (OBJECTID)
;

ALTER TABLE TREPORTSUBSCRIBE
    ADD CONSTRAINT TREPORTSUBSCRIBE_FK_3 FOREIGN KEY (REPORTTEMPLATE)
    REFERENCES TEXPORTTEMPLATE (OBJECTID)
;

ALTER TABLE TGRIDLAYOUT
    ADD CONSTRAINT TGRIDLAYOUT_FK_1 FOREIGN KEY (PERSON)
    REFERENCES TPERSON (PKEY)
;

ALTER TABLE TGRIDFIELD
    ADD CONSTRAINT TGRIDFIELD_FK_1 FOREIGN KEY (GRIDLAYOUT)
    REFERENCES TGRIDLAYOUT (OBJECTID)
;

ALTER TABLE TGRIDGROUPINGSORTING
    ADD CONSTRAINT TGRIDGROUPINGSORTING_FK_1 FOREIGN KEY (GRIDLAYOUT)
    REFERENCES TGRIDLAYOUT (OBJECTID)
;

ALTER TABLE TNAVIGATORLAYOUT
    ADD CONSTRAINT TNAVIGATORLAYOUT_FK_1 FOREIGN KEY (PERSON)
    REFERENCES TPERSON (PKEY)
;

ALTER TABLE TNAVIGATORCOLUMN
    ADD CONSTRAINT TNAVIGATORCOL_FK_1 FOREIGN KEY (NAVIGATORLAYOUT)
    REFERENCES TNAVIGATORLAYOUT (OBJECTID)
;

ALTER TABLE TNAVIGATORGROUPINGSORTING
    ADD CONSTRAINT TNAVIGATORGROUPINGSORTING_FK_1 FOREIGN KEY (NAVIGATORLAYOUT)
    REFERENCES TNAVIGATORLAYOUT (OBJECTID)
;

ALTER TABLE TCARDGROUPINGFIELD
    ADD CONSTRAINT TCARDGROUPINGFIELD_FK_1 FOREIGN KEY (NAVIGATORLAYOUT)
    REFERENCES TNAVIGATORLAYOUT (OBJECTID)
;

ALTER TABLE TCARDFIELDOPTION
    ADD CONSTRAINT TCARDFIELDOPT_FK_1 FOREIGN KEY (GROUPINGFIELD)
    REFERENCES TCARDGROUPINGFIELD (OBJECTID)
;

ALTER TABLE TCARDFIELD
    ADD CONSTRAINT TCARDFIELD_FK_1 FOREIGN KEY (CARDPANEL)
    REFERENCES TCARDPANEL (OBJECTID)
;

ALTER TABLE TVIEWPARAM
    ADD CONSTRAINT TVIEWPARAM_FK_1 FOREIGN KEY (NAVIGATORLAYOUT)
    REFERENCES TNAVIGATORLAYOUT (OBJECTID)
;

ALTER TABLE TVERSIONCONTROL
    ADD CONSTRAINT TVERSIONCONTROL_FK_1 FOREIGN KEY (PARENT)
    REFERENCES TVERSIONCONTROL (OBJECTID)
;

ALTER TABLE TMAILTEXTBLOCK
    ADD CONSTRAINT TMAILTEXTBLOCK_FK_1 FOREIGN KEY (PERSON)
    REFERENCES TPERSON (PKEY)
;

ALTER TABLE TMAILTEXTBLOCK
    ADD CONSTRAINT TMAILTEXTBLOCK_FK_2 FOREIGN KEY (PROJECT)
    REFERENCES TPROJECT (PKEY)
;

ALTER TABLE TPROLE
    ADD CONSTRAINT TPROLE_FK_1 FOREIGN KEY (PROJECTTYPE)
    REFERENCES TPROJECTTYPE (OBJECTID)
;

ALTER TABLE TPROLE
    ADD CONSTRAINT TPROLE_FK_2 FOREIGN KEY (ROLEKEY)
    REFERENCES TROLE (PKEY)
;

ALTER TABLE TCHILDPROJECTTYPE
    ADD CONSTRAINT TCHILDPROJECTTYPE_FK_1 FOREIGN KEY (PROJECTTYPEPARENT)
    REFERENCES TPROJECTTYPE (OBJECTID)
;

ALTER TABLE TCHILDPROJECTTYPE
    ADD CONSTRAINT TCHILDPROJECTTYPE_FK_2 FOREIGN KEY (PROJECTTYPECHILD)
    REFERENCES TPROJECTTYPE (OBJECTID)
;

ALTER TABLE TPERSONINDOMAIN
    ADD CONSTRAINT TPERSONINDOMAIN_FK_1 FOREIGN KEY (PERSONKEY)
    REFERENCES TPERSON (PKEY)
;

ALTER TABLE TPERSONINDOMAIN
    ADD CONSTRAINT TPERSONINDOMAIN_FK_2 FOREIGN KEY (DOMAINKEY)
    REFERENCES TDOMAIN (OBJECTID)
;

ALTER TABLE TATTACHMENTVERSION
    ADD CONSTRAINT TATTACHMENTVERSION_FK_1 FOREIGN KEY (WORKITEM)
    REFERENCES TWORKITEM (WORKITEMKEY)
;

ALTER TABLE TATTACHMENTVERSION
    ADD CONSTRAINT TATTACHMENTVERSION_FK_2 FOREIGN KEY (CHANGEDBY)
    REFERENCES TPERSON (PKEY)
;

ALTER TABLE TATTACHMENTVERSION
    ADD CONSTRAINT TATTACHMENTVERSION_FK_3 FOREIGN KEY (DOCUMENTSTATE)
    REFERENCES TDOCSTATE (OBJECTID)
;

ALTER TABLE TUSERLEVELSETTING
    ADD CONSTRAINT TUSERLEVELSETTING_FK_1 FOREIGN KEY (USERLEVEL)
    REFERENCES TUSERLEVEL (OBJECTID)
;

-----------------------------------------------------------------------------
-- TUSERFEATURE: FOREIGN KEYS
-----------------------------------------------------------------------------
ALTER TABLE TUSERFEATURE
    ADD CONSTRAINT TUSERFEATURE_FK_1 FOREIGN KEY (PERSON)
    REFERENCES TPERSON (PKEY)
;

-----------------------------------------------------------------------------
-- TITEMTRANSITION: FOREIGN KEYS
-----------------------------------------------------------------------------
ALTER TABLE TITEMTRANSITION
    ADD CONSTRAINT TITEMTRANSITI_FK_1 FOREIGN KEY (WORKITEM)
    REFERENCES TWORKITEM (WORKITEMKEY)
;
ALTER TABLE TITEMTRANSITION
    ADD CONSTRAINT TITEMTRANSITI_FK_2 FOREIGN KEY (TRANSITION)
    REFERENCES TWORKFLOWTRANSITION (OBJECTID)
;
COMMIT;