-- Not yet tested!

INSERT INTO ID_TABLE (ID_TABLE_ID, TABLE_NAME, NEXT_ID, QUANTITY)
VALUES (21, 'TPRIVATEREPORTREPOSITORY', 1, 1);


INSERT INTO ID_TABLE (ID_TABLE_ID, TABLE_NAME, NEXT_ID, QUANTITY)
VALUES (22, 'TPROJECTREPORTREPOSITORY', 1, 1);


INSERT INTO ID_TABLE (ID_TABLE_ID, TABLE_NAME, NEXT_ID, QUANTITY)
VALUES (23, 'TPUBLICREPORTREPOSITORY', 1, 1);


CREATE TABLE TPRIVATEREPORTREPOSITORY
(
	PKEY INTEGER NOT NULL,
	OWNER INTEGER NOT NULL,
	NAME CLOB NOT NULL,
	QUERY CLOB NOT NULL
);

ALTER TABLE TPRIVATEREPORTREPOSITORY
	ADD PRIMARY KEY (PKEY);


CREATE TABLE TPUBLICREPORTREPOSITORY
(
	PKEY INTEGER NOT NULL,
	OWNER INTEGER NOT NULL,
	NAME CLOB NOT NULL,
	QUERY CLOB NOT NULL
);

ALTER TABLE TPUBLICREPORTREPOSITORY
	ADD PRIMARY KEY (PKEY);


CREATE TABLE TPROJECTREPORTREPOSITORY
(
	PKEY INTEGER NOT NULL,
	PROJECT INTEGER NOT NULL,
	NAME CLOB NOT NULL,
	QUERY CLOB NOT NULL
);

ALTER TABLE TPROJECTREPORTREPOSITORY
	ADD PRIMARY KEY (PKEY);


ALTER TABLE TPRIVATEREPORTREPOSITORY
	ADD CONSTRAINT TPRIVATEREPOR_FK_1 FOREIGN KEY (OWNER)
	REFERENCES TPERSON (PKEY)
;


ALTER TABLE TPUBLICREPORTREPOSITORY
	ADD CONSTRAINT TPUBLICREPORT_FK_1 FOREIGN KEY (OWNER)
	REFERENCES TPERSON (PKEY)
;


ALTER TABLE TPROJECTREPORTREPOSITORY
	ADD CONSTRAINT TPROJECTREPOR_FK_1 FOREIGN KEY (PROJECT)
	REFERENCES TPROJECT (PKEY)
;


COMMIT;

