ALTER TABLE TMAILTEMPLATEDEF DROP COLUMN MAILBODY;
ALTER TABLE TMAILTEMPLATEDEF ADD MAILBODY LONGTEXT;
SET SQL_SAFE_UPDATES=0;
UPDATE TWORKITEM AS a
  LEFT JOIN TWORKITEM AS b ON a.SUPERIORWORKITEM=b.WORKITEMKEY 
  SET a.SUPERIORWORKITEM = null
WHERE a.SUPERIORWORKITEM IS NOT NULL and b.WORKITEMKEY IS NULL;
SET SQL_SAFE_UPDATES=1; 
ALTER TABLE TWORKITEM
    ADD CONSTRAINT TWORKITEM_FK_14
    FOREIGN KEY (SUPERIORWORKITEM)
    REFERENCES TWORKITEM (WORKITEMKEY);