-- ALTER TABLE `TCARDFIELD` ADD `HIDELABEL` char(1) DEFAULT 'Y';
ALTER TABLE `TCARDFIELD` ADD `ICONRENDERING` int(11) DEFAULT NULL;
  

ALTER TABLE `TITEMLINKHISTORY` ADD `SORTORDER` int(11) DEFAULT NULL;
ALTER TABLE `TPROJECT` ADD  `ISTEMPLATE` char(1) DEFAULT 'N';

ALTER TABLE `TSCREENFIELD` ADD `ICONRENDERING` int(11) DEFAULT NULL;

DROP TABLE IF EXISTS `TWFACTIVITYCONTEXTPARAMS`;
CREATE TABLE `TWFACTIVITYCONTEXTPARAMS` (
  `OBJECTID` int(11) NOT NULL,
  `WORKFLOWACTIVITY` int(11) NOT NULL,
  `ISSUETYPE` int(11) DEFAULT NULL,
  `PROJECTTYPE` int(11) DEFAULT NULL,
  `PROJECT` int(11) DEFAULT NULL,
  `SETTERORPARTID` int(11) DEFAULT NULL,
  `ACTIVITYPARAMS` mediumtext,
  `TPUUID` varchar(36) DEFAULT NULL,
  PRIMARY KEY (`OBJECTID`),
  KEY `TWFACTIVITYCONTEXTPARAMSINDEX1` (`WORKFLOWACTIVITY`),
  KEY `TWFACTIVITYCONTEXTPARAMSINDEX2` (`ISSUETYPE`),
  KEY `TWFACTIVITYCONTEXTPARAMSINDEX3` (`PROJECTTYPE`),
  KEY `TWFACTIVITYCONTEXTPARAMSINDEX4` (`PROJECT`),
  KEY `TWFACTIVITYCONTEXTPARAMSINDEX5` (`TPUUID`),
  CONSTRAINT `TWFACTIVITYCONTEXTPARAMS_FK_4` FOREIGN KEY (`PROJECT`) REFERENCES `TPROJECT` (`PKEY`),
  CONSTRAINT `TWFACTIVITYCONTEXTPARAMS_FK_1` FOREIGN KEY (`WORKFLOWACTIVITY`) REFERENCES `TWORKFLOWACTIVITY` (`OBJECTID`),
  CONSTRAINT `TWFACTIVITYCONTEXTPARAMS_FK_2` FOREIGN KEY (`ISSUETYPE`) REFERENCES `TCATEGORY` (`PKEY`),
  CONSTRAINT `TWFACTIVITYCONTEXTPARAMS_FK_3` FOREIGN KEY (`PROJECTTYPE`) REFERENCES `TPROJECTTYPE` (`OBJECTID`)

) ENGINE=InnoDB DEFAULT CHARSET=utf8;


DROP TABLE IF EXISTS `TWORKFLOWCOMMENT`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `TWORKFLOWCOMMENT` (
  `OBJECTID` int(11) NOT NULL,
  `DESCRIPTION` mediumtext,
  `WORKFLOW` int(11) DEFAULT NULL,
  `NODEX` int(11) DEFAULT NULL,
  `NODEY` int(11) DEFAULT NULL,
  `TPUUID` varchar(36) DEFAULT NULL,
  PRIMARY KEY (`OBJECTID`),
  KEY `TWORKFLOWCOMMENTINDEX1` (`WORKFLOW`),
  KEY `TWORKFLOWCOMMENTINDEX2` (`TPUUID`),
  CONSTRAINT `TWORKFLOWCOMMENT_FK_1` FOREIGN KEY (`WORKFLOW`) REFERENCES `TWORKFLOWDEF` (`OBJECTID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/* ALTER TABLE `TWORKITEM` MODIFY COLUMN `ACCESSLEVEL` int(11) DEFAULT '0';
ALTER TABLE `TWORKITEM` MODIFY COLUMN `ARCHIVELEVEL` int(11) DEFAULT '0';
*/
ALTER TABLE `TWORKITEM` ADD `OVERBUDGET` char(1) DEFAULT 'N';
  
  
ALTER TABLE `TWORKITEMLINK` ADD `SORTORDER` int(11) DEFAULT NULL;






