-- MySQL update script from 300 to 310

# Turn it off in case of InnoDB
SET FOREIGN_KEY_CHECKS = 0; 

update TWORKITEM set ENDDATE=NULL where ENDDATE = '0000-00-00 00:00:00';  
update TWORKITEM set STARTDATE=NULL where STARTDATE = '0000-00-00 00:00:00';  
update TWORKITEM set ACTUALSTARTDATE=null where ACTUALSTARTDATE='0000-00-00 00:00:00';  
update TWORKITEM set ACTUALENDDATE=null where ACTUALENDDATE='0000-00-00 00:00:00';  
update TBASELINE set STARTDATE=null where STARTDATE='0000-00-00 00:00:00';  
update TBASELINE set ENDDATE=null where ENDDATE='0000-00-00 00:00:00';  

-- TBASELINE
ALTER TABLE TBASELINE CHANGE STARTDATE  STARTDATE  DATETIME ;
ALTER TABLE TBASELINE CHANGE ENDDATE    ENDDATE    DATETIME ;

-- TPERSON
ALTER TABLE TPERSON   CHANGE VALIDUNTIL VALIDUNTIL DATETIME;
ALTER TABLE TPERSON ADD REMINDMEASORIGINATOR CHAR (1) default 'N';
ALTER TABLE TPERSON ADD REMINDMEASMANAGER CHAR (1) default 'Y';
ALTER TABLE TPERSON ADD REMINDMEASRESPONSIBLE CHAR (1) default 'Y';
ALTER TABLE TPERSON ADD EMAILREMINDPLEVEL INTEGER;
ALTER TABLE TPERSON ADD EMAILREMINDSLEVEL INTEGER;
UPDATE TPERSON SET NOEMAILSPLEASE = 0, TOKENEXPDATE='2005-04-04', EMAILLASTREMINDED='2005-04-04'; 

-- TPRIORITY
ALTER TABLE TPRIORITY ADD WLEVEL INTEGER;


# -----------------------------------------------------------------------
# TPPRIORITY
# -----------------------------------------------------------------------
drop table if exists TPPRIORITY;

CREATE TABLE TPPRIORITY
(
		            OBJECTID INTEGER NOT NULL,
		            PRIORITY INTEGER,
		            PROJECTTYPE INTEGER,
		            LISTTYPE INTEGER,
    PRIMARY KEY(OBJECTID),
    FOREIGN KEY (PRIORITY) REFERENCES TPRIORITY (PKEY)
    ,
    FOREIGN KEY (PROJECTTYPE) REFERENCES TPROJECTTYPE (OBJECTID)
    ,
    FOREIGN KEY (LISTTYPE) REFERENCES TCATEGORY (PKEY)
    
);

-- TPROJECT
ALTER TABLE TPROJECT ADD VERSIONSYSTEMFIELD0 VARCHAR (255);
ALTER TABLE TPROJECT ADD VERSIONSYSTEMFIELD1 VARCHAR (255);
ALTER TABLE TPROJECT ADD VERSIONSYSTEMFIELD2 VARCHAR (255);
ALTER TABLE TPROJECT ADD VERSIONSYSTEMFIELD3 VARCHAR (255);
ALTER TABLE TPROJECT ADD DELETED VARCHAR (1) default 'N' NOT NULL;


-- TSEVERITY
ALTER TABLE TSEVERITY ADD WLEVEL INTEGER;

# -----------------------------------------------------------------------
# TPSEVERITY
# -----------------------------------------------------------------------
drop table if exists TPSEVERITY;

CREATE TABLE TPSEVERITY
(
		            OBJECTID INTEGER NOT NULL,
		            SEVERITY INTEGER,
		            PROJECTTYPE INTEGER,
		            LISTTYPE INTEGER,
    PRIMARY KEY(OBJECTID),
    FOREIGN KEY (SEVERITY) REFERENCES TSEVERITY (PKEY)
    ,
    FOREIGN KEY (PROJECTTYPE) REFERENCES TPROJECTTYPE (OBJECTID)
    ,
    FOREIGN KEY (LISTTYPE) REFERENCES TCATEGORY (PKEY)
    
);



-- TWORKITEM
ALTER TABLE TWORKITEM CHANGE STARTDATE  STARTDATE  DATETIME;
ALTER TABLE TWORKITEM CHANGE ENDDATE    ENDDATE    DATETIME;
ALTER TABLE TWORKITEM CHANGE ACTUALSTARTDATE ACTUALSTARTDATE DATETIME ;  
ALTER TABLE TWORKITEM CHANGE ACTUALENDDATE ACTUALENDDATE DATETIME ;  
ALTER TABLE TWORKITEM ADD WLEVEL VARCHAR(14);
ALTER TABLE TWORKITEM ADD INDEX TWIINDEX17 (WLEVEL);


-- TSITE
ALTER TABLE TSITE ADD LICENSEEXT VARCHAR (255);
ALTER TABLE TSITE ADD EXECUTABLE1 VARCHAR (255);
ALTER TABLE TSITE ADD EXECUTABLE2 VARCHAR (255);
ALTER TABLE TSITE ADD LDAPBINDDN VARCHAR (255);
ALTER TABLE TSITE ADD LDAPBINDPASSW VARCHAR (20);



# -----------------------------------------------------------------------
# TWORKFLOW
# -----------------------------------------------------------------------
drop table if exists TWORKFLOW;

CREATE TABLE TWORKFLOW
(
		            OBJECTID INTEGER NOT NULL,
		            STATEFROM INTEGER,
		            STATETO INTEGER,
		            PROJECTTYPE INTEGER,
    PRIMARY KEY(OBJECTID),
    FOREIGN KEY (STATEFROM) REFERENCES TSTATE (PKEY)
    ,
    FOREIGN KEY (STATETO) REFERENCES TSTATE (PKEY)
    ,
    FOREIGN KEY (PROJECTTYPE) REFERENCES TPROJECTTYPE (OBJECTID)
    
);


# -----------------------------------------------------------------------
# TWORKFLOWROLE
# -----------------------------------------------------------------------
drop table if exists TWORKFLOWROLE;

CREATE TABLE TWORKFLOWROLE
(
		            OBJECTID INTEGER NOT NULL,
		            WORKFLOW INTEGER,
		            MAYCHANGEROLE INTEGER,
    PRIMARY KEY(OBJECTID),
    FOREIGN KEY (WORKFLOW) REFERENCES TWORKFLOW (OBJECTID)
    ,
    FOREIGN KEY (MAYCHANGEROLE) REFERENCES TROLE (PKEY)
    
);

# -----------------------------------------------------------------------
# TWORKFLOWCATEGORY
# -----------------------------------------------------------------------
drop table if exists TWORKFLOWCATEGORY;

CREATE TABLE TWORKFLOWCATEGORY
(
		            OBJECTID INTEGER NOT NULL,
		            WORKFLOW INTEGER,
		            CATEGORY INTEGER,
    PRIMARY KEY(OBJECTID),
    FOREIGN KEY (WORKFLOW) REFERENCES TWORKFLOW (OBJECTID)
    ,
    FOREIGN KEY (CATEGORY) REFERENCES TCATEGORY (PKEY)
    
);


# -----------------------------------------------------------------------
# TISSUEATTRIBUTEVALUE
# -----------------------------------------------------------------------
drop table if exists TISSUEATTRIBUTEVALUE;

CREATE TABLE TISSUEATTRIBUTEVALUE
(
		            OBJECTID INTEGER NOT NULL,
		            ATTRIBUTEID INTEGER NOT NULL,
		            DELETED INTEGER,
		            ISSUE INTEGER NOT NULL,
		            NUMERICVALUE INTEGER,
		            TIMESTAMPVALUE TIMESTAMP,
		            LONGTEXTVALUE LONGTEXT,
		            OPTIONID INTEGER,
		            PERSON INTEGER,
		            CHARVALUE VARCHAR (255),
		            DISPLAYVALUE VARCHAR (255),
    PRIMARY KEY(OBJECTID),
    FOREIGN KEY (PERSON) REFERENCES TPERSON (PKEY)
    ,
    FOREIGN KEY (ISSUE) REFERENCES TWORKITEM (WORKITEMKEY)
    ,
    FOREIGN KEY (ATTRIBUTEID) REFERENCES TATTRIBUTE (OBJECTID)
    ,
    FOREIGN KEY (OPTIONID) REFERENCES TATTRIBUTEOPTION (OBJECTID)
    
);

# -----------------------------------------------------------------------
# TATTRIBUTEOPTION
# -----------------------------------------------------------------------
drop table if exists TATTRIBUTEOPTION;

CREATE TABLE TATTRIBUTEOPTION
(
		            OBJECTID INTEGER NOT NULL,
		            ATTRIBUTEID INTEGER NOT NULL,
		            PARENTOPTION INTEGER,
		            OPTIONNAME VARCHAR (255) NOT NULL,
		            DELETED INTEGER,
    PRIMARY KEY(OBJECTID),
    FOREIGN KEY (ATTRIBUTEID) REFERENCES TATTRIBUTE (OBJECTID)
    
);

# -----------------------------------------------------------------------
# TATTRIBUTECLASS
# -----------------------------------------------------------------------
drop table if exists TATTRIBUTECLASS;

CREATE TABLE TATTRIBUTECLASS
(
		            OBJECTID INTEGER NOT NULL,
		            ATTRIBUTECLASSNAME VARCHAR (255) NOT NULL,
		            ATTRIBUTECLASSDESC VARCHAR (64),
		            JAVACLASSNAME VARCHAR (255),
    PRIMARY KEY(OBJECTID)
);

# -----------------------------------------------------------------------
# TATTRIBUTETYPE
# -----------------------------------------------------------------------
drop table if exists TATTRIBUTETYPE;

CREATE TABLE TATTRIBUTETYPE
(
		            OBJECTID INTEGER NOT NULL,
		            ATTRIBUTETYPENAME VARCHAR (255) NOT NULL,
		            ATTRIBUTECLASS INTEGER NOT NULL,
		            JAVACLASSNAME VARCHAR (255),
		            VALIDATIONKEY VARCHAR (25),
    PRIMARY KEY(OBJECTID),
    FOREIGN KEY (ATTRIBUTECLASS) REFERENCES TATTRIBUTECLASS (OBJECTID)
    
);

# -----------------------------------------------------------------------
# TATTRIBUTE
# -----------------------------------------------------------------------
drop table if exists TATTRIBUTE;

CREATE TABLE TATTRIBUTE
(
		            OBJECTID INTEGER NOT NULL,
		            ATTRIBUTENAME VARCHAR (255) NOT NULL,
		            ATTRIBUTETYPE INTEGER NOT NULL,
		            DELETED INTEGER,
		            DESCRIPTION VARCHAR (64),
		            PERMISSION VARCHAR (255),
		            REQUIREDOPTION INTEGER,
    PRIMARY KEY(OBJECTID),
    FOREIGN KEY (REQUIREDOPTION) REFERENCES TATTRIBUTEOPTION (OBJECTID)
    
);

# -----------------------------------------------------------------------
# TREPORTLAYOUT
# -----------------------------------------------------------------------
drop table if exists TREPORTLAYOUT;

CREATE TABLE TREPORTLAYOUT
(
		            OBJECTID INTEGER NOT NULL,
		            PROJECTTYPE INTEGER,
		            PROJECT INTEGER,
		            PERSON INTEGER,
		            REPORTFIELD INTEGER NOT NULL,
		            FPOSITION INTEGER NOT NULL,
		            FWIDTH INTEGER NOT NULL,
		            FSORTORDER INTEGER,
		            FSORTDIR VARCHAR (1),
    PRIMARY KEY(OBJECTID),
    FOREIGN KEY (PROJECTTYPE) REFERENCES TPROJECTTYPE (OBJECTID)
    ,
    FOREIGN KEY (PROJECT) REFERENCES TPROJECT (PKEY)
    ,
    FOREIGN KEY (PERSON) REFERENCES TPERSON (PKEY)
    ,
    FOREIGN KEY (REPORTFIELD) REFERENCES TISSUEATTRIBUTEVALUE (OBJECTID)
    
);

# -----------------------------------------------------------------------
# TSCHEDULER
# -----------------------------------------------------------------------
drop table if exists TSCHEDULER;

CREATE TABLE TSCHEDULER
(
		            OBJECTID INTEGER NOT NULL,
		            CRONWHEN VARCHAR (64) NOT NULL,
		            JAVACLASSNAME VARCHAR (255),
		            EXTERNALEXE VARCHAR (255),
		            PERSON INTEGER NOT NULL,
    PRIMARY KEY(OBJECTID),
    FOREIGN KEY (PERSON) REFERENCES TPERSON (PKEY)
    
);


INSERT INTO ID_TABLE (ID_TABLE_ID, TABLE_NAME, NEXT_ID, QUANTITY) VALUES
			(36, 'TWORKFLOWCATEGORY', 1, 1);

INSERT INTO ID_TABLE (ID_TABLE_ID, TABLE_NAME, NEXT_ID, QUANTITY) VALUES
			(37, 'TWORKFLOWROLE', 1, 1);

INSERT INTO ID_TABLE (ID_TABLE_ID, TABLE_NAME, NEXT_ID, QUANTITY) VALUES
			(38, 'TPPRIORITY', 1, 1);

INSERT INTO ID_TABLE (ID_TABLE_ID, TABLE_NAME, NEXT_ID, QUANTITY) VALUES
			(39, 'TPSEVERITY', 1, 1);

INSERT INTO ID_TABLE (ID_TABLE_ID, TABLE_NAME, NEXT_ID, QUANTITY) VALUES
			(40, 'TISSUEATTRIBUTEVALUE', 1, 1); 

INSERT INTO ID_TABLE (ID_TABLE_ID, TABLE_NAME, NEXT_ID, QUANTITY) VALUES
			(41, 'TATTRIBUTEOPTION', 1, 1);

INSERT INTO ID_TABLE (ID_TABLE_ID, TABLE_NAME, NEXT_ID, QUANTITY) VALUES
			(42, 'TATTRIBUTECLASS', 1, 1);

INSERT INTO ID_TABLE (ID_TABLE_ID, TABLE_NAME, NEXT_ID, QUANTITY) VALUES
			(43, 'TATTRIBUTETYPE', 1, 1);

INSERT INTO ID_TABLE (ID_TABLE_ID, TABLE_NAME, NEXT_ID, QUANTITY) VALUES
			(44, 'TATTRIBUTE', 1, 1);

INSERT INTO ID_TABLE (ID_TABLE_ID, TABLE_NAME, NEXT_ID, QUANTITY) VALUES
			(45, 'TREPORTLAYOUT', 1, 1);

INSERT INTO ID_TABLE (ID_TABLE_ID, TABLE_NAME, NEXT_ID, QUANTITY) VALUES
			(46, 'TSCHEDULER', 1, 1);

-- some changes we missed in the old upgrade scripts

ALTER TABLE TWORKITEM CHANGE PACKAGESYNOPSYS PACKAGESYNOPSYS VARCHAR(80);

# Turn it on in case of InnoDB
SET FOREIGN_KEY_CHECKS = 1; 
COMMIT;










