-- Migration script from 3.8.x to 4.0.x MySQL 5.x
-- $Id$
ALTER TABLE TCATEGORY ADD ICONCHANGED CHAR(1) default 'N';
ALTER TABLE TCATEGORY ADD CSSSTYLE VARCHAR (255);

--
ALTER TABLE TDEPARTMENT ADD PARENT INTEGER;

--
ALTER TABLE TNOTIFY ADD PROJCATKEY2 INTEGER;
-- ALTER TABLE TNOTIFY DROP FOREIGN KEY TNOTIFY_FK_1;
COMMIT;
UPDATE TNOTIFY SET PROJCATKEY2 = PROJCATKEY;
ALTER TABLE TNOTIFY DROP COLUMN PROJCATKEY;
COMMIT;
ALTER TABLE TNOTIFY ADD PROJCATKEY INTEGER;
COMMIT;
UPDATE TNOTIFY SET PROJCATKEY=PROJCATKEY2;
ALTER TABLE TNOTIFY DROP COLUMN PROJCATKEY2;
COMMIT;
-- ALTER TABLE TNOTIFY
--    ADD CONSTRAINT TNOTIFY_FK_1
--    FOREIGN KEY (PROJCATKEY)
--    REFERENCES TPROJCAT (PKEY);
-- COMMIT;

--
ALTER TABLE TPERSON ADD PASSWDTMP VARCHAR(160);
COMMIT;
UPDATE TPERSON SET PASSWDTMP = PASSWD;
ALTER TABLE TPERSON DROP COLUMN PASSWD;
COMMIT;
ALTER TABLE TPERSON ADD PASSWD VARCHAR(160);
UPDATE TPERSON SET PASSWD=PASSWDTMP;
ALTER TABLE TPERSON DROP COLUMN PASSWDTMP;
COMMIT;
ALTER TABLE TPERSON ADD SALT VARCHAR(80);
ALTER TABLE TPERSON ADD FORGOTPASSWORDKEY VARCHAR(100);
ALTER TABLE TPERSON ADD CREATED DATETIME;
ALTER TABLE TPERSON ADD MAXASSIGNEDITEMS INTEGER;
ALTER TABLE TPERSON ADD MESSENGERURL VARCHAR(255);
ALTER TABLE TPERSON ADD CALLURL VARCHAR(255);
ALTER TABLE TPERSON ADD SYMBOL VARCHAR(255);
ALTER TABLE TPERSON ADD ICONKEY INTEGER;

--
ALTER TABLE TPRIORITY ADD ICONCHANGED CHAR(1) default 'N';
ALTER TABLE TPRIORITY ADD CSSSTYLE VARCHAR (255);

--
ALTER TABLE TPROJECT ADD TAGLABEL VARCHAR(50);
ALTER TABLE TPROJECT MODIFY PREFIX VARCHAR(50);
ALTER TABLE TPROJECT ADD NEXTITEMID INTEGER;
ALTER TABLE TPROJECT ADD PARENT INTEGER;
ALTER TABLE TPROJECT ADD ISPRIVATE VARCHAR(1) default 'N';

--
ALTER TABLE TRELEASE ADD PARENT INTEGER;

--
ALTER TABLE TSEVERITY ADD ICONCHANGED CHAR(1) default 'N';
ALTER TABLE TSEVERITY ADD CSSSTYLE VARCHAR (255);

--
ALTER TABLE TSTATE ADD ICONCHANGED CHAR(1) default 'N';
ALTER TABLE TSTATE ADD CSSSTYLE VARCHAR (255);

--
ALTER TABLE TWORKITEM ADD PROJECTKEY INTEGER;
ALTER TABLE TWORKITEM ADD TMPVAL INTEGER;
-- ALTER TABLE TWORKITEM DROP FOREIGN KEY TWORKITEM_FK_5;
COMMIT;

-- set the projects directly in TWORKITEM
UPDATE TWORKITEM SET TWORKITEM.PROJECTKEY=(SELECT max(PROJKEY)
        FROM TPROJCAT WHERE TWORKITEM.PROJCATKEY=TPROJCAT.PKEY);
        
UPDATE TWORKITEM SET TMPVAL = PROJCATKEY;
ALTER TABLE TWORKITEM DROP COLUMN PROJCATKEY;
COMMIT;
ALTER TABLE TWORKITEM ADD PROJCATKEY INTEGER;
UPDATE TWORKITEM SET PROJCATKEY=TMPVAL;
ALTER TABLE TWORKITEM DROP COLUMN TMPVAL;
COMMIT;
-- ALTER TABLE TWORKITEM
--    ADD CONSTRAINT TWORKITEM_FK_5
--    FOREIGN KEY (PROJCATKEY)
--    REFERENCES TPROJCAT (PKEY)
--;
COMMIT;
ALTER TABLE TWORKITEM ADD ESCALATIONLEVEL INTEGER;
ALTER TABLE TWORKITEM ADD WBSONLEVEL INTEGER;
ALTER TABLE TWORKITEM ADD REMINDERDATE DATETIME;
ALTER TABLE TWORKITEM ADD TOPDOWNSTARTDATE DATETIME;
ALTER TABLE TWORKITEM ADD TOPDOWNENDDATE DATETIME;

--
ALTER TABLE TPROJECTTYPE ADD DEFAULTFORPRIVATE VARCHAR(1) default 'N';

--
ALTER TABLE TBUDGET ADD BUDGETTYPE INTEGER;

--
ALTER TABLE TSYSTEMSTATE ADD ICONKEY INTEGER;
ALTER TABLE TSYSTEMSTATE ADD CSSSTYLE VARCHAR (255);

--
ALTER TABLE TMOTD ADD TEASERTEXT VARCHAR(255);

--
ALTER TABLE TDASHBOARDSCREEN ADD TMPVAL INTEGER;
-- ALTER TABLE TDASHBOARDSCREEN DROP FOREIGN KEY TDASHBOARDSCREEN_FK_1;
COMMIT;
UPDATE TDASHBOARDSCREEN SET TMPVAL = PERSONPKEY;
ALTER TABLE TDASHBOARDSCREEN DROP COLUMN PERSONPKEY;
COMMIT;
ALTER TABLE TDASHBOARDSCREEN ADD PERSONPKEY INTEGER;
UPDATE TDASHBOARDSCREEN SET PERSONPKEY=TMPVAL;
ALTER TABLE TDASHBOARDSCREEN DROP COLUMN TMPVAL;
COMMIT;
-- ALTER TABLE TDASHBOARDSCREEN
--    ADD CONSTRAINT TDASHBOARDSCREEN_FK_1
--    FOREIGN KEY (PERSONPKEY)
--    REFERENCES TPERSON (PKEY)
--;
COMMIT;

--
ALTER TABLE TFIELD ADD FILTERFIELD CHAR(1) default 'N';

--
ALTER TABLE TFIELDCONFIG ADD GROOVYSCRIPT INTEGER;

--
ALTER TABLE TTEXTBOXSETTINGS ADD DATEISWITHTIME CHAR(1) default 'N';

--
ALTER TABLE TLIST ADD TAGLABEL VARCHAR(50);
ALTER TABLE TLIST ADD DESCR_temp VARCHAR(255);
COMMIT;
UPDATE TLIST SET DESCR_temp = DESCRIPTION;
ALTER TABLE TLIST DROP DESCRIPTION;
COMMIT;
ALTER TABLE TLIST CHANGE DESCR_temp DESCRIPTION VARCHAR(255);
ALTER TABLE TLIST ADD MOREPROPS MEDIUMTEXT;

--
ALTER TABLE TOPTION ADD SYMBOL VARCHAR(255);
ALTER TABLE TOPTION ADD ICONCHANGED CHAR(1) default 'N';
ALTER TABLE TOPTION ADD CSSSTYLE VARCHAR (255);

--
ALTER TABLE TSCREEN ADD TAGLABEL VARCHAR(50);

--
ALTER TABLE TACTION ADD ACTIONTYPE INTEGER;
ALTER TABLE TACTION ADD ICONKEY INTEGER;

--
ALTER TABLE TQUERYREPOSITORY ADD CATEGORYKEY INTEGER;

--
ALTER TABLE TLOCALIZEDRESOURCES ADD TMPVAL MEDIUMTEXT;
COMMIT;
UPDATE TLOCALIZEDRESOURCES SET TMPVAL = LOCALIZEDTEXT;
ALTER TABLE TLOCALIZEDRESOURCES DROP COLUMN LOCALIZEDTEXT;
COMMIT;
ALTER TABLE TLOCALIZEDRESOURCES ADD LOCALIZEDTEXT MEDIUMTEXT;
UPDATE TLOCALIZEDRESOURCES SET LOCALIZEDTEXT=TMPVAL;
ALTER TABLE TLOCALIZEDRESOURCES DROP COLUMN TMPVAL;
COMMIT;
ALTER TABLE TLOCALIZEDRESOURCES ADD TEXTCHANGED CHAR(1) default 'N';

--
ALTER TABLE TEXPORTTEMPLATE ADD CATEGORYKEY INTEGER;
ALTER TABLE TEXPORTTEMPLATE ADD DELETED CHAR(1) default 'N';

--
ALTER TABLE CLUSTERNODE ADD  RELOADCHANGES VARCHAR(255);

--
ALTER TABLE TSCRIPTS ADD SCRIPTROLE INTEGER;

--
ALTER TABLE TREPORTPERSONSETTINGS ADD PARAMSETTINGS MEDIUMTEXT;

--
# -----------------------------------------------------------------------
# TFILTERCATEGORY
# -----------------------------------------------------------------------
drop table if exists TFILTERCATEGORY;

CREATE TABLE TFILTERCATEGORY
(
    OBJECTID INTEGER NOT NULL,
    LABEL VARCHAR(255) NOT NULL,
    REPOSITORY INTEGER NOT NULL,
    FILTERTYPE INTEGER NOT NULL,
    CREATEDBY INTEGER NOT NULL,
    PROJECT INTEGER,
    PARENTID INTEGER,
    TPUUID VARCHAR(36),
    PRIMARY KEY(OBJECTID),
    INDEX TFILTERCATEGORYINDEX1 (TPUUID));


# -----------------------------------------------------------------------
# TREPORTCATEGORY
# -----------------------------------------------------------------------
drop table if exists TREPORTCATEGORY;

CREATE TABLE TREPORTCATEGORY
(
    OBJECTID INTEGER NOT NULL,
    LABEL VARCHAR(255) NOT NULL,
    REPOSITORY INTEGER NOT NULL,
    CREATEDBY INTEGER NOT NULL,
    PROJECT INTEGER,
    PARENTID INTEGER,
    TPUUID VARCHAR(36),
    PRIMARY KEY(OBJECTID),
    INDEX TREPORTCATEGORYINDEX1 (TPUUID));


# -----------------------------------------------------------------------
# TMENUITEMQUERY
# -----------------------------------------------------------------------
drop table if exists TMENUITEMQUERY;

CREATE TABLE TMENUITEMQUERY
(
    OBJECTID INTEGER NOT NULL,
    PERSON INTEGER NOT NULL,
    QUERYKEY INTEGER NOT NULL,
    INCLUDEINMENU CHAR(1) default 'N',
    CSSSTYLEFIELD INTEGER,
    TPUUID VARCHAR(36),
    PRIMARY KEY(OBJECTID),
    INDEX TMENUITEMQUERYINDEX1 (TPUUID));


# -----------------------------------------------------------------------
# TCHILDISSUETYPE
# -----------------------------------------------------------------------
drop table if exists TCHILDISSUETYPE;

CREATE TABLE TCHILDISSUETYPE
(
    OBJECTID INTEGER NOT NULL,
    ISSUETYPEPARENT INTEGER NOT NULL,
    ISSUETYPECHILD INTEGER NOT NULL,
    TPUUID VARCHAR(36),
    PRIMARY KEY(OBJECTID),
    INDEX TCHILDISSUETYPEINDEX1 (TPUUID));


# -----------------------------------------------------------------------
# TPERSONBASKET
# -----------------------------------------------------------------------
drop table if exists TPERSONBASKET;

CREATE TABLE TPERSONBASKET
(
    OBJECTID INTEGER NOT NULL,
    BASKET INTEGER NOT NULL,
    WORKITEM INTEGER NOT NULL,
    PERSON INTEGER,
    REMINDERDATE TIMESTAMP,
    DELEGATETEXT MEDIUMTEXT,
    MOREPROPS MEDIUMTEXT,
    TPUUID VARCHAR(36),
    PRIMARY KEY(OBJECTID),
    INDEX TPERSONBASKETINDEX1 (PERSON),
    INDEX TPERSONBASKETINDEX2 (TPUUID));


# -----------------------------------------------------------------------
# TBASKET
# -----------------------------------------------------------------------
drop table if exists TBASKET;

CREATE TABLE TBASKET
(
    OBJECTID INTEGER NOT NULL,
    LABEL VARCHAR(255) NOT NULL,
    DIVISIBLE CHAR(1) default 'N',
    PARENTBASKET INTEGER,
    PERSON INTEGER,
    TPUUID VARCHAR(36),
    PRIMARY KEY(OBJECTID),
    INDEX TBASKETINDEX1 (TPUUID));

# -----------------------------------------------------------------------
# TMAILTEMPLATECONFIG
# -----------------------------------------------------------------------
drop table if exists TMAILTEMPLATECONFIG;

CREATE TABLE TMAILTEMPLATECONFIG
(
    OBJECTID INTEGER NOT NULL,
    MAILTEMPLATE INTEGER NOT NULL,
    ISSUETYPE INTEGER,
    PROJECTTYPE INTEGER,
    PROJECT INTEGER,
    EVENTKEY INTEGER NOT NULL,
    TPUUID VARCHAR(36),
    PRIMARY KEY(OBJECTID),
    INDEX TMAILTEMPLATECONFIGINDEX1 (TPUUID));


# -----------------------------------------------------------------------
# TMAILTEMPLATE
# -----------------------------------------------------------------------
drop table if exists TMAILTEMPLATE;

CREATE TABLE TMAILTEMPLATE
(
    OBJECTID INTEGER NOT NULL,
    TEMPLATETYPE INTEGER,
    NAME VARCHAR(255),
    DESCRIPTION VARCHAR(255),
    TAGLABEL VARCHAR(255),
    TPUUID VARCHAR(36),
    PRIMARY KEY(OBJECTID),
    INDEX TMAILTEMPLATEINDEX1 (TPUUID));


# -----------------------------------------------------------------------
# TMAILTEMPLATEDEF
# -----------------------------------------------------------------------
drop table if exists TMAILTEMPLATEDEF;

CREATE TABLE TMAILTEMPLATEDEF
(
    OBJECTID INTEGER NOT NULL,
    MAILTEMPLATE INTEGER NOT NULL,
    MAILSUBJECT VARCHAR(255),
    MAILBODY MEDIUMTEXT,
    THELOCALE VARCHAR(20),
    PLAINEMAIL CHAR(1) default 'N',
    TEMPLATECHANGED CHAR(1) default 'N',
    TPUUID VARCHAR(36),
    PRIMARY KEY(OBJECTID),
    INDEX TMAILTEMPLATEDEFINDEX1 (TPUUID));

# -----------------------------------------------------------------------
# TLASTVISITEDITEM
# -----------------------------------------------------------------------
drop table if exists TLASTVISITEDITEM;

CREATE TABLE TLASTVISITEDITEM
(
    OBJECTID INTEGER NOT NULL,
    WORKITEM INTEGER NOT NULL,
    PERSON INTEGER NOT NULL,
    LASTVISITEDDATE TIMESTAMP,
    TPUUID VARCHAR(36),
    PRIMARY KEY(OBJECTID),
    INDEX TLASTVISITEDITEMINDEX1 (PERSON),
    INDEX TLASTVISITEDITEMINDEX2 (TPUUID));


# -----------------------------------------------------------------------
# TWORKFLOWDEF
# -----------------------------------------------------------------------
drop table if exists TWORKFLOWDEF;

CREATE TABLE TWORKFLOWDEF
(
    OBJECTID INTEGER NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR(255),
    TAGLABEL VARCHAR(255),
    OWNER INTEGER,
    TPUUID VARCHAR(36),
    PRIMARY KEY(OBJECTID),
    INDEX TWORKFLOWDEFINDEX1 (TPUUID));


# -----------------------------------------------------------------------
# TWORKFLOWTRANSITION
# -----------------------------------------------------------------------
drop table if exists TWORKFLOWTRANSITION;

CREATE TABLE TWORKFLOWTRANSITION
(
    OBJECTID INTEGER NOT NULL,
    STATIONFROM INTEGER,
    STATIONTO INTEGER,
    ACTIONKEY INTEGER,
    WORKFLOW INTEGER NOT NULL,
    TEXTPOSITIONX INTEGER,
    TEXTPOSITIONY INTEGER,
    TRANSITIONTYPE INTEGER,
    CONTROLPOINTS VARCHAR(255),
    TPUUID VARCHAR(36),
    PRIMARY KEY(OBJECTID),
    INDEX TWORKFLOWTRANSITIONINDEX1 (WORKFLOW),
    INDEX TWORKFLOWTRANSITIONINDEX2 (TPUUID));


# -----------------------------------------------------------------------
# TWORKFLOWSTATION
# -----------------------------------------------------------------------
drop table if exists TWORKFLOWSTATION;

CREATE TABLE TWORKFLOWSTATION
(
    OBJECTID INTEGER NOT NULL,
    NAME VARCHAR(255),
    STATUS INTEGER,
    WORKFLOW INTEGER,
    NODEX INTEGER,
    NODEY INTEGER,
    STATIONTYPE INTEGER,
    TPUUID VARCHAR(36),
    PRIMARY KEY(OBJECTID),
    INDEX TWORKFLOWSTATIONINDEX1 (STATUS),
    INDEX TWORKFLOWSTATIONINDEX2 (WORKFLOW),
    INDEX TWORKFLOWSTATIONINDEX3 (TPUUID));


# -----------------------------------------------------------------------
# TWORKFLOWACTIVITY
# -----------------------------------------------------------------------
drop table if exists TWORKFLOWACTIVITY;

CREATE TABLE TWORKFLOWACTIVITY
(
    OBJECTID INTEGER NOT NULL,
    TRANSITIONACTIVITY INTEGER,
    STATIONENTRYACTIVITY INTEGER,
    STATIONEXITACTIVITY INTEGER,
    STATIONDOACTIVITY INTEGER,
    ACTIVITYTYPE INTEGER NOT NULL,
    ACTIVITYPARAMS MEDIUMTEXT,
    GROOVYSCRIPT INTEGER,
    NEWMAN INTEGER,
    NEWRESP INTEGER,
    SLA INTEGER,
    SCREEN INTEGER,
    TPUUID VARCHAR(36),
    PRIMARY KEY(OBJECTID),
    INDEX TWORKFLOWACTIVITYINDEX1 (TRANSITIONACTIVITY),
    INDEX TWORKFLOWACTIVITYINDEX2 (STATIONENTRYACTIVITY),
    INDEX TWORKFLOWACTIVITYINDEX3 (STATIONEXITACTIVITY),
    INDEX TWORKFLOWACTIVITYINDEX4 (STATIONDOACTIVITY),
    INDEX TWORKFLOWACTIVITYINDEX5 (TPUUID));


# -----------------------------------------------------------------------
# TWORKFLOWGUARD
# -----------------------------------------------------------------------
drop table if exists TWORKFLOWGUARD;

CREATE TABLE TWORKFLOWGUARD
(
    OBJECTID INTEGER NOT NULL,
    GUARDTYPE INTEGER NOT NULL,
    GUARDPARAMS MEDIUMTEXT,
    WORKFLOWTRANSITION INTEGER NOT NULL,
    ROLEKEY INTEGER,
    GROOVYSCRIPT INTEGER,
    PERSON INTEGER,
    TPUUID VARCHAR(36),
    PRIMARY KEY(OBJECTID),
    INDEX TWORKFLOWGUARDINDEX1 (WORKFLOWTRANSITION),
    INDEX TWORKFLOWGUARDINDEX2 (TPUUID));


# -----------------------------------------------------------------------
# TWORKFLOWCONNECT
# -----------------------------------------------------------------------
drop table if exists TWORKFLOWCONNECT;

CREATE TABLE TWORKFLOWCONNECT
(
    OBJECTID INTEGER NOT NULL,
    WORKFLOW INTEGER NOT NULL,
    ISSUETYPE INTEGER,
    PROJECTTYPE INTEGER,
    PROJECT INTEGER,
    TPUUID VARCHAR(36),
    PRIMARY KEY(OBJECTID),
    INDEX TWORKFLOWCONNECTINDEX1 (TPUUID));


# -----------------------------------------------------------------------
# TSLA
# -----------------------------------------------------------------------
drop table if exists TSLA;

CREATE TABLE TSLA
(
    OBJECTID INTEGER NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    TPUUID VARCHAR(36),
    PRIMARY KEY(OBJECTID),
    INDEX TSLAINDEX1 (TPUUID));


# -----------------------------------------------------------------------
# TESCALATIONENTRY
# -----------------------------------------------------------------------
drop table if exists TESCALATIONENTRY;

CREATE TABLE TESCALATIONENTRY
(
    OBJECTID INTEGER NOT NULL,
    SLA INTEGER NOT NULL,
    PRIORITY INTEGER,
    ESCALATETO INTEGER,
    SPARAMETERS MEDIUMTEXT,
    NLEVEL INTEGER,
    TPUUID VARCHAR(36),
    PRIMARY KEY(OBJECTID),
    INDEX TESCALATIONENTRYINDEX1 (SLA),
    INDEX TESCALATIONENTRYINDEX2 (TPUUID));


# -----------------------------------------------------------------------
# TESCALATIONSTATE
# -----------------------------------------------------------------------
drop table if exists TESCALATIONSTATE;

CREATE TABLE TESCALATIONSTATE
(
    OBJECTID INTEGER NOT NULL,
    ESCALATIONENTRY INTEGER NOT NULL,
    STATUS INTEGER,
    TPUUID VARCHAR(36),
    PRIMARY KEY(OBJECTID),
    INDEX TESCALATIONSTATEINDEX1 (ESCALATIONENTRY),
    INDEX TESCALATIONSTATEINDEX2 (TPUUID));


# -----------------------------------------------------------------------
# TORGPROJECTSLA
# -----------------------------------------------------------------------
drop table if exists TORGPROJECTSLA;

CREATE TABLE TORGPROJECTSLA
(
    OBJECTID INTEGER NOT NULL,
    DEPARTMENT INTEGER NOT NULL,
    PROJECT INTEGER NOT NULL,
    SLA INTEGER NOT NULL,
    TPUUID VARCHAR(36),
    PRIMARY KEY(OBJECTID),
    INDEX TORGPROJECTSLAINDEX1 (TPUUID));


# -----------------------------------------------------------------------
# TREADISSUE
# -----------------------------------------------------------------------
drop table if exists TREADISSUE;

CREATE TABLE TREADISSUE
(
    OBJECTID INTEGER NOT NULL,
    WORKITEM INTEGER NOT NULL,
    PERSON INTEGER NOT NULL,
    READTYPE INTEGER,
    TPUUID VARCHAR(36),
    PRIMARY KEY(OBJECTID),
    INDEX TREADISSUEINDEX1 (PERSON),
    INDEX TREADISSUEINDEX2 (WORKITEM),
    INDEX TREADISSUEINDEX3 (TPUUID));


# -----------------------------------------------------------------------
# TLASTEXECUTEDQUERY
# -----------------------------------------------------------------------
drop table if exists TLASTEXECUTEDQUERY;

CREATE TABLE TLASTEXECUTEDQUERY
(
    OBJECTID INTEGER NOT NULL,
    PERSON INTEGER NOT NULL,
    QUERYTYPE INTEGER NOT NULL,
    QUERYCLOB INTEGER,
    QUERYKEY INTEGER,
    LASTEXECUTEDTIME TIMESTAMP,
    TPUUID VARCHAR(36),
    PRIMARY KEY(OBJECTID),
    INDEX TLASTEXECUTEDQUERYINDEX1 (PERSON),
    INDEX TLASTEXECUTEDQUERYINDEX2 (TPUUID));

# -----------------------------------------------------------------------
# TGLOBALCSSSTYLE
# -----------------------------------------------------------------------

drop table if exists TGLOBALCSSSTYLE;

CREATE TABLE TGLOBALCSSSTYLE
(
    OBJECTID INTEGER NOT NULL,
    STYLEFOR INTEGER NOT NULL,
    CSSSTYLE VARCHAR (255),
    TPUUID VARCHAR (36),
    PRIMARY KEY(OBJECTID),
    INDEX TGLOBALCSSSTYLEINDEX1 (TPUUID));

ALTER TABLE TACL
    ADD CONSTRAINT TACL_FK_1
    FOREIGN KEY (PERSONKEY)
    REFERENCES TPERSON (PKEY)
;

ALTER TABLE TACL
    ADD CONSTRAINT TACL_FK_2
    FOREIGN KEY (ROLEKEY)
    REFERENCES TROLE (PKEY)
;

ALTER TABLE TACL
    ADD CONSTRAINT TACL_FK_3
    FOREIGN KEY (PROJKEY)
    REFERENCES TPROJECT (PKEY)
;

ALTER TABLE TBASELINE
    ADD CONSTRAINT TBASELINE_FK_1
    FOREIGN KEY (WORKITEMKEY)
    REFERENCES TWORKITEM (WORKITEMKEY)
;

ALTER TABLE TBASELINE
    ADD CONSTRAINT TBASELINE_FK_2
    FOREIGN KEY (CHANGEDBY)
    REFERENCES TPERSON (PKEY)
;

ALTER TABLE TCATEGORY
    ADD CONSTRAINT TCATEGORY_FK_1
    FOREIGN KEY (ICONKEY)
    REFERENCES TBLOB (OBJECTID)
;

ALTER TABLE TCLASS
    ADD CONSTRAINT TCLASS_FK_1
    FOREIGN KEY (PROJKEY)
    REFERENCES TPROJECT (PKEY)
;

ALTER TABLE TDEPARTMENT
    ADD CONSTRAINT TDEPARTMENT_FK_1
    FOREIGN KEY (COSTCENTER)
    REFERENCES TCOSTCENTER (OBJECTID)
;

ALTER TABLE TNOTIFY
    ADD CONSTRAINT TNOTIFY_FK_1
    FOREIGN KEY (PROJCATKEY)
    REFERENCES TPROJCAT (PKEY)
;

ALTER TABLE TNOTIFY
    ADD CONSTRAINT TNOTIFY_FK_2
    FOREIGN KEY (STATEKEY)
    REFERENCES TSTATE (PKEY)
;

ALTER TABLE TNOTIFY
    ADD CONSTRAINT TNOTIFY_FK_3
    FOREIGN KEY (PERSONKEY)
    REFERENCES TPERSON (PKEY)
;

ALTER TABLE TNOTIFY
    ADD CONSTRAINT TNOTIFY_FK_4
    FOREIGN KEY (WORKITEM)
    REFERENCES TWORKITEM (WORKITEMKEY)
;

ALTER TABLE TPERSON
    ADD CONSTRAINT TPERSON_FK_1
    FOREIGN KEY (DEPKEY)
    REFERENCES TDEPARTMENT (PKEY)
;

ALTER TABLE TPERSON
    ADD CONSTRAINT TPERSON_FK_2
    FOREIGN KEY (MYDEFAULTREPORT)
    REFERENCES TPRIVATEREPORTREPOSITORY (PKEY)
;

ALTER TABLE TPERSON
    ADD CONSTRAINT TPERSON_FK_3
    FOREIGN KEY (ICONKEY)
    REFERENCES TBLOB (OBJECTID)
;

ALTER TABLE TPRIORITY
    ADD CONSTRAINT TPRIORITY_FK_1
    FOREIGN KEY (ICONKEY)
    REFERENCES TBLOB (OBJECTID)
;

ALTER TABLE TPPRIORITY
    ADD CONSTRAINT TPPRIORITY_FK_1
    FOREIGN KEY (PRIORITY)
    REFERENCES TPRIORITY (PKEY)
;

ALTER TABLE TPPRIORITY
    ADD CONSTRAINT TPPRIORITY_FK_2
    FOREIGN KEY (PROJECTTYPE)
    REFERENCES TPROJECTTYPE (OBJECTID)
;

ALTER TABLE TPPRIORITY
    ADD CONSTRAINT TPPRIORITY_FK_3
    FOREIGN KEY (LISTTYPE)
    REFERENCES TCATEGORY (PKEY)
;

ALTER TABLE TPROJCAT
    ADD CONSTRAINT TPROJCAT_FK_1
    FOREIGN KEY (PROJKEY)
    REFERENCES TPROJECT (PKEY)
;

ALTER TABLE TPROJECT
    ADD CONSTRAINT TPROJECT_FK_1
    FOREIGN KEY (DEFOWNER)
    REFERENCES TPERSON (PKEY)
;

ALTER TABLE TPROJECT
    ADD CONSTRAINT TPROJECT_FK_2
    FOREIGN KEY (DEFMANAGER)
    REFERENCES TPERSON (PKEY)
;

ALTER TABLE TPROJECT
    ADD CONSTRAINT TPROJECT_FK_3
    FOREIGN KEY (DEFINITSTATE)
    REFERENCES TSTATE (PKEY)
;

ALTER TABLE TPROJECT
    ADD CONSTRAINT TPROJECT_FK_4
    FOREIGN KEY (PROJECTTYPE)
    REFERENCES TPROJECTTYPE (OBJECTID)
;

ALTER TABLE TPROJECT
    ADD CONSTRAINT TPROJECT_FK_5
    FOREIGN KEY (STATUS)
    REFERENCES TSYSTEMSTATE (OBJECTID)
;

ALTER TABLE TPROJECT
    ADD CONSTRAINT TPROJECT_FK_6
    FOREIGN KEY (PARENT)
    REFERENCES TPROJECT (PKEY)
;

ALTER TABLE TRELEASE
    ADD CONSTRAINT TRELEASE_FK_1
    FOREIGN KEY (PROJKEY)
    REFERENCES TPROJECT (PKEY)
;

ALTER TABLE TRELEASE
    ADD CONSTRAINT TRELEASE_FK_2
    FOREIGN KEY (STATUS)
    REFERENCES TSYSTEMSTATE (OBJECTID)
;

ALTER TABLE TRELEASE
    ADD CONSTRAINT TRELEASE_FK_3
    FOREIGN KEY (PARENT)
    REFERENCES TRELEASE (PKEY)
;

ALTER TABLE TROLE
    ADD CONSTRAINT TROLE_FK_1
    FOREIGN KEY (PROJECTTYPE)
    REFERENCES TPROJECTTYPE (OBJECTID)
;

ALTER TABLE TSEVERITY
    ADD CONSTRAINT TSEVERITY_FK_1
    FOREIGN KEY (ICONKEY)
    REFERENCES TBLOB (OBJECTID)
;

ALTER TABLE TPSEVERITY
    ADD CONSTRAINT TPSEVERITY_FK_1
    FOREIGN KEY (SEVERITY)
    REFERENCES TSEVERITY (PKEY)
;

ALTER TABLE TPSEVERITY
    ADD CONSTRAINT TPSEVERITY_FK_2
    FOREIGN KEY (PROJECTTYPE)
    REFERENCES TPROJECTTYPE (OBJECTID)
;

ALTER TABLE TPSEVERITY
    ADD CONSTRAINT TPSEVERITY_FK_3
    FOREIGN KEY (LISTTYPE)
    REFERENCES TCATEGORY (PKEY)
;

ALTER TABLE TSTATE
    ADD CONSTRAINT TSTATE_FK_1
    FOREIGN KEY (ICONKEY)
    REFERENCES TBLOB (OBJECTID)
;

ALTER TABLE TSTATECHANGE
    ADD CONSTRAINT TSTATECHANGE_FK_1
    FOREIGN KEY (CHANGEDBY)
    REFERENCES TPERSON (PKEY)
;

ALTER TABLE TSTATECHANGE
    ADD CONSTRAINT TSTATECHANGE_FK_2
    FOREIGN KEY (CHANGEDTO)
    REFERENCES TSTATE (PKEY)
;

ALTER TABLE TSTATECHANGE
    ADD CONSTRAINT TSTATECHANGE_FK_3
    FOREIGN KEY (WORKITEMKEY)
    REFERENCES TWORKITEM (WORKITEMKEY)
;

ALTER TABLE TTRAIL
    ADD CONSTRAINT TTRAIL_FK_1
    FOREIGN KEY (WORKITEMKEY)
    REFERENCES TWORKITEM (WORKITEMKEY)
;

ALTER TABLE TTRAIL
    ADD CONSTRAINT TTRAIL_FK_2
    FOREIGN KEY (CHANGEDBY)
    REFERENCES TPERSON (PKEY)
;

ALTER TABLE TWORKITEM
    ADD CONSTRAINT TWORKITEM_FK_1
    FOREIGN KEY (OWNER)
    REFERENCES TPERSON (PKEY)
;

ALTER TABLE TWORKITEM
    ADD CONSTRAINT TWORKITEM_FK_2
    FOREIGN KEY (CHANGEDBY)
    REFERENCES TPERSON (PKEY)
;

ALTER TABLE TWORKITEM
    ADD CONSTRAINT TWORKITEM_FK_3
    FOREIGN KEY (ORIGINATOR)
    REFERENCES TPERSON (PKEY)
;

ALTER TABLE TWORKITEM
    ADD CONSTRAINT TWORKITEM_FK_4
    FOREIGN KEY (RESPONSIBLE)
    REFERENCES TPERSON (PKEY)
;

ALTER TABLE TWORKITEM
    ADD CONSTRAINT TWORKITEM_FK_5
    FOREIGN KEY (PROJCATKEY)
    REFERENCES TPROJCAT (PKEY)
;

ALTER TABLE TWORKITEM
    ADD CONSTRAINT TWORKITEM_FK_6
    FOREIGN KEY (CATEGORYKEY)
    REFERENCES TCATEGORY (PKEY)
;

ALTER TABLE TWORKITEM
    ADD CONSTRAINT TWORKITEM_FK_7
    FOREIGN KEY (CLASSKEY)
    REFERENCES TCLASS (PKEY)
;

ALTER TABLE TWORKITEM
    ADD CONSTRAINT TWORKITEM_FK_8
    FOREIGN KEY (PRIORITYKEY)
    REFERENCES TPRIORITY (PKEY)
;

ALTER TABLE TWORKITEM
    ADD CONSTRAINT TWORKITEM_FK_9
    FOREIGN KEY (SEVERITYKEY)
    REFERENCES TSEVERITY (PKEY)
;

ALTER TABLE TWORKITEM
    ADD CONSTRAINT TWORKITEM_FK_10
    FOREIGN KEY (RELNOTICEDKEY)
    REFERENCES TRELEASE (PKEY)
;

ALTER TABLE TWORKITEM
    ADD CONSTRAINT TWORKITEM_FK_11
    FOREIGN KEY (RELSCHEDULEDKEY)
    REFERENCES TRELEASE (PKEY)
;

ALTER TABLE TWORKITEM
    ADD CONSTRAINT TWORKITEM_FK_12
    FOREIGN KEY (STATE)
    REFERENCES TSTATE (PKEY)
;

ALTER TABLE TWORKITEM
    ADD CONSTRAINT TWORKITEM_FK_13
    FOREIGN KEY (PROJECTKEY)
    REFERENCES TPROJECT (PKEY)
;

ALTER TABLE TCOMPUTEDVALUES
    ADD CONSTRAINT TCOMPUTEDVALUES_FK_1
    FOREIGN KEY (WORKITEMKEY)
    REFERENCES TWORKITEM (WORKITEMKEY)
;

ALTER TABLE TCOMPUTEDVALUES
    ADD CONSTRAINT TCOMPUTEDVALUES_FK_2
    FOREIGN KEY (PERSON)
    REFERENCES TPERSON (PKEY)
;

ALTER TABLE TPRIVATEREPORTREPOSITORY
    ADD CONSTRAINT TPRIVATEREPORTREPOSITORY_FK_1
    FOREIGN KEY (OWNER)
    REFERENCES TPERSON (PKEY)
;

ALTER TABLE TPUBLICREPORTREPOSITORY
    ADD CONSTRAINT TPUBLICREPORTREPOSITORY_FK_1
    FOREIGN KEY (OWNER)
    REFERENCES TPERSON (PKEY)
;

ALTER TABLE TPROJECTREPORTREPOSITORY
    ADD CONSTRAINT TPROJECTREPORTREPOSITORY_FK_1
    FOREIGN KEY (PROJECT)
    REFERENCES TPROJECT (PKEY)
;

ALTER TABLE TACCOUNT
    ADD CONSTRAINT TACCOUNT_FK_1
    FOREIGN KEY (STATUS)
    REFERENCES TSYSTEMSTATE (OBJECTID)
;

ALTER TABLE TACCOUNT
    ADD CONSTRAINT TACCOUNT_FK_2
    FOREIGN KEY (COSTCENTER)
    REFERENCES TCOSTCENTER (OBJECTID)
;

ALTER TABLE TATTACHMENT
    ADD CONSTRAINT TATTACHMENT_FK_1
    FOREIGN KEY (WORKITEM)
    REFERENCES TWORKITEM (WORKITEMKEY)
;

ALTER TABLE TATTACHMENT
    ADD CONSTRAINT TATTACHMENT_FK_2
    FOREIGN KEY (CHANGEDBY)
    REFERENCES TPERSON (PKEY)
;

ALTER TABLE TATTACHMENT
    ADD CONSTRAINT TATTACHMENT_FK_3
    FOREIGN KEY (DOCUMENTSTATE)
    REFERENCES TDOCSTATE (OBJECTID)
;

ALTER TABLE TCOST
    ADD CONSTRAINT TCOST_FK_1
    FOREIGN KEY (ACCOUNT)
    REFERENCES TACCOUNT (OBJECTID)
;

ALTER TABLE TCOST
    ADD CONSTRAINT TCOST_FK_2
    FOREIGN KEY (PERSON)
    REFERENCES TPERSON (PKEY)
;

ALTER TABLE TCOST
    ADD CONSTRAINT TCOST_FK_3
    FOREIGN KEY (WORKITEM)
    REFERENCES TWORKITEM (WORKITEMKEY)
;

ALTER TABLE TCOST
    ADD CONSTRAINT TCOST_FK_4
    FOREIGN KEY (EFFORTTYPE)
    REFERENCES TEFFORTTYPE (OBJECTID)
;

ALTER TABLE TEFFORTTYPE
    ADD CONSTRAINT TEFFORTTYPE_FK_1
    FOREIGN KEY (EFFORTUNIT)
    REFERENCES TEFFORTUNIT (OBJECTID)
;

ALTER TABLE TDOCSTATE
    ADD CONSTRAINT TDOCSTATE_FK_1
    FOREIGN KEY (PROJECTTYPE)
    REFERENCES TPROJECTTYPE (OBJECTID)
;

ALTER TABLE TDISABLEFIELD
    ADD CONSTRAINT TDISABLEFIELD_FK_1
    FOREIGN KEY (LISTTYPE)
    REFERENCES TCATEGORY (PKEY)
;

ALTER TABLE TDISABLEFIELD
    ADD CONSTRAINT TDISABLEFIELD_FK_2
    FOREIGN KEY (PROJECTTYPE)
    REFERENCES TPROJECTTYPE (OBJECTID)
;

ALTER TABLE TPLISTTYPE
    ADD CONSTRAINT TPLISTTYPE_FK_1
    FOREIGN KEY (PROJECTTYPE)
    REFERENCES TPROJECTTYPE (OBJECTID)
;

ALTER TABLE TPLISTTYPE
    ADD CONSTRAINT TPLISTTYPE_FK_2
    FOREIGN KEY (CATEGORY)
    REFERENCES TCATEGORY (PKEY)
;

ALTER TABLE TPSTATE
    ADD CONSTRAINT TPSTATE_FK_1
    FOREIGN KEY (STATE)
    REFERENCES TSTATE (PKEY)
;

ALTER TABLE TPSTATE
    ADD CONSTRAINT TPSTATE_FK_2
    FOREIGN KEY (PROJECTTYPE)
    REFERENCES TPROJECTTYPE (OBJECTID)
;

ALTER TABLE TPSTATE
    ADD CONSTRAINT TPSTATE_FK_3
    FOREIGN KEY (LISTTYPE)
    REFERENCES TCATEGORY (PKEY)
;

ALTER TABLE TWORKFLOW
    ADD CONSTRAINT TWORKFLOW_FK_1
    FOREIGN KEY (STATEFROM)
    REFERENCES TSTATE (PKEY)
;

ALTER TABLE TWORKFLOW
    ADD CONSTRAINT TWORKFLOW_FK_2
    FOREIGN KEY (STATETO)
    REFERENCES TSTATE (PKEY)
;

ALTER TABLE TWORKFLOW
    ADD CONSTRAINT TWORKFLOW_FK_3
    FOREIGN KEY (PROJECTTYPE)
    REFERENCES TPROJECTTYPE (OBJECTID)
;

ALTER TABLE TWORKFLOW
    ADD CONSTRAINT TWORKFLOW_FK_4
    FOREIGN KEY (RESPONSIBLE)
    REFERENCES TPERSON (PKEY)
;

ALTER TABLE TWORKFLOWROLE
    ADD CONSTRAINT TWORKFLOWROLE_FK_1
    FOREIGN KEY (WORKFLOW)
    REFERENCES TWORKFLOW (OBJECTID)
;

ALTER TABLE TWORKFLOWROLE
    ADD CONSTRAINT TWORKFLOWROLE_FK_2
    FOREIGN KEY (MAYCHANGEROLE)
    REFERENCES TROLE (PKEY)
;

ALTER TABLE TWORKFLOWCATEGORY
    ADD CONSTRAINT TWORKFLOWCATEGORY_FK_1
    FOREIGN KEY (WORKFLOW)
    REFERENCES TWORKFLOW (OBJECTID)
;

ALTER TABLE TWORKFLOWCATEGORY
    ADD CONSTRAINT TWORKFLOWCATEGORY_FK_2
    FOREIGN KEY (CATEGORY)
    REFERENCES TCATEGORY (PKEY)
;

ALTER TABLE TROLELISTTYPE
    ADD CONSTRAINT TROLELISTTYPE_FK_1
    FOREIGN KEY (PROLE)
    REFERENCES TROLE (PKEY)
;

ALTER TABLE TROLELISTTYPE
    ADD CONSTRAINT TROLELISTTYPE_FK_2
    FOREIGN KEY (LISTTYPE)
    REFERENCES TCATEGORY (PKEY)
;

ALTER TABLE TISSUEATTRIBUTEVALUE
    ADD CONSTRAINT TISSUEATTRIBUTEVALUE_FK_1
    FOREIGN KEY (PERSON)
    REFERENCES TPERSON (PKEY)
;

ALTER TABLE TISSUEATTRIBUTEVALUE
    ADD CONSTRAINT TISSUEATTRIBUTEVALUE_FK_2
    FOREIGN KEY (ISSUE)
    REFERENCES TWORKITEM (WORKITEMKEY)
;

ALTER TABLE TISSUEATTRIBUTEVALUE
    ADD CONSTRAINT TISSUEATTRIBUTEVALUE_FK_3
    FOREIGN KEY (ATTRIBUTEID)
    REFERENCES TATTRIBUTE (OBJECTID)
;

ALTER TABLE TISSUEATTRIBUTEVALUE
    ADD CONSTRAINT TISSUEATTRIBUTEVALUE_FK_4
    FOREIGN KEY (OPTIONID)
    REFERENCES TATTRIBUTEOPTION (OBJECTID)
;

ALTER TABLE TATTRIBUTEOPTION
    ADD CONSTRAINT TATTRIBUTEOPTION_FK_1
    FOREIGN KEY (ATTRIBUTEID)
    REFERENCES TATTRIBUTE (OBJECTID)
;

ALTER TABLE TATTRIBUTETYPE
    ADD CONSTRAINT TATTRIBUTETYPE_FK_1
    FOREIGN KEY (ATTRIBUTECLASS)
    REFERENCES TATTRIBUTECLASS (OBJECTID)
;

ALTER TABLE TATTRIBUTE
    ADD CONSTRAINT TATTRIBUTE_FK_1
    FOREIGN KEY (REQUIREDOPTION)
    REFERENCES TATTRIBUTEOPTION (OBJECTID)
;

ALTER TABLE TREPORTLAYOUT
    ADD CONSTRAINT TREPORTLAYOUT_FK_1
    FOREIGN KEY (PROJECTTYPE)
    REFERENCES TPROJECTTYPE (OBJECTID)
;

ALTER TABLE TREPORTLAYOUT
    ADD CONSTRAINT TREPORTLAYOUT_FK_2
    FOREIGN KEY (PROJECT)
    REFERENCES TPROJECT (PKEY)
;

ALTER TABLE TREPORTLAYOUT
    ADD CONSTRAINT TREPORTLAYOUT_FK_3
    FOREIGN KEY (PERSON)
    REFERENCES TPERSON (PKEY)
;

ALTER TABLE TSCHEDULER
    ADD CONSTRAINT TSCHEDULER_FK_1
    FOREIGN KEY (PERSON)
    REFERENCES TPERSON (PKEY)
;

ALTER TABLE TPROJECTACCOUNT
    ADD CONSTRAINT TPROJECTACCOUNT_FK_1
    FOREIGN KEY (PROJECT)
    REFERENCES TPROJECT (PKEY)
;

ALTER TABLE TPROJECTACCOUNT
    ADD CONSTRAINT TPROJECTACCOUNT_FK_2
    FOREIGN KEY (ACCOUNT)
    REFERENCES TACCOUNT (OBJECTID)
;

ALTER TABLE TGROUPMEMBER
    ADD CONSTRAINT TGROUPMEMBER_FK_1
    FOREIGN KEY (THEGROUP)
    REFERENCES TPERSON (PKEY)
;

ALTER TABLE TGROUPMEMBER
    ADD CONSTRAINT TGROUPMEMBER_FK_2
    FOREIGN KEY (PERSON)
    REFERENCES TPERSON (PKEY)
;

ALTER TABLE TBUDGET
    ADD CONSTRAINT TBUDGET_FK_1
    FOREIGN KEY (WORKITEMKEY)
    REFERENCES TWORKITEM (WORKITEMKEY)
;

ALTER TABLE TBUDGET
    ADD CONSTRAINT TBUDGET_FK_2
    FOREIGN KEY (CHANGEDBY)
    REFERENCES TPERSON (PKEY)
;

ALTER TABLE TACTUALESTIMATEDBUDGET
    ADD CONSTRAINT TACTUALESTIMATEDBUDGET_FK_1
    FOREIGN KEY (WORKITEMKEY)
    REFERENCES TWORKITEM (WORKITEMKEY)
;

ALTER TABLE TACTUALESTIMATEDBUDGET
    ADD CONSTRAINT TACTUALESTIMATEDBUDGET_FK_2
    FOREIGN KEY (CHANGEDBY)
    REFERENCES TPERSON (PKEY)
;

ALTER TABLE TSYSTEMSTATE
    ADD CONSTRAINT TSYSTEMSTATE_FK_1
    FOREIGN KEY (ICONKEY)
    REFERENCES TBLOB (OBJECTID)
;

ALTER TABLE TDASHBOARDSCREEN
    ADD CONSTRAINT TDASHBOARDSCREEN_FK_1
    FOREIGN KEY (PERSONPKEY)
    REFERENCES TPERSON (PKEY)
;

ALTER TABLE TDASHBOARDSCREEN
    ADD CONSTRAINT TDASHBOARDSCREEN_FK_2
    FOREIGN KEY (PROJECT)
    REFERENCES TPROJECT (PKEY)
;

ALTER TABLE TDASHBOARDTAB
    ADD CONSTRAINT TDASHBOARDTAB_FK_1
    FOREIGN KEY (PARENT)
    REFERENCES TDASHBOARDSCREEN (OBJECTID)
;

ALTER TABLE TDASHBOARDPANEL
    ADD CONSTRAINT TDASHBOARDPANEL_FK_1
    FOREIGN KEY (PARENT)
    REFERENCES TDASHBOARDTAB (OBJECTID)
;

ALTER TABLE TDASHBOARDFIELD
    ADD CONSTRAINT TDASHBOARDFIELD_FK_1
    FOREIGN KEY (PARENT)
    REFERENCES TDASHBOARDPANEL (OBJECTID)
;

ALTER TABLE TDASHBOARDPARAMETER
    ADD CONSTRAINT TDASHBOARDPARAMETER_FK_1
    FOREIGN KEY (DASHBOARDFIELD)
    REFERENCES TDASHBOARDFIELD (OBJECTID)
;

ALTER TABLE TVERSIONCONTROLPARAMETER
    ADD CONSTRAINT TVERSIONCONTROLPARAMETER_FK_1
    FOREIGN KEY (PROJECT)
    REFERENCES TPROJECT (PKEY)
;

ALTER TABLE TFIELD
    ADD CONSTRAINT TFIELD_FK_1
    FOREIGN KEY (OWNER)
    REFERENCES TPERSON (PKEY)
;

ALTER TABLE TFIELDCONFIG
    ADD CONSTRAINT TFIELDCONFIG_FK_1
    FOREIGN KEY (FIELDKEY)
    REFERENCES TFIELD (OBJECTID)
;

ALTER TABLE TFIELDCONFIG
    ADD CONSTRAINT TFIELDCONFIG_FK_2
    FOREIGN KEY (ISSUETYPE)
    REFERENCES TCATEGORY (PKEY)
;

ALTER TABLE TFIELDCONFIG
    ADD CONSTRAINT TFIELDCONFIG_FK_3
    FOREIGN KEY (PROJECTTYPE)
    REFERENCES TPROJECTTYPE (OBJECTID)
;

ALTER TABLE TFIELDCONFIG
    ADD CONSTRAINT TFIELDCONFIG_FK_4
    FOREIGN KEY (PROJECT)
    REFERENCES TPROJECT (PKEY)
;

ALTER TABLE TFIELDCONFIG
    ADD CONSTRAINT TFIELDCONFIG_FK_5
    FOREIGN KEY (GROOVYSCRIPT)
    REFERENCES TSCRIPTS (OBJECTID)
;

ALTER TABLE TROLEFIELD
    ADD CONSTRAINT TROLEFIELD_FK_1
    FOREIGN KEY (ROLEKEY)
    REFERENCES TROLE (PKEY)
;

ALTER TABLE TCONFIGOPTIONSROLE
    ADD CONSTRAINT TCONFIGOPTIONSROLE_FK_1
    FOREIGN KEY (CONFIGKEY)
    REFERENCES TFIELDCONFIG (OBJECTID)
;

ALTER TABLE TCONFIGOPTIONSROLE
    ADD CONSTRAINT TCONFIGOPTIONSROLE_FK_2
    FOREIGN KEY (ROLEKEY)
    REFERENCES TROLE (PKEY)
;

ALTER TABLE TCONFIGOPTIONSROLE
    ADD CONSTRAINT TCONFIGOPTIONSROLE_FK_3
    FOREIGN KEY (OPTIONKEY)
    REFERENCES TOPTION (OBJECTID)
;

ALTER TABLE TTEXTBOXSETTINGS
    ADD CONSTRAINT TTEXTBOXSETTINGS_FK_1
    FOREIGN KEY (CONFIG)
    REFERENCES TFIELDCONFIG (OBJECTID)
;

ALTER TABLE TGENERALSETTINGS
    ADD CONSTRAINT TGENERALSETTINGS_FK_1
    FOREIGN KEY (CONFIG)
    REFERENCES TFIELDCONFIG (OBJECTID)
;

ALTER TABLE TLIST
    ADD CONSTRAINT TLIST_FK_1
    FOREIGN KEY (PARENTLIST)
    REFERENCES TLIST (OBJECTID)
;

ALTER TABLE TLIST
    ADD CONSTRAINT TLIST_FK_2
    FOREIGN KEY (PROJECT)
    REFERENCES TPROJECT (PKEY)
;

ALTER TABLE TLIST
    ADD CONSTRAINT TLIST_FK_3
    FOREIGN KEY (OWNER)
    REFERENCES TPERSON (PKEY)
;

ALTER TABLE TOPTION
    ADD CONSTRAINT TOPTION_FK_1
    FOREIGN KEY (LIST)
    REFERENCES TLIST (OBJECTID)
;

ALTER TABLE TOPTION
    ADD CONSTRAINT TOPTION_FK_2
    FOREIGN KEY (ICONKEY)
    REFERENCES TBLOB (OBJECTID)
;

ALTER TABLE TOPTIONSETTINGS
    ADD CONSTRAINT TOPTIONSETTINGS_FK_1
    FOREIGN KEY (LIST)
    REFERENCES TLIST (OBJECTID)
;

ALTER TABLE TOPTIONSETTINGS
    ADD CONSTRAINT TOPTIONSETTINGS_FK_2
    FOREIGN KEY (CONFIG)
    REFERENCES TFIELDCONFIG (OBJECTID)
;

ALTER TABLE TATTRIBUTEVALUE
    ADD CONSTRAINT TATTRIBUTEVALUE_FK_1
    FOREIGN KEY (FIELDKEY)
    REFERENCES TFIELD (OBJECTID)
;

ALTER TABLE TATTRIBUTEVALUE
    ADD CONSTRAINT TATTRIBUTEVALUE_FK_2
    FOREIGN KEY (WORKITEM)
    REFERENCES TWORKITEM (WORKITEMKEY)
;

ALTER TABLE TSCREEN
    ADD CONSTRAINT TSCREEN_FK_1
    FOREIGN KEY (OWNER)
    REFERENCES TPERSON (PKEY)
;

ALTER TABLE TSCREENTAB
    ADD CONSTRAINT TSCREENTAB_FK_1
    FOREIGN KEY (PARENT)
    REFERENCES TSCREEN (OBJECTID)
;

ALTER TABLE TSCREENPANEL
    ADD CONSTRAINT TSCREENPANEL_FK_1
    FOREIGN KEY (PARENT)
    REFERENCES TSCREENTAB (OBJECTID)
;

ALTER TABLE TSCREENFIELD
    ADD CONSTRAINT TSCREENFIELD_FK_1
    FOREIGN KEY (PARENT)
    REFERENCES TSCREENPANEL (OBJECTID)
;

ALTER TABLE TSCREENFIELD
    ADD CONSTRAINT TSCREENFIELD_FK_2
    FOREIGN KEY (FIELDKEY)
    REFERENCES TFIELD (OBJECTID)
;

ALTER TABLE TSCREENCONFIG
    ADD CONSTRAINT TSCREENCONFIG_FK_1
    FOREIGN KEY (SCREEN)
    REFERENCES TSCREEN (OBJECTID)
;

ALTER TABLE TSCREENCONFIG
    ADD CONSTRAINT TSCREENCONFIG_FK_2
    FOREIGN KEY (ISSUETYPE)
    REFERENCES TCATEGORY (PKEY)
;

ALTER TABLE TSCREENCONFIG
    ADD CONSTRAINT TSCREENCONFIG_FK_3
    FOREIGN KEY (PROJECTTYPE)
    REFERENCES TPROJECTTYPE (OBJECTID)
;

ALTER TABLE TSCREENCONFIG
    ADD CONSTRAINT TSCREENCONFIG_FK_4
    FOREIGN KEY (PROJECT)
    REFERENCES TPROJECT (PKEY)
;

ALTER TABLE TSCREENCONFIG
    ADD CONSTRAINT TSCREENCONFIG_FK_5
    FOREIGN KEY (ACTIONKEY)
    REFERENCES TACTION (OBJECTID)
;

ALTER TABLE TINITSTATE
    ADD CONSTRAINT TINITSTATE_FK_1
    FOREIGN KEY (PROJECT)
    REFERENCES TPROJECT (PKEY)
;

ALTER TABLE TINITSTATE
    ADD CONSTRAINT TINITSTATE_FK_2
    FOREIGN KEY (LISTTYPE)
    REFERENCES TCATEGORY (PKEY)
;

ALTER TABLE TINITSTATE
    ADD CONSTRAINT TINITSTATE_FK_3
    FOREIGN KEY (STATEKEY)
    REFERENCES TSTATE (PKEY)
;

ALTER TABLE TEVENT
    ADD CONSTRAINT TEVENT_FK_1
    FOREIGN KEY (PROJECTTYPE)
    REFERENCES TPROJECTTYPE (OBJECTID)
;

ALTER TABLE TEVENT
    ADD CONSTRAINT TEVENT_FK_2
    FOREIGN KEY (PROJECT)
    REFERENCES TPROJECT (PKEY)
;

ALTER TABLE TEVENT
    ADD CONSTRAINT TEVENT_FK_3
    FOREIGN KEY (EVENTSCRIPT)
    REFERENCES TCLOB (OBJECTID)
;

ALTER TABLE TNOTIFYFIELD
    ADD CONSTRAINT TNOTIFYFIELD_FK_1
    FOREIGN KEY (NOTIFYTRIGGER)
    REFERENCES TNOTIFYTRIGGER (OBJECTID)
;

ALTER TABLE TNOTIFYTRIGGER
    ADD CONSTRAINT TNOTIFYTRIGGER_FK_1
    FOREIGN KEY (PERSON)
    REFERENCES TPERSON (PKEY)
;

ALTER TABLE TNOTIFYSETTINGS
    ADD CONSTRAINT TNOTIFYSETTINGS_FK_1
    FOREIGN KEY (PERSON)
    REFERENCES TPERSON (PKEY)
;

ALTER TABLE TNOTIFYSETTINGS
    ADD CONSTRAINT TNOTIFYSETTINGS_FK_2
    FOREIGN KEY (PROJECT)
    REFERENCES TPROJECT (PKEY)
;

ALTER TABLE TNOTIFYSETTINGS
    ADD CONSTRAINT TNOTIFYSETTINGS_FK_3
    FOREIGN KEY (NOTIFYTRIGGER)
    REFERENCES TNOTIFYTRIGGER (OBJECTID)
;

ALTER TABLE TNOTIFYSETTINGS
    ADD CONSTRAINT TNOTIFYSETTINGS_FK_4
    FOREIGN KEY (NOTIFYFILTER)
    REFERENCES TQUERYREPOSITORY (OBJECTID)
;

ALTER TABLE TQUERYREPOSITORY
    ADD CONSTRAINT TQUERYREPOSITORY_FK_1
    FOREIGN KEY (PERSON)
    REFERENCES TPERSON (PKEY)
;

ALTER TABLE TQUERYREPOSITORY
    ADD CONSTRAINT TQUERYREPOSITORY_FK_2
    FOREIGN KEY (PROJECT)
    REFERENCES TPROJECT (PKEY)
;

ALTER TABLE TQUERYREPOSITORY
    ADD CONSTRAINT TQUERYREPOSITORY_FK_3
    FOREIGN KEY (QUERYKEY)
    REFERENCES TCLOB (OBJECTID)
;

ALTER TABLE TQUERYREPOSITORY
    ADD CONSTRAINT TQUERYREPOSITORY_FK_4
    FOREIGN KEY (CATEGORYKEY)
    REFERENCES TFILTERCATEGORY (OBJECTID)
;

ALTER TABLE TLINKTYPE
    ADD CONSTRAINT TLINKTYPE_FK_1
    FOREIGN KEY (OUTWARDICONKEY)
    REFERENCES TBLOB (OBJECTID)
;

ALTER TABLE TLINKTYPE
    ADD CONSTRAINT TLINKTYPE_FK_2
    FOREIGN KEY (INWARDICONKEY)
    REFERENCES TBLOB (OBJECTID)
;

ALTER TABLE TWORKITEMLINK
    ADD CONSTRAINT TWORKITEMLINK_FK_1
    FOREIGN KEY (LINKPRED)
    REFERENCES TWORKITEM (WORKITEMKEY)
;

ALTER TABLE TWORKITEMLINK
    ADD CONSTRAINT TWORKITEMLINK_FK_2
    FOREIGN KEY (LINKSUCC)
    REFERENCES TWORKITEM (WORKITEMKEY)
;

ALTER TABLE TWORKITEMLINK
    ADD CONSTRAINT TWORKITEMLINK_FK_3
    FOREIGN KEY (LINKTYPE)
    REFERENCES TLINKTYPE (OBJECTID)
;

ALTER TABLE TWORKITEMLINK
    ADD CONSTRAINT TWORKITEMLINK_FK_4
    FOREIGN KEY (CHANGEDBY)
    REFERENCES TPERSON (PKEY)
;

ALTER TABLE TWORKITEMLOCK
    ADD CONSTRAINT TWORKITEMLOCK_FK_1
    FOREIGN KEY (WORKITEM)
    REFERENCES TWORKITEM (WORKITEMKEY)
;

ALTER TABLE TWORKITEMLOCK
    ADD CONSTRAINT TWORKITEMLOCK_FK_2
    FOREIGN KEY (PERSON)
    REFERENCES TPERSON (PKEY)
;

ALTER TABLE TEXPORTTEMPLATE
    ADD CONSTRAINT TEXPORTTEMPLATE_FK_1
    FOREIGN KEY (PERSON)
    REFERENCES TPERSON (PKEY)
;

ALTER TABLE TEXPORTTEMPLATE
    ADD CONSTRAINT TEXPORTTEMPLATE_FK_2
    FOREIGN KEY (PROJECT)
    REFERENCES TPROJECT (PKEY)
;

ALTER TABLE TEXPORTTEMPLATE
    ADD CONSTRAINT TEXPORTTEMPLATE_FK_3
    FOREIGN KEY (CATEGORYKEY)
    REFERENCES TREPORTCATEGORY (OBJECTID)
;

ALTER TABLE TLOGGEDINUSERS
    ADD CONSTRAINT TLOGGEDINUSERS_FK_1
    FOREIGN KEY (LOGGEDUSER)
    REFERENCES TPERSON (PKEY)
;

ALTER TABLE TLOGGEDINUSERS
    ADD CONSTRAINT TLOGGEDINUSERS_FK_2
    FOREIGN KEY (NODEADDRESS)
    REFERENCES CLUSTERNODE (OBJECTID)
;

ALTER TABLE TENTITYCHANGES
    ADD CONSTRAINT TENTITYCHANGES_FK_1
    FOREIGN KEY (CLUSTERNODE)
    REFERENCES CLUSTERNODE (OBJECTID)
;

ALTER TABLE TSUMMARYMAIL
    ADD CONSTRAINT TSUMMARYMAIL_FK_1
    FOREIGN KEY (WORKITEM)
    REFERENCES TWORKITEM (WORKITEMKEY)
;

ALTER TABLE TSUMMARYMAIL
    ADD CONSTRAINT TSUMMARYMAIL_FK_2
    FOREIGN KEY (PERSONFROM)
    REFERENCES TPERSON (PKEY)
;

ALTER TABLE TSUMMARYMAIL
    ADD CONSTRAINT TSUMMARYMAIL_FK_3
    FOREIGN KEY (PERSONTO)
    REFERENCES TPERSON (PKEY)
;

ALTER TABLE TOUTLINECODE
    ADD CONSTRAINT TOUTLINECODE_FK_1
    FOREIGN KEY (OUTLINETEMPLATE)
    REFERENCES TOUTLINETEMPLATE (OBJECTID)
;

ALTER TABLE TOUTLINETEMPLATEDEF
    ADD CONSTRAINT TOUTLINETEMPLATEDEF_FK_1
    FOREIGN KEY (OUTLINETEMPLATE)
    REFERENCES TOUTLINETEMPLATE (OBJECTID)
;

ALTER TABLE THISTORYTRANSACTION
    ADD CONSTRAINT THISTORYTRANSACTION_FK_1
    FOREIGN KEY (WORKITEM)
    REFERENCES TWORKITEM (WORKITEMKEY)
;

ALTER TABLE THISTORYTRANSACTION
    ADD CONSTRAINT THISTORYTRANSACTION_FK_2
    FOREIGN KEY (CHANGEDBY)
    REFERENCES TPERSON (PKEY)
;

ALTER TABLE TFIELDCHANGE
    ADD CONSTRAINT TFIELDCHANGE_FK_1
    FOREIGN KEY (HISTORYTRANSACTION)
    REFERENCES THISTORYTRANSACTION (OBJECTID)
;

ALTER TABLE TFIELDCHANGE
    ADD CONSTRAINT TFIELDCHANGE_FK_2
    FOREIGN KEY (PARENTCOMMENT)
    REFERENCES TFIELDCHANGE (OBJECTID)
;

ALTER TABLE TFIELDCHANGE
    ADD CONSTRAINT TFIELDCHANGE_FK_3
    FOREIGN KEY (NEWCUSTOMOPTIONID)
    REFERENCES TOPTION (OBJECTID)
;

ALTER TABLE TFIELDCHANGE
    ADD CONSTRAINT TFIELDCHANGE_FK_4
    FOREIGN KEY (OLDCUSTOMOPTIONID)
    REFERENCES TOPTION (OBJECTID)
;

ALTER TABLE TSCRIPTS
    ADD CONSTRAINT TSCRIPTS_FK_1
    FOREIGN KEY (CHANGEDBY)
    REFERENCES TPERSON (PKEY)
;

ALTER TABLE TSCRIPTS
    ADD CONSTRAINT TSCRIPTS_FK_2
    FOREIGN KEY (PROJECTTYPE)
    REFERENCES TPROJECTTYPE (OBJECTID)
;

ALTER TABLE TSCRIPTS
    ADD CONSTRAINT TSCRIPTS_FK_3
    FOREIGN KEY (PROJECT)
    REFERENCES TPROJECT (PKEY)
;

ALTER TABLE TREVISION
    ADD CONSTRAINT TREVISION_FK_1
    FOREIGN KEY (REPOSITORYKEY)
    REFERENCES TREPOSITORY (OBJECTID)
;

ALTER TABLE TREVISIONWORKITEMS
    ADD CONSTRAINT TREVISIONWORKITEMS_FK_1
    FOREIGN KEY (REVISIONKEY)
    REFERENCES TREVISION (OBJECTID)
;

ALTER TABLE TTEMPLATEPERSON
    ADD CONSTRAINT TTEMPLATEPERSON_FK_1
    FOREIGN KEY (PERSON)
    REFERENCES TPERSON (PKEY)
;

ALTER TABLE TTEMPLATEPERSON
    ADD CONSTRAINT TTEMPLATEPERSON_FK_2
    FOREIGN KEY (REPORTTEMPLATE)
    REFERENCES TEXPORTTEMPLATE (OBJECTID)
;

ALTER TABLE TREPORTPERSONSETTINGS
    ADD CONSTRAINT TREPORTPERSONSETTINGS_FK_1
    FOREIGN KEY (PERSON)
    REFERENCES TPERSON (PKEY)
;

ALTER TABLE TREPORTPERSONSETTINGS
    ADD CONSTRAINT TREPORTPERSONSETTINGS_FK_2
    FOREIGN KEY (RECURRENCEPATTERN)
    REFERENCES TRECURRENCEPATTERN (OBJECTID)
;

ALTER TABLE TREPORTPERSONSETTINGS
    ADD CONSTRAINT TREPORTPERSONSETTINGS_FK_3
    FOREIGN KEY (REPORTTEMPLATE)
    REFERENCES TEXPORTTEMPLATE (OBJECTID)
;

ALTER TABLE TREPORTPARAMETER
    ADD CONSTRAINT TREPORTPARAMETER_FK_1
    FOREIGN KEY (REPORTPERSONSETTINGS)
    REFERENCES TREPORTPERSONSETTINGS (OBJECTID)
;

ALTER TABLE TMSPROJECTTASK
    ADD CONSTRAINT TMSPROJECTTASK_FK_1
    FOREIGN KEY (WORKITEM)
    REFERENCES TWORKITEM (WORKITEMKEY)
;

ALTER TABLE TMSPROJECTEXCHANGE
    ADD CONSTRAINT TMSPROJECTEXCHANGE_FK_1
    FOREIGN KEY (CHANGEDBY)
    REFERENCES TPERSON (PKEY)
;

ALTER TABLE TFILTERCATEGORY
    ADD CONSTRAINT TFILTERCATEGORY_FK_1
    FOREIGN KEY (PROJECT)
    REFERENCES TPROJECT (PKEY)
;

ALTER TABLE TFILTERCATEGORY
    ADD CONSTRAINT TFILTERCATEGORY_FK_2
    FOREIGN KEY (CREATEDBY)
    REFERENCES TPERSON (PKEY)
;

ALTER TABLE TFILTERCATEGORY
    ADD CONSTRAINT TFILTERCATEGORY_FK_3
    FOREIGN KEY (PARENTID)
    REFERENCES TFILTERCATEGORY (OBJECTID)
;

ALTER TABLE TREPORTCATEGORY
    ADD CONSTRAINT TREPORTCATEGORY_FK_1
    FOREIGN KEY (PROJECT)
    REFERENCES TPROJECT (PKEY)
;

ALTER TABLE TREPORTCATEGORY
    ADD CONSTRAINT TREPORTCATEGORY_FK_2
    FOREIGN KEY (CREATEDBY)
    REFERENCES TPERSON (PKEY)
;

ALTER TABLE TREPORTCATEGORY
    ADD CONSTRAINT TREPORTCATEGORY_FK_3
    FOREIGN KEY (PARENTID)
    REFERENCES TREPORTCATEGORY (OBJECTID)
;

ALTER TABLE TMENUITEMQUERY
    ADD CONSTRAINT TMENUITEMQUERY_FK_1
    FOREIGN KEY (PERSON)
    REFERENCES TPERSON (PKEY)
;

ALTER TABLE TMENUITEMQUERY
    ADD CONSTRAINT TMENUITEMQUERY_FK_2
    FOREIGN KEY (QUERYKEY)
    REFERENCES TQUERYREPOSITORY (OBJECTID)
;

ALTER TABLE TCHILDISSUETYPE
    ADD CONSTRAINT TCHILDISSUETYPE_FK_1
    FOREIGN KEY (ISSUETYPEPARENT)
    REFERENCES TCATEGORY (PKEY)
;

ALTER TABLE TCHILDISSUETYPE
    ADD CONSTRAINT TCHILDISSUETYPE_FK_2
    FOREIGN KEY (ISSUETYPECHILD)
    REFERENCES TCATEGORY (PKEY)
;

ALTER TABLE TPERSONBASKET
    ADD CONSTRAINT TPERSONBASKET_FK_1
    FOREIGN KEY (BASKET)
    REFERENCES TBASKET (OBJECTID)
;

ALTER TABLE TPERSONBASKET
    ADD CONSTRAINT TPERSONBASKET_FK_2
    FOREIGN KEY (WORKITEM)
    REFERENCES TWORKITEM (WORKITEMKEY)
;

ALTER TABLE TPERSONBASKET
    ADD CONSTRAINT TPERSONBASKET_FK_3
    FOREIGN KEY (PERSON)
    REFERENCES TPERSON (PKEY)
;

ALTER TABLE TBASKET
    ADD CONSTRAINT TBASKET_FK_1
    FOREIGN KEY (PERSON)
    REFERENCES TPERSON (PKEY)
;

ALTER TABLE TMAILTEMPLATECONFIG
    ADD CONSTRAINT TMAILTEMPLATECONFIG_FK_1
    FOREIGN KEY (MAILTEMPLATE)
    REFERENCES TMAILTEMPLATE (OBJECTID)
;

ALTER TABLE TMAILTEMPLATECONFIG
    ADD CONSTRAINT TMAILTEMPLATECONFIG_FK_2
    FOREIGN KEY (ISSUETYPE)
    REFERENCES TCATEGORY (PKEY)
;

ALTER TABLE TMAILTEMPLATECONFIG
    ADD CONSTRAINT TMAILTEMPLATECONFIG_FK_3
    FOREIGN KEY (PROJECTTYPE)
    REFERENCES TPROJECTTYPE (OBJECTID)
;

ALTER TABLE TMAILTEMPLATECONFIG
    ADD CONSTRAINT TMAILTEMPLATECONFIG_FK_4
    FOREIGN KEY (PROJECT)
    REFERENCES TPROJECT (PKEY)
;

ALTER TABLE TMAILTEMPLATEDEF
    ADD CONSTRAINT TMAILTEMPLATEDEF_FK_1
    FOREIGN KEY (MAILTEMPLATE)
    REFERENCES TMAILTEMPLATE (OBJECTID)
;

ALTER TABLE TLASTVISITEDITEM
    ADD CONSTRAINT TLASTVISITEDITEM_FK_1
    FOREIGN KEY (WORKITEM)
    REFERENCES TWORKITEM (WORKITEMKEY)
;

ALTER TABLE TLASTVISITEDITEM
    ADD CONSTRAINT TLASTVISITEDITEM_FK_2
    FOREIGN KEY (PERSON)
    REFERENCES TPERSON (PKEY)
;

ALTER TABLE TWORKFLOWDEF
    ADD CONSTRAINT TWORKFLOWDEF_FK_1
    FOREIGN KEY (OWNER)
    REFERENCES TPERSON (PKEY)
;

ALTER TABLE TWORKFLOWTRANSITION
    ADD CONSTRAINT TWORKFLOWTRANSITION_FK_1
    FOREIGN KEY (STATIONFROM)
    REFERENCES TWORKFLOWSTATION (OBJECTID)
;

ALTER TABLE TWORKFLOWTRANSITION
    ADD CONSTRAINT TWORKFLOWTRANSITION_FK_2
    FOREIGN KEY (STATIONTO)
    REFERENCES TWORKFLOWSTATION (OBJECTID)
;

ALTER TABLE TWORKFLOWTRANSITION
    ADD CONSTRAINT TWORKFLOWTRANSITION_FK_3
    FOREIGN KEY (ACTIONKEY)
    REFERENCES TACTION (OBJECTID)
;

ALTER TABLE TWORKFLOWTRANSITION
    ADD CONSTRAINT TWORKFLOWTRANSITION_FK_4
    FOREIGN KEY (WORKFLOW)
    REFERENCES TWORKFLOWDEF (OBJECTID)
;

ALTER TABLE TWORKFLOWSTATION
    ADD CONSTRAINT TWORKFLOWSTATION_FK_1
    FOREIGN KEY (STATUS)
    REFERENCES TSTATE (PKEY)
;

ALTER TABLE TWORKFLOWSTATION
    ADD CONSTRAINT TWORKFLOWSTATION_FK_2
    FOREIGN KEY (WORKFLOW)
    REFERENCES TWORKFLOWDEF (OBJECTID)
;

ALTER TABLE TWORKFLOWACTIVITY
    ADD CONSTRAINT TWORKFLOWACTIVITY_FK_1
    FOREIGN KEY (TRANSITIONACTIVITY)
    REFERENCES TWORKFLOWTRANSITION (OBJECTID)
;

ALTER TABLE TWORKFLOWACTIVITY
    ADD CONSTRAINT TWORKFLOWACTIVITY_FK_2
    FOREIGN KEY (STATIONENTRYACTIVITY)
    REFERENCES TWORKFLOWSTATION (OBJECTID)
;

ALTER TABLE TWORKFLOWACTIVITY
    ADD CONSTRAINT TWORKFLOWACTIVITY_FK_3
    FOREIGN KEY (STATIONEXITACTIVITY)
    REFERENCES TWORKFLOWSTATION (OBJECTID)
;

ALTER TABLE TWORKFLOWACTIVITY
    ADD CONSTRAINT TWORKFLOWACTIVITY_FK_4
    FOREIGN KEY (STATIONDOACTIVITY)
    REFERENCES TWORKFLOWSTATION (OBJECTID)
;

ALTER TABLE TWORKFLOWACTIVITY
    ADD CONSTRAINT TWORKFLOWACTIVITY_FK_5
    FOREIGN KEY (GROOVYSCRIPT)
    REFERENCES TSCRIPTS (OBJECTID)
;

ALTER TABLE TWORKFLOWACTIVITY
    ADD CONSTRAINT TWORKFLOWACTIVITY_FK_6
    FOREIGN KEY (NEWMAN)
    REFERENCES TPERSON (PKEY)
;

ALTER TABLE TWORKFLOWACTIVITY
    ADD CONSTRAINT TWORKFLOWACTIVITY_FK_7
    FOREIGN KEY (NEWRESP)
    REFERENCES TPERSON (PKEY)
;

ALTER TABLE TWORKFLOWACTIVITY
    ADD CONSTRAINT TWORKFLOWACTIVITY_FK_8
    FOREIGN KEY (SLA)
    REFERENCES TSLA (OBJECTID)
;

ALTER TABLE TWORKFLOWACTIVITY
    ADD CONSTRAINT TWORKFLOWACTIVITY_FK_9
    FOREIGN KEY (SCREEN)
    REFERENCES TSCREEN (OBJECTID)
;

ALTER TABLE TWORKFLOWGUARD
    ADD CONSTRAINT TWORKFLOWGUARD_FK_1
    FOREIGN KEY (WORKFLOWTRANSITION)
    REFERENCES TWORKFLOWTRANSITION (OBJECTID)
;

ALTER TABLE TWORKFLOWGUARD
    ADD CONSTRAINT TWORKFLOWGUARD_FK_2
    FOREIGN KEY (ROLEKEY)
    REFERENCES TROLE (PKEY)
;

ALTER TABLE TWORKFLOWGUARD
    ADD CONSTRAINT TWORKFLOWGUARD_FK_3
    FOREIGN KEY (GROOVYSCRIPT)
    REFERENCES TSCRIPTS (OBJECTID)
;

ALTER TABLE TWORKFLOWGUARD
    ADD CONSTRAINT TWORKFLOWGUARD_FK_4
    FOREIGN KEY (PERSON)
    REFERENCES TPERSON (PKEY)
;

ALTER TABLE TWORKFLOWCONNECT
    ADD CONSTRAINT TWORKFLOWCONNECT_FK_1
    FOREIGN KEY (WORKFLOW)
    REFERENCES TWORKFLOWDEF (OBJECTID)
;

ALTER TABLE TWORKFLOWCONNECT
    ADD CONSTRAINT TWORKFLOWCONNECT_FK_2
    FOREIGN KEY (ISSUETYPE)
    REFERENCES TCATEGORY (PKEY)
;

ALTER TABLE TWORKFLOWCONNECT
    ADD CONSTRAINT TWORKFLOWCONNECT_FK_3
    FOREIGN KEY (PROJECTTYPE)
    REFERENCES TPROJECTTYPE (OBJECTID)
;

ALTER TABLE TWORKFLOWCONNECT
    ADD CONSTRAINT TWORKFLOWCONNECT_FK_4
    FOREIGN KEY (PROJECT)
    REFERENCES TPROJECT (PKEY)
;

ALTER TABLE TESCALATIONENTRY
    ADD CONSTRAINT TESCALATIONENTRY_FK_1
    FOREIGN KEY (SLA)
    REFERENCES TSLA (OBJECTID)
;

ALTER TABLE TESCALATIONENTRY
    ADD CONSTRAINT TESCALATIONENTRY_FK_2
    FOREIGN KEY (PRIORITY)
    REFERENCES TPRIORITY (PKEY)
;

ALTER TABLE TESCALATIONENTRY
    ADD CONSTRAINT TESCALATIONENTRY_FK_3
    FOREIGN KEY (ESCALATETO)
    REFERENCES TPERSON (PKEY)
;

ALTER TABLE TESCALATIONSTATE
    ADD CONSTRAINT TESCALATIONSTATE_FK_1
    FOREIGN KEY (ESCALATIONENTRY)
    REFERENCES TESCALATIONENTRY (OBJECTID)
;

ALTER TABLE TESCALATIONSTATE
    ADD CONSTRAINT TESCALATIONSTATE_FK_2
    FOREIGN KEY (STATUS)
    REFERENCES TSTATE (PKEY)
;

ALTER TABLE TORGPROJECTSLA
    ADD CONSTRAINT TORGPROJECTSLA_FK_1
    FOREIGN KEY (DEPARTMENT)
    REFERENCES TDEPARTMENT (PKEY)
;

ALTER TABLE TORGPROJECTSLA
    ADD CONSTRAINT TORGPROJECTSLA_FK_2
    FOREIGN KEY (PROJECT)
    REFERENCES TPROJECT (PKEY)
;

ALTER TABLE TORGPROJECTSLA
    ADD CONSTRAINT TORGPROJECTSLA_FK_3
    FOREIGN KEY (SLA)
    REFERENCES TSLA (OBJECTID)
;

ALTER TABLE TREADISSUE
    ADD CONSTRAINT TREADISSUE_FK_1
    FOREIGN KEY (WORKITEM)
    REFERENCES TWORKITEM (WORKITEMKEY)
;

ALTER TABLE TREADISSUE
    ADD CONSTRAINT TREADISSUE_FK_2
    FOREIGN KEY (PERSON)
    REFERENCES TPERSON (PKEY)
;

ALTER TABLE TLASTEXECUTEDQUERY
    ADD CONSTRAINT TLASTEXECUTEDQUERY_FK_1
    FOREIGN KEY (PERSON)
    REFERENCES TPERSON (PKEY)
;

ALTER TABLE TLASTEXECUTEDQUERY
    ADD CONSTRAINT TLASTEXECUTEDQUERY_FK_2
    FOREIGN KEY (QUERYCLOB)
    REFERENCES TCLOB (OBJECTID)
;

INSERT INTO TFIELD (OBJECTID, NAME, FIELDTYPE, DEPRECATED, ISCUSTOM, REQUIRED)
			VALUES (27, 'WBS', 'com.aurel.track.fieldType.types.system.text.SystemWBS', 'N', 'N', 'N');
INSERT INTO TFIELDCONFIG(OBJECTID, FIELDKEY, LABEL, TOOLTIP, REQUIRED)
			VALUES (27, 27, 'WBS', 'WBS', 'N');	
INSERT INTO TFIELD (OBJECTID, NAME, FIELDTYPE, DEPRECATED, ISCUSTOM, REQUIRED)
			VALUES (28, 'ProjectSpecificIssueNo', 'com.aurel.track.fieldType.types.system.text.SystemProjectSpecificIssueNo', 'N', 'N', 'N');
INSERT INTO TFIELDCONFIG(OBJECTID, FIELDKEY, LABEL, TOOLTIP, REQUIRED)
			VALUES (28, 28, 'ProjectSpecificIssueNo', 'ProjectSpecificIssueNo', 'N');
INSERT INTO TFIELD (OBJECTID, NAME, FIELDTYPE, DEPRECATED, ISCUSTOM, REQUIRED)
			VALUES (29, 'TargetStartDate', 'com.aurel.track.fieldType.types.system.text.SystemTextBoxTargetDate', 'N', 'N', 'N');
INSERT INTO TFIELDCONFIG(OBJECTID, FIELDKEY, LABEL, TOOLTIP, REQUIRED, HISTORY)
			VALUES (29, 29, 'Start date target', 'Start date target (top-down)', 'N', 'Y');
INSERT INTO TFIELD (OBJECTID, NAME, FIELDTYPE, DEPRECATED, ISCUSTOM, REQUIRED)
			VALUES (30, 'TargetEndDate', 'com.aurel.track.fieldType.types.system.text.SystemTextBoxTargetDate', 'N', 'N', 'N');
INSERT INTO TFIELDCONFIG(OBJECTID, FIELDKEY, LABEL, TOOLTIP, REQUIRED, HISTORY)
			VALUES (30, 30, 'End date target', 'End date target (top-down)', 'N', 'Y');

commit;
