/* MySQL migration script */
/* $Id: migrate350to370.sql 1209 2009-04-23 17:29:16Z tamas $ */

ALTER TABLE TACL ADD TPUUID VARCHAR(36);
CREATE  INDEX TACLINDEX1 ON TACL (TPUUID);

ALTER TABLE TBASELINE ADD TPUUID VARCHAR(36);
CREATE  INDEX TBASINDEX3 ON TBASELINE (TPUUID);

ALTER TABLE TCATEGORY ADD TPUUID VARCHAR(36);
CREATE  INDEX TCATEGORYINDEX1 ON TCATEGORY (TPUUID);

ALTER TABLE TCLASS ADD TPUUID VARCHAR(36);
CREATE  INDEX TCLASSINDEX1 ON TCLASS (TPUUID);

ALTER TABLE TDEPARTMENT ADD TPUUID VARCHAR(36);
CREATE  INDEX TDEPARTMENTINDEX1 ON TDEPARTMENT (TPUUID);

ALTER TABLE TNOTIFY ADD TPUUID VARCHAR(36);
CREATE  INDEX TNOTIFYINDEX1 ON TNOTIFY (TPUUID);

ALTER TABLE TPERSON ADD USERLEVEL INTEGER;
ALTER TABLE TPERSON ADD TPUUID VARCHAR(36);
CREATE  INDEX TPERSINDEX2 ON TPERSON (TPUUID);

ALTER TABLE TPRIORITY ADD TPUUID VARCHAR(36);
CREATE  INDEX TPRIOINDEX1 ON TPRIORITY (TPUUID);

ALTER TABLE TPPRIORITY ADD TPUUID VARCHAR(36);
CREATE  INDEX TPPRIOINDEX1 ON TPPRIORITY (TPUUID);

ALTER TABLE TPROJCAT ADD TPUUID VARCHAR(36);
CREATE  INDEX TPROJCATINDEX2 ON TPROJCAT (TPUUID);

ALTER TABLE TPROJECT ADD TPUUID VARCHAR(36);
CREATE  INDEX TPROJECTINDEX ON TPROJECT (TPUUID);

ALTER TABLE TRELEASE ADD TPUUID VARCHAR(36);
CREATE  INDEX TRELINDEX2 ON TRELEASE (TPUUID);

ALTER TABLE TROLE ADD TPUUID VARCHAR(36);
CREATE  INDEX TROLEINDEX1 ON TROLE (TPUUID);

ALTER TABLE TSEVERITY ADD TPUUID VARCHAR(36);
CREATE  INDEX TSEVINDEX1 ON TSEVERITY (TPUUID);

ALTER TABLE TPSEVERITY ADD TPUUID VARCHAR(36);
CREATE  INDEX TPSEVINDEX1 ON TPSEVERITY (TPUUID);

ALTER TABLE TSTATE ADD TPUUID VARCHAR(36);
CREATE  INDEX TSTATEINDEX1 ON TSTATE (TPUUID);

ALTER TABLE TSTATECHANGE ADD TPUUID VARCHAR(36);
CREATE  INDEX TSTATECHANGEINDEX4 ON TSTATECHANGE (TPUUID);

ALTER TABLE TTRAIL ADD TPUUID VARCHAR(36);
CREATE  INDEX TTRAILINDEX3 ON TTRAIL (TPUUID);

ALTER TABLE TWORKITEM ADD ARCHIVELEVEL INTEGER;
ALTER TABLE TWORKITEM ADD TPUUID VARCHAR(36);
CREATE  INDEX TWIINDEX19 ON TWORKITEM (ARCHIVELEVEL);
CREATE  INDEX TWIINDEX20 ON TWORKITEM (TPUUID);

ALTER TABLE TCOMPUTEDVALUES ADD TPUUID VARCHAR(36);
CREATE  INDEX TCVINDEX1 ON TCOMPUTEDVALUES (TPUUID);

ALTER TABLE TPRIVATEREPORTREPOSITORY ADD TPUUID VARCHAR(36);
CREATE  INDEX TPRIVREPREPINDEX1 ON TPRIVATEREPORTREPOSITORY (TPUUID);

ALTER TABLE TPUBLICREPORTREPOSITORY ADD TPUUID VARCHAR(36);
CREATE  INDEX TPUBREPREPINDEX1 ON TPUBLICREPORTREPOSITORY (TPUUID);

ALTER TABLE TPROJECTREPORTREPOSITORY ADD TPUUID VARCHAR(36);
CREATE  INDEX TPROJREPREPINDEX1 ON TPROJECTREPORTREPOSITORY (TPUUID);

ALTER TABLE TACCOUNT ADD TPUUID VARCHAR(36);
CREATE  INDEX TACCOUNTINDEX1 ON TACCOUNT (TPUUID);

ALTER TABLE TATTACHMENT ADD TPUUID VARCHAR(36);
CREATE  INDEX TATTACHINDEX1 ON TATTACHMENT (TPUUID);

ALTER TABLE TCOST ADD TPUUID VARCHAR(36);
CREATE  INDEX TCOSTINDEX1 ON TCOST (TPUUID);

ALTER TABLE TEFFORTTYPE ADD TPUUID VARCHAR(36);
CREATE  INDEX TEFFORTTYPEINDEX1 ON TEFFORTTYPE (TPUUID);

ALTER TABLE TEFFORTUNIT ADD TPUUID VARCHAR(36);
CREATE  INDEX TEFFORTUNITINDEX1 ON TEFFORTUNIT (TPUUID);

ALTER TABLE TDOCSTATE ADD TPUUID VARCHAR(36);
CREATE  INDEX TDOCSTATEINDEX1 ON TDOCSTATE (TPUUID);

ALTER TABLE TDISABLEFIELD ADD TPUUID VARCHAR(36);
CREATE  INDEX TDISABLEFINDEX1 ON TDISABLEFIELD (TPUUID);

ALTER TABLE TPLISTTYPE ADD TPUUID VARCHAR(36);
CREATE  INDEX TPLISTTYPEINDEX1 ON TPLISTTYPE (TPUUID);

ALTER TABLE TPROJECTTYPE ADD TPUUID VARCHAR(36);
CREATE  INDEX TPROJTYPEINDEX1 ON TPROJECTTYPE (TPUUID);

ALTER TABLE TPSTATE ADD TPUUID VARCHAR(36);
CREATE  INDEX TPSTATEINDEX1 ON TPSTATE (TPUUID);

ALTER TABLE TSITE ADD TPUUID VARCHAR(36);
CREATE  INDEX TSITEINDEX1 ON TSITE (TPUUID);

ALTER TABLE TWORKFLOW ADD TPUUID VARCHAR(36);
CREATE  INDEX TWORKFLOWINDEX1 ON TWORKFLOW (TPUUID);

ALTER TABLE TWORKFLOWROLE ADD TPUUID VARCHAR(36);
CREATE  INDEX TWORKFLOWROLEINDEX1 ON TWORKFLOWROLE (TPUUID);

ALTER TABLE TWORKFLOWCATEGORY ADD TPUUID VARCHAR(36);
CREATE  INDEX TWORKFLOWCATINDEX1 ON TWORKFLOWCATEGORY (TPUUID);

ALTER TABLE TROLELISTTYPE ADD TPUUID VARCHAR(36);
CREATE  INDEX TROLELISTTINDEX1 ON TROLELISTTYPE (TPUUID);

ALTER TABLE TISSUEATTRIBUTEVALUE ADD TPUUID VARCHAR(36);
CREATE  INDEX TISSUEATTINDEX1 ON TISSUEATTRIBUTEVALUE (TPUUID);

ALTER TABLE TATTRIBUTEOPTION ADD TPUUID VARCHAR(36);
CREATE  INDEX TATTOPTINDEX1 ON TATTRIBUTEOPTION (TPUUID);

ALTER TABLE TATTRIBUTECLASS ADD TPUUID VARCHAR(36);
CREATE  INDEX TATTCLASSINDEX1 ON TATTRIBUTECLASS (TPUUID);

ALTER TABLE TATTRIBUTETYPE ADD TPUUID VARCHAR(36);
CREATE  INDEX TATTTYPEINDEX1 ON TATTRIBUTETYPE (TPUUID);

ALTER TABLE TATTRIBUTE ADD TPUUID VARCHAR(36);
CREATE  INDEX TATTRIBUTEINDEX1 ON TATTRIBUTE (TPUUID);

ALTER TABLE TREPORTLAYOUT ADD EXPANDING VARCHAR (1);
ALTER TABLE TREPORTLAYOUT ADD LAYOUTKEY INTEGER;
ALTER TABLE TREPORTLAYOUT ADD TPUUID VARCHAR(36);
CREATE  INDEX TREPORTLAYOUTINDEX1 ON TREPORTLAYOUT (FIELDTYPE);
CREATE  INDEX TREPORTLAYOUTINDEX2 ON TREPORTLAYOUT (LAYOUTKEY);
CREATE  INDEX TREPORTLAYOUTINDEX3 ON TREPORTLAYOUT (TPUUID);

ALTER TABLE TSCHEDULER ADD TPUUID VARCHAR(36);
CREATE  INDEX TSCHEDULERINDEX1 ON TSCHEDULER (TPUUID);

ALTER TABLE TPROJECTACCOUNT ADD TPUUID VARCHAR(36);
CREATE  INDEX TPROJACCINDEX1 ON TPROJECTACCOUNT (TPUUID);

ALTER TABLE TGROUPMEMBER ADD TPUUID VARCHAR(36);
CREATE  INDEX TGROUPMEMINDEX1 ON TGROUPMEMBER (TPUUID);

ALTER TABLE TBUDGET ADD TPUUID VARCHAR(36);
CREATE  INDEX TBUDGETINDEX3 ON TBUDGET (TPUUID);

ALTER TABLE TACTUALESTIMATEDBUDGET ADD TPUUID VARCHAR(36);
CREATE  INDEX TACTUALESTINDEX3 ON TACTUALESTIMATEDBUDGET (TPUUID);

ALTER TABLE TSYSTEMSTATE ADD TPUUID VARCHAR(36);
CREATE  INDEX TSYSTEMSTATEINDEX1 ON TSYSTEMSTATE (TPUUID);

ALTER TABLE TCOSTCENTER ADD TPUUID VARCHAR(36);
CREATE  INDEX TCOSTCENTERINDEX1 ON TCOSTCENTER (TPUUID);

ALTER TABLE TMOTD ADD TPUUID VARCHAR(36);
CREATE  INDEX TMOTDINDEX1 ON TMOTD (TPUUID);

ALTER TABLE TDASHBOARDSCREEN ADD TPUUID VARCHAR(36);
CREATE  INDEX TDBSCREENINDEX1 ON TDASHBOARDSCREEN (TPUUID);

ALTER TABLE TDASHBOARDTAB ADD TPUUID VARCHAR(36);
CREATE  INDEX TDBTABINDEX1 ON TDASHBOARDTAB (TPUUID);

ALTER TABLE TDASHBOARDPANEL ADD TPUUID VARCHAR(36);
CREATE  INDEX TDBPANELINDEX1 ON TDASHBOARDPANEL (TPUUID);

ALTER TABLE TDASHBOARDFIELD ADD TPUUID VARCHAR(36);
CREATE  INDEX TDBFIELDINDEX1 ON TDASHBOARDFIELD (TPUUID);

ALTER TABLE TDASHBOARDPARAMETER ADD TPUUID VARCHAR(36);
CREATE  INDEX TDBPARAMINDEX1 ON TDASHBOARDPARAMETER (TPUUID);

ALTER TABLE TVERSIONCONTROLPARAMETER ADD TPUUID VARCHAR(36);
CREATE  INDEX TVCPARAMINDEX1 ON TVERSIONCONTROLPARAMETER (TPUUID);

ALTER TABLE TFIELD ADD TPUUID VARCHAR(36);
CREATE  INDEX TFIELDINDEX1 ON TFIELD (TPUUID);

ALTER TABLE TFIELDCONFIG ADD TPUUID VARCHAR(36);
CREATE  INDEX TFIELDCONFIGINDEX1 ON TFIELDCONFIG (TPUUID);

ALTER TABLE TROLEFIELD ADD TPUUID VARCHAR(36);
CREATE  INDEX TROLEFIELDINDEX1 ON TROLEFIELD (TPUUID);

ALTER TABLE TCONFIGOPTIONSROLE ADD TPUUID VARCHAR(36);
CREATE  INDEX TCONFIGOPTINDEX1 ON TCONFIGOPTIONSROLE (TPUUID);

ALTER TABLE TTEXTBOXSETTINGS ADD TPUUID VARCHAR(36);
CREATE  INDEX TTEXTBOXCONFINDEX1 ON TTEXTBOXSETTINGS (TPUUID);

ALTER TABLE TGENERALSETTINGS ADD TPUUID VARCHAR(36);
CREATE  INDEX TGENERALCONFINDEX1 ON TGENERALSETTINGS (TPUUID);

ALTER TABLE TLIST ADD TPUUID VARCHAR(36);
CREATE  INDEX TLISTINDEX1 ON TLIST (TPUUID);

ALTER TABLE TOPTION ADD TPUUID VARCHAR(36);
CREATE  INDEX TOPTIONINDEX1 ON TOPTION (TPUUID);

ALTER TABLE TOPTIONSETTINGS ADD TPUUID VARCHAR(36);
CREATE  INDEX TOPTIONCONFINDEX1 ON TOPTIONSETTINGS (TPUUID);

ALTER TABLE TATTRIBUTEVALUE ADD TPUUID VARCHAR(36);
CREATE  INDEX TATTVALUEINDEX1 ON TATTRIBUTEVALUE (TPUUID);

ALTER TABLE TSCREEN ADD TPUUID VARCHAR(36);
CREATE  INDEX TSCREENINDEX1 ON TSCREEN (TPUUID);

ALTER TABLE TSCREENTAB ADD TPUUID VARCHAR(36);
CREATE  INDEX TSCREENTABINDEX1 ON TSCREENTAB (TPUUID);

ALTER TABLE TSCREENPANEL ADD TPUUID VARCHAR(36);
CREATE  INDEX TSCREENPANELINDEX1 ON TSCREENPANEL (TPUUID);

ALTER TABLE TSCREENFIELD ADD TPUUID VARCHAR(36);
CREATE  INDEX TSCREENFIELDINDEX1 ON TSCREENFIELD (TPUUID);

ALTER TABLE TACTION ADD TPUUID VARCHAR(36);
CREATE  INDEX TACTIONINDEX1 ON TACTION (TPUUID);

ALTER TABLE TSCREENCONFIG ADD TPUUID VARCHAR(36);
CREATE  INDEX TSCREENCONFINDEX1 ON TSCREENCONFIG (TPUUID);

ALTER TABLE TINITSTATE ADD TPUUID VARCHAR(36);
CREATE  INDEX TINITSTATEINDEX1 ON TINITSTATE (TPUUID);

ALTER TABLE TEVENT ADD TPUUID VARCHAR(36);
CREATE  INDEX TEVENTINDEX1 ON TEVENT (TPUUID);

ALTER TABLE TCLOB ADD TPUUID VARCHAR(36);
CREATE  INDEX TCLOBINDEX1 ON TCLOB (TPUUID);

ALTER TABLE TNOTIFYFIELD ADD TPUUID VARCHAR(36);
CREATE  INDEX TNOTIFYFIELDINDEX1 ON TNOTIFYFIELD (TPUUID);

ALTER TABLE TNOTIFYTRIGGER ADD TPUUID VARCHAR(36);
CREATE  INDEX TNOTIFYTRIGGERINDEX1 ON TNOTIFYTRIGGER (TPUUID);

ALTER TABLE TNOTIFYSETTINGS ADD TPUUID VARCHAR(36);
CREATE  INDEX TNOTIFYCONFINDEX1 ON TNOTIFYSETTINGS (TPUUID);

ALTER TABLE TQUERYREPOSITORY ADD TPUUID VARCHAR(36);
CREATE  INDEX TQUERYREPINDEX1 ON TQUERYREPOSITORY (TPUUID);

ALTER TABLE TLOCALIZEDRESOURCES ADD TPUUID VARCHAR(36);
CREATE  INDEX TLOCALRESINDEX1 ON TLOCALIZEDRESOURCES (TPUUID);

# -----------------------------------------------------------------------
# TWORKITEMLINK
# -----------------------------------------------------------------------
drop table if exists TWORKITEMLINK;

CREATE TABLE TWORKITEMLINK
(
    OBJECTID INTEGER NOT NULL,
    LINKISCROSSPROJECT CHAR(1) default 'N',
    LINKPRED INTEGER NOT NULL,
    LINKSUCC INTEGER,
    LINKTYPE INTEGER NOT NULL,
	LINKDIRECTION INTEGER,
    LINKLAG DOUBLE,
    LINKLAGFORMAT INTEGER,
    STRINGVALUE1 VARCHAR(255),
    STRINGVALUE2 VARCHAR(255),
    STRINGVALUE3 VARCHAR(255),
    INTEGERVALUE1 INTEGER,
    INTEGERVALUE2 INTEGER,
    INTEGERVALUE3 INTEGER,
    DATEVALUE DATETIME,
    DESCRIPTION MEDIUMTEXT,
    EXTERNALLINK VARCHAR(255),
	CHANGEDBY INTEGER,
    LASTEDIT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    TPUUID VARCHAR(36),
    PRIMARY KEY(OBJECTID),
    INDEX TWORKITEMLINKINDEX1 (TPUUID));

# -----------------------------------------------------------------------
# TLINKTYPE
# -----------------------------------------------------------------------
drop table if exists TLINKTYPE;

CREATE TABLE TLINKTYPE
(
    OBJECTID INTEGER NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    REVERSENAME VARCHAR(255),
    LEFTTORIGHTFIRST VARCHAR(255),
    LEFTTORIGHTLEVEL VARCHAR(255),
    LEFTTORIGHTALL VARCHAR(255),
    RIGHTTOLEFTFIRST VARCHAR(255),
    RIGHTTOLEFTLEVEL VARCHAR(255),
    RIGHTTOLEFTALL VARCHAR(255),
    LINKDIRECTION INTEGER,
    LINKTYPEPLUGIN VARCHAR(255),
    MOREPROPS MEDIUMTEXT,
    TPUUID VARCHAR(36),
    PRIMARY KEY(OBJECTID),
    INDEX TLINKTYPEINDEX1 (TPUUID));

ALTER TABLE TLOGGINGLEVEL ADD TPUUID VARCHAR(36);
CREATE  INDEX TLOGLEVELINDEX1 ON TLOGGINGLEVEL (TPUUID);

ALTER TABLE TWORKITEMLOCK ADD TPUUID VARCHAR(36);
CREATE  INDEX TWORKITEMLOCKINDEX1 ON TWORKITEMLOCK (TPUUID);

ALTER TABLE TEXPORTTEMPLATE ADD TPUUID VARCHAR(36);
CREATE  INDEX TEXPOPRTTEMPINDEX1 ON TEXPORTTEMPLATE (TPUUID);

ALTER TABLE TEMAILPROCESSED ADD TPUUID VARCHAR(36);
CREATE  INDEX TEMAILPROCINDEX1 ON TEMAILPROCESSED (TPUUID);

# -----------------------------------------------------------------------
# TAPPLICATIONCONTEXT
# -----------------------------------------------------------------------
drop table if exists TAPPLICATIONCONTEXT;

CREATE TABLE TAPPLICATIONCONTEXT
(
    OBJECTID INTEGER NOT NULL,
    LOGGEDFULLUSERS INTEGER,
    LOGGEDLIMITEDUSERS INTEGER,
    REFRESHCONFIGURATION INTEGER default 0 NOT NULL,
    FIRSTTIME INTEGER default 0 NOT NULL,
    MOREPROPS MEDIUMTEXT,
    PRIMARY KEY(OBJECTID)
);


# -------------------------------------------------------------------------
# TLOGGEDINUSERS
# -------------------------------------------------------------------------
drop table if exists TLOGGEDINUSERS;

CREATE TABLE TLOGGEDINUSERS
(
    OBJECTID INTEGER NOT NULL,
    NODEADDRESS INTEGER,
    SESSIONID VARCHAR (255),
    LOGGEDUSER INTEGER NOT NULL,
    USERLEVEL INTEGER,
    LASTUPDATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MOREPROPS MEDIUMTEXT,
    PRIMARY KEY(OBJECTID)
);


# -----------------------------------------------------------------------
# CLUSTERNODE
# -----------------------------------------------------------------------
drop table if exists CLUSTERNODE;

CREATE TABLE CLUSTERNODE
(
    OBJECTID INTEGER NOT NULL,
    NODEADDRESS VARCHAR (40),
    NODEURL VARCHAR (255),
    LASTUPDATE TIMESTAMP,
    MASTERNODE INTEGER default 0,
	RELOADCONFIG INTEGER default 0,
    PRIMARY KEY(OBJECTID));

# -----------------------------------------------------------------------
# TENTITYCHANGES
# -----------------------------------------------------------------------
drop table if exists TENTITYCHANGES;

CREATE TABLE TENTITYCHANGES
(
    OBJECTID INTEGER NOT NULL,
    ENTITYKEY INTEGER NOT NULL,
    ENTITYTYPE INTEGER NOT NULL,
    CLUSTERNODE INTEGER,
    PRIMARY KEY(OBJECTID),
    INDEX ENTITYCHANGESINDEX1 (ENTITYTYPE),
    INDEX ENTITYCHANGESINDEX2 (CLUSTERNODE));

# -----------------------------------------------------------------------
# TSUMMARYMAIL
# -----------------------------------------------------------------------
drop table if exists TSUMMARYMAIL;

CREATE TABLE TSUMMARYMAIL
(
    OBJECTID INTEGER NOT NULL,
    WORKITEM INTEGER NOT NULL,
    PERSONFROM INTEGER NOT NULL,
    FROMADDRESS VARCHAR (255),
    MAILSUBJECT VARCHAR (255),
    WORKITEMLINK VARCHAR (255),
    PERSONTO INTEGER NOT NULL,
    LASTEDIT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    TPUUID VARCHAR (36),
    PRIMARY KEY(OBJECTID),
    INDEX TSUMMARYMAILINDEX1 (WORKITEM),
    INDEX TSUMMARYMAILINDEX2 (PERSONFROM),
    INDEX TSUMMARYMAILINDEX3 (PERSONTO),
    INDEX TSUMMARYMAILINDEX4 (TPUUID));


# -----------------------------------------------------------------------
# TOUTLINECODE
# -----------------------------------------------------------------------
drop table if exists TOUTLINECODE;

CREATE TABLE TOUTLINECODE
(
    OBJECTID INTEGER NOT NULL,
    PARENTID INTEGER,
    LEVELNO INTEGER NOT NULL,
    LEVELCODE VARCHAR (50) NOT NULL,
    FULLCODE VARCHAR (255) NOT NULL,
    ENTITYID INTEGER NOT NULL,
    OUTLINETEMPLATE INTEGER NOT NULL,
    TPUUID VARCHAR (36),
    PRIMARY KEY(OBJECTID),
    INDEX TOUTLINECODEINDEX1 (PARENTID),
    INDEX TOUTLINECODEINDEX2 (ENTITYID),
    INDEX TOUTLINECODEINDEX3 (TPUUID));


# -----------------------------------------------------------------------
# TOUTLINETEMPLATEDEF
# -----------------------------------------------------------------------
drop table if exists TOUTLINETEMPLATEDEF;

CREATE TABLE TOUTLINETEMPLATEDEF
(
    OBJECTID INTEGER NOT NULL,
    LEVELNO INTEGER NOT NULL,
    SEQUENCETYPE INTEGER NOT NULL,
    LISTID INTEGER,
    SEQUENCELENGTH INTEGER NOT NULL,
    SEPARATORCHAR VARCHAR (10) NOT NULL,
    OUTLINETEMPLATE INTEGER NOT NULL,
    TPUUID VARCHAR (36),
    PRIMARY KEY(OBJECTID),
    INDEX TOUTLINETEMPLATEDEFINDEX1 (TPUUID));


# -----------------------------------------------------------------------
# TOUTLINETEMPLATE
# -----------------------------------------------------------------------
drop table if exists TOUTLINETEMPLATE;

CREATE TABLE TOUTLINETEMPLATE
(
    OBJECTID INTEGER NOT NULL,
    LABEL VARCHAR (255) NOT NULL,
    ENTITYTYPE INTEGER NOT NULL,
    TPUUID VARCHAR (36),
    PRIMARY KEY(OBJECTID),
    INDEX TOUTLINETEMPLATEINDEX1 (TPUUID));


# -----------------------------------------------------------------------
# THISTORYTRANSACTION
# -----------------------------------------------------------------------
drop table if exists THISTORYTRANSACTION;

CREATE TABLE THISTORYTRANSACTION
(
    OBJECTID INTEGER NOT NULL,
    WORKITEM INTEGER NOT NULL,
    CHANGEDBY INTEGER NOT NULL,
    LASTEDIT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    TPUUID VARCHAR (36),
    PRIMARY KEY(OBJECTID),
    INDEX THISTORYTRANSINDEX1 (WORKITEM),
    INDEX THISTORYTRANSINDEX2 (CHANGEDBY),
    INDEX THISTORYTRANSINDEX3 (TPUUID));


# -----------------------------------------------------------------------
# TFIELDCHANGE
# -----------------------------------------------------------------------
drop table if exists TFIELDCHANGE;

CREATE TABLE TFIELDCHANGE
(
    OBJECTID INTEGER NOT NULL,
    FIELDKEY INTEGER NOT NULL,
    HISTORYTRANSACTION INTEGER NOT NULL,
    NEWTEXTVALUE VARCHAR (255),
    OLDTEXTVALUE VARCHAR (255),
    NEWINTEGERVALUE INTEGER,
    OLDINTEGERVALUE INTEGER,
    NEWDOUBLEVALUE DOUBLE,
    OLDDOUBLEVALUE DOUBLE,
    NEWDATEVALUE DATETIME,
    OLDDATEVALUE DATETIME,
    NEWCHARACTERVALUE CHAR (1),
    OLDCHARACTERVALUE CHAR (1),
    NEWLONGTEXTVALUE MEDIUMTEXT,
    OLDLONGTEXTVALUE MEDIUMTEXT,
    NEWSYSTEMOPTIONID INTEGER,
    OLDSYSTEMOPTIONID INTEGER,
    SYSTEMOPTIONTYPE INTEGER,
    NEWCUSTOMOPTIONID INTEGER,
    OLDCUSTOMOPTIONID INTEGER,
    PARAMETERCODE INTEGER,
    VALIDVALUE INTEGER,
    PARENTCOMMENT INTEGER,
    TIMESEDITED INTEGER,
    TPUUID VARCHAR (36),
    PRIMARY KEY(OBJECTID),
    INDEX TFIELDCHANGE1 (FIELDKEY),
    INDEX TFIELDCHANGE2 (HISTORYTRANSACTION),
    INDEX TFIELDCHANGE3 (VALIDVALUE),
    INDEX TFIELDCHANGE4 (TPUUID));

# -----------------------------------------------------------------------
# TSCRIPTS
# -----------------------------------------------------------------------
drop table if exists TSCRIPTS;

CREATE TABLE TSCRIPTS
(
    OBJECTID INTEGER NOT NULL,
    CHANGEDBY INTEGER,
    LASTEDIT TIMESTAMP,
    SCRIPTVERSION INTEGER,
    ORIGINALVERSION INTEGER,
    PROJECTTYPE INTEGER,
    PROJECT INTEGER,
    SCRIPTTYPE INTEGER,
    CLAZZNAME VARCHAR(253),
    SOURCECODE MEDIUMTEXT,
    TPUUID VARCHAR(36),
    PRIMARY KEY(OBJECTID),
    INDEX TSCRIPTINDEX1 (CLAZZNAME),
    INDEX TSCRIPTINDEX2 (PROJECTTYPE),
    INDEX TSCRIPTINDEX3 (PROJECT),
    INDEX TSCRIPTINDEX4 (TPUUID));



# -----------------------------------------------------------------------
# TREVISION
# -----------------------------------------------------------------------
drop table if exists TREVISION;

CREATE TABLE TREVISION
(
    OBJECTID INTEGER NOT NULL,
    FILENAME VARCHAR(255) NOT NULL,
    AUTHORNAME VARCHAR(255) NOT NULL,
    CHANGEDESCRIPTION MEDIUMTEXT,
    REVISIONDATE TIMESTAMP NOT NULL,
    REVISIONNUMBR VARCHAR(255) NOT NULL,
    REPOSITORYKEY INTEGER NOT NULL,
    TPUUID VARCHAR(36),
    PRIMARY KEY(OBJECTID),
	INDEX TREVISIONINDEX1 (TPUUID));

# -----------------------------------------------------------------------
# TREVISIONWORKITEMS
# -----------------------------------------------------------------------
drop table if exists TREVISIONWORKITEMS;

CREATE TABLE TREVISIONWORKITEMS
(
    OBJECTID INTEGER NOT NULL,
    WORKITEMKEY INTEGER NOT NULL,
    REVISIONKEY INTEGER NOT NULL,
    TPUUID VARCHAR(36),
    PRIMARY KEY(OBJECTID),
	INDEX TREVISIONWORKITEMSINDEX1 (WORKITEMKEY),
    INDEX TREVISIONWORKITEMSINDEX2 (TPUUID));


# -----------------------------------------------------------------------
# TREPOSITORY
# -----------------------------------------------------------------------
drop table if exists TREPOSITORY;

CREATE TABLE TREPOSITORY
(
    OBJECTID INTEGER NOT NULL,
    REPOSITORYTYPE VARCHAR(255) NOT NULL,
    REPOSITORYURL VARCHAR(255) NOT NULL,
    STARTDATE TIMESTAMP,
    ENDDATE TIMESTAMP,
    STATUSKEY INTEGER NOT NULL,
    TPUUID VARCHAR(36),
    PRIMARY KEY(OBJECTID),
 	INDEX TREPOSITORYINDEX1 (TPUUID));

# -----------------------------------------------------------------------
# TTEMPLATEPERSON
# -----------------------------------------------------------------------
drop table if exists TTEMPLATEPERSON;

CREATE TABLE TTEMPLATEPERSON
(
    OBJECTID INTEGER NOT NULL,
    REPORTTEMPLATE INTEGER NOT NULL,
    PERSON INTEGER NOT NULL,
    RIGHTFLAG INTEGER,
    TPUUID VARCHAR(36),
    PRIMARY KEY(OBJECTID),
    INDEX TTEMPLATEPERSONINDEX1 (TPUUID));

ALTER TABLE TWORKITEMLINK
    ADD CONSTRAINT TWORKITEMLINK_FK_1
    FOREIGN KEY (LINKPRED)
    REFERENCES TWORKITEM (WORKITEMKEY)
;

ALTER TABLE TWORKITEMLINK
    ADD CONSTRAINT TWORKITEMLINK_FK_2
    FOREIGN KEY (LINKSUCC)
    REFERENCES TWORKITEM (WORKITEMKEY)
;

ALTER TABLE TWORKITEMLINK
    ADD CONSTRAINT TWORKITEMLINK_FK_3
    FOREIGN KEY (LINKTYPE)
    REFERENCES TLINKTYPE (OBJECTID)
;

ALTER TABLE TWORKITEMLINK
    ADD CONSTRAINT TWORKITEMLINK_FK_4
    FOREIGN KEY (CHANGEDBY)
    REFERENCES TPERSON (PKEY)
;

ALTER TABLE TLOGGEDINUSERS
    ADD CONSTRAINT TLOGGEDINUSERS_FK_1
    FOREIGN KEY (LOGGEDUSER)
    REFERENCES TPERSON (PKEY)
;

ALTER TABLE TLOGGEDINUSERS
    ADD CONSTRAINT TLOGGEDINUSERS_FK_2
    FOREIGN KEY (NODEADDRESS)
    REFERENCES CLUSTERNODE (OBJECTID)
;

ALTER TABLE TENTITYCHANGES
    ADD CONSTRAINT TENTITYCHANGES_FK_1
    FOREIGN KEY (CLUSTERNODE)
    REFERENCES CLUSTERNODE (OBJECTID)
;
ALTER TABLE TSUMMARYMAIL
    ADD CONSTRAINT TSUMMARYMAIL_FK_1
    FOREIGN KEY (WORKITEM)
    REFERENCES TWORKITEM (WORKITEMKEY)
;

ALTER TABLE TSUMMARYMAIL
    ADD CONSTRAINT TSUMMARYMAIL_FK_2
    FOREIGN KEY (PERSONFROM)
    REFERENCES TPERSON (PKEY)
;

ALTER TABLE TSUMMARYMAIL
    ADD CONSTRAINT TSUMMARYMAIL_FK_3
    FOREIGN KEY (PERSONTO)
    REFERENCES TPERSON (PKEY)
;

ALTER TABLE TOUTLINECODE
    ADD CONSTRAINT TOUTLINECODE_FK_1
    FOREIGN KEY (OUTLINETEMPLATE)
    REFERENCES TOUTLINETEMPLATE (OBJECTID)
;

ALTER TABLE TOUTLINETEMPLATEDEF
    ADD CONSTRAINT TOUTLINETEMPLATEDEF_FK_1
    FOREIGN KEY (OUTLINETEMPLATE)
    REFERENCES TOUTLINETEMPLATE (OBJECTID)
;

ALTER TABLE THISTORYTRANSACTION
    ADD CONSTRAINT THISTORYTRANSACTION_FK_1
    FOREIGN KEY (WORKITEM)
    REFERENCES TWORKITEM (WORKITEMKEY)
;

ALTER TABLE THISTORYTRANSACTION
    ADD CONSTRAINT THISTORYTRANSACTION_FK_2
    FOREIGN KEY (CHANGEDBY)
    REFERENCES TPERSON (PKEY)
;

ALTER TABLE TFIELDCHANGE
    ADD CONSTRAINT TFIELDCHANGE_FK_1
    FOREIGN KEY (HISTORYTRANSACTION)
    REFERENCES THISTORYTRANSACTION (OBJECTID)
;

ALTER TABLE TFIELDCHANGE
    ADD CONSTRAINT TFIELDCHANGE_FK_2
    FOREIGN KEY (PARENTCOMMENT)
    REFERENCES TFIELDCHANGE (OBJECTID)
;

ALTER TABLE TFIELDCHANGE
    ADD CONSTRAINT TFIELDCHANGE_FK_3
    FOREIGN KEY (NEWCUSTOMOPTIONID)
    REFERENCES TOPTION (OBJECTID)
;

ALTER TABLE TFIELDCHANGE
    ADD CONSTRAINT TFIELDCHANGE_FK_4
    FOREIGN KEY (OLDCUSTOMOPTIONID)
    REFERENCES TOPTION (OBJECTID)
;

ALTER TABLE TSCRIPTS
    ADD CONSTRAINT TSCRIPTS_FK_1
    FOREIGN KEY (CHANGEDBY)
    REFERENCES TPERSON (PKEY)
;

ALTER TABLE TSCRIPTS
    ADD CONSTRAINT TSCRIPTS_FK_2
    FOREIGN KEY (PROJECTTYPE)
    REFERENCES TPROJECTTYPE (OBJECTID)
;

ALTER TABLE TSCRIPTS
    ADD CONSTRAINT TSCRIPTS_FK_3
    FOREIGN KEY (PROJECT)
    REFERENCES TPROJECT (PKEY)
;

ALTER TABLE TREVISION
    ADD CONSTRAINT TREVISION_FK_1
    FOREIGN KEY (REPOSITORYKEY)
    REFERENCES TREPOSITORY (OBJECTID)
;

ALTER TABLE TREVISIONWORKITEMS
    ADD CONSTRAINT TREVISIONWORKITEMS_FK_1
    FOREIGN KEY (REVISIONKEY)
    REFERENCES TREVISION (OBJECTID)
;

ALTER TABLE TTEMPLATEPERSON
    ADD CONSTRAINT TTEMPLATEPERSON_FK_1
    FOREIGN KEY (PERSON)
    REFERENCES TPERSON (PKEY)
;

ALTER TABLE TTEMPLATEPERSON
    ADD CONSTRAINT TTEMPLATEPERSON_FK_2
    FOREIGN KEY (REPORTTEMPLATE)
    REFERENCES TEXPORTTEMPLATE (OBJECTID)
;

ALTER TABLE TCATEGORY ADD ICONKEY INTEGER;
ALTER TABLE TPRIORITY ADD ICONKEY INTEGER;
ALTER TABLE TSEVERITY ADD ICONKEY INTEGER;
ALTER TABLE TSTATE ADD ICONKEY INTEGER;
ALTER TABLE TOPTION ADD ICONKEY INTEGER;
ALTER TABLE TLINKTYPE ADD OUTWARDICONKEY INTEGER;
ALTER TABLE TLINKTYPE ADD INWARDICONKEY INTEGER;

# -----------------------------------------------------------------------
# TBLOB
# -----------------------------------------------------------------------
drop table if exists TBLOB;

CREATE TABLE TBLOB
(
    OBJECTID INTEGER NOT NULL,
    BLOBVALUE LONGBLOB,
    TPUUID VARCHAR(36),
    PRIMARY KEY(OBJECTID),
    INDEX TBLOBINDEX1 (TPUUID));


ALTER TABLE TCATEGORY
    ADD CONSTRAINT TCATEGORY_FK_1 FOREIGN KEY (ICONKEY)
    REFERENCES TBLOB (OBJECTID)
;

ALTER TABLE TPRIORITY
    ADD CONSTRAINT TPRIORITY_FK_1 FOREIGN KEY (ICONKEY)
    REFERENCES TBLOB (OBJECTID)
;

ALTER TABLE TSEVERITY
    ADD CONSTRAINT TSEVERITY_FK_1 FOREIGN KEY (ICONKEY)
    REFERENCES TBLOB (OBJECTID)
;

ALTER TABLE TSTATE
    ADD CONSTRAINT TSTATE_FK_1 FOREIGN KEY (ICONKEY)
    REFERENCES TBLOB (OBJECTID)
;

ALTER TABLE TOPTION
    ADD CONSTRAINT TOPTION_FK_2 FOREIGN KEY (ICONKEY)
    REFERENCES TBLOB (OBJECTID)
;

ALTER TABLE TLINKTYPE
    ADD CONSTRAINT TLINKTYPE_FK_1 FOREIGN KEY (OUTWARDICONKEY)
    REFERENCES TBLOB (OBJECTID)
;

ALTER TABLE TLINKTYPE
    ADD CONSTRAINT TLINKTYPE_FK_2 FOREIGN KEY (INWARDICONKEY)
    REFERENCES TBLOB (OBJECTID)
;


ALTER TABLE TPROJECT ADD PREFIX VARCHAR(10);
ALTER TABLE TPROJECT ADD LASTID INTEGER;

ALTER TABLE TPROJECT ADD INDEX TPROJECTINDEXIDPF (PREFIX);

ALTER TABLE TWORKITEM ADD IDNUMBER INTEGER;

ALTER TABLE TWORKITEM ADD INDEX TWIINDEX21 (IDNUMBER);

INSERT INTO ID_TABLE (ID_TABLE_ID, TABLE_NAME, NEXT_ID, QUANTITY) VALUES(90, 'TAPPLICATIONCONTEXT', 1, 1);
INSERT INTO ID_TABLE (ID_TABLE_ID, TABLE_NAME, NEXT_ID, QUANTITY) VALUES(91, 'TLOGGEDINUSERS', 1, 1);
INSERT INTO ID_TABLE (ID_TABLE_ID, TABLE_NAME, NEXT_ID, QUANTITY) VALUES(92, 'TEMAILCONNECTIONPOINT', 1, 1);
INSERT INTO ID_TABLE (ID_TABLE_ID, TABLE_NAME, NEXT_ID, QUANTITY) VALUES(93, 'CLUSTERNODE', 1, 1);
INSERT INTO ID_TABLE (ID_TABLE_ID, TABLE_NAME, NEXT_ID, QUANTITY) VALUES(94, 'TSUMMARYMAIL', 1, 1);
INSERT INTO ID_TABLE (ID_TABLE_ID, TABLE_NAME, NEXT_ID, QUANTITY) VALUES(95, 'TOUTLINECODE', 1, 1);
INSERT INTO ID_TABLE (ID_TABLE_ID, TABLE_NAME, NEXT_ID, QUANTITY) VALUES(96, 'TOUTLINETEMPLATEDEF', 1, 1);
INSERT INTO ID_TABLE (ID_TABLE_ID, TABLE_NAME, NEXT_ID, QUANTITY) VALUES(97, 'TOUTLINETEMPLATE', 1, 1);
INSERT INTO ID_TABLE (ID_TABLE_ID, TABLE_NAME, NEXT_ID, QUANTITY) VALUES(98, 'THISTORYTRANSACTION', 1, 1);
INSERT INTO ID_TABLE (ID_TABLE_ID, TABLE_NAME, NEXT_ID, QUANTITY) VALUES(99, 'TFIELDCHANGE', 1, 1);
INSERT INTO ID_TABLE (ID_TABLE_ID, TABLE_NAME, NEXT_ID, QUANTITY) VALUES(100, 'TSCRIPTS', 1, 1);
INSERT INTO ID_TABLE (ID_TABLE_ID, TABLE_NAME, NEXT_ID, QUANTITY) VALUES(101, 'TREVISION', 1, 1);
INSERT INTO ID_TABLE (ID_TABLE_ID, TABLE_NAME, NEXT_ID, QUANTITY) VALUES(102, 'TREVISIONWORKITEMS', 1, 1);
INSERT INTO ID_TABLE (ID_TABLE_ID, TABLE_NAME, NEXT_ID, QUANTITY) VALUES(103, 'TREPOSITORY', 1, 1);
INSERT INTO ID_TABLE (ID_TABLE_ID, TABLE_NAME, NEXT_ID, QUANTITY) VALUES(104, 'TTEMPLATEPERSON', 1, 1);
INSERT INTO ID_TABLE (ID_TABLE_ID, TABLE_NAME, NEXT_ID, QUANTITY) VALUES(105, 'TBLOB', 1, 1);

INSERT INTO TFIELD (OBJECTID, NAME, FIELDTYPE, DEPRECATED, ISCUSTOM, REQUIRED)
			VALUES (25, 'ArchiveLevel', 'com.aurel.track.fieldType.types.system.text.SystemArchiveLevel', 'N', 'N', 'N');
INSERT INTO TFIELDCONFIG(OBJECTID, FIELDKEY, LABEL, TOOLTIP, REQUIRED)
			VALUES (25, 25, 'ArchiveLevel', 'ArchiveLevel', 'N');
INSERT INTO TFIELD (OBJECTID, NAME, FIELDTYPE, DEPRECATED, ISCUSTOM, REQUIRED)
			VALUES (26, 'SubmitterEmail', 'com.aurel.track.fieldType.types.system.text.SystemSubmitterEmail', 'N', 'N', 'N');
INSERT INTO TFIELDCONFIG(OBJECTID, FIELDKEY, LABEL, TOOLTIP, REQUIRED)
			VALUES (26, 26, 'SubmitterEmail', 'SubmitterEmail', 'N');

INSERT INTO TLINKTYPE (OBJECTID, NAME, REVERSENAME, LEFTTORIGHTFIRST, RIGHTTOLEFTFIRST, LINKDIRECTION, LINKTYPEPLUGIN) 
	VALUES	(1, 'duplicate of', 'duplicated by', 'duplicates of these issues', 'duplicated by these issues', 3, 'com.aurel.track.linkType.GenericLinkType');
INSERT INTO TLINKTYPE (OBJECTID, NAME, REVERSENAME, LEFTTORIGHTFIRST, RIGHTTOLEFTFIRST, LINKDIRECTION, LINKTYPEPLUGIN) 
	VALUES	(2, 'test case for', 'verified by', 'test cases for these issues', 'verified by these issues', 3, 'com.aurel.track.linkType.GenericLinkType');
COMMIT;
