# -----------------------------------------------------------------------
# TDOMAIN
# -----------------------------------------------------------------------
drop table if exists TDOMAIN;

CREATE TABLE TDOMAIN
(
    OBJECTID INTEGER NOT NULL,
    LABEL VARCHAR(255),
    DESCRIPTION MEDIUMTEXT,
    TPUUID VARCHAR(36),
    PRIMARY KEY(OBJECTID),
    INDEX TDOMAININDEX1 (TPUUID));
  
ALTER TABLE TPERSON ADD HOURLYWAGE DOUBLE;
ALTER TABLE TPERSON ADD EXTRAHOURWAGE DOUBLE;
ALTER TABLE TWORKITEM ADD OVERBUDGET CHAR(1) default 'N';
ALTER TABLE TSCREENFIELD ADD ICONRENDERING INTEGER;
ALTER TABLE TWORKITEMLINK ADD SORTORDER INTEGER;
    
    
ALTER TABLE TCATEGORY ADD TOOLTIP VARCHAR(255);
ALTER TABLE TDEPARTMENT ADD DOMAINKEY INTEGER;
ALTER TABLE TDEPARTMENT
    ADD CONSTRAINT TDEPARTMENT_FK_2
    FOREIGN KEY (DOMAINKEY)
    REFERENCES TDOMAIN (OBJECTID);
ALTER TABLE TPRIORITY ADD TOOLTIP VARCHAR(255);
ALTER TABLE TPROJECT ADD SORTORDER INTEGER;
ALTER TABLE TPROJECT ADD ISTEMPLATE CHAR(1) default 'N';
ALTER TABLE TPROJECT ADD DOMAINKEY INTEGER;
CREATE INDEX TPROJECTINDEX2 ON TPROJECT(SORTORDER);
ALTER TABLE TPROJECT
    ADD CONSTRAINT TPROJECT_FK_7
    FOREIGN KEY (DOMAINKEY)
    REFERENCES TDOMAIN (OBJECTID);
ALTER TABLE TSEVERITY ADD TOOLTIP VARCHAR(255);
ALTER TABLE TSTATE ADD TOOLTIP VARCHAR(255);
ALTER TABLE TATTACHMENT ADD ISURL CHAR(1) default 'N';
ALTER TABLE TFIELD ADD PROJECTTYPE INTEGER;
ALTER TABLE TFIELD ADD PROJECT INTEGER;
ALTER TABLE TFIELD
    ADD CONSTRAINT TFIELD_FK_2
    FOREIGN KEY (PROJECTTYPE)
    REFERENCES TPROJECTTYPE (OBJECTID);
ALTER TABLE TFIELD
    ADD CONSTRAINT TFIELD_FK_3
    FOREIGN KEY (PROJECT)
    REFERENCES TPROJECT (PKEY);
ALTER TABLE TOPTION ADD TOOLTIP VARCHAR(255);
ALTER TABLE TSCREEN ADD PROJECTTYPE INTEGER;
ALTER TABLE TSCREEN ADD PROJECT INTEGER;
ALTER TABLE TSCREEN
    ADD CONSTRAINT TSCREEN_FK_2 FOREIGN KEY (PROJECTTYPE)
    REFERENCES TPROJECTTYPE (OBJECTID);
ALTER TABLE TSCREEN
    ADD CONSTRAINT TSCREEN_FK_3 FOREIGN KEY (PROJECT)
    REFERENCES TPROJECT (PKEY);
    
ALTER TABLE TDASHBOARDSCREEN ADD OWNER INTEGER;
ALTER TABLE TDASHBOARDSCREEN
    ADD CONSTRAINT TDASHBOARDSCREEN_FK_3 FOREIGN KEY (OWNER)
    REFERENCES TPERSON (PKEY);

ALTER TABLE TQUERYREPOSITORY ADD SORTORDER INTEGER;
ALTER TABLE TQUERYREPOSITORY ADD VIEWID VARCHAR(255);
CREATE  INDEX TQUERYREPINDEX2 ON TQUERYREPOSITORY (SORTORDER);
ALTER TABLE TEXPORTTEMPLATE ADD PARENT INTEGER;
ALTER TABLE TEXPORTTEMPLATE ADD SORTORDER INTEGER;
CREATE  INDEX TEXPOPRTTEMPINDEX2 ON TEXPORTTEMPLATE (SORTORDER);
ALTER TABLE TEXPORTTEMPLATE
    ADD CONSTRAINT TEXPORTTEMPLATE_FK_4
    FOREIGN KEY (PARENT)
    REFERENCES TEXPORTTEMPLATE (OBJECTID);
ALTER TABLE TREPORTPERSONSETTINGS
    DROP FOREIGN KEY TREPORTPERSONSETTINGS_FK_2;
ALTER TABLE TREPORTPERSONSETTINGS
    DROP FOREIGN KEY TREPORTPERSONSETTINGS_FK_3;
ALTER TABLE TREPORTPERSONSETTINGS
    DROP INDEX TREPORTPERSONSETTINGS_FK_2;
ALTER TABLE TREPORTPERSONSETTINGS
    DROP INDEX TREPORTPERSONSETTINGS_FK_3;
ALTER TABLE TREPORTPERSONSETTINGS
    ADD CONSTRAINT TREPORTPERSONSETTINGS_FK_2
    FOREIGN KEY (REPORTTEMPLATE)
    REFERENCES TEXPORTTEMPLATE (OBJECTID);   
ALTER TABLE TREPORTPERSONSETTINGS DROP COLUMN RECURRENCEPATTERN;
ALTER TABLE TFILTERCATEGORY ADD SORTORDER INTEGER;
CREATE  INDEX TFILTERCATEGORYINDEX2 ON TFILTERCATEGORY (SORTORDER);
ALTER TABLE TREPORTCATEGORY ADD SORTORDER INTEGER;
CREATE  INDEX TREPORTCATEGORYINDEX2 ON TREPORTCATEGORY (SORTORDER);
ALTER TABLE TWORKFLOWTRANSITION ADD ELAPSEDTIME INTEGER;
ALTER TABLE TWORKFLOWTRANSITION ADD TIMEUNIT INTEGER;
ALTER TABLE TWORKFLOWACTIVITY ADD FIELDSETTERRELATION INTEGER;
ALTER TABLE TWORKFLOWACTIVITY ADD PARAMNAME VARCHAR(255);
ALTER TABLE TWORKFLOWACTIVITY ADD FIELDSETMODE INTEGER;
ALTER TABLE TWORKFLOWACTIVITY ADD SORTORDER INTEGER;
ALTER TABLE TREADISSUE ADD FIELDKEY INTEGER;
ALTER TABLE TREADISSUE ADD LASTEDIT TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
CREATE INDEX TREADISSUEINDEX4 ON TREADISSUE(FIELDKEY);

# -----------------------------------------------------------------------
# TWFACTIVITYCONTEXTPARAMS
# -----------------------------------------------------------------------
drop table if exists TWFACTIVITYCONTEXTPARAMS;

CREATE TABLE TWFACTIVITYCONTEXTPARAMS
(
    OBJECTID INTEGER NOT NULL,
    WORKFLOWACTIVITY INTEGER NOT NULL,
    ISSUETYPE INTEGER,
    PROJECTTYPE INTEGER,
    PROJECT INTEGER,
    SETTERORPARTID INTEGER,
    ACTIVITYPARAMS MEDIUMTEXT,
    TPUUID VARCHAR(36),
    PRIMARY KEY(OBJECTID),
    INDEX TWFACTIVITYCONTEXTPARAMSINDEX1 (WORKFLOWACTIVITY),
    INDEX TWFACTIVITYCONTEXTPARAMSINDEX2 (ISSUETYPE),
    INDEX TWFACTIVITYCONTEXTPARAMSINDEX3 (PROJECTTYPE),
    INDEX TWFACTIVITYCONTEXTPARAMSINDEX4 (PROJECT),
    INDEX TWFACTIVITYCONTEXTPARAMSINDEX5 (TPUUID));

# -----------------------------------------------------------------------
# TWORKFLOWCOMMENT
# -----------------------------------------------------------------------
drop table if exists TWORKFLOWCOMMENT;

CREATE TABLE TWORKFLOWCOMMENT
(
    OBJECTID INTEGER NOT NULL,
    DESCRIPTION MEDIUMTEXT,
    WORKFLOW INTEGER,
    NODEX INTEGER,
    NODEY INTEGER,
    TPUUID VARCHAR(36),
    PRIMARY KEY(OBJECTID),
    INDEX TWORKFLOWCOMMENTINDEX1 (WORKFLOW),
    INDEX TWORKFLOWCOMMENTINDEX2 (TPUUID));
    
# -----------------------------------------------------------------------
# TREPORTSUBSCRIBE
# -----------------------------------------------------------------------
drop table if exists TREPORTSUBSCRIBE;

CREATE TABLE TREPORTSUBSCRIBE
(
    OBJECTID INTEGER NOT NULL,
    PERSON INTEGER NOT NULL,
    RECURRENCEPATTERN INTEGER,
    REPORTTEMPLATE INTEGER NOT NULL,
    TPUUID VARCHAR(36),
    PRIMARY KEY(OBJECTID),
    INDEX TREPORTSUBSCRIBEINDEX1 (TPUUID));

# -----------------------------------------------------------------------
# TGRIDLAYOUT
# -----------------------------------------------------------------------
drop table if exists TGRIDLAYOUT;

CREATE TABLE TGRIDLAYOUT
(
    OBJECTID INTEGER NOT NULL,
    PERSON INTEGER,
    LAYOUTKEY INTEGER NOT NULL,
    TPUUID VARCHAR(36),
    PRIMARY KEY(OBJECTID),
    INDEX TGRIDLAYOUTINDEX1 (PERSON),
    INDEX TGRIDLAYOUTINDEX2 (LAYOUTKEY),
    INDEX TGRIDLAYOUTINDEX3 (TPUUID));


# -----------------------------------------------------------------------
# TGRIDFIELD
# -----------------------------------------------------------------------
drop table if exists TGRIDFIELD;

CREATE TABLE TGRIDFIELD
(
    OBJECTID INTEGER NOT NULL,
    GRIDLAYOUT INTEGER NOT NULL,
    GRIDFIELD INTEGER NOT NULL,
    FIELDPOSITION INTEGER NOT NULL,
    FIELDWIDTH INTEGER NOT NULL,
    FILTERSTRING VARCHAR(255),
    TPUUID VARCHAR(36),
    PRIMARY KEY(OBJECTID),
    INDEX TGRIDFIELDINDEX1 (GRIDLAYOUT),
    INDEX TGRIDFIELDINDEX2 (TPUUID));


# -----------------------------------------------------------------------
# TGRIDGROUPINGSORTING
# -----------------------------------------------------------------------
drop table if exists TGRIDGROUPINGSORTING;

CREATE TABLE TGRIDGROUPINGSORTING
(
    OBJECTID INTEGER NOT NULL,
    GRIDLAYOUT INTEGER NOT NULL,
    GRIDFIELD INTEGER NOT NULL,
    SORTPOSITION INTEGER NOT NULL,
    ISGROUPING CHAR(1) default 'N',
    ISDESCENDING CHAR(1) default 'N',
    ISCOLLAPSED CHAR(1) default 'N',
    TPUUID VARCHAR(36),
    PRIMARY KEY(OBJECTID),
    INDEX TGRIDGROUPINGSORTINGINDEX1 (GRIDLAYOUT),
    INDEX TGRIDGROUPINGSORTINGINDEX2 (TPUUID));


# -----------------------------------------------------------------------
# TNAVIGATORLAYOUT
# -----------------------------------------------------------------------
drop table if exists TNAVIGATORLAYOUT;

CREATE TABLE TNAVIGATORLAYOUT
(
    OBJECTID INTEGER NOT NULL,
    PERSON INTEGER,
    FILTERID INTEGER,
    FILTERTYPE INTEGER,
    TPUUID VARCHAR(36),
    PRIMARY KEY(OBJECTID),
    INDEX TNAVIGATORLAYOUTINDEX1 (PERSON),
    INDEX TNAVIGATORLAYOUTINDEX2 (TPUUID));


# -----------------------------------------------------------------------
# TNAVIGATORCOLUMN
# -----------------------------------------------------------------------
drop table if exists TNAVIGATORCOLUMN;

CREATE TABLE TNAVIGATORCOLUMN
(
    OBJECTID INTEGER NOT NULL,
    NAVIGATORLAYOUT INTEGER NOT NULL,
    FIELD INTEGER NOT NULL,
    FIELDPOSITION INTEGER NOT NULL,
    FIELDWIDTH INTEGER NULL,
    TPUUID VARCHAR(36),
    PRIMARY KEY(OBJECTID),
    INDEX TNAVIGATORCOLUMNINDEX1 (NAVIGATORLAYOUT),
    INDEX TNAVIGATORCOLUMNINDEX2 (TPUUID));



# -----------------------------------------------------------------------
# TNAVIGATORGROUPINGSORTING
# -----------------------------------------------------------------------
drop table if exists TNAVIGATORGROUPINGSORTING;

CREATE TABLE TNAVIGATORGROUPINGSORTING
(
    OBJECTID INTEGER NOT NULL,
    NAVIGATORLAYOUT INTEGER NOT NULL,
  	FIELD INTEGER NOT NULL,
    SORTPOSITION INTEGER,
    ISGROUPING CHAR(1) default 'N',
    ISDESCENDING CHAR(1) default 'N',
    ISCOLLAPSED CHAR(1) default 'N',
    TPUUID VARCHAR(36),
    PRIMARY KEY(OBJECTID),
    INDEX TNAVIGATORGROUPINGSORTINGIDX1 (NAVIGATORLAYOUT),
    INDEX TNAVIGATORGROUPINGSORTINGIDX2 (TPUUID));


# -----------------------------------------------------------------------
# TCARDGROUPINGFIELD
# -----------------------------------------------------------------------
drop table if exists TCARDGROUPINGFIELD;

CREATE TABLE TCARDGROUPINGFIELD
(
    OBJECTID INTEGER NOT NULL,
    NAVIGATORLAYOUT INTEGER NOT NULL,
    CARDFIELD INTEGER NOT NULL,
    ISACTIV CHAR(1) default 'N',
    SORTFIELD INTEGER,
    ISDESCENDING CHAR(1) default 'N',
    TPUUID VARCHAR(36),
    PRIMARY KEY(OBJECTID),
    INDEX TCARDGROUPINGFIELDINDEX1 (NAVIGATORLAYOUT),
    INDEX TCARDGROUPINGFIELDINDEX2 (TPUUID));


# -----------------------------------------------------------------------
# TCARDFIELDOPTION
# -----------------------------------------------------------------------
drop table if exists TCARDFIELDOPTION;

CREATE TABLE TCARDFIELDOPTION
(
    OBJECTID INTEGER NOT NULL,
    GROUPINGFIELD INTEGER NOT NULL,
    OPTIONID INTEGER NOT NULL,
    OPTIONPOSITION INTEGER NOT NULL,
    OPTIONWIDTH INTEGER NOT NULL,
    MAXNUMBER INTEGER,
    TPUUID VARCHAR(36),
    PRIMARY KEY(OBJECTID),
    INDEX TCARDFIELDOPTIONINDEX1 (GROUPINGFIELD),
    INDEX TCARDFIELDOPTIONINDEX2 (TPUUID));


# -----------------------------------------------------------------------
# TCARDPANEL
# -----------------------------------------------------------------------
drop table if exists TCARDPANEL;

CREATE TABLE TCARDPANEL
(
    OBJECTID INTEGER NOT NULL,
    PERSON INTEGER,
    ROWSNO INTEGER NOT NULL,
    COLSNO INTEGER NOT NULL,
    TPUUID VARCHAR(36),
    PRIMARY KEY(OBJECTID),
    INDEX TCARDPANELINDEX1 (TPUUID));


# -----------------------------------------------------------------------
# TCARDFIELD
# -----------------------------------------------------------------------
drop table if exists TCARDFIELD;

CREATE TABLE TCARDFIELD
(
    OBJECTID INTEGER NOT NULL,
    NAME VARCHAR(255),
    COLINDEX INTEGER,
    ROWINDEX INTEGER,
    COLSPAN INTEGER,
    ROWSPAN INTEGER,
    LABELHALIGN INTEGER NOT NULL,
    LABELVALIGN INTEGER NOT NULL,
    VALUEHALIGN INTEGER NOT NULL,
    VALUEVALIGN INTEGER NOT NULL,
    CARDPANEL INTEGER NOT NULL,
    FIELDKEY INTEGER,
    HIDELABEL CHAR(1) default 'Y',
    ICONRENDERING INTEGER,
    TPUUID VARCHAR(36),
    PRIMARY KEY(OBJECTID),
    INDEX TCARDFIELDINDEX1 (TPUUID));


# -----------------------------------------------------------------------
# TVIEWPARAM
# -----------------------------------------------------------------------
drop table if exists TVIEWPARAM;

CREATE TABLE TVIEWPARAM
(
    OBJECTID INTEGER NOT NULL,
    NAVIGATORLAYOUT INTEGER NOT NULL,
    PARAMNAME VARCHAR(255) NOT NULL,
    PARAMVALUE MEDIUMTEXT,
    TPUUID VARCHAR(36),
    PRIMARY KEY(OBJECTID),
    INDEX TVIEWPARAMINDEX1 (NAVIGATORLAYOUT),
    INDEX TVIEWPARAMINDEX2 (TPUUID));


# -----------------------------------------------------------------------
# TGENERALPARAM
# -----------------------------------------------------------------------
drop table if exists TGENERALPARAM;

CREATE TABLE TGENERALPARAM
(
    OBJECTID INTEGER NOT NULL,
    PARAMNAME VARCHAR(255) NOT NULL,
    PARAMVALUE MEDIUMTEXT,
    TPUUID VARCHAR(36),
    PRIMARY KEY(OBJECTID),
    INDEX TGENERALPARAMINDEX1 (TPUUID));


# -----------------------------------------------------------------------
# TVERSIONCONTROL
# -----------------------------------------------------------------------
drop table if exists TVERSIONCONTROL;

CREATE TABLE TVERSIONCONTROL
(
    OBJECTID INTEGER NOT NULL,
    VCTYPE INTEGER NOT NULL,
    REPOSITORYBROWSER INTEGER NOT NULL,
    CHANGESETLINK VARCHAR(255),
    ADDEDFILESLINK VARCHAR(255),
    MODIFIEDEDFILESLINK VARCHAR(255),
    REPLACEDFILESLINK VARCHAR(255),
    DELETEDFILESLINK VARCHAR(255),
    CONNECTIONTYPE INTEGER NOT NULL,
    SERVERNAME VARCHAR(255) NOT NULL,
    REPOSITORYPATH VARCHAR(255) NOT NULL,
    DEFAULTSEVERPORT CHAR(1) default 'Y',
    SEVERPORT INTEGER,
    AUTHENTICATIONMODE INTEGER NOT NULL,
    USERNAME VARCHAR(100),
    PASSWORD VARCHAR(255),
    PRIVATEKEY MEDIUMTEXT,
    PASSPHRASE VARCHAR(255),
    PARENT INTEGER,
    TPUUID VARCHAR(36),
    PRIMARY KEY(OBJECTID),
    INDEX TVERSIONCONTROLINDEX1 (TPUUID));


# -----------------------------------------------------------------------
# TSHORTCUT
# -----------------------------------------------------------------------
drop table if exists TSHORTCUT;

CREATE TABLE TSHORTCUT
(
    OBJECTID INTEGER NOT NULL,
    SHORTCUTKEY INTEGER,
    CTRLKEY CHAR(1) default 'N',
    SHIFTKEY CHAR(1) default 'N',
    ALTKEY CHAR(1) default 'N',
    MENUITEMKEY INTEGER,
    MENUCONTEXT INTEGER,
    TPUUID VARCHAR(36),
    PRIMARY KEY(OBJECTID),
    INDEX TSHORTCUTSINDEX1 (TPUUID));


# -----------------------------------------------------------------------
# TMAILTEXTBLOCK
# -----------------------------------------------------------------------
drop table if exists TMAILTEXTBLOCK;

CREATE TABLE TMAILTEXTBLOCK
(
    OBJECTID INTEGER NOT NULL,
    PERSON INTEGER,
    BLOCKTITLE VARCHAR(255),
    BLOCKCONTENT MEDIUMTEXT,
    TAGLABEL VARCHAR(100),
    REPOSITORYTYPE INTEGER,
    PROJECT INTEGER,
    TPUUID VARCHAR(36),
    PRIMARY KEY(OBJECTID),
    INDEX TMAILTEXTBLOCKINDEX1 (PERSON),
    INDEX TMAILTEXTBLOCKINDEX2 (TPUUID));


# -----------------------------------------------------------------------
# TPROLE
# -----------------------------------------------------------------------
drop table if exists TPROLE;

CREATE TABLE TPROLE
(
    OBJECTID INTEGER NOT NULL,
    PROJECTTYPE INTEGER,
    ROLEKEY INTEGER,
    TPUUID VARCHAR(36),
    PRIMARY KEY(OBJECTID),
    INDEX TPROLEINDEX1 (TPUUID));


# -----------------------------------------------------------------------
# TCHILDPROJECTTYPE
# -----------------------------------------------------------------------
drop table if exists TCHILDPROJECTTYPE;

CREATE TABLE TCHILDPROJECTTYPE
(
    OBJECTID INTEGER NOT NULL,
    PROJECTTYPEPARENT INTEGER NOT NULL,
    PROJECTTYPECHILD INTEGER NOT NULL,
    TPUUID VARCHAR(36),
    PRIMARY KEY(OBJECTID),
    INDEX TCHILDPROJECTTYPEINDEX1 (TPUUID));

# -----------------------------------------------------------------------
# TPERSONINDOMAIN
# -----------------------------------------------------------------------
drop table if exists TPERSONINDOMAIN;

CREATE TABLE TPERSONINDOMAIN
(
    OBJECTID INTEGER NOT NULL,
    PERSONKEY INTEGER NOT NULL,
    DOMAINKEY INTEGER NOT NULL,
    DESCRIPTION MEDIUMTEXT,
    TPUUID VARCHAR(36),
    PRIMARY KEY(OBJECTID),
    INDEX TPERSONINDOMAININDEX1 (TPUUID));


# -----------------------------------------------------------------------
# TATTACHMENTVERSION
# -----------------------------------------------------------------------
drop table if exists TATTACHMENTVERSION;

CREATE TABLE TATTACHMENTVERSION
(
    OBJECTID INTEGER NOT NULL,
    WORKITEM INTEGER NOT NULL,
    CHANGEDBY INTEGER,
    DOCUMENTSTATE INTEGER,
    FILENAME VARCHAR(256) NOT NULL,
    ISURL CHAR(1) default 'N',
    FILESIZE VARCHAR(20),
    MIMETYPE VARCHAR(15),
    LASTEDIT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    VERSION VARCHAR(20),
    DESCRIPTION MEDIUMTEXT,
    CRYPTKEY MEDIUMTEXT,
    ISENCRYPTED CHAR(1) default 'N',
    ISDELETED CHAR(1) default 'N',
    TPUUID VARCHAR(36),
    PRIMARY KEY(OBJECTID),
    INDEX TATTACHMENTVERSIONINDEX1 (TPUUID));

# -----------------------------------------------------------------------
# TUSERLEVEL
# -----------------------------------------------------------------------
drop table if exists TUSERLEVEL;

CREATE TABLE TUSERLEVEL
(
    OBJECTID INTEGER NOT NULL,
    LABEL VARCHAR(255),
    DESCRIPTION MEDIUMTEXT,
    TPUUID VARCHAR(36),
    PRIMARY KEY(OBJECTID),
    INDEX TUSERLEVELINDEX1 (TPUUID));


# -----------------------------------------------------------------------
# TUSERLEVELSETTING
# -----------------------------------------------------------------------
drop table if exists TUSERLEVELSETTING;

CREATE TABLE TUSERLEVELSETTING
(
    OBJECTID INTEGER NOT NULL,
    USERLEVEL INTEGER NOT NULL,
    ACTIONKEY INTEGER NOT NULL,
    ISACTIVE CHAR(1) default 'N',
    TPUUID VARCHAR(36),
    PRIMARY KEY(OBJECTID),
    INDEX TUSERLEVELSETTINGINDEX1 (TPUUID));
  

# -----------------------------------------------------------------------
# TUSERFEATURE
# -----------------------------------------------------------------------
drop table if exists TUSERFEATURE;

CREATE TABLE TUSERFEATURE
(
    OBJECTID INTEGER NOT NULL,
    FEATURENAME VARCHAR(255) NOT NULL,
    PERSON INTEGER,
    ISACTIVE CHAR(1) default 'N',
    TPUUID VARCHAR(36),
    PRIMARY KEY(OBJECTID),
    INDEX TUSERFEATUREINDEX1 (TPUUID));
    
# -----------------------------------------------------------------------
# TITEMTRANSITION
# -----------------------------------------------------------------------
drop table if exists TITEMTRANSITION;

CREATE TABLE TITEMTRANSITION
(
    OBJECTID INTEGER NOT NULL,
    WORKITEM INTEGER NOT NULL,
    TRANSITION INTEGER NOT NULL,
    TRANSITIONTIME TIMESTAMP,
    TPUUID VARCHAR(36),
    PRIMARY KEY(OBJECTID),
    INDEX TITEMTRANSITIONINDEX1 (WORKITEM),
    INDEX TITEMTRANSITIONINDEX2 (TRANSITION),
    INDEX TITEMTRANSITIONINDEX3 (TPUUID));
    
 ALTER TABLE TWFACTIVITYCONTEXTPARAMS
    ADD CONSTRAINT TWFACTIVITYCONTEXTPARAMS_FK_1
    FOREIGN KEY (WORKFLOWACTIVITY)
    REFERENCES TWORKFLOWACTIVITY (OBJECTID)
;

ALTER TABLE TWFACTIVITYCONTEXTPARAMS
    ADD CONSTRAINT TWFACTIVITYCONTEXTPARAMS_FK_2
    FOREIGN KEY (ISSUETYPE)
    REFERENCES TCATEGORY (PKEY)
;

ALTER TABLE TWFACTIVITYCONTEXTPARAMS
    ADD CONSTRAINT TWFACTIVITYCONTEXTPARAMS_FK_3
    FOREIGN KEY (PROJECTTYPE)
    REFERENCES TPROJECTTYPE (OBJECTID)
;

ALTER TABLE TWFACTIVITYCONTEXTPARAMS
    ADD CONSTRAINT TWFACTIVITYCONTEXTPARAMS_FK_4
    FOREIGN KEY (PROJECT)
    REFERENCES TPROJECT (PKEY)
;

ALTER TABLE TWORKFLOWCOMMENT
    ADD CONSTRAINT TWORKFLOWCOMMENT_FK_1
    FOREIGN KEY (WORKFLOW)
    REFERENCES TWORKFLOWDEF (OBJECTID)
;

ALTER TABLE TREPORTSUBSCRIBE
    ADD CONSTRAINT TREPORTSUBSCRIBE_FK_1
    FOREIGN KEY (PERSON)
    REFERENCES TPERSON (PKEY)
;

ALTER TABLE TREPORTSUBSCRIBE
    ADD CONSTRAINT TREPORTSUBSCRIBE_FK_2
    FOREIGN KEY (RECURRENCEPATTERN)
    REFERENCES TRECURRENCEPATTERN (OBJECTID)
;

ALTER TABLE TREPORTSUBSCRIBE
    ADD CONSTRAINT TREPORTSUBSCRIBE_FK_3
    FOREIGN KEY (REPORTTEMPLATE)
    REFERENCES TEXPORTTEMPLATE (OBJECTID)
;

ALTER TABLE TGRIDLAYOUT
    ADD CONSTRAINT TGRIDLAYOUT_FK_1
    FOREIGN KEY (PERSON)
    REFERENCES TPERSON (PKEY)
;

ALTER TABLE TGRIDFIELD
    ADD CONSTRAINT TGRIDFIELD_FK_1
    FOREIGN KEY (GRIDLAYOUT)
    REFERENCES TGRIDLAYOUT (OBJECTID)
;

ALTER TABLE TGRIDGROUPINGSORTING
    ADD CONSTRAINT TGRIDGROUPINGSORTING_FK_1
    FOREIGN KEY (GRIDLAYOUT)
    REFERENCES TGRIDLAYOUT (OBJECTID)
;

ALTER TABLE TNAVIGATORLAYOUT
    ADD CONSTRAINT TNAVIGATORLAYOUT_FK_1
    FOREIGN KEY (PERSON)
    REFERENCES TPERSON (PKEY)
;

ALTER TABLE TNAVIGATORCOLUMN
    ADD CONSTRAINT TNAVIGATORCOLUMN_FK_1
    FOREIGN KEY (NAVIGATORLAYOUT)
    REFERENCES TNAVIGATORLAYOUT (OBJECTID)
;

ALTER TABLE TNAVIGATORGROUPINGSORTING
    ADD CONSTRAINT TNAVIGATORGROUPINGSORTING_FK_1
    FOREIGN KEY (NAVIGATORLAYOUT)
    REFERENCES TNAVIGATORLAYOUT (OBJECTID)
;

ALTER TABLE TCARDGROUPINGFIELD
    ADD CONSTRAINT TCARDGROUPINGFIELD_FK_1
    FOREIGN KEY (NAVIGATORLAYOUT)
    REFERENCES TNAVIGATORLAYOUT (OBJECTID)
;

ALTER TABLE TCARDFIELDOPTION
    ADD CONSTRAINT TCARDFIELDOPTION_FK_1
    FOREIGN KEY (GROUPINGFIELD)
    REFERENCES TCARDGROUPINGFIELD (OBJECTID)
;

ALTER TABLE TCARDFIELD
    ADD CONSTRAINT TCARDFIELD_FK_1
    FOREIGN KEY (CARDPANEL)
    REFERENCES TCARDPANEL (OBJECTID)
;

ALTER TABLE TVIEWPARAM
    ADD CONSTRAINT TVIEWPARAM_FK_1
    FOREIGN KEY (NAVIGATORLAYOUT)
    REFERENCES TNAVIGATORLAYOUT (OBJECTID)
;

ALTER TABLE TVERSIONCONTROL
    ADD CONSTRAINT TVERSIONCONTROL_FK_1
    FOREIGN KEY (PARENT)
    REFERENCES TVERSIONCONTROL (OBJECTID)
;

ALTER TABLE TMAILTEXTBLOCK
    ADD CONSTRAINT TMAILTEXTBLOCK_FK_1
    FOREIGN KEY (PERSON)
    REFERENCES TPERSON (PKEY)
;

ALTER TABLE TMAILTEXTBLOCK
    ADD CONSTRAINT TMAILTEXTBLOCK_FK_2
    FOREIGN KEY (PROJECT)
    REFERENCES TPROJECT (PKEY)
;

ALTER TABLE TPROLE
    ADD CONSTRAINT TPROLE_FK_1
    FOREIGN KEY (PROJECTTYPE)
    REFERENCES TPROJECTTYPE (OBJECTID)
;

ALTER TABLE TPROLE
    ADD CONSTRAINT TPROLE_FK_2
    FOREIGN KEY (ROLEKEY)
    REFERENCES TROLE (PKEY)
;

ALTER TABLE TCHILDPROJECTTYPE
    ADD CONSTRAINT TCHILDPROJECTTYPE_FK_1
    FOREIGN KEY (PROJECTTYPEPARENT)
    REFERENCES TPROJECTTYPE (OBJECTID)
;

ALTER TABLE TCHILDPROJECTTYPE
    ADD CONSTRAINT TCHILDPROJECTTYPE_FK_2
    FOREIGN KEY (PROJECTTYPECHILD)
    REFERENCES TPROJECTTYPE (OBJECTID)
;

ALTER TABLE TPERSONINDOMAIN
    ADD CONSTRAINT TPERSONINDOMAIN_FK_1
    FOREIGN KEY (PERSONKEY)
    REFERENCES TPERSON (PKEY)
;

ALTER TABLE TPERSONINDOMAIN
    ADD CONSTRAINT TPERSONINDOMAIN_FK_2
    FOREIGN KEY (DOMAINKEY)
    REFERENCES TDOMAIN (OBJECTID)
;

ALTER TABLE TATTACHMENTVERSION
    ADD CONSTRAINT TATTACHMENTVERSION_FK_1
    FOREIGN KEY (WORKITEM)
    REFERENCES TWORKITEM (WORKITEMKEY)
;

ALTER TABLE TATTACHMENTVERSION
    ADD CONSTRAINT TATTACHMENTVERSION_FK_2
    FOREIGN KEY (CHANGEDBY)
    REFERENCES TPERSON (PKEY)
;

ALTER TABLE TATTACHMENTVERSION
    ADD CONSTRAINT TATTACHMENTVERSION_FK_3
    FOREIGN KEY (DOCUMENTSTATE)
    REFERENCES TDOCSTATE (OBJECTID)
;
  
ALTER TABLE TUSERLEVELSETTING
    ADD CONSTRAINT TUSERLEVELSETTING_FK_1 FOREIGN KEY (USERLEVEL)
    REFERENCES TUSERLEVEL (OBJECTID)
;

ALTER TABLE TUSERFEATURE
    ADD CONSTRAINT TUSERFEATURE_FK_1
    FOREIGN KEY (PERSON)
    REFERENCES TPERSON (PKEY)
;

ALTER TABLE TITEMTRANSITION
    ADD CONSTRAINT TITEMTRANSITION_FK_1
    FOREIGN KEY (WORKITEM)
    REFERENCES TWORKITEM (WORKITEMKEY)
;

ALTER TABLE TITEMTRANSITION
    ADD CONSTRAINT TITEMTRANSITION_FK_2
    FOREIGN KEY (TRANSITION)
    REFERENCES TWORKFLOWTRANSITION (OBJECTID)
;
COMMIT;