ALTER TABLE TCATEGORY MODIFY COLUMN LABEL VARCHAR(255) NOT NULL;
ALTER TABLE TDEPARTMENT MODIFY COLUMN LABEL VARCHAR(255) NOT NULL;
ALTER TABLE TPERSON ADD SUBSTITUTEKEY INTEGER;
ALTER TABLE TPERSON ADD SUBSTITUTEACTIVE CHAR (1) default 'N';
ALTER TABLE TPRIORITY MODIFY COLUMN LABEL VARCHAR(255) NULL;
ALTER TABLE TPROJECT MODIFY COLUMN LABEL VARCHAR(255) NULL;
ALTER TABLE TRELEASE MODIFY COLUMN LABEL VARCHAR(255) NULL;
ALTER TABLE TROLE MODIFY COLUMN LABEL VARCHAR(255) NOT NULL;
ALTER TABLE TSEVERITY MODIFY COLUMN LABEL VARCHAR(255) NULL;
ALTER TABLE TSTATE MODIFY COLUMN LABEL VARCHAR(255) NOT NULL;
ALTER TABLE TWORKITEM MODIFY COLUMN PACKAGESYNOPSYS VARCHAR (255) NOT NULL;
ALTER TABLE TPROJECTTYPE MODIFY COLUMN LABEL VARCHAR(255) NULL;
ALTER TABLE TSITE DROP COLUMN LICENSEKEY;
ALTER TABLE TSITE DROP COLUMN EXECUTABLE1;
ALTER TABLE TSITE DROP COLUMN EXECUTABLE2;
ALTER TABLE TSITE MODIFY COLUMN LICENSEEXT VARCHAR(512);
ALTER TABLE TSCREENFIELD ADD HIDELABEL CHAR (1) default 'N';
ALTER TABLE TPERSON
    ADD CONSTRAINT TPERSON_FK_4 FOREIGN KEY (SUBSTITUTEKEY)
    REFERENCES TPERSON (PKEY);
COMMIT;