/**
 * Genji Scrum Tool and Issue Tracker
 * Copyright (C) 2015 Steinbeis GmbH & Co. KG Task Management Solutions

 * <a href="http://www.trackplus.com">Genji Scrum Tool</a>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

/* $Id:$ */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.05 at 02:08:43 PM EEST 
//


package com.aurel.track.configExchange.exporter.jaxb;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.aurel.track.configExchange.exporter.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _TrackplusExchange_QNAME = new QName("http://www.trackplus.com/exporter/", "trackplusExchange");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.aurel.track.configExchange.exporter.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TrackplusRoot }
     * 
     */
    public TrackplusRoot createTrackplusRoot() {
        return new TrackplusRoot();
    }

    /**
     * Create an instance of {@link DependencyData }
     * 
     */
    public DependencyData createDependencyData() {
        return new DependencyData();
    }

    /**
     * Create an instance of {@link Entity }
     * 
     */
    public Entity createEntity() {
        return new Entity();
    }

    /**
     * Create an instance of {@link Attribute }
     * 
     */
    public Attribute createAttribute() {
        return new Attribute();
    }

    /**
     * Create an instance of {@link Reference }
     * 
     */
    public Reference createReference() {
        return new Reference();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TrackplusRoot }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.trackplus.com/exporter/", name = "trackplusExchange")
    public JAXBElement<TrackplusRoot> createTrackplusExchange(TrackplusRoot value) {
        return new JAXBElement<TrackplusRoot>(_TrackplusExchange_QNAME, TrackplusRoot.class, null, value);
    }

}
