--
-- Project:      Track+
--
-- Date Created:  Monday, January 21, 2002
-- Last Modified: Thursday, July 27, 2006
-- $Id: populate.sql 5686 2014-01-23 10:31:33Z friedric $
--
--
-- Populates the Track+ database with some useful defaults

-- SET NAMES ISO8859_1

-- project
-- INSERT INTO TPROJECT (PKEY, LABEL, DEFOWNER, DEFMANAGER, DEFINITSTATE, PROJECTTYPE, DELETED, STATUS) VALUES (0, 'Generic Project', 1, 1, 1, 0, 'N', 3);

-- roles
INSERT INTO TROLE (PKEY, LABEL, ACCESSKEY, EXTENDEDACCESSKEY) VALUES (2,'Project Admin.', 999, '11111111111');
INSERT INTO TROLE (PKEY, LABEL, ACCESSKEY, EXTENDEDACCESSKEY) VALUES (6,'Manager', 777, '11111111110');
INSERT INTO TROLE (PKEY, LABEL, ACCESSKEY, EXTENDEDACCESSKEY) VALUES (7,'Responsible', 660, '00100001110');
INSERT INTO TROLE (PKEY, LABEL, ACCESSKEY, EXTENDEDACCESSKEY) VALUES (9,'Consulted', 220, '00100000110');
INSERT INTO TROLE (PKEY, LABEL, ACCESSKEY, EXTENDEDACCESSKEY) VALUES (10,'Informed', 660, '00100000010');
INSERT INTO TROLE (PKEY, LABEL, ACCESSKEY, EXTENDEDACCESSKEY) VALUES (11,'Extern', 220, '00100000000');

-- -1301 : total budget bottom up
-- -1201: my expense
-- -1101:  total expense
-- -1003: watchers

INSERT INTO TROLEFIELD (OBJECTID, ROLEKEY, FIELDKEY, ACCESSRIGHT) VALUES(1, 7, -1301, 2);

INSERT INTO TROLEFIELD (OBJECTID, ROLEKEY, FIELDKEY, ACCESSRIGHT) VALUES(2, 9, -1301, 2);
INSERT INTO TROLEFIELD (OBJECTID, ROLEKEY, FIELDKEY, ACCESSRIGHT) VALUES(3, 9, 19, 2);
INSERT INTO TROLEFIELD (OBJECTID, ROLEKEY, FIELDKEY, ACCESSRIGHT) VALUES(4, 9, 20, 2);
INSERT INTO TROLEFIELD (OBJECTID, ROLEKEY, FIELDKEY, ACCESSRIGHT) VALUES(5, 9, -1201, 3);
INSERT INTO TROLEFIELD (OBJECTID, ROLEKEY, FIELDKEY, ACCESSRIGHT) VALUES(6, 9, -1101, 3);
INSERT INTO TROLEFIELD (OBJECTID, ROLEKEY, FIELDKEY, ACCESSRIGHT) VALUES(7, 9, 5, 2);
INSERT INTO TROLEFIELD (OBJECTID, ROLEKEY, FIELDKEY, ACCESSRIGHT) VALUES(8, 9, 6, 2);

INSERT INTO TROLEFIELD (OBJECTID, ROLEKEY, FIELDKEY, ACCESSRIGHT) VALUES(9, 10, -1301, 2);
INSERT INTO TROLEFIELD (OBJECTID, ROLEKEY, FIELDKEY, ACCESSRIGHT) VALUES(10, 10, 19, 2);
INSERT INTO TROLEFIELD (OBJECTID, ROLEKEY, FIELDKEY, ACCESSRIGHT) VALUES(11, 10, 20, 2);
INSERT INTO TROLEFIELD (OBJECTID, ROLEKEY, FIELDKEY, ACCESSRIGHT) VALUES(12, 10, -1201, 3);
INSERT INTO TROLEFIELD (OBJECTID, ROLEKEY, FIELDKEY, ACCESSRIGHT) VALUES(13, 10, -1101, 3);
INSERT INTO TROLEFIELD (OBJECTID, ROLEKEY, FIELDKEY, ACCESSRIGHT) VALUES(14, 10, 5, 2);
INSERT INTO TROLEFIELD (OBJECTID, ROLEKEY, FIELDKEY, ACCESSRIGHT) VALUES(15, 10, 6, 2);


INSERT INTO TROLEFIELD (OBJECTID, ROLEKEY, FIELDKEY, ACCESSRIGHT) VALUES(16, 11, -1301, 2);
INSERT INTO TROLEFIELD (OBJECTID, ROLEKEY, FIELDKEY, ACCESSRIGHT) VALUES(17, 11, 19, 2);
INSERT INTO TROLEFIELD (OBJECTID, ROLEKEY, FIELDKEY, ACCESSRIGHT) VALUES(18, 11, 20, 2);
INSERT INTO TROLEFIELD (OBJECTID, ROLEKEY, FIELDKEY, ACCESSRIGHT) VALUES(19, 11, -1201, 3);
INSERT INTO TROLEFIELD (OBJECTID, ROLEKEY, FIELDKEY, ACCESSRIGHT) VALUES(20, 11, -1101, 3);
INSERT INTO TROLEFIELD (OBJECTID, ROLEKEY, FIELDKEY, ACCESSRIGHT) VALUES(21, 11, 5, 2);
INSERT INTO TROLEFIELD (OBJECTID, ROLEKEY, FIELDKEY, ACCESSRIGHT) VALUES(22, 11, 6, 2);




INSERT INTO TDOCSTATE (OBJECTID, LABEL, STATEFLAG)
               VALUES (1, 'open',0);
INSERT INTO TDOCSTATE (OBJECTID, LABEL, STATEFLAG)
               VALUES (2, 'approved',0);
INSERT INTO TDOCSTATE (OBJECTID, LABEL, STATEFLAG)
               VALUES (3, 'published',0);
INSERT INTO TDOCSTATE (OBJECTID, LABEL, STATEFLAG)
               VALUES (4, 'withdrawn',1);

-- INSERT INTO TACCOUNT (OBJECTID, ACCOUNTNUMBER, ACCOUNTNAME, STATUS)
--               VALUES (0,'0','Default Account', 14);


--  system fields
-- Required system dropdowns
INSERT INTO TFIELD (OBJECTID, NAME, FIELDTYPE, DEPRECATED, ISCUSTOM, REQUIRED)
			VALUES (1, 'Project', 'com.aurel.track.fieldType.types.system.select.SystemSelectProject', 'N', 'N', 'Y');
INSERT INTO TFIELD (OBJECTID, NAME, FIELDTYPE, DEPRECATED, ISCUSTOM, REQUIRED)
			VALUES (2, 'IssueType', 'com.aurel.track.fieldType.types.system.select.SystemSelectIssueType', 'N', 'N', 'Y');
-- INSERT INTO TFIELD (OBJECTID, NAME, FIELDTYPE, DEPRECATED, ISCUSTOM, REQUIRED)
--			VALUES (3, 'Subproject', 'com.aurel.track.fieldType.types.system.select.SystemSelectSubproject', 'N', 'N', 'Y');*/
INSERT INTO TFIELD (OBJECTID, NAME, FIELDTYPE, DEPRECATED, ISCUSTOM, REQUIRED)
			VALUES (4, 'Status', 'com.aurel.track.fieldType.types.system.select.SystemSelectState', 'N', 'N', 'Y');
INSERT INTO TFIELD (OBJECTID, NAME, FIELDTYPE, DEPRECATED, ISCUSTOM, REQUIRED)
			VALUES (5, 'Manager', 'com.aurel.track.fieldType.types.system.select.SystemSelectManager', 'N', 'N', 'Y');
INSERT INTO TFIELD (OBJECTID, NAME, FIELDTYPE, DEPRECATED, ISCUSTOM, REQUIRED)
			VALUES (6, 'Responsible', 'com.aurel.track.fieldType.types.system.select.SystemSelectResponsible', 'N', 'N', 'Y');
-- Not required system dropdowns
-- INSERT INTO TFIELD (OBJECTID, NAME, FIELDTYPE, DEPRECATED, ISCUSTOM, REQUIRED)
--			VALUES (7, 'Class', 'com.aurel.track.fieldType.types.system.select.SystemSelectTheClass', 'N', 'N', 'N');*/
INSERT INTO TFIELD (OBJECTID, NAME, FIELDTYPE, DEPRECATED, ISCUSTOM, REQUIRED)
			VALUES (8, 'ReleaseNoticed', 'com.aurel.track.fieldType.types.system.select.SystemSelectReleaseNoticed', 'N', 'N', 'N');
INSERT INTO TFIELD (OBJECTID, NAME, FIELDTYPE, DEPRECATED, ISCUSTOM, REQUIRED)
			VALUES (9, 'ReleaseScheduled', 'com.aurel.track.fieldType.types.system.select.SystemSelectReleaseScheduled', 'N', 'N', 'N');
INSERT INTO TFIELD (OBJECTID, NAME, FIELDTYPE, DEPRECATED, ISCUSTOM, REQUIRED)
			VALUES (10, 'Priority', 'com.aurel.track.fieldType.types.system.select.SystemSelectPriority', 'N', 'N', 'Y');
INSERT INTO TFIELD (OBJECTID, NAME, FIELDTYPE, DEPRECATED, ISCUSTOM, REQUIRED)
			VALUES (11, 'Severity', 'com.aurel.track.fieldType.types.system.select.SystemSelectSeverity', 'N', 'N', 'N');
-- System label fields
INSERT INTO TFIELD (OBJECTID, NAME, FIELDTYPE, DEPRECATED, ISCUSTOM, REQUIRED)
			VALUES (12, 'IssueNo', 'com.aurel.track.fieldType.types.system.text.SystemLabel', 'N', 'N', 'Y');
INSERT INTO TFIELD (OBJECTID, NAME, FIELDTYPE, DEPRECATED, ISCUSTOM, REQUIRED)
			VALUES (13, 'Originator', 'com.aurel.track.fieldType.types.system.text.SystemOriginator', 'N', 'N', 'Y');
INSERT INTO TFIELD (OBJECTID, NAME, FIELDTYPE, DEPRECATED, ISCUSTOM, REQUIRED)
			VALUES (14, 'CreateDate', 'com.aurel.track.fieldType.types.system.text.SystemLabelDate', 'N', 'N', 'Y');
INSERT INTO TFIELD (OBJECTID, NAME, FIELDTYPE, DEPRECATED, ISCUSTOM, REQUIRED)
			VALUES (15, 'LastModifiedDate', 'com.aurel.track.fieldType.types.system.text.SystemLabelDate', 'N', 'N', 'Y');
INSERT INTO TFIELD (OBJECTID, NAME, FIELDTYPE, DEPRECATED, ISCUSTOM, REQUIRED)
			VALUES (16, 'SuperiorWorkItem', 'com.aurel.track.fieldType.types.system.SystemParent', 'N', 'N', 'N');
-- Required system textbox
INSERT INTO TFIELD (OBJECTID, NAME, FIELDTYPE, DEPRECATED, ISCUSTOM, REQUIRED)
			VALUES (17, 'Synopsis', 'com.aurel.track.fieldType.types.system.text.SystemSynopsis', 'N', 'N', 'Y');
-- Not required system textbox
INSERT INTO TFIELD (OBJECTID, NAME, FIELDTYPE, DEPRECATED, ISCUSTOM, REQUIRED)
			VALUES (18, 'Build', 'com.aurel.track.fieldType.types.system.text.SystemTextBoxText', 'N', 'N', 'N');
INSERT INTO TFIELD (OBJECTID, NAME, FIELDTYPE, DEPRECATED, ISCUSTOM, REQUIRED)
			VALUES (19, 'StartDate', 'com.aurel.track.fieldType.types.system.text.SystemStartDate', 'N', 'N', 'N');
INSERT INTO TFIELD (OBJECTID, NAME, FIELDTYPE, DEPRECATED, ISCUSTOM, REQUIRED)
			VALUES (20, 'EndDate', 'com.aurel.track.fieldType.types.system.text.SystemEndDate', 'N', 'N', 'N');
INSERT INTO TFIELD (OBJECTID, NAME, FIELDTYPE, DEPRECATED, ISCUSTOM, REQUIRED)
			VALUES (21, 'Description', 'com.aurel.track.fieldType.types.system.text.SystemDescriptionTextEditor', 'N', 'N', 'N');
-- Not required system checkbox
INSERT INTO TFIELD (OBJECTID, NAME, FIELDTYPE, DEPRECATED, ISCUSTOM, REQUIRED)
			VALUES (22, 'AccessLevel', 'com.aurel.track.fieldType.types.system.check.SystemAccessLevel', 'N', 'N', 'N');
INSERT INTO TFIELD (OBJECTID, NAME, FIELDTYPE, DEPRECATED, ISCUSTOM, REQUIRED)
			VALUES (23, 'Comment', 'com.aurel.track.fieldType.types.system.text.SystemCommentTextEditor', 'N', 'N', 'N');
-- lastEditedBy person
INSERT INTO TFIELD (OBJECTID, NAME, FIELDTYPE, DEPRECATED, ISCUSTOM, REQUIRED)
			VALUES (24, 'LastEditedBy', 'com.aurel.track.fieldType.types.system.text.SystemLastEditedBy', 'N', 'N', 'Y');
-- archive level
INSERT INTO TFIELD (OBJECTID, NAME, FIELDTYPE, DEPRECATED, ISCUSTOM, REQUIRED)
			VALUES (25, 'ArchiveLevel', 'com.aurel.track.fieldType.types.system.text.SystemArchiveLevel', 'N', 'N', 'N');
INSERT INTO TFIELD (OBJECTID, NAME, FIELDTYPE, DEPRECATED, ISCUSTOM, REQUIRED)
			VALUES (26, 'SubmitterEmail', 'com.aurel.track.fieldType.types.system.text.SystemSubmitterEmail', 'N', 'N', 'N');
INSERT INTO TFIELD (OBJECTID, NAME, FIELDTYPE, DEPRECATED, ISCUSTOM, REQUIRED)
			VALUES (27, 'WBS', 'com.aurel.track.fieldType.types.system.text.SystemWBS', 'N', 'N', 'N');
INSERT INTO TFIELD (OBJECTID, NAME, FIELDTYPE, DEPRECATED, ISCUSTOM, REQUIRED)
			VALUES (28, 'ProjectSpecificIssueNo', 'com.aurel.track.fieldType.types.system.text.SystemProjectSpecificIssueNo', 'N', 'N', 'N');
INSERT INTO TFIELD (OBJECTID, NAME, FIELDTYPE, DEPRECATED, ISCUSTOM, REQUIRED)
			VALUES (29, 'TargetStartDate', 'com.aurel.track.fieldType.types.system.text.SystemStartDateTarget', 'N', 'N', 'N');
INSERT INTO TFIELD (OBJECTID, NAME, FIELDTYPE, DEPRECATED, ISCUSTOM, REQUIRED)
			VALUES (30, 'TargetEndDate', 'com.aurel.track.fieldType.types.system.text.SystemEndDateTarget', 'N', 'N', 'N');
INSERT INTO TFIELD (OBJECTID, NAME, FIELDTYPE, DEPRECATED, ISCUSTOM, REQUIRED)
			VALUES (31, 'Participants', 'com.aurel.track.fieldType.types.custom.CustomTextArea', 'N', 'Y', 'N');
INSERT INTO TFIELD (OBJECTID, NAME, FIELDTYPE, DEPRECATED, ISCUSTOM, REQUIRED)
			VALUES (32, 'TaskIsMilestone', 'com.aurel.track.fieldType.types.system.check.SystemTaskIsMilestone', 'N', 'N', 'N');
INSERT INTO TFIELD (OBJECTID, NAME, FIELDTYPE, DEPRECATED, ISCUSTOM, REQUIRED)
			VALUES (33, 'Duration', 'com.aurel.track.fieldType.types.system.text.SystemDuration', 'N', 'N', 'N');
INSERT INTO TFIELD (OBJECTID, NAME, FIELDTYPE, DEPRECATED, ISCUSTOM, REQUIRED)
			VALUES (34, 'TargetDuration', 'com.aurel.track.fieldType.types.system.text.SystemTargetDuration', 'N', 'N', 'N');			


--  system field configs
-- Configs for required system dropdowns
INSERT INTO TFIELDCONFIG(OBJECTID, FIELDKEY, LABEL, TOOLTIP, REQUIRED)
			VALUES (1, 1, 'Space', 'Space', 'Y');
INSERT INTO TFIELDCONFIG(OBJECTID, FIELDKEY, LABEL, TOOLTIP, REQUIRED)
			VALUES (2, 2, 'Item Type', 'The type of item', 'Y');
-- INSERT INTO TFIELDCONFIG(OBJECTID, FIELDKEY, LABEL, TOOLTIP, REQUIRED)
--			VALUES (3, 3, 'Subproject', 'Subproject', 'Y');*/
INSERT INTO TFIELDCONFIG(OBJECTID, FIELDKEY, LABEL, TOOLTIP, REQUIRED, HISTORY)
			VALUES (4, 4, 'Status', 'Status', 'Y', 'Y');
INSERT INTO TFIELDCONFIG(OBJECTID, FIELDKEY, LABEL, TOOLTIP, REQUIRED, HISTORY)
			VALUES (5, 5, 'Manager', 'Manager', 'Y', 'Y');
INSERT INTO TFIELDCONFIG(OBJECTID, FIELDKEY, LABEL, TOOLTIP, REQUIRED, HISTORY)
			VALUES (6, 6, 'Responsible', 'Responsible', 'Y', 'Y');
-- Configs for not required system dropdowns
-- INSERT INTO TFIELDCONFIG(OBJECTID, FIELDKEY, LABEL, TOOLTIP, REQUIRED)
--			VALUES (7, 7, 'Class', 'Class', 'Y');*/
INSERT INTO TFIELDCONFIG(OBJECTID, FIELDKEY, LABEL, TOOLTIP, REQUIRED)
			VALUES (8, 8, 'Affects Release', 'Release which is affected by this issue', 'N');
INSERT INTO TFIELDCONFIG(OBJECTID, FIELDKEY, LABEL, TOOLTIP, REQUIRED)
			VALUES (9, 9, 'Fix Release', 'Release where this issue is resolved', 'N');
INSERT INTO TFIELDCONFIG(OBJECTID, FIELDKEY, LABEL, TOOLTIP, REQUIRED)
			VALUES (10, 10, 'Priority', 'Priority', 'N');
INSERT INTO TFIELDCONFIG(OBJECTID, FIELDKEY, LABEL, TOOLTIP, REQUIRED)
			VALUES (11, 11, 'Severity', 'Severity', 'N');
-- Configs for system label fields
INSERT INTO TFIELDCONFIG(OBJECTID, FIELDKEY, LABEL, TOOLTIP, REQUIRED)
			VALUES (12, 12, 'Item No.', 'The item identification number', 'Y');
INSERT INTO TFIELDCONFIG(OBJECTID, FIELDKEY, LABEL, TOOLTIP, REQUIRED)
			VALUES (13, 13, 'Originator', 'Originator', 'Y');
INSERT INTO TFIELDCONFIG(OBJECTID, FIELDKEY, LABEL, TOOLTIP, REQUIRED)
			VALUES (14, 14, 'Create Date', 'Created on', 'Y');
INSERT INTO TFIELDCONFIG(OBJECTID, FIELDKEY, LABEL, TOOLTIP, REQUIRED)
			VALUES (15, 15, 'Last Modified', 'Last modified on this date', 'Y');
INSERT INTO TFIELDCONFIG(OBJECTID, FIELDKEY, LABEL, TOOLTIP, REQUIRED)
			VALUES (16, 16, 'Parent Issue', 'The parent issue', 'N');
-- Configs for required system textbox
INSERT INTO TFIELDCONFIG(OBJECTID, FIELDKEY, LABEL, TOOLTIP, REQUIRED)
			VALUES (17, 17, 'Synopsis', 'Synopsis', 'Y');
-- Configs for not required system textbox
INSERT INTO TFIELDCONFIG(OBJECTID, FIELDKEY, LABEL, TOOLTIP, REQUIRED)
			VALUES (18, 18, 'Build', 'Build', 'N');
INSERT INTO TFIELDCONFIG(OBJECTID, FIELDKEY, LABEL, TOOLTIP, REQUIRED, HISTORY)
			VALUES (19, 19, 'Start Date', 'Start Date', 'N', 'Y');
INSERT INTO TFIELDCONFIG(OBJECTID, FIELDKEY, LABEL, TOOLTIP, REQUIRED, HISTORY)
			VALUES (20, 20, 'End Date', 'End Date', 'N', 'Y');
INSERT INTO TFIELDCONFIG(OBJECTID, FIELDKEY, LABEL, TOOLTIP, REQUIRED)
			VALUES (21, 21, 'Description', 'Description', 'N');
INSERT INTO TFIELDCONFIG(OBJECTID, FIELDKEY, LABEL, TOOLTIP, REQUIRED)
			VALUES (22, 22, 'Private issue', 'set to deprecated to disable private issues', 'N');
INSERT INTO TFIELDCONFIG(OBJECTID, FIELDKEY, LABEL, TOOLTIP, REQUIRED)
			VALUES (23, 23, 'Comment', 'Comment', 'N');
INSERT INTO TFIELDCONFIG(OBJECTID, FIELDKEY, LABEL, TOOLTIP, REQUIRED)
			VALUES (24, 24, 'LastEditedBy', 'Last Edited By', 'Y');
INSERT INTO TFIELDCONFIG(OBJECTID, FIELDKEY, LABEL, TOOLTIP, REQUIRED)
			VALUES (25, 25, 'ArchiveLevel', 'Archive Level', 'N');
INSERT INTO TFIELDCONFIG(OBJECTID, FIELDKEY, LABEL, TOOLTIP, REQUIRED)
			VALUES (26, 26, 'SubmitterEmail', 'SubmitterEmail', 'N');
INSERT INTO TFIELDCONFIG(OBJECTID, FIELDKEY, LABEL, TOOLTIP, REQUIRED)
			VALUES (27, 27, 'WBS', 'WBS', 'N');
INSERT INTO TFIELDCONFIG(OBJECTID, FIELDKEY, LABEL, TOOLTIP, REQUIRED)
			VALUES (28, 28, 'ItemNo (Project specific)', 'ItemNo (Project specific)', 'N');
INSERT INTO TFIELDCONFIG(OBJECTID, FIELDKEY, LABEL, TOOLTIP, REQUIRED, HISTORY)
			VALUES (29, 29, 'Start date target', 'Start date target (top-down)', 'N', 'Y');
INSERT INTO TFIELDCONFIG(OBJECTID, FIELDKEY, LABEL, TOOLTIP, REQUIRED, HISTORY)
			VALUES (30, 30, 'End date target', 'End date target (top-down)', 'N', 'Y');
INSERT INTO TFIELDCONFIG(OBJECTID, FIELDKEY, LABEL, TOOLTIP, REQUIRED, HISTORY)
			VALUES (31, 31, 'Participants', 'Meeting participants', 'N', 'N');
INSERT INTO TFIELDCONFIG(OBJECTID, FIELDKEY, LABEL, TOOLTIP, REQUIRED, HISTORY)
			VALUES (32, 32, 'TaskIsMilestone', 'Is milestone', 'N', 'N');
INSERT INTO TFIELDCONFIG(OBJECTID, FIELDKEY, LABEL, TOOLTIP, REQUIRED, HISTORY)
			VALUES (33, 33, 'Duration', 'Duration', 'N', 'N');			
INSERT INTO TFIELDCONFIG(OBJECTID, FIELDKEY, LABEL, TOOLTIP, REQUIRED, HISTORY)
			VALUES (34, 34, 'Target duration', 'Target duration', 'N', 'N');
			
-- default notification filters
INSERT INTO TCLOB (OBJECTID, CLOBVALUE) VALUES (1, '<QUERY><AND id="0" negate="false"></AND></QUERY>');
INSERT INTO TQUERYREPOSITORY (OBJECTID, PERSON, LABEL, QUERYTYPE, REPOSITORYTYPE, QUERYKEY) VALUES(1,1,'Default Filter',2,2,1);
-- default notification triggers
INSERT INTO TNOTIFYTRIGGER (OBJECTID, LABEL, PERSON, ISSYSTEM) VALUES (1, 'Full Trigger', 1, 'Y');
INSERT INTO TNOTIFYTRIGGER (OBJECTID, LABEL, PERSON, ISSYSTEM) VALUES (2, 'Empty Trigger', 1, 'Y');
-- notify field for new item
INSERT INTO TNOTIFYFIELD (OBJECTID, ACTIONTYPE, FIELDTYPE, NOTIFYTRIGGER, ORIGINATOR, MANAGER, RESPONSIBLE, CONSULTANT, INFORMANT, OBSERVER)
VALUES (1, 1, 1, 1, 'N', 'Y', 'Y', 'Y', 'Y', 'N');
-- notify field for edit item fields
INSERT INTO TNOTIFYFIELD (OBJECTID, FIELD, ACTIONTYPE, FIELDTYPE, NOTIFYTRIGGER, ORIGINATOR, MANAGER, RESPONSIBLE, CONSULTANT, INFORMANT, OBSERVER)
VALUES (2, 1, 2, 1, 1, 'Y', 'Y', 'Y', 'Y', 'Y', 'N');
INSERT INTO TNOTIFYFIELD (OBJECTID, FIELD, ACTIONTYPE, FIELDTYPE, NOTIFYTRIGGER, ORIGINATOR, MANAGER, RESPONSIBLE, CONSULTANT, INFORMANT, OBSERVER)
VALUES (3, 2, 2, 1, 1, 'Y', 'Y', 'Y', 'Y', 'Y', 'N');
INSERT INTO TNOTIFYFIELD (OBJECTID, FIELD, ACTIONTYPE, FIELDTYPE, NOTIFYTRIGGER, ORIGINATOR, MANAGER, RESPONSIBLE, CONSULTANT, INFORMANT, OBSERVER)
VALUES (4, 4, 2, 1, 1, 'Y', 'Y', 'Y', 'Y', 'Y', 'N');
INSERT INTO TNOTIFYFIELD (OBJECTID, FIELD, ACTIONTYPE, FIELDTYPE, NOTIFYTRIGGER, ORIGINATOR, MANAGER, RESPONSIBLE, CONSULTANT, INFORMANT, OBSERVER)
VALUES (5, 5, 2, 1, 1, 'Y', 'Y', 'Y', 'Y', 'Y', 'N');
INSERT INTO TNOTIFYFIELD (OBJECTID, FIELD, ACTIONTYPE, FIELDTYPE, NOTIFYTRIGGER, ORIGINATOR, MANAGER, RESPONSIBLE, CONSULTANT, INFORMANT, OBSERVER)
VALUES (6, 6, 2, 1, 1, 'Y', 'Y', 'Y', 'Y', 'Y', 'N');
INSERT INTO TNOTIFYFIELD (OBJECTID, FIELD, ACTIONTYPE, FIELDTYPE, NOTIFYTRIGGER, ORIGINATOR, MANAGER, RESPONSIBLE, CONSULTANT, INFORMANT, OBSERVER)
VALUES (7, 8, 2, 1, 1, 'Y', 'Y', 'Y', 'Y', 'Y', 'N');
INSERT INTO TNOTIFYFIELD (OBJECTID, FIELD, ACTIONTYPE, FIELDTYPE, NOTIFYTRIGGER, ORIGINATOR, MANAGER, RESPONSIBLE, CONSULTANT, INFORMANT, OBSERVER)
VALUES (8, 9, 2, 1, 1, 'Y', 'Y', 'Y', 'Y', 'Y', 'N');
INSERT INTO TNOTIFYFIELD (OBJECTID, FIELD, ACTIONTYPE, FIELDTYPE, NOTIFYTRIGGER, ORIGINATOR, MANAGER, RESPONSIBLE, CONSULTANT, INFORMANT, OBSERVER)
VALUES (9, 10, 2, 1, 1, 'Y', 'Y', 'Y', 'Y', 'Y', 'N');
INSERT INTO TNOTIFYFIELD (OBJECTID, FIELD, ACTIONTYPE, FIELDTYPE, NOTIFYTRIGGER, ORIGINATOR, MANAGER, RESPONSIBLE, CONSULTANT, INFORMANT, OBSERVER)
VALUES (10, 11, 2, 1, 1, 'Y', 'Y', 'Y', 'Y', 'Y', 'N');
INSERT INTO TNOTIFYFIELD (OBJECTID, FIELD, ACTIONTYPE, FIELDTYPE, NOTIFYTRIGGER, ORIGINATOR, MANAGER, RESPONSIBLE, CONSULTANT, INFORMANT, OBSERVER)
VALUES (11, 16, 2, 1, 1, 'Y', 'Y', 'Y', 'Y', 'Y', 'N');
INSERT INTO TNOTIFYFIELD (OBJECTID, FIELD, ACTIONTYPE, FIELDTYPE, NOTIFYTRIGGER, ORIGINATOR, MANAGER, RESPONSIBLE, CONSULTANT, INFORMANT, OBSERVER)
VALUES (12, 17, 2, 1, 1, 'Y', 'Y', 'Y', 'Y', 'Y', 'N');
INSERT INTO TNOTIFYFIELD (OBJECTID, FIELD, ACTIONTYPE, FIELDTYPE, NOTIFYTRIGGER, ORIGINATOR, MANAGER, RESPONSIBLE, CONSULTANT, INFORMANT, OBSERVER)
VALUES (13, 18, 2, 1, 1, 'Y', 'Y', 'Y', 'Y', 'Y', 'N');
INSERT INTO TNOTIFYFIELD (OBJECTID, FIELD, ACTIONTYPE, FIELDTYPE, NOTIFYTRIGGER, ORIGINATOR, MANAGER, RESPONSIBLE, CONSULTANT, INFORMANT, OBSERVER)
VALUES (14, 19, 2, 1, 1, 'Y', 'Y', 'Y', 'Y', 'Y', 'N');
INSERT INTO TNOTIFYFIELD (OBJECTID, FIELD, ACTIONTYPE, FIELDTYPE, NOTIFYTRIGGER, ORIGINATOR, MANAGER, RESPONSIBLE, CONSULTANT, INFORMANT, OBSERVER)
VALUES (15, 20, 2, 1, 1, 'Y', 'Y', 'Y', 'Y', 'Y', 'N');
INSERT INTO TNOTIFYFIELD (OBJECTID, FIELD, ACTIONTYPE, FIELDTYPE, NOTIFYTRIGGER, ORIGINATOR, MANAGER, RESPONSIBLE, CONSULTANT, INFORMANT, OBSERVER)
VALUES (16, 21, 2, 1, 1, 'Y', 'Y', 'Y', 'Y', 'Y', 'N');
INSERT INTO TNOTIFYFIELD (OBJECTID, FIELD, ACTIONTYPE, FIELDTYPE, NOTIFYTRIGGER, ORIGINATOR, MANAGER, RESPONSIBLE, CONSULTANT, INFORMANT, OBSERVER)
VALUES (17, 23, 2, 1, 1, 'Y', 'Y', 'Y', 'Y', 'Y', 'N');
INSERT INTO TNOTIFYFIELD (OBJECTID, FIELD, ACTIONTYPE, FIELDTYPE, NOTIFYTRIGGER, ORIGINATOR, MANAGER, RESPONSIBLE, CONSULTANT, INFORMANT, OBSERVER)
VALUES (18, 29, 2, 1, 1, 'Y', 'Y', 'Y', 'Y', 'Y', 'N');
INSERT INTO TNOTIFYFIELD (OBJECTID, FIELD, ACTIONTYPE, FIELDTYPE, NOTIFYTRIGGER, ORIGINATOR, MANAGER, RESPONSIBLE, CONSULTANT, INFORMANT, OBSERVER)
VALUES (19, 30, 2, 1, 1, 'Y', 'Y', 'Y', 'Y', 'Y', 'N');
-- notify field for budget fields
INSERT INTO TNOTIFYFIELD (OBJECTID, FIELD, ACTIONTYPE, FIELDTYPE, NOTIFYTRIGGER, ORIGINATOR, MANAGER, RESPONSIBLE, CONSULTANT, INFORMANT, OBSERVER)
VALUES (20, 1, 2, 5, 1, 'Y', 'Y', 'Y', 'Y', 'Y', 'N');
INSERT INTO TNOTIFYFIELD (OBJECTID, FIELD, ACTIONTYPE, FIELDTYPE, NOTIFYTRIGGER, ORIGINATOR, MANAGER, RESPONSIBLE, CONSULTANT, INFORMANT, OBSERVER)
VALUES (21, 2, 2, 5, 1, 'Y', 'Y', 'Y', 'Y', 'Y', 'N');
-- notify field for planned value fields
INSERT INTO TNOTIFYFIELD (OBJECTID, FIELD, ACTIONTYPE, FIELDTYPE, NOTIFYTRIGGER, ORIGINATOR, MANAGER, RESPONSIBLE, CONSULTANT, INFORMANT, OBSERVER)
VALUES (22, 1, 2, 2, 1, 'Y', 'Y', 'Y', 'Y', 'Y', 'N');
INSERT INTO TNOTIFYFIELD (OBJECTID, FIELD, ACTIONTYPE, FIELDTYPE, NOTIFYTRIGGER, ORIGINATOR, MANAGER, RESPONSIBLE, CONSULTANT, INFORMANT, OBSERVER)
VALUES (23, 2, 2, 2, 1, 'Y', 'Y', 'Y', 'Y', 'Y', 'N');
-- notify field for edit estimated remaining budget fields
INSERT INTO TNOTIFYFIELD (OBJECTID, FIELD, ACTIONTYPE, FIELDTYPE, NOTIFYTRIGGER, ORIGINATOR, MANAGER, RESPONSIBLE, CONSULTANT, INFORMANT, OBSERVER)
VALUES (24, 1, 2, 3, 1, 'Y', 'Y', 'Y', 'Y', 'Y', 'N');
INSERT INTO TNOTIFYFIELD (OBJECTID, FIELD, ACTIONTYPE, FIELDTYPE, NOTIFYTRIGGER, ORIGINATOR, MANAGER, RESPONSIBLE, CONSULTANT, INFORMANT, OBSERVER)
VALUES (25, 2, 2, 3, 1, 'Y', 'Y', 'Y', 'Y', 'Y', 'N');
-- notify field for edit expense fields
INSERT INTO TNOTIFYFIELD (OBJECTID, FIELD, ACTIONTYPE, FIELDTYPE, NOTIFYTRIGGER, ORIGINATOR, MANAGER, RESPONSIBLE, CONSULTANT, INFORMANT, OBSERVER)
VALUES (26, 1, 2, 4, 1, 'Y', 'Y', 'Y', 'Y', 'Y', 'N');
INSERT INTO TNOTIFYFIELD (OBJECTID, FIELD, ACTIONTYPE, FIELDTYPE, NOTIFYTRIGGER, ORIGINATOR, MANAGER, RESPONSIBLE, CONSULTANT, INFORMANT, OBSERVER)
VALUES (27, 2, 2, 4, 1, 'Y', 'Y', 'Y', 'Y', 'Y', 'N');
-- default notify setting for all projects
INSERT INTO TNOTIFYSETTINGS (OBJECTID, PROJECT, NOTIFYTRIGGER, NOTIFYFILTER)
VALUES (1, 0, 1, 1);

INSERT INTO TPSTATE (OBJECTID, STATE, PROJECTTYPE, LISTTYPE) VALUES (1, 1, 0, -3);
INSERT INTO TPSTATE (OBJECTID, STATE, PROJECTTYPE, LISTTYPE) VALUES (2, 8, 0, -3);
INSERT INTO TPSTATE (OBJECTID, STATE, PROJECTTYPE, LISTTYPE) VALUES (3, 1, 0, 5);
INSERT INTO TPSTATE (OBJECTID, STATE, PROJECTTYPE, LISTTYPE) VALUES (4, 3, 0, 5);
INSERT INTO TPSTATE (OBJECTID, STATE, PROJECTTYPE, LISTTYPE) VALUES (5, 8, 0, 5);

INSERT INTO TCOSTCENTER (OBJECTID, COSTCENTERNUMBER, COSTCENTERNAME) VALUES (1, '8500', 'Development');
INSERT INTO TACCOUNT (OBJECTID, ACCOUNTNUMBER, ACCOUNTNAME, STATUS, COSTCENTER) VALUES	(1, '350', 'Research & development', 13, 1);
INSERT INTO TACCOUNT (OBJECTID, ACCOUNTNUMBER, ACCOUNTNAME, STATUS, COSTCENTER) VALUES	(2, '351', 'SW development', 13, 1);


-- LINK TYPES
-- duplicates   is duplicated by    issues duplicated by these   all their duplicates
-- is implementation for requirement    is requirement for implementation    its requirements   its implementations
-- is test for requirement     is requirement for test   its associated requirements   its associated tests

INSERT INTO TLINKTYPE (OBJECTID, NAME, REVERSENAME, LEFTTORIGHTFIRST, RIGHTTOLEFTFIRST, LINKDIRECTION, LINKTYPEPLUGIN)
	VALUES	(1, 'duplicate of', 'duplicated by', 'duplicates of these issues', 'duplicated by these issues', 3, 'com.aurel.track.linkType.GenericLinkType');
INSERT INTO TLINKTYPE (OBJECTID, NAME, REVERSENAME, LEFTTORIGHTFIRST, RIGHTTOLEFTFIRST, LINKDIRECTION, LINKTYPEPLUGIN)
	VALUES	(3, 'close depends on', null, 'close depends on these issues', null, 2, 'com.aurel.track.linkType.CloseDependsOnLinkType');

INSERT INTO QRTZ_LOCKS values('TRIGGER_ACCESS');
INSERT INTO QRTZ_LOCKS values('JOB_ACCESS');
INSERT INTO QRTZ_LOCKS values('CALENDAR_ACCESS');
INSERT INTO QRTZ_LOCKS values('STATE_ACCESS');
INSERT INTO QRTZ_LOCKS values('MISFIRE_ACCESS');
