--
-- Project:      Track+
--
-- Date Created:  Monday, September 30, 2013
--
--
-- Populates the Track+ database with some useful defaults

-- SET NAMES ISO8859_1

--  default screens
-- INSERT INTO TSCREEN (OBJECTID,NAME,LABEL,DESCRIPTION,OWNER) VALUES (1,'Default form (NEW)','Default Mask (NEW)','The default input mask for creating new items', 1);
-- INSERT INTO TSCREEN (OBJECTID,NAME,LABEL,DESCRIPTION,OWNER) VALUES (2,'Default form (EDIT)','Default Mask (EDIT)','The default input mask for editing items', 1);
-- INSERT INTO TSCREEN (OBJECTID,NAME,LABEL,DESCRIPTION,OWNER) VALUES (3,'Default form (MOVE)','Default Mask (OTHER)','The default mask for other actions', 1);
-- INSERT INTO TSCREEN (OBJECTID,NAME,LABEL,DESCRIPTION,OWNER) VALUES (4,'Default form (NEW CHILD)','Copy of Default Mask (NEW)','The default input mask for creating new items', 1);
-- INSERT INTO TSCREEN (OBJECTID,NAME,LABEL,DESCRIPTION,OWNER) VALUES (5,'Default form (CHANGE STATUS)','Copy of Default Mask (OTHER)','The default mask for other actions', 1);
-- INSERT INTO TSCREEN (OBJECTID,NAME,LABEL,DESCRIPTION,OWNER) VALUES (6,'Meeting form (NEW/EDIT)','Meeting form','A form for meetings', 1);

--  default screenConfigs for action:new,edit,Move
INSERT INTO TSCREENCONFIG (OBJECTID,SCREEN,ACTIONKEY) VALUES (1,1007,1);
INSERT INTO TSCREENCONFIG (OBJECTID,SCREEN,ACTIONKEY) VALUES (2,1003,2);
INSERT INTO TSCREENCONFIG (OBJECTID,SCREEN,ACTIONKEY) VALUES (3,1005,3);
INSERT INTO TSCREENCONFIG (OBJECTID,SCREEN,ACTIONKEY) VALUES (4,1006,4);
INSERT INTO TSCREENCONFIG (OBJECTID,SCREEN,ACTIONKEY) VALUES (5,1002,5);

-- Action item
INSERT INTO TSCREENCONFIG (OBJECTID,SCREEN,ISSUETYPE,ACTIONKEY) VALUES (8, 1000, 5, 1);
INSERT INTO TSCREENCONFIG (OBJECTID,SCREEN,ISSUETYPE,ACTIONKEY) VALUES (9, 1000, 5, 2);
-- Bug report
INSERT INTO TSCREENCONFIG (OBJECTID,SCREEN,ISSUETYPE,ACTIONKEY) VALUES (10, 1001, 1, 1);
INSERT INTO TSCREENCONFIG (OBJECTID,SCREEN,ISSUETYPE,ACTIONKEY) VALUES (11, 1001, 1, 2);




