/*
 * Project:      Track+
 * Author:       Joerg Friedrich
 *
 * Date Created: Thursday, June 24, 2004
 *
 * Updates the database from previous database release 2.0 to 3.0
 * 
 *//*
 * Project:      Track+
 * Author:       Joerg Friedrich
 *
 * Date Created: Thursday, June 24, 2004
 *
 * Updates the database from previous database release 2.0 to 3.0
 * 
 */

drop table TATTACHMENT;

-- TBASELINE
ALTER TABLE TBASELINE ADD ESTIMATEDHOURS DOUBLE PRECISION;
ALTER TABLE TBASELINE ADD ESTIMATEDCOST DOUBLE PRECISION;
ALTER TABLE TBASELINE ADD CURRENCY integer;

-- TCATEGORY
ALTER TABLE TCATEGORY ADD SORTORDER integer;

-- TNOTIFY
ALTER TABLE TNOTIFY ADD WORKITEM integer;

-- TPERSON
ALTER TABLE TPERSON ADD TOKENPASSWD VARCHAR(80);
ALTER TABLE TPERSON ADD TOKENEXPDATE timestamp;
ALTER TABLE TPERSON ADD EMAILFREQUENCY integer;
ALTER TABLE TPERSON ADD EMAILLEAD integer;
ALTER TABLE TPERSON ADD EMAILLASTREMINDED timestamp;
ALTER TABLE TPERSON ADD EMAILREMINDME CHAR(1) default 'N';
ALTER TABLE TPERSON ADD PREFEMAILTYPE VARCHAR(15) default 'Plain';
ALTER TABLE TPERSON ADD PREFLOCALE VARCHAR(10);
ALTER TABLE TPERSON ADD MYDEFAULTREPORT integer;
ALTER TABLE TPERSON ADD NOEMAILSPLEASE INTEGER;

-- TPRIORITY
ALTER TABLE TPRIORITY ADD SORTORDER integer;

-- TPROJECT
ALTER TABLE TPROJECT ADD DEFMANAGER integer;
ALTER TABLE TPROJECT ADD PROJECTTYPE integer;

-- TROLE
ALTER TABLE TROLE ADD EXTENDEDACCESSKEY VARCHAR(30);
ALTER TABLE TROLE ADD PROJECTTYPE integer;

-- TSEVERITY
ALTER TABLE TSEVERITY ADD SORTORDER integer;

-- TSTATE
ALTER TABLE TSTATE ADD SORTORDER integer;

-- TWORKITEM
ALTER TABLE TWORKITEM ADD ESTIMATEDHOURS DOUBLE PRECISION;
ALTER TABLE TWORKITEM ADD ESTIMATEDCOST DOUBLE PRECISION;
ALTER TABLE TWORKITEM ADD CURRENCY integer;
ALTER TABLE TWORKITEM ADD ACTUALSTARTDATE timestamp;
ALTER TABLE TWORKITEM ADD ACTUALENDDATE timestamp;

CREATE INDEX TWIINDEX15 ON TWORKITEM (ACTUALSTARTDATE);
CREATE INDEX TWIINDEX16 ON TWORKITEM (ACTUALENDDATE);

CREATE TABLE TPRIVATEREPORTREPOSITORY
(
	"PKEY" INTEGER NOT NULL,
	"OWNER" INTEGER NOT NULL,
	"NAME" VARCHAR(100) NOT NULL,
	"QUERY" VARCHAR(10000) NOT NULL,
	PRIMARY KEY(PKEY)
);


CREATE TABLE TPUBLICREPORTREPOSITORY
(
	"PKEY" INTEGER NOT NULL,
	"OWNER" INTEGER NOT NULL,
	"NAME" VARCHAR(100) NOT NULL,
	"QUERY" VARCHAR(10000) NOT NULL,
	PRIMARY KEY(PKEY)
);


CREATE TABLE TPROJECTREPORTREPOSITORY
(
	"PKEY" INTEGER NOT NULL,
	"PROJECT" INTEGER NOT NULL,
	"NAME" VARCHAR(100) NOT NULL,
	"QUERY" VARCHAR(10000) NOT NULL,
	PRIMARY KEY(PKEY)
);

-- TACCOUNT
CREATE TABLE TACCOUNT
(
	OBJECTID integer NOT NULL,
	ACCOUNTNUMBER VARCHAR(30) NOT NULL,
	PROJECT integer NOT NULL,
    PRIMARY KEY(OBJECTID)
);

-- TATTACHMENT
CREATE TABLE TATTACHMENT
(
	OBJECTID integer NOT NULL,
	WORKITEM integer NOT NULL,
	CHANGEDBY integer,
	DOCUMENTSTATE integer,
	FILENAME VARCHAR(256) NOT NULL,
	FILESIZE VARCHAR(20),
	MIMETYPE VARCHAR(15),
	LASTEDIT timestamp,
	VERSION VARCHAR(20),
	DESCRIPTION VARCHAR(10000),
	CRYPTKEY VARCHAR(4096),
	ISENCRYPTED CHAR(1) default 'N',
	ISDELETED CHAR(1) default 'N',
    PRIMARY KEY(OBJECTID)
);

-- TCOST
CREATE TABLE TCOST
(
	OBJECTID integer NOT NULL,
	ACCOUNT integer,
	PERSON integer,
	WORKITEM integer,
	HOURS DOUBLE PRECISION,
	COST DOUBLE PRECISION,
	CURRENCY integer,
    PRIMARY KEY(OBJECTID)
);

-- TCURRENCY
CREATE TABLE TCURRENCY
(
	OBJECTID integer NOT NULL,
	CURRENCY VARCHAR (10) NOT NULL,
	CONVERSIONFACTOR DOUBLE PRECISION NOT NULL,
    PRIMARY KEY(OBJECTID)
);

-- TDOCSTATE
CREATE TABLE TDOCSTATE
(
	OBJECTID integer NOT NULL,
	LABEL VARCHAR (25) NOT NULL,
	STATEFLAG integer,
	PROJECTTYPE integer,
    PRIMARY KEY(OBJECTID)
);

-- TDISABLEFIELD
CREATE TABLE TDISABLEFIELD
(
	OBJECTID integer NOT NULL,
	FIELDNAME VARCHAR(25) NOT NULL,
	LISTTYPE integer,
	PROJECTTYPE integer,
    PRIMARY KEY(OBJECTID)
);

-- TPCURRENCY
CREATE TABLE TPCURRENCY
(
	OBJECTID integer NOT NULL,
	CURRENCY integer,
	PROJECTTYPE integer,
    PRIMARY KEY(OBJECTID)
);

-- TPLISTTYPE
CREATE TABLE TPLISTTYPE
(
	OBJECTID integer NOT NULL,
	PROJECTTYPE integer,
	CATEGORY integer,
    PRIMARY KEY(OBJECTID)
);

-- TPROJECTTYPE
CREATE TABLE TPROJECTTYPE
(
	OBJECTID integer NOT NULL,
	LABEL VARCHAR (35),
    NOTIFYOWNERLEVEL INTEGER,
    NOTIFYMANAGERLEVEL INTEGER,
    PRIMARY KEY(OBJECTID)
);



-- TPSTATE
CREATE TABLE TPSTATE
(
	OBJECTID integer NOT NULL,
	STATE integer,
	PROJECTTYPE integer,
    LISTTYPE INTEGER NOT NULL,
    PRIMARY KEY(OBJECTID)
);

-- TSITE
CREATE TABLE TSITE
(
	OBJECTID integer NOT NULL,
	TRACKVERSION VARCHAR (10),
	DBVERSION VARCHAR (10),
	LICENSEKEY VARCHAR (80),
	EXPDATE date,
	NUMBEROFUSERS integer,
	TRACKEMAIL VARCHAR (100),
	SMTPSERVERNAME VARCHAR (100),
	SMTPPORT integer,
	MAILENCODING VARCHAR (20),
	SMTPUSER VARCHAR (100),
	SMTPPASSWORD VARCHAR (30),
	POPSERVERNAME VARCHAR (100),
	POPPORT integer,
	POPUSER VARCHAR (100),
	POPPASSWORD VARCHAR (30),
	ALLOWEDEMAILPATTERN VARCHAR(20000),
	ISLDAPON CHAR(1),
	LDAPSERVERURL VARCHAR (100),
	LDAPATTRIBUTELOGINNAME VARCHAR (10),
	ATTACHMENTROOTDIR VARCHAR(512),
	SERVERURL VARCHAR (100),
	DESCRIPTIONLENGTH integer,
	ISSELFREGISTERALLOWED CHAR(1) default 'Y',
	ISDEMOSITE CHAR(1) default 'N',
    USETRACKFROMADDRESS CHAR (1) default 'Y',
    RESERVEDUSE INTEGER,
    PRIMARY KEY(OBJECTID)
);

-- TWORKFLOW
CREATE TABLE TWORKFLOW
(
	OBJECTID integer NOT NULL,
	STATEFROM integer,
	STATETO integer,
	MAYCHANGEROLE integer,
	CHANGETOROLE integer,
	PROJECTTYPE integer,
    LISTTYPE integer NOT NULL,
    PRIMARY KEY(OBJECTID)
);

/* --------------------------------------------------------------------------
TROLELISTTYPE
-------------------------------------------------------------------------- */
CREATE TABLE TROLELISTTYPE
(
    "OBJECTID" INTEGER NOT NULL,
    "PROLE" INTEGER NOT NULL,
    "LISTTYPE" INTEGER NOT NULL,
    PRIMARY KEY(OBJECTID)
);


ALTER TABLE TBASELINE 
	ADD CONSTRAINT TBASELINE_FK_3 FOREIGN KEY (CURRENCY)
		REFERENCES TCURRENCY (OBJECTID);

ALTER TABLE TNOTIFY
	ADD CONSTRAINT TNOTIFY_FK_4 FOREIGN KEY (WORKITEM)
		REFERENCES TWORKITEM (WORKITEMKEY);

ALTER TABLE TPERSON
        ADD CONSTRAINT TPERSON_FK_2 FOREIGN KEY (MYDEFAULTREPORT)
            REFERENCES TPRIVATEREPORTREPOSITORY (PKEY);
                        
ALTER TABLE TPROJECT
	ADD CONSTRAINT TPROJECT_FK_3 FOREIGN KEY (DEFMANAGER)
		REFERENCES TPERSON (PKEY);
ALTER TABLE TPROJECT
	ADD CONSTRAINT TPROJECT_FK_4 FOREIGN KEY (PROJECTTYPE)
		REFERENCES TPROJECTTYPE (OBJECTID);

ALTER TABLE TROLE
	ADD CONSTRAINT TROLE_FK_1 FOREIGN KEY (PROJECTTYPE)
		REFERENCES TPROJECTTYPE (OBJECTID);
		
ALTER TABLE TWORKITEM
	ADD CONSTRAINT TWORKITEM_FK_13 FOREIGN KEY (CURRENCY)
		REFERENCES TCURRENCY (OBJECTID);
		
ALTER TABLE TPRIVATEREPORTREPOSITORY
	ADD CONSTRAINT TPRIVATEREPORTREPOSITORY_FK_1 FOREIGN KEY (OWNER)
		REFERENCES TPERSON (PKEY);


ALTER TABLE TPUBLICREPORTREPOSITORY
	ADD CONSTRAINT TPUBLICREPORTREPOSITORY_FK_1 FOREIGN KEY (OWNER)
		REFERENCES TPERSON (PKEY);


ALTER TABLE TPROJECTREPORTREPOSITORY
	ADD CONSTRAINT TPROJECTREPORTREPOSITORY_FK_1 FOREIGN KEY (PROJECT)
		REFERENCES TPROJECT (PKEY);

		
ALTER TABLE TACCOUNT
	ADD CONSTRAINT TACCOUNT_FK_1 FOREIGN KEY (PROJECT)
		REFERENCES TPROJECT (PKEY);

ALTER TABLE TATTACHMENT
	ADD CONSTRAINT TATTACHMENT_FK_1 FOREIGN KEY (WORKITEM)
		REFERENCES TWORKITEM (WORKITEMKEY);
ALTER TABLE TATTACHMENT
	ADD CONSTRAINT TATTACHMENT_FK_2 FOREIGN KEY (CHANGEDBY)
		REFERENCES TPERSON (PKEY);
ALTER TABLE TATTACHMENT
	ADD CONSTRAINT TATTACHMENT_FK_3 FOREIGN KEY (DOCUMENTSTATE)
		REFERENCES TDOCSTATE (OBJECTID);

ALTER TABLE TCOST
	ADD CONSTRAINT TCOST_FK_1 FOREIGN KEY (ACCOUNT)
		REFERENCES TACCOUNT (OBJECTID);
ALTER TABLE TCOST
	ADD CONSTRAINT TCOST_FK_2 FOREIGN KEY (PERSON)
		REFERENCES TPERSON (PKEY);
ALTER TABLE TCOST
	ADD CONSTRAINT TCOST_FK_3 FOREIGN KEY (WORKITEM)
		REFERENCES TWORKITEM (WORKITEMKEY);
ALTER TABLE TCOST
	ADD CONSTRAINT TCOST_FK_4 FOREIGN KEY (CURRENCY)
		REFERENCES TCURRENCY (OBJECTID);

ALTER TABLE TDOCSTATE
	ADD CONSTRAINT TDOCSTATE_FK_1 FOREIGN KEY (PROJECTTYPE)
		REFERENCES TPROJECTTYPE (OBJECTID);

ALTER TABLE TDISABLEFIELD
	ADD CONSTRAINT TDISABLEFIELD_FK_1 FOREIGN KEY (LISTTYPE)
		REFERENCES TCATEGORY (PKEY);
ALTER TABLE TDISABLEFIELD
	ADD CONSTRAINT TDISABLEFIELD_FK_2 FOREIGN KEY (PROJECTTYPE)
		REFERENCES TPROJECTTYPE (OBJECTID);

ALTER TABLE TPCURRENCY
	ADD CONSTRAINT TPCURRENCY_FK_1 FOREIGN KEY (CURRENCY)
		REFERENCES TCURRENCY (OBJECTID);
ALTER TABLE TPCURRENCY
	ADD CONSTRAINT TPCURRENCY_FK_2 FOREIGN KEY (PROJECTTYPE)
		REFERENCES TPROJECTTYPE (OBJECTID);

ALTER TABLE TPLISTTYPE
	ADD CONSTRAINT TPLISTTYPE_FK_1 FOREIGN KEY (PROJECTTYPE)
		REFERENCES TPROJECTTYPE (OBJECTID);
ALTER TABLE TPLISTTYPE
	ADD CONSTRAINT TPLISTTYPE_FK_2 FOREIGN KEY (CATEGORY)
		REFERENCES TCATEGORY (PKEY);

ALTER TABLE TPSTATE
	ADD CONSTRAINT TPSTATE_FK_1 FOREIGN KEY (STATE)
		REFERENCES TSTATE (PKEY);
ALTER TABLE TPSTATE
	ADD CONSTRAINT TPSTATE_FK_2 FOREIGN KEY (PROJECTTYPE)
		REFERENCES TPROJECTTYPE (OBJECTID);
ALTER TABLE TPSTATE
    ADD CONSTRAINT TPSTATE_FK_3 FOREIGN KEY (LISTTYPE) 
        REFERENCES TCATEGORY (PKEY);

ALTER TABLE TWORKFLOW
	ADD CONSTRAINT TWORKFLOW_FK_1 FOREIGN KEY (STATEFROM)
		REFERENCES TSTATE (PKEY);
ALTER TABLE TWORKFLOW
	ADD CONSTRAINT TWORKFLOW_FK_2 FOREIGN KEY (STATETO)
		REFERENCES TSTATE (PKEY);
ALTER TABLE TWORKFLOW
	ADD CONSTRAINT TWORKFLOW_FK_3 FOREIGN KEY (MAYCHANGEROLE)
		REFERENCES TROLE (PKEY);
ALTER TABLE TWORKFLOW
	ADD CONSTRAINT TWORKFLOW_FK_4 FOREIGN KEY (CHANGETOROLE)
		REFERENCES TROLE (PKEY);
ALTER TABLE TWORKFLOW
	ADD CONSTRAINT TWORKFLOW_FK_5 FOREIGN KEY (PROJECTTYPE)
		REFERENCES TPROJECTTYPE (OBJECTID);

ALTER TABLE TWORKFLOW
	ADD CONSTRAINT TWORKFLOW_FK_6 FOREIGN KEY (LISTTYPE) 
        REFERENCES TCATEGORY (PKEY);

ALTER TABLE TROLELISTTYPE
    ADD CONSTRAINT TROLELISTTYPE_FK_1 FOREIGN KEY (PROLE) 
        REFERENCES TROLE (PKEY);
ALTER TABLE TROLELISTTYPE
    ADD CONSTRAINT TROLELISTTYPE_FK_2 FOREIGN KEY (LISTTYPE) 
        REFERENCES TCATEGORY (PKEY);


INSERT INTO ID_TABLE (ID_TABLE_ID, TABLE_NAME, NEXT_ID, QUANTITY) 
VALUES (21, 'TPRIVATEREPORTREPOSITORY', 1, 1);


INSERT INTO ID_TABLE (ID_TABLE_ID, TABLE_NAME, NEXT_ID, QUANTITY) 
VALUES (22, 'TPROJECTREPORTREPOSITORY', 1, 1);


INSERT INTO ID_TABLE (ID_TABLE_ID, TABLE_NAME, NEXT_ID, QUANTITY) 
VALUES (23, 'TPUBLICREPORTREPOSITORY', 1, 1);


INSERT INTO ID_TABLE (ID_TABLE_ID, TABLE_NAME, NEXT_ID, QUANTITY) VALUES
			(24, 'TPLISTTYPE', 1, 1);

INSERT INTO ID_TABLE (ID_TABLE_ID, TABLE_NAME, NEXT_ID, QUANTITY) VALUES
			(25, 'TPTDISABLEFIELD', 1, 1);

INSERT INTO ID_TABLE (ID_TABLE_ID, TABLE_NAME, NEXT_ID, QUANTITY) VALUES
			(26, 'TCOST', 1, 1);

INSERT INTO ID_TABLE (ID_TABLE_ID, TABLE_NAME, NEXT_ID, QUANTITY) VALUES
			(27, 'TACCOUNT', 1, 1);

INSERT INTO ID_TABLE (ID_TABLE_ID, TABLE_NAME, NEXT_ID, QUANTITY) VALUES
			(28, 'TCURRENCY', 3, 1);

INSERT INTO ID_TABLE (ID_TABLE_ID, TABLE_NAME, NEXT_ID, QUANTITY) VALUES
			(29, 'TPCURRENCY', 1, 1);

INSERT INTO ID_TABLE (ID_TABLE_ID, TABLE_NAME, NEXT_ID, QUANTITY) VALUES
			(30, 'TPROJECTTYPE', 1, 1);

INSERT INTO ID_TABLE (ID_TABLE_ID, TABLE_NAME, NEXT_ID, QUANTITY) VALUES
			(31, 'TPSTATE', 1, 1);

INSERT INTO ID_TABLE (ID_TABLE_ID, TABLE_NAME, NEXT_ID, QUANTITY) VALUES
			(32, 'TWORKFLOW', 1, 1);

INSERT INTO ID_TABLE (ID_TABLE_ID, TABLE_NAME, NEXT_ID, QUANTITY) VALUES
			(33, 'TDOCSTATE', 5, 1);

INSERT INTO ID_TABLE (ID_TABLE_ID, TABLE_NAME, NEXT_ID, QUANTITY) VALUES
			(34, 'TSITE', 1, 1);

INSERT INTO ID_TABLE (ID_TABLE_ID, TABLE_NAME, NEXT_ID, QUANTITY) VALUES
			(35, 'TROLELISTTYPE', 1, 1);

COMMIT;










