INSERT INTO ID_TABLE (ID_TABLE_ID, TABLE_NAME, NEXT_ID, QUANTITY) VALUES(88, 'TCOMPUTEDVALUES', 1, 1);
INSERT INTO ID_TABLE (ID_TABLE_ID, TABLE_NAME, NEXT_ID, QUANTITY) VALUES(89, 'TLINKTYPE', 1, 1);

ALTER TABLE TREPORTLAYOUT DROP CONSTRAINT TREPORTLAYOUT_FK_4;
ALTER TABLE TREPORTLAYOUT ADD FIELDTYPE INTEGER;

DROP TABLE TCOMPUTEDVALUES;
CREATE TABLE TCOMPUTEDVALUES
(
    PKEY INTEGER NOT NULL,
    WORKITEMKEY INTEGER NOT NULL,
    EFFORTTYPE INTEGER NOT NULL,
    COMPUTEDVALUETYPE INTEGER NOT NULL,
    COMPUTEDVALUE DOUBLE PRECISION,
    MEASUREMENTUNIT INTEGER,
    PERSON INTEGER,
    PRIMARY KEY(PKEY)
);
ALTER TABLE TCOMPUTEDVALUES
    ADD CONSTRAINT TCOMPUTEDVALUES_FK_1 FOREIGN KEY (WORKITEMKEY)
    REFERENCES TWORKITEM (WORKITEMKEY)
;
ALTER TABLE TCOMPUTEDVALUES
    ADD CONSTRAINT TCOMPUTEDVALUES_FK_2 FOREIGN KEY (PERSON)
    REFERENCES TPERSON (PKEY)
;


DROP TABLE TLOCALIZEDRESOURCES;
CREATE TABLE TLOCALIZEDRESOURCES
(
    OBJECTID INTEGER NOT NULL,
    TABLENAME VARCHAR (255),
    PRIMARYKEYVALUE INTEGER,
    FIELDNAME VARCHAR (255) NOT NULL,
    LOCALIZEDTEXT VARCHAR (255),
    LOCALE VARCHAR (20),
    PRIMARY KEY(OBJECTID)
);

CREATE TABLE TLINKTYPE
(
    OBJECTID INTEGER NOT NULL,
    NAME VARCHAR (255) NOT NULL,
    MOREPROPS VARCHAR (10000),
    PRIMARY KEY(OBJECTID)
);
ALTER TABLE TWORKITEMLINK
    ADD CONSTRAINT TWORKITEMLINK_FK_3 FOREIGN KEY (LINKTYPE)
    REFERENCES TLINKTYPE (OBJECTID);
	
update TSTATE set symbol='opened.gif' where pkey=1;
update TSTATE set symbol='analyzed.gif' where pkey=2;
update TSTATE set symbol='assigned.gif' where pkey=3;
update TSTATE set symbol='suspended.gif' where pkey=4;
update TSTATE set symbol='processing.gif' where pkey=5;
update TSTATE set symbol='implemented.gif' where pkey=6;
update TSTATE set symbol='integrated.gif' where pkey=7;
update TSTATE set symbol='closed.gif' where pkey=8;
update TSTATE set symbol='assessing.gif' where pkey=9;

update TPRIORITY set symbol='occasionally.gif' where pkey=1;
update TPRIORITY set symbol='soon.gif' where pkey=2;
update TPRIORITY set symbol='immediate.gif' where pkey=3;

update TSEVERITY set symbol='minor.gif' where pkey=1;
update TSEVERITY set symbol='major.gif' where pkey=2;
update TSEVERITY set symbol='blocker.gif' where pkey=3;
commit;