-- Firebird update script 310 to 320
-- $Id: migrate310to320.sql 658 2009-01-02 10:48:52Z friedj $

-- TATTRIBUTEOPTION
ALTER TABLE TATTRIBUTEOPTION ADD SORTORDER INTEGER;

/* Table: TREPORTLAYOUT */

ALTER TABLE "TREPORTLAYOUT" DROP CONSTRAINT "TREPORTLAYOUT_FK_4";
ALTER TABLE "TREPORTLAYOUT" ADD CONSTRAINT "TREPORTLAYOUT_FK_4" FOREIGN KEY ("REPORTFIELD") REFERENCES TATTRIBUTE ("OBJECTID");

ALTER TABLE TSITE ADD "PREFERENCES" VARCHAR(8000);

/* Additional changes from 3.2.0 B1 to 3.2.0 B2 */

ALTER TABLE TNOTIFY ADD "RACIROLE" VARCHAR (1);
ALTER TABLE TNOTIFY ADD "THEGROUP" INTEGER;

ALTER TABLE TPERSON ADD "EMPLOYEEID" VARCHAR(30);

ALTER TABLE TACCOUNT DROP CONSTRAINT TACCOUNT_FK_1;
ALTER TABLE TACCOUNT DROP "PROJECT";

ALTER TABLE TACCOUNT ADD "ACCOUNTNAME" VARCHAR (80);
ALTER TABLE TACCOUNT ADD "ACTIVE" VARCHAR (1);
ALTER TABLE TACCOUNT ADD "COSTCENTER" VARCHAR (20);


/* --------------------------------------------------------------------------
TPROJECTACCOUNT
-------------------------------------------------------------------------- */
CREATE TABLE TPROJECTACCOUNT
(
            "ACCOUNT" INTEGER NOT NULL,
            "PROJECT" INTEGER NOT NULL,
    PRIMARY KEY(ACCOUNT,PROJECT)
);


/* --------------------------------------------------------------------------
TGROUP
-------------------------------------------------------------------------- */
CREATE TABLE TGROUP
(
            "OBJECTID" INTEGER NOT NULL,
            "EMAIL" VARCHAR (60),
            "PREFERENCES" VARCHAR(2000),
    PRIMARY KEY(OBJECTID)
);


/* --------------------------------------------------------------------------
TGROUPMEMBER
-------------------------------------------------------------------------- */
CREATE TABLE TGROUPMEMBER
(
            "OBJECTID" INTEGER NOT NULL,
            "THEGROUP" INTEGER NOT NULL,
            "PERSON" INTEGER NOT NULL,
    PRIMARY KEY(OBJECTID)
);

    ALTER TABLE TPROJECTACCOUNT
        ADD CONSTRAINT TPROJECTACCOUNT_FK_1 FOREIGN KEY (PROJECT)
            REFERENCES TPROJECT (PKEY);


    ALTER TABLE TPROJECTACCOUNT
        ADD CONSTRAINT TPROJECTACCOUNT_FK_2 FOREIGN KEY (ACCOUNT)
            REFERENCES TACCOUNT (OBJECTID);


    ALTER TABLE TGROUPMEMBER
        ADD CONSTRAINT TGROUPMEMBER_FK_1 FOREIGN KEY (THEGROUP)
            REFERENCES TGROUP (OBJECTID);


    ALTER TABLE TGROUPMEMBER
        ADD CONSTRAINT TGROUPMEMBER_FK_2 FOREIGN KEY (PERSON)
            REFERENCES TPERSON (PKEY);
            
    ALTER TABLE TNOTIFY ADD CONSTRAINT TNOTIFY_FK_5 FOREIGN KEY (THEGROUP)
            REFERENCES TGROUP (OBJECTID);

INSERT INTO ID_TABLE (ID_TABLE_ID, TABLE_NAME, NEXT_ID, QUANTITY) VALUES
			(47, 'TGROUP', 1, 1);

INSERT INTO ID_TABLE (ID_TABLE_ID, TABLE_NAME, NEXT_ID, QUANTITY) VALUES
			(48, 'TGROUPMEMBER', 1, 1);

UPDATE ID_TABLE SET NEXT_ID=14 WHERE TABLE_NAME='TCATEGORY';
