UPDATE TCATEGORY SET SYMBOL='task.png' WHERE SYMBOL='task.gif';
UPDATE TCATEGORY SET SYMBOL='problemReport.png' WHERE SYMBOL='problemReport.gif';
UPDATE TCATEGORY SET SYMBOL='actionItem.png' WHERE SYMBOL='actionItem.gif';
UPDATE TCATEGORY SET SYMBOL='requirements.png' WHERE SYMBOL='requirements.gif';

UPDATE TPRIORITY SET SYMBOL='occasionally.png' WHERE SYMBOL='occasionally.gif';
UPDATE TPRIORITY SET SYMBOL='soon.png' WHERE SYMBOL='soon.gif';
UPDATE TPRIORITY SET SYMBOL='immediate.png' WHERE SYMBOL='immediate.gif';

UPDATE TSEVERITY SET SYMBOL='minor.png' WHERE SYMBOL='minor.gif';
UPDATE TSEVERITY SET SYMBOL='major.png' WHERE SYMBOL='major.gif';
UPDATE TSEVERITY SET SYMBOL='blocker.png' WHERE SYMBOL='blocker.gif';

ALTER TABLE CLUSTERNODE ADD RELOADCHANGES VARCHAR (255);
ALTER TABLE TDEPARTMENT ADD PARENT INTEGER;
ALTER TABLE TPROJECT ADD PARENT INTEGER;
ALTER TABLE TPROJECT ADD TAGLABEL VARCHAR (50);
ALTER TABLE TRELEASE ADD PARENT INTEGER;
ALTER TABLE TWORKITEM ADD PROJECTKEY INTEGER;
ALTER TABLE TFIELD ADD FILTERFIELD CHAR (1) default 'N';
ALTER TABLE TEXPORTTEMPLATE ADD DELETED CHAR (1) default 'N';
ALTER TABLE TLIST ADD TAGLABEL VARCHAR (50);
ALTER TABLE TSCREEN ADD TAGLABEL VARCHAR (50);

DROP INDEX TPROJECTINDEXIDPF;
ALTER TABLE TPROJECT DROP PREFIX;
ALTER TABLE TPROJECT ADD PREFIX VARCHAR (50);
ALTER TABLE TPROJECT ADD NEXTITEMID INTEGER;

ALTER TABLE TROLEFIELD DROP CONSTRAINT TROLEFIELD_FK_2;

ALTER TABLE TPROJECT
    ADD CONSTRAINT TPROJECT_FK_6 FOREIGN KEY (PARENT)
    REFERENCES TPROJECT (PKEY)
;

ALTER TABLE TRELEASE
    ADD CONSTRAINT TRELEASE_FK_3 FOREIGN KEY (PARENT)
    REFERENCES TRELEASE (PKEY)
;

ALTER TABLE TWORKITEM
    ADD CONSTRAINT TWORKITEM_FK_13 FOREIGN KEY (PROJECTKEY)
    REFERENCES TPROJECT (PKEY)
;

ALTER TABLE TPROJECT ADD ISPRIVATE VARCHAR (1) default 'N';
ALTER TABLE TWORKITEM ADD TOPDOWNSTARTDATE TIMESTAMP;
ALTER TABLE TWORKITEM ADD TOPDOWNENDDATE TIMESTAMP;
ALTER TABLE TWORKITEM ADD REMINDERDATE TIMESTAMP;
ALTER TABLE TPROJECTTYPE ADD DEFAULTFORPRIVATE VARCHAR (1) default 'N';
ALTER TABLE TMOTD ADD TEASERTEXT VARCHAR (255);
ALTER TABLE TLOCALIZEDRESOURCES ALTER COLUMN LOCALIZEDTEXT TYPE VARCHAR(2000);
ALTER TABLE TBUDGET ADD BUDGETTYPE INTEGER;
ALTER TABLE TFIELDCONFIG ADD GROOVYSCRIPT INTEGER;
ALTER TABLE TTEXTBOXSETTINGS ADD DATEISWITHTIME CHAR (1) default 'N';

--In firebird the length of a field can't be reduced directly 
--ALTER TABLE TLIST ALTER COLUMN DESCRIPTION VARCHAR (255);
ALTER TABLE TLIST ADD DESCR_temp VARCHAR(255);
COMMIT;
UPDATE TLIST SET DESCR_temp = DESCRIPTION;
ALTER TABLE TLIST DROP DESCRIPTION;
COMMIT;
ALTER TABLE TLIST ALTER DESCR_temp TO DESCRIPTION;
ALTER TABLE TLIST ADD MOREPROPS VARCHAR (8191);
ALTER TABLE TSCRIPTS ADD SCRIPTROLE INTEGER;
ALTER TABLE TREPORTPERSONSETTINGS ADD PARAMSETTINGS VARCHAR (8191);

--set the projects directly in TWORKITEM
UPDATE TWORKITEM SET TWORKITEM.PROJECTKEY=(SELECT max(PROJKEY)
FROM TPROJCAT WHERE TWORKITEM.PROJCATKEY=TPROJCAT.PKEY);

--remove the not null constraint from TWORKITEM.PROJCATKEY
--by using a temorary column. Although neither the field, nor the foreign keys or indexes 
--are nedded any more in the future, reconstruct them with the same name to remain compatible  
--with the old Track+ versions regarding the generated constraint (forignn key and index) naming:
--older Track+ would have holes in generated constraint naming while the new Track+ installations not, 
--and the generated constarint naming would be not any more compatible for eventual further constraint drops
--The field can't be dropped (should be recreated) because the subsystem data should be migrated in custom lists.  
ALTER TABLE TWORKITEM DROP CONSTRAINT TWORKITEM_FK_5;
DROP INDEX TWIINDEX11;
ALTER TABLE TWORKITEM ADD PROJCATKEYTMP INTEGER;
COMMIT;
UPDATE TWORKITEM SET PROJCATKEYTMP=PROJCATKEY;
COMMIT;
ALTER TABLE TWORKITEM DROP PROJCATKEY;
COMMIT;
ALTER TABLE TWORKITEM ADD PROJCATKEY INTEGER;
COMMIT;
UPDATE TWORKITEM SET PROJCATKEY=PROJCATKEYTMP;
ALTER TABLE TWORKITEM DROP PROJCATKEYTMP;
COMMIT;
ALTER TABLE TWORKITEM
	ADD CONSTRAINT TWORKITEM_FK_5 FOREIGN KEY (PROJCATKEY)
	REFERENCES TPROJCAT (PKEY);
CREATE  INDEX TWIINDEX11 ON TWORKITEM (PROJCATKEY);
COMMIT;


--remove the not null constraint from TNOTIFY.PROJCATKEY
ALTER TABLE TNOTIFY DROP CONSTRAINT TNOTIFY_FK_1;
ALTER TABLE TNOTIFY ADD PROJCATKEYTMP INTEGER;
COMMIT;
UPDATE TNOTIFY SET PROJCATKEYTMP=PROJCATKEY;
COMMIT;
ALTER TABLE TNOTIFY DROP PROJCATKEY;
COMMIT;
ALTER TABLE TNOTIFY ADD PROJCATKEY INTEGER;
COMMIT;
UPDATE TNOTIFY SET PROJCATKEY=PROJCATKEYTMP;
ALTER TABLE TNOTIFY DROP PROJCATKEYTMP;
COMMIT;
ALTER TABLE TNOTIFY
	ADD CONSTRAINT TNOTIFY_FK_1 FOREIGN KEY (PROJCATKEY)
	REFERENCES TPROJCAT (PKEY);
COMMIT;

--remove the not null constraint from TDASHBOARDSCREEN.PERSONPKEY
ALTER TABLE TDASHBOARDSCREEN DROP CONSTRAINT TDASHBOARDSCREEN_FK_1;
ALTER TABLE TDASHBOARDSCREEN ADD PERSONPKEYTMP INTEGER;
COMMIT;
UPDATE TDASHBOARDSCREEN SET PERSONPKEYTMP=PERSONPKEY;
COMMIT;
ALTER TABLE TDASHBOARDSCREEN DROP PERSONPKEY;
COMMIT;
ALTER TABLE TDASHBOARDSCREEN ADD PERSONPKEY INTEGER;
COMMIT;
UPDATE TDASHBOARDSCREEN SET PERSONPKEY=PERSONPKEYTMP;
ALTER TABLE TDASHBOARDSCREEN DROP PERSONPKEYTMP;
COMMIT;
ALTER TABLE TDASHBOARDSCREEN
    ADD CONSTRAINT TDASHBOARDSCREEN_FK_1 FOREIGN KEY (PERSONPKEY)
    REFERENCES TPERSON (PKEY);
COMMIT;

ALTER TABLE TPERSON ALTER COLUMN PASSWD TYPE VARCHAR (160);
ALTER TABLE TPERSON ADD SALT VARCHAR (80);
ALTER TABLE TPERSON ADD FORGOTPASSWORDKEY VARCHAR (100);
ALTER TABLE TPERSON ADD CREATED TIMESTAMP;
ALTER TABLE TPERSON ADD MAXASSIGNEDITEMS INTEGER;
ALTER TABLE TPERSON ADD MESSENGERURL VARCHAR (255);
ALTER TABLE TPERSON ADD CALLURL VARCHAR (255);
ALTER TABLE TPERSON ADD SYMBOL VARCHAR (255);
ALTER TABLE TPERSON ADD ICONKEY INTEGER;    

ALTER TABLE TCATEGORY ADD CSSSTYLE VARCHAR (255);
ALTER TABLE TCATEGORY ADD ICONCHANGED CHAR (1) default 'N';
ALTER TABLE TPRIORITY ADD CSSSTYLE VARCHAR (255);
ALTER TABLE TPRIORITY ADD ICONCHANGED CHAR (1) default 'N';
ALTER TABLE TSEVERITY ADD CSSSTYLE VARCHAR (255);
ALTER TABLE TSEVERITY ADD ICONCHANGED CHAR (1) default 'N';
ALTER TABLE TSTATE ADD CSSSTYLE VARCHAR (255);
ALTER TABLE TSTATE ADD ICONCHANGED CHAR (1) default 'N';

ALTER TABLE TWORKITEM ADD WBSONLEVEL INTEGER;
ALTER TABLE TWORKITEM ADD ESCALATIONLEVEL INTEGER;
ALTER TABLE TOPTION ADD SYMBOL VARCHAR (255);
ALTER TABLE TOPTION ADD CSSSTYLE VARCHAR (255);
ALTER TABLE TOPTION ADD ICONCHANGED CHAR (1) default 'N';
ALTER TABLE TQUERYREPOSITORY ADD CATEGORYKEY INTEGER;
ALTER TABLE TEXPORTTEMPLATE ADD CATEGORYKEY INTEGER;
ALTER TABLE TSYSTEMSTATE ADD ICONKEY INTEGER;
ALTER TABLE TSYSTEMSTATE ADD CSSSTYLE VARCHAR (255);

ALTER TABLE TLOCALIZEDRESOURCES ADD TEXTCHANGED CHAR (1) default 'N';

ALTER TABLE TACTION ADD ACTIONTYPE INTEGER;
ALTER TABLE TACTION ADD ICONKEY INTEGER;
ALTER TABLE TACTION
    ADD CONSTRAINT TACTION_FK_1 FOREIGN KEY (ICONKEY)
    REFERENCES TBLOB (OBJECTID);

--------------------------------------------------------------------------
-- TFILTERCATEGORY
--------------------------------------------------------------------------


CREATE TABLE TFILTERCATEGORY
(
    OBJECTID INTEGER NOT NULL,
    LABEL VARCHAR (255) NOT NULL,
    REPOSITORY INTEGER NOT NULL,
    FILTERTYPE INTEGER NOT NULL,
    CREATEDBY INTEGER NOT NULL,
    PROJECT INTEGER,
    PARENTID INTEGER,
    TPUUID VARCHAR (36),
    PRIMARY KEY(OBJECTID)
);

CREATE  INDEX TFILTERCATEGORYINDEX1 ON TFILTERCATEGORY (TPUUID);
--------------------------------------------------------------------------
-- TREPORTCATEGORY
--------------------------------------------------------------------------


CREATE TABLE TREPORTCATEGORY
(
    OBJECTID INTEGER NOT NULL,
    LABEL VARCHAR (255) NOT NULL,
    REPOSITORY INTEGER NOT NULL,
    CREATEDBY INTEGER NOT NULL,
    PROJECT INTEGER,
    PARENTID INTEGER,
    TPUUID VARCHAR (36),
    PRIMARY KEY(OBJECTID)
);

CREATE  INDEX TREPORTCATEGORYINDEX1 ON TREPORTCATEGORY (TPUUID);
--------------------------------------------------------------------------
-- TMENUITEMQUERY
--------------------------------------------------------------------------


CREATE TABLE TMENUITEMQUERY
(
    OBJECTID INTEGER NOT NULL,
    PERSON INTEGER NOT NULL,
    QUERYKEY INTEGER NOT NULL,
	INCLUDEINMENU CHAR (1) default 'N',
 	CSSSTYLEFIELD INTEGER,
    TPUUID VARCHAR (36),
    PRIMARY KEY(OBJECTID)
);

CREATE  INDEX TMENUITEMQUERYINDEX1 ON TMENUITEMQUERY (TPUUID);
--------------------------------------------------------------------------
-- TCHILDISSUETYPE
--------------------------------------------------------------------------


CREATE TABLE TCHILDISSUETYPE
(
    OBJECTID INTEGER NOT NULL,
    ISSUETYPEPARENT INTEGER NOT NULL,
    ISSUETYPECHILD INTEGER NOT NULL,
    TPUUID VARCHAR (36),
    PRIMARY KEY(OBJECTID)
);

CREATE  INDEX TCHILDISSUETYPEINDEX1 ON TCHILDISSUETYPE (TPUUID);

--------------------------------------------------------------------------
-- TPERSONBASKET
--------------------------------------------------------------------------


CREATE TABLE TPERSONBASKET
(
    OBJECTID INTEGER NOT NULL,
    BASKET INTEGER NOT NULL,
    WORKITEM INTEGER NOT NULL,
    PERSON INTEGER,
    REMINDERDATE TIMESTAMP,
    DELEGATETEXT VARCHAR (6000),
    MOREPROPS VARCHAR (6000),
    TPUUID VARCHAR (36),
    PRIMARY KEY(OBJECTID)
);

CREATE  INDEX TPERSONBASKETINDEX1 ON TPERSONBASKET (PERSON);
CREATE  INDEX TPERSONBASKETINDEX2 ON TPERSONBASKET (TPUUID);

--------------------------------------------------------------------------
-- TBASKET
--------------------------------------------------------------------------


CREATE TABLE TBASKET
(
    OBJECTID INTEGER NOT NULL,
    LABEL VARCHAR (255) NOT NULL,
    DIVISIBLE CHAR (1) default 'N',
    PARENTBASKET INTEGER,
    PERSON INTEGER,
    TPUUID VARCHAR (36),
    PRIMARY KEY(OBJECTID)
);

CREATE  INDEX TBASKETINDEX1 ON TBASKET (TPUUID);
--------------------------------------------------------------------------
-- TMAILTEMPLATECONFIG
--------------------------------------------------------------------------


CREATE TABLE TMAILTEMPLATECONFIG
(
    OBJECTID INTEGER NOT NULL,
    MAILTEMPLATE INTEGER NOT NULL,
    ISSUETYPE INTEGER,
    PROJECTTYPE INTEGER,
    PROJECT INTEGER,
    EVENTKEY INTEGER NOT NULL,
    TPUUID VARCHAR (36),
    PRIMARY KEY(OBJECTID)
);

CREATE  INDEX TMAILTEMPLATECONFIGINDEX1 ON TMAILTEMPLATECONFIG (TPUUID);
--------------------------------------------------------------------------
-- TMAILTEMPLATE
--------------------------------------------------------------------------


CREATE TABLE TMAILTEMPLATE
(
    OBJECTID INTEGER NOT NULL,
    TEMPLATETYPE INTEGER,
    NAME VARCHAR (255),
    DESCRIPTION VARCHAR (255),
    TAGLABEL VARCHAR (255),
    TPUUID VARCHAR (36),
    PRIMARY KEY(OBJECTID)
);

CREATE  INDEX TMAILTEMPLATEINDEX1 ON TMAILTEMPLATE (TPUUID);
--------------------------------------------------------------------------
-- TMAILTEMPLATEDEF
--------------------------------------------------------------------------


CREATE TABLE TMAILTEMPLATEDEF
(
    OBJECTID INTEGER NOT NULL,
    MAILTEMPLATE INTEGER NOT NULL,
    MAILSUBJECT VARCHAR (255),
    MAILBODY VARCHAR (8191),
    THELOCALE VARCHAR (20),
    PLAINEMAIL CHAR (1) default 'N',
    TEMPLATECHANGED CHAR (1) default 'N',
    TPUUID VARCHAR (36),
    PRIMARY KEY(OBJECTID)
);

CREATE  INDEX TMAILTEMPLATEDEFINDEX1 ON TMAILTEMPLATEDEF (TPUUID);
--------------------------------------------------------------------------
-- TLASTVISITEDITEM
--------------------------------------------------------------------------


CREATE TABLE TLASTVISITEDITEM
(
    OBJECTID INTEGER NOT NULL,
    WORKITEM INTEGER NOT NULL,
    PERSON INTEGER NOT NULL,
    LASTVISITEDDATE TIMESTAMP,
    TPUUID VARCHAR (36),
    PRIMARY KEY(OBJECTID)
);

CREATE  INDEX TLASTVISITEDITEMINDEX1 ON TLASTVISITEDITEM (PERSON);
CREATE  INDEX TLASTVISITEDITEMINDEX2 ON TLASTVISITEDITEM (TPUUID);

--------------------------------------------------------------------------
-- TWORKFLOWDEF
--------------------------------------------------------------------------


CREATE TABLE TWORKFLOWDEF
(
    OBJECTID INTEGER NOT NULL,
    NAME VARCHAR (255) NOT NULL,
    DESCRIPTION VARCHAR (255),
    TAGLABEL VARCHAR (255),
    OWNER INTEGER,
    TPUUID VARCHAR (36),
    PRIMARY KEY(OBJECTID)
);

CREATE  INDEX TWORKFLOWDEFINDEX1 ON TWORKFLOWDEF (TPUUID);
--------------------------------------------------------------------------
-- TWORKFLOWTRANSITION
--------------------------------------------------------------------------

CREATE TABLE TWORKFLOWTRANSITION
(
    OBJECTID INTEGER NOT NULL,
    STATIONFROM INTEGER,
    STATIONTO INTEGER,
    ACTIONKEY INTEGER,
    WORKFLOW INTEGER NOT NULL,
    TEXTPOSITIONX INTEGER,
    TEXTPOSITIONY INTEGER,
    TRANSITIONTYPE INTEGER,
    CONTROLPOINTS VARCHAR (255),
    TPUUID VARCHAR (36),
    PRIMARY KEY(OBJECTID)
);


CREATE  INDEX TWORKFLOWTRANSITIONINDEX1 ON TWORKFLOWTRANSITION (WORKFLOW);
CREATE  INDEX TWORKFLOWTRANSITIONINDEX2 ON TWORKFLOWTRANSITION (TPUUID);
--------------------------------------------------------------------------
-- TWORKFLOWSTATION
--------------------------------------------------------------------------


CREATE TABLE TWORKFLOWSTATION
(
    OBJECTID INTEGER NOT NULL,
    NAME VARCHAR (255),
    STATUS INTEGER,
    WORKFLOW INTEGER,
    NODEX INTEGER,
    NODEY INTEGER,
    STATIONTYPE INTEGER,
    TPUUID VARCHAR (36),
    PRIMARY KEY(OBJECTID)
);

CREATE  INDEX TWORKFLOWSTATIONINDEX1 ON TWORKFLOWSTATION (STATUS);
CREATE  INDEX TWORKFLOWSTATIONINDEX2 ON TWORKFLOWSTATION (WORKFLOW);
CREATE  INDEX TWORKFLOWSTATIONINDEX3 ON TWORKFLOWSTATION (TPUUID);
--------------------------------------------------------------------------
-- TWORKFLOWACTIVITY
--------------------------------------------------------------------------


CREATE TABLE TWORKFLOWACTIVITY
(
    OBJECTID INTEGER NOT NULL,
    TRANSITIONACTIVITY INTEGER,
    STATIONENTRYACTIVITY INTEGER,
    STATIONEXITACTIVITY INTEGER,
    STATIONDOACTIVITY INTEGER,
    ACTIVITYTYPE INTEGER NOT NULL,
    ACTIVITYPARAMS VARCHAR (8191),
    GROOVYSCRIPT INTEGER,
    NEWMAN INTEGER,
    NEWRESP INTEGER,
    SLA INTEGER,
    SCREEN INTEGER,
    TPUUID VARCHAR (36),
    PRIMARY KEY(OBJECTID)
);

CREATE  INDEX TWORKFLOWACTIVITYINDEX1 ON TWORKFLOWACTIVITY (TRANSITIONACTIVITY);
CREATE  INDEX TWORKFLOWACTIVITYINDEX2 ON TWORKFLOWACTIVITY (STATIONENTRYACTIVITY);
CREATE  INDEX TWORKFLOWACTIVITYINDEX3 ON TWORKFLOWACTIVITY (STATIONEXITACTIVITY);
CREATE  INDEX TWORKFLOWACTIVITYINDEX4 ON TWORKFLOWACTIVITY (STATIONDOACTIVITY);
CREATE  INDEX TWORKFLOWACTIVITYINDEX5 ON TWORKFLOWACTIVITY (TPUUID);
--------------------------------------------------------------------------
-- TWORKFLOWGUARD
--------------------------------------------------------------------------


CREATE TABLE TWORKFLOWGUARD
(
    OBJECTID INTEGER NOT NULL,
    GUARDTYPE INTEGER NOT NULL,
    GUARDPARAMS VARCHAR (8191),
    WORKFLOWTRANSITION INTEGER NOT NULL,
    ROLEKEY INTEGER,
    GROOVYSCRIPT INTEGER,
    PERSON INTEGER,
    TPUUID VARCHAR (36),
    PRIMARY KEY(OBJECTID)
);

CREATE  INDEX TWORKFLOWGUARDINDEX1 ON TWORKFLOWGUARD (WORKFLOWTRANSITION);
CREATE  INDEX TWORKFLOWGUARDINDEX2 ON TWORKFLOWGUARD (TPUUID);
--------------------------------------------------------------------------
-- TWORKFLOWCONNECT
--------------------------------------------------------------------------


CREATE TABLE TWORKFLOWCONNECT
(
    OBJECTID INTEGER NOT NULL,
    WORKFLOW INTEGER NOT NULL,
    ISSUETYPE INTEGER,
    PROJECTTYPE INTEGER,
    PROJECT INTEGER,
    TPUUID VARCHAR (36),
    PRIMARY KEY(OBJECTID)
);

CREATE  INDEX TWORKFLOWCONNECTINDEX1 ON TWORKFLOWCONNECT (TPUUID);
--------------------------------------------------------------------------
-- TSLA
--------------------------------------------------------------------------


CREATE TABLE TSLA
(
    OBJECTID INTEGER NOT NULL,
    NAME VARCHAR (255) NOT NULL,
    TPUUID VARCHAR (36),
    PRIMARY KEY(OBJECTID)
);

CREATE  INDEX TSLAINDEX1 ON TSLA (TPUUID);
--------------------------------------------------------------------------
-- TESCALATIONENTRY
--------------------------------------------------------------------------


CREATE TABLE TESCALATIONENTRY
(
    OBJECTID INTEGER NOT NULL,
    SLA INTEGER NOT NULL,
    PRIORITY INTEGER,
    ESCALATETO INTEGER,
    SPARAMETERS VARCHAR (8191),
    NLEVEL INTEGER,
    TPUUID VARCHAR (36),
    PRIMARY KEY(OBJECTID)
);

CREATE  INDEX TESCALATIONENTRYINDEX1 ON TESCALATIONENTRY (SLA);
CREATE  INDEX TESCALATIONENTRYINDEX2 ON TESCALATIONENTRY (TPUUID);
--------------------------------------------------------------------------
-- TESCALATIONSTATE
--------------------------------------------------------------------------


CREATE TABLE TESCALATIONSTATE
(
    OBJECTID INTEGER NOT NULL,
    ESCALATIONENTRY INTEGER NOT NULL,
    STATUS INTEGER,
    TPUUID VARCHAR (36),
    PRIMARY KEY(OBJECTID)
);

CREATE  INDEX TESCALATIONSTATEINDEX1 ON TESCALATIONSTATE (ESCALATIONENTRY);
CREATE  INDEX TESCALATIONSTATEINDEX2 ON TESCALATIONSTATE (TPUUID);
--------------------------------------------------------------------------
-- TORGPROJECTSLA
--------------------------------------------------------------------------


CREATE TABLE TORGPROJECTSLA
(
    OBJECTID INTEGER NOT NULL,
    DEPARTMENT INTEGER NOT NULL,
    PROJECT INTEGER NOT NULL,
    SLA INTEGER NOT NULL,
    TPUUID VARCHAR (36),
    PRIMARY KEY(OBJECTID)
);

CREATE  INDEX TORGPROJECTSLAINDEX1 ON TORGPROJECTSLA (TPUUID);

--------------------------------------------------------------------------
-- TREADISSUE
--------------------------------------------------------------------------


CREATE TABLE TREADISSUE
(
    OBJECTID INTEGER NOT NULL,
    WORKITEM INTEGER NOT NULL,
    PERSON INTEGER NOT NULL,
    READTYPE INTEGER,
    TPUUID VARCHAR (36),
    PRIMARY KEY(OBJECTID)
);

CREATE  INDEX TREADISSUEINDEX1 ON TREADISSUE (PERSON);
CREATE  INDEX TREADISSUEINDEX2 ON TREADISSUE (WORKITEM);
CREATE  INDEX TREADISSUEINDEX3 ON TREADISSUE (TPUUID);
--------------------------------------------------------------------------
-- TLASTEXECUTEDQUERY
--------------------------------------------------------------------------


CREATE TABLE TLASTEXECUTEDQUERY
(
    OBJECTID INTEGER NOT NULL,
    PERSON INTEGER NOT NULL,
    QUERYTYPE INTEGER NOT NULL,
    QUERYCLOB INTEGER,
    QUERYKEY INTEGER,
    LASTEXECUTEDTIME TIMESTAMP,
    TPUUID VARCHAR (36),
    PRIMARY KEY(OBJECTID)
);

CREATE  INDEX TLASTEXECUTEDQUERYINDEX1 ON TLASTEXECUTEDQUERY (PERSON);
CREATE  INDEX TLASTEXECUTEDQUERYINDEX2 ON TLASTEXECUTEDQUERY (TPUUID);

--------------------------------------------------------------------------
-- TGLOBALCSSSTYLE
--------------------------------------------------------------------------


CREATE TABLE TGLOBALCSSSTYLE
(
    OBJECTID INTEGER NOT NULL,
    STYLEFOR INTEGER NOT NULL,
    CSSSTYLE VARCHAR (255),
    TPUUID VARCHAR (36),
    PRIMARY KEY(OBJECTID)
);

CREATE  INDEX TGLOBALCSSSTYLEINDEX1 ON TGLOBALCSSSTYLE (TPUUID);

ALTER TABLE TPERSON
    ADD CONSTRAINT TPERSON_FK_3 FOREIGN KEY (ICONKEY)
    REFERENCES TBLOB (OBJECTID)
;

ALTER TABLE TFIELDCONFIG
    ADD CONSTRAINT TFIELDCONFIG_FK_5 FOREIGN KEY (GROOVYSCRIPT)
    REFERENCES TSCRIPTS (OBJECTID)
;

ALTER TABLE TREADISSUE
    ADD CONSTRAINT TREADISSUE_FK_1 FOREIGN KEY (WORKITEM)
    REFERENCES TWORKITEM (WORKITEMKEY)
;

ALTER TABLE TREADISSUE
    ADD CONSTRAINT TREADISSUE_FK_2 FOREIGN KEY (PERSON)
    REFERENCES TPERSON (PKEY)
;

ALTER TABLE TLASTEXECUTEDQUERY
    ADD CONSTRAINT TLASTEXECUTEDQUERY_FK_1 FOREIGN KEY (PERSON)
    REFERENCES TPERSON (PKEY)
;

ALTER TABLE TLASTEXECUTEDQUERY
    ADD CONSTRAINT TLASTEXECUTEDQUERY_FK_2 FOREIGN KEY (QUERYCLOB)
    REFERENCES TCLOB (OBJECTID)
;


ALTER TABLE TSYSTEMSTATE
    ADD CONSTRAINT TSYSTEMSTATE_FK_1 FOREIGN KEY (ICONKEY)
    REFERENCES TBLOB (OBJECTID);

ALTER TABLE TQUERYREPOSITORY
    ADD CONSTRAINT TQUERYREPOSITORY_FK_4 FOREIGN KEY (CATEGORYKEY)
    REFERENCES TFILTERCATEGORY (OBJECTID);

ALTER TABLE TEXPORTTEMPLATE
    ADD CONSTRAINT TEXPORTTEMPLATE_FK_3 FOREIGN KEY (CATEGORYKEY)
    REFERENCES TREPORTCATEGORY (OBJECTID);

ALTER TABLE TFILTERCATEGORY
    ADD CONSTRAINT TFILTERCATEGORY_FK_1 FOREIGN KEY (PROJECT)
    REFERENCES TPROJECT (PKEY)
;

ALTER TABLE TFILTERCATEGORY
    ADD CONSTRAINT TFILTERCATEGORY_FK_2 FOREIGN KEY (CREATEDBY)
    REFERENCES TPERSON (PKEY)
;

ALTER TABLE TFILTERCATEGORY
    ADD CONSTRAINT TFILTERCATEGORY_FK_3 FOREIGN KEY (PARENTID)
    REFERENCES TFILTERCATEGORY (OBJECTID)
;

ALTER TABLE TREPORTCATEGORY
    ADD CONSTRAINT TREPORTCATEGORY_FK_1 FOREIGN KEY (PROJECT)
    REFERENCES TPROJECT (PKEY)
;

ALTER TABLE TREPORTCATEGORY
    ADD CONSTRAINT TREPORTCATEGORY_FK_2 FOREIGN KEY (CREATEDBY)
    REFERENCES TPERSON (PKEY)
;

ALTER TABLE TREPORTCATEGORY
    ADD CONSTRAINT TREPORTCATEGORY_FK_3 FOREIGN KEY (PARENTID)
    REFERENCES TREPORTCATEGORY (OBJECTID)
;

ALTER TABLE TMENUITEMQUERY
    ADD CONSTRAINT TMENUITEMQUERY_FK_1 FOREIGN KEY (PERSON)
    REFERENCES TPERSON (PKEY)
;

ALTER TABLE TMENUITEMQUERY
    ADD CONSTRAINT TMENUITEMQUERY_FK_2 FOREIGN KEY (QUERYKEY)
    REFERENCES TQUERYREPOSITORY (OBJECTID)
;

ALTER TABLE TCHILDISSUETYPE
    ADD CONSTRAINT TCHILDISSUETYPE_FK_1 FOREIGN KEY (ISSUETYPEPARENT)
    REFERENCES TCATEGORY (PKEY)
;

ALTER TABLE TCHILDISSUETYPE
    ADD CONSTRAINT TCHILDISSUETYPE_FK_2 FOREIGN KEY (ISSUETYPECHILD)
    REFERENCES TCATEGORY (PKEY)
;

ALTER TABLE TPERSONBASKET
    ADD CONSTRAINT TPERSONBASKET_FK_1 FOREIGN KEY (BASKET)
    REFERENCES TBASKET (OBJECTID)
;

ALTER TABLE TPERSONBASKET
    ADD CONSTRAINT TPERSONBASKET_FK_2 FOREIGN KEY (WORKITEM)
    REFERENCES TWORKITEM (WORKITEMKEY)
;

ALTER TABLE TPERSONBASKET
    ADD CONSTRAINT TPERSONBASKET_FK_3 FOREIGN KEY (PERSON)
    REFERENCES TPERSON (PKEY)
;

ALTER TABLE TBASKET
    ADD CONSTRAINT TBASKET_FK_1 FOREIGN KEY (PERSON)
    REFERENCES TPERSON (PKEY)
;

ALTER TABLE TMAILTEMPLATECONFIG
    ADD CONSTRAINT TMAILTEMPLATECONFIG_FK_1 FOREIGN KEY (MAILTEMPLATE)
    REFERENCES TMAILTEMPLATE (OBJECTID)
;

ALTER TABLE TMAILTEMPLATECONFIG
    ADD CONSTRAINT TMAILTEMPLATECONFIG_FK_2 FOREIGN KEY (ISSUETYPE)
    REFERENCES TCATEGORY (PKEY)
;

ALTER TABLE TMAILTEMPLATECONFIG
    ADD CONSTRAINT TMAILTEMPLATECONFIG_FK_3 FOREIGN KEY (PROJECTTYPE)
    REFERENCES TPROJECTTYPE (OBJECTID)
;

ALTER TABLE TMAILTEMPLATECONFIG
    ADD CONSTRAINT TMAILTEMPLATECONFIG_FK_4 FOREIGN KEY (PROJECT)
    REFERENCES TPROJECT (PKEY)
;

ALTER TABLE TMAILTEMPLATEDEF
    ADD CONSTRAINT TMAILTEMPLATEDEF_FK_1 FOREIGN KEY (MAILTEMPLATE)
    REFERENCES TMAILTEMPLATE (OBJECTID)
;

ALTER TABLE TLASTVISITEDITEM
    ADD CONSTRAINT TLASTVISITEDITEM_FK_1 FOREIGN KEY (WORKITEM)
    REFERENCES TWORKITEM (WORKITEMKEY)
;

ALTER TABLE TLASTVISITEDITEM
    ADD CONSTRAINT TLASTVISITEDITEM_FK_2 FOREIGN KEY (PERSON)
    REFERENCES TPERSON (PKEY)
;

ALTER TABLE TWORKFLOWDEF
    ADD CONSTRAINT TWORKFLOWDEF_FK_1 FOREIGN KEY (OWNER)
    REFERENCES TPERSON (PKEY)
;

ALTER TABLE TWORKFLOWTRANSITION
    ADD CONSTRAINT TWORKFLOWTRANSITION_FK_1 FOREIGN KEY (STATIONFROM)
    REFERENCES TWORKFLOWSTATION (OBJECTID)
;

ALTER TABLE TWORKFLOWTRANSITION
    ADD CONSTRAINT TWORKFLOWTRANSITION_FK_2 FOREIGN KEY (STATIONTO)
    REFERENCES TWORKFLOWSTATION (OBJECTID)
;

ALTER TABLE TWORKFLOWTRANSITION
    ADD CONSTRAINT TWORKFLOWTRANSITION_FK_3 FOREIGN KEY (ACTIONKEY)
    REFERENCES TACTION (OBJECTID)
;

ALTER TABLE TWORKFLOWTRANSITION
    ADD CONSTRAINT TWORKFLOWTRANSITION_FK_4 FOREIGN KEY (WORKFLOW)
    REFERENCES TWORKFLOWDEF (OBJECTID)
;

ALTER TABLE TWORKFLOWSTATION
    ADD CONSTRAINT TWORKFLOWSTATION_FK_1 FOREIGN KEY (STATUS)
    REFERENCES TSTATE (PKEY)
;

ALTER TABLE TWORKFLOWSTATION
    ADD CONSTRAINT TWORKFLOWSTATION_FK_2 FOREIGN KEY (WORKFLOW)
    REFERENCES TWORKFLOWDEF (OBJECTID)
;

ALTER TABLE TWORKFLOWACTIVITY
    ADD CONSTRAINT TWORKFLOWACTIVITY_FK_1 FOREIGN KEY (TRANSITIONACTIVITY)
    REFERENCES TWORKFLOWTRANSITION (OBJECTID)
;

ALTER TABLE TWORKFLOWACTIVITY
    ADD CONSTRAINT TWORKFLOWACTIVITY_FK_2 FOREIGN KEY (STATIONENTRYACTIVITY)
    REFERENCES TWORKFLOWSTATION (OBJECTID)
;

ALTER TABLE TWORKFLOWACTIVITY
    ADD CONSTRAINT TWORKFLOWACTIVITY_FK_3 FOREIGN KEY (STATIONEXITACTIVITY)
    REFERENCES TWORKFLOWSTATION (OBJECTID)
;

ALTER TABLE TWORKFLOWACTIVITY
    ADD CONSTRAINT TWORKFLOWACTIVITY_FK_4 FOREIGN KEY (STATIONDOACTIVITY)
    REFERENCES TWORKFLOWSTATION (OBJECTID)
;

ALTER TABLE TWORKFLOWACTIVITY
    ADD CONSTRAINT TWORKFLOWACTIVITY_FK_5 FOREIGN KEY (GROOVYSCRIPT)
    REFERENCES TSCRIPTS (OBJECTID)
;

ALTER TABLE TWORKFLOWACTIVITY
    ADD CONSTRAINT TWORKFLOWACTIVITY_FK_6 FOREIGN KEY (NEWMAN)
    REFERENCES TPERSON (PKEY)
;

ALTER TABLE TWORKFLOWACTIVITY
    ADD CONSTRAINT TWORKFLOWACTIVITY_FK_7 FOREIGN KEY (NEWRESP)
    REFERENCES TPERSON (PKEY)
;

ALTER TABLE TWORKFLOWACTIVITY
    ADD CONSTRAINT TWORKFLOWACTIVITY_FK_8 FOREIGN KEY (SLA)
    REFERENCES TSLA (OBJECTID)
;

ALTER TABLE TWORKFLOWACTIVITY
    ADD CONSTRAINT TWORKFLOWACTIVITY_FK_9 FOREIGN KEY (SCREEN)
    REFERENCES TSCREEN (OBJECTID)
;

ALTER TABLE TWORKFLOWGUARD
    ADD CONSTRAINT TWORKFLOWGUARD_FK_1 FOREIGN KEY (WORKFLOWTRANSITION)
    REFERENCES TWORKFLOWTRANSITION (OBJECTID)
;

ALTER TABLE TWORKFLOWGUARD
    ADD CONSTRAINT TWORKFLOWGUARD_FK_2 FOREIGN KEY (ROLEKEY)
    REFERENCES TROLE (PKEY)
;

ALTER TABLE TWORKFLOWGUARD
    ADD CONSTRAINT TWORKFLOWGUARD_FK_3 FOREIGN KEY (GROOVYSCRIPT)
    REFERENCES TSCRIPTS (OBJECTID)
;

ALTER TABLE TWORKFLOWGUARD
    ADD CONSTRAINT TWORKFLOWGUARD_FK_4 FOREIGN KEY (PERSON)
    REFERENCES TPERSON (PKEY)
;

ALTER TABLE TWORKFLOWCONNECT
    ADD CONSTRAINT TWORKFLOWCONNECT_FK_1 FOREIGN KEY (WORKFLOW)
    REFERENCES TWORKFLOWDEF (OBJECTID)
;

ALTER TABLE TWORKFLOWCONNECT
    ADD CONSTRAINT TWORKFLOWCONNECT_FK_2 FOREIGN KEY (ISSUETYPE)
    REFERENCES TCATEGORY (PKEY)
;

ALTER TABLE TWORKFLOWCONNECT
    ADD CONSTRAINT TWORKFLOWCONNECT_FK_3 FOREIGN KEY (PROJECTTYPE)
    REFERENCES TPROJECTTYPE (OBJECTID)
;

ALTER TABLE TWORKFLOWCONNECT
    ADD CONSTRAINT TWORKFLOWCONNECT_FK_4 FOREIGN KEY (PROJECT)
    REFERENCES TPROJECT (PKEY)
;

ALTER TABLE TESCALATIONENTRY
    ADD CONSTRAINT TESCALATIONENTRY_FK_1 FOREIGN KEY (SLA)
    REFERENCES TSLA (OBJECTID)
;

ALTER TABLE TESCALATIONENTRY
    ADD CONSTRAINT TESCALATIONENTRY_FK_2 FOREIGN KEY (PRIORITY)
    REFERENCES TPRIORITY (PKEY)
;

ALTER TABLE TESCALATIONENTRY
    ADD CONSTRAINT TESCALATIONENTRY_FK_3 FOREIGN KEY (ESCALATETO)
    REFERENCES TPERSON (PKEY)
;

ALTER TABLE TESCALATIONSTATE
    ADD CONSTRAINT TESCALATIONSTATE_FK_1 FOREIGN KEY (ESCALATIONENTRY)
    REFERENCES TESCALATIONENTRY (OBJECTID)
;

ALTER TABLE TESCALATIONSTATE
    ADD CONSTRAINT TESCALATIONSTATE_FK_2 FOREIGN KEY (STATUS)
    REFERENCES TSTATE (PKEY)
;

ALTER TABLE TORGPROJECTSLA
    ADD CONSTRAINT TORGPROJECTSLA_FK_1 FOREIGN KEY (DEPARTMENT)
    REFERENCES TDEPARTMENT (PKEY)
;

ALTER TABLE TORGPROJECTSLA
    ADD CONSTRAINT TORGPROJECTSLA_FK_2 FOREIGN KEY (PROJECT)
    REFERENCES TPROJECT (PKEY)
;

ALTER TABLE TORGPROJECTSLA
    ADD CONSTRAINT TORGPROJECTSLA_FK_3 FOREIGN KEY (SLA)
    REFERENCES TSLA (OBJECTID)
;
COMMIT;

INSERT INTO ID_TABLE (ID_TABLE_ID, TABLE_NAME, NEXT_ID, QUANTITY) VALUES(111, 'TFILTERCATEGORY', 1, 1);
INSERT INTO ID_TABLE (ID_TABLE_ID, TABLE_NAME, NEXT_ID, QUANTITY) VALUES(112, 'TREPORTCATEGORY', 1, 1);
INSERT INTO ID_TABLE (ID_TABLE_ID, TABLE_NAME, NEXT_ID, QUANTITY) VALUES(113, 'TMENUITEMQUERY', 1, 1);
INSERT INTO ID_TABLE (ID_TABLE_ID, TABLE_NAME, NEXT_ID, QUANTITY) VALUES(114, 'TCHILDISSUETYPE', 1, 1);
INSERT INTO ID_TABLE (ID_TABLE_ID, TABLE_NAME, NEXT_ID, QUANTITY) VALUES(115, 'TBASKET', 1, 100);
INSERT INTO ID_TABLE (ID_TABLE_ID, TABLE_NAME, NEXT_ID, QUANTITY) VALUES(116, 'TPERSONBASKET', 1, 1);
INSERT INTO ID_TABLE (ID_TABLE_ID, TABLE_NAME, NEXT_ID, QUANTITY) VALUES(117, 'TMAILTEMPLATE', 1, 1000);
INSERT INTO ID_TABLE (ID_TABLE_ID, TABLE_NAME, NEXT_ID, QUANTITY) VALUES(118, 'TLASTVISITEDITEM', 1, 1);
INSERT INTO ID_TABLE (ID_TABLE_ID, TABLE_NAME, NEXT_ID, QUANTITY) VALUES(119, 'TWORKFLOWDEF', 1, 1);
INSERT INTO ID_TABLE (ID_TABLE_ID, TABLE_NAME, NEXT_ID, QUANTITY) VALUES(120, 'TWORKFLOWTRANSITION', 1, 1);
INSERT INTO ID_TABLE (ID_TABLE_ID, TABLE_NAME, NEXT_ID, QUANTITY) VALUES(121, 'TWORKFLOWSTATION', 1, 1);
INSERT INTO ID_TABLE (ID_TABLE_ID, TABLE_NAME, NEXT_ID, QUANTITY) VALUES(122, 'TWORKFLOWACTIVITY', 1, 1);
INSERT INTO ID_TABLE (ID_TABLE_ID, TABLE_NAME, NEXT_ID, QUANTITY) VALUES(123, 'TWORKFLOWGUARD', 1, 1);
INSERT INTO ID_TABLE (ID_TABLE_ID, TABLE_NAME, NEXT_ID, QUANTITY) VALUES(124, 'TWORKFLOWCONNECT', 1, 1);
INSERT INTO ID_TABLE (ID_TABLE_ID, TABLE_NAME, NEXT_ID, QUANTITY) VALUES(125, 'TSLA', 1, 1);
INSERT INTO ID_TABLE (ID_TABLE_ID, TABLE_NAME, NEXT_ID, QUANTITY) VALUES(126, 'TESCALATIONENTRY', 1, 1);
INSERT INTO ID_TABLE (ID_TABLE_ID, TABLE_NAME, NEXT_ID, QUANTITY) VALUES(127, 'TESCALATIONSTATE', 1, 1);
INSERT INTO ID_TABLE (ID_TABLE_ID, TABLE_NAME, NEXT_ID, QUANTITY) VALUES(128, 'TORGPROJECTSLA', 1, 1);


INSERT INTO TFIELD (OBJECTID, NAME, FIELDTYPE, DEPRECATED, ISCUSTOM, REQUIRED)
			VALUES (27, 'WBS', 'com.aurel.track.fieldType.types.system.text.SystemWBS', 'N', 'N', 'N');
INSERT INTO TFIELDCONFIG(OBJECTID, FIELDKEY, LABEL, TOOLTIP, REQUIRED)
			VALUES (27, 27, 'WBS', 'WBS', 'N');
INSERT INTO TFIELD (OBJECTID, NAME, FIELDTYPE, DEPRECATED, ISCUSTOM, REQUIRED)
			VALUES (28, 'ProjectSpecificIssueNo', 'com.aurel.track.fieldType.types.system.text.SystemProjectSpecificIssueNo', 'N', 'N', 'N');
INSERT INTO TFIELDCONFIG(OBJECTID, FIELDKEY, LABEL, TOOLTIP, REQUIRED)
			VALUES (28, 28, 'ProjectSpecificIssueNo', 'ProjectSpecificIssueNo', 'N');
INSERT INTO TFIELD (OBJECTID, NAME, FIELDTYPE, DEPRECATED, ISCUSTOM, REQUIRED)
			VALUES (29, 'TargetStartDate', 'com.aurel.track.fieldType.types.system.text.SystemTextBoxTargetDate', 'N', 'N', 'N');
INSERT INTO TFIELDCONFIG(OBJECTID, FIELDKEY, LABEL, TOOLTIP, REQUIRED, HISTORY)
			VALUES (29, 29, 'Start date target', 'Start date target (top-down)', 'N', 'Y');
INSERT INTO TFIELD (OBJECTID, NAME, FIELDTYPE, DEPRECATED, ISCUSTOM, REQUIRED)
			VALUES (30, 'TargetEndDate', 'com.aurel.track.fieldType.types.system.text.SystemTextBoxTargetDate', 'N', 'N', 'N');
INSERT INTO TFIELDCONFIG(OBJECTID, FIELDKEY, LABEL, TOOLTIP, REQUIRED, HISTORY)
			VALUES (30, 30, 'End date target', 'End date target (top-down)', 'N', 'Y');
			
			
COMMIT;