ALTER TABLE TACL ADD TPUUID VARCHAR(36);
CREATE  INDEX TACLINDEX1 ON TACL (TPUUID);

ALTER TABLE TBASELINE ADD TPUUID VARCHAR(36);
CREATE  INDEX TBASINDEX3 ON TBASELINE (TPUUID);

ALTER TABLE TCATEGORY ADD TPUUID VARCHAR(36);
CREATE  INDEX TCATEGORYINDEX1 ON TCATEGORY (TPUUID);

ALTER TABLE TCLASS ADD TPUUID VARCHAR(36);
CREATE  INDEX TCLASSINDEX1 ON TCLASS (TPUUID);

ALTER TABLE TDEPARTMENT ADD TPUUID VARCHAR(36);
CREATE  INDEX TDEPARTMENTINDEX1 ON TDEPARTMENT (TPUUID);

ALTER TABLE TNOTIFY ADD TPUUID VARCHAR(36);
CREATE  INDEX TNOTIFYINDEX1 ON TNOTIFY (TPUUID);

ALTER TABLE TPERSON ADD USERLEVEL INTEGER;
ALTER TABLE TPERSON ADD TPUUID VARCHAR(36);
CREATE  INDEX TPERSINDEX2 ON TPERSON (TPUUID);

ALTER TABLE TPRIORITY ADD TPUUID VARCHAR(36);
CREATE  INDEX TPRIOINDEX1 ON TPRIORITY (TPUUID);

ALTER TABLE TPPRIORITY ADD TPUUID VARCHAR(36);
CREATE  INDEX TPPRIOINDEX1 ON TPPRIORITY (TPUUID);

ALTER TABLE TPROJCAT ADD TPUUID VARCHAR(36);
CREATE  INDEX TPROJCATINDEX2 ON TPROJCAT (TPUUID);

ALTER TABLE TPROJECT ADD TPUUID VARCHAR(36);
CREATE  INDEX TPROJECTINDEX ON TPROJECT (TPUUID);

ALTER TABLE TRELEASE ADD TPUUID VARCHAR(36);
CREATE  INDEX TRELINDEX2 ON TRELEASE (TPUUID);

ALTER TABLE TROLE ADD TPUUID VARCHAR(36);
CREATE  INDEX TROLEINDEX1 ON TROLE (TPUUID);

ALTER TABLE TSEVERITY ADD TPUUID VARCHAR(36);
CREATE  INDEX TSEVINDEX1 ON TSEVERITY (TPUUID);

ALTER TABLE TPSEVERITY ADD TPUUID VARCHAR(36);
CREATE  INDEX TPSEVINDEX1 ON TPSEVERITY (TPUUID);

ALTER TABLE TSTATE ADD TPUUID VARCHAR(36);
CREATE  INDEX TSTATEINDEX1 ON TSTATE (TPUUID);

ALTER TABLE TSTATECHANGE ADD TPUUID VARCHAR(36);
CREATE  INDEX TSTATECHANGEINDEX4 ON TSTATECHANGE (TPUUID);

ALTER TABLE TTRAIL ADD TPUUID VARCHAR(36);
CREATE  INDEX TTRAILINDEX3 ON TTRAIL (TPUUID);

ALTER TABLE TWORKITEM ADD ARCHIVELEVEL INTEGER;
ALTER TABLE TWORKITEM ADD TPUUID VARCHAR(36);
CREATE  INDEX TWIINDEX19 ON TWORKITEM (ARCHIVELEVEL);
CREATE  INDEX TWIINDEX20 ON TWORKITEM (TPUUID);

ALTER TABLE TCOMPUTEDVALUES ADD TPUUID VARCHAR(36);
CREATE  INDEX TCVINDEX1 ON TCOMPUTEDVALUES (TPUUID);

ALTER TABLE TPRIVATEREPORTREPOSITORY ADD TPUUID VARCHAR(36);
CREATE  INDEX TPRIVREPREPINDEX1 ON TPRIVATEREPORTREPOSITORY (TPUUID);

ALTER TABLE TPUBLICREPORTREPOSITORY ADD TPUUID VARCHAR(36);
CREATE  INDEX TPUBREPREPINDEX1 ON TPUBLICREPORTREPOSITORY (TPUUID);

ALTER TABLE TPROJECTREPORTREPOSITORY ADD TPUUID VARCHAR(36);
CREATE  INDEX TPROJREPREPINDEX1 ON TPROJECTREPORTREPOSITORY (TPUUID);

ALTER TABLE TACCOUNT ADD TPUUID VARCHAR(36);
CREATE  INDEX TACCOUNTINDEX1 ON TACCOUNT (TPUUID);

ALTER TABLE TATTACHMENT ADD TPUUID VARCHAR(36);
CREATE  INDEX TATTACHINDEX1 ON TATTACHMENT (TPUUID);

ALTER TABLE TCOST ADD TPUUID VARCHAR(36);
CREATE  INDEX TCOSTINDEX1 ON TCOST (TPUUID);

ALTER TABLE TEFFORTTYPE ADD TPUUID VARCHAR(36);
CREATE  INDEX TEFFORTTYPEINDEX1 ON TEFFORTTYPE (TPUUID);

ALTER TABLE TEFFORTUNIT ADD TPUUID VARCHAR(36);
CREATE  INDEX TEFFORTUNITINDEX1 ON TEFFORTUNIT (TPUUID);

ALTER TABLE TDOCSTATE ADD TPUUID VARCHAR(36);
CREATE  INDEX TDOCSTATEINDEX1 ON TDOCSTATE (TPUUID);

ALTER TABLE TDISABLEFIELD ADD TPUUID VARCHAR(36);
CREATE  INDEX TDISABLEFINDEX1 ON TDISABLEFIELD (TPUUID);

ALTER TABLE TPLISTTYPE ADD TPUUID VARCHAR(36);
CREATE  INDEX TPLISTTYPEINDEX1 ON TPLISTTYPE (TPUUID);

ALTER TABLE TPROJECTTYPE ADD TPUUID VARCHAR(36);
CREATE  INDEX TPROJTYPEINDEX1 ON TPROJECTTYPE (TPUUID);

ALTER TABLE TPSTATE ADD TPUUID VARCHAR(36);
CREATE  INDEX TPSTATEINDEX1 ON TPSTATE (TPUUID);

ALTER TABLE TSITE ADD TPUUID VARCHAR(36);
CREATE  INDEX TSITEINDEX1 ON TSITE (TPUUID);

ALTER TABLE TWORKFLOW ADD TPUUID VARCHAR(36);
CREATE  INDEX TWORKFLOWINDEX1 ON TWORKFLOW (TPUUID);

ALTER TABLE TWORKFLOWROLE ADD TPUUID VARCHAR(36);
CREATE  INDEX TWORKFLOWROLEINDEX1 ON TWORKFLOWROLE (TPUUID);

ALTER TABLE TWORKFLOWCATEGORY ADD TPUUID VARCHAR(36);
CREATE  INDEX TWORKFLOWCATINDEX1 ON TWORKFLOWCATEGORY (TPUUID);

ALTER TABLE TROLELISTTYPE ADD TPUUID VARCHAR(36);
CREATE  INDEX TROLELISTTINDEX1 ON TROLELISTTYPE (TPUUID);

ALTER TABLE TISSUEATTRIBUTEVALUE ADD TPUUID VARCHAR(36);
CREATE  INDEX TISSUEATTINDEX1 ON TISSUEATTRIBUTEVALUE (TPUUID);

ALTER TABLE TATTRIBUTEOPTION ADD TPUUID VARCHAR(36);
CREATE  INDEX TATTOPTINDEX1 ON TATTRIBUTEOPTION (TPUUID);

ALTER TABLE TATTRIBUTECLASS ADD TPUUID VARCHAR(36);
CREATE  INDEX TATTCLASSINDEX1 ON TATTRIBUTECLASS (TPUUID);

ALTER TABLE TATTRIBUTETYPE ADD TPUUID VARCHAR(36);
CREATE  INDEX TATTTYPEINDEX1 ON TATTRIBUTETYPE (TPUUID);

ALTER TABLE TATTRIBUTE ADD TPUUID VARCHAR(36);
CREATE  INDEX TATTRIBUTEINDEX1 ON TATTRIBUTE (TPUUID);

ALTER TABLE TREPORTLAYOUT ADD EXPANDING VARCHAR (1);
ALTER TABLE TREPORTLAYOUT ADD LAYOUTKEY INTEGER;
ALTER TABLE TREPORTLAYOUT ADD TPUUID VARCHAR(36);
CREATE  INDEX TREPORTLAYOUTINDEX1 ON TREPORTLAYOUT (FIELDTYPE);
CREATE  INDEX TREPORTLAYOUTINDEX2 ON TREPORTLAYOUT (LAYOUTKEY);
CREATE  INDEX TREPORTLAYOUTINDEX3 ON TREPORTLAYOUT (TPUUID);

ALTER TABLE TSCHEDULER ADD TPUUID VARCHAR(36);
CREATE  INDEX TSCHEDULERINDEX1 ON TSCHEDULER (TPUUID);

ALTER TABLE TPROJECTACCOUNT ADD TPUUID VARCHAR(36);
CREATE  INDEX TPROJACCINDEX1 ON TPROJECTACCOUNT (TPUUID);

ALTER TABLE TGROUPMEMBER ADD TPUUID VARCHAR(36);
CREATE  INDEX TGROUPMEMINDEX1 ON TGROUPMEMBER (TPUUID);

ALTER TABLE TBUDGET ADD TPUUID VARCHAR(36);
CREATE  INDEX TBUDGETINDEX3 ON TBUDGET (TPUUID);

ALTER TABLE TACTUALESTIMATEDBUDGET ADD TPUUID VARCHAR(36);
CREATE  INDEX TACTUALESTINDEX3 ON TACTUALESTIMATEDBUDGET (TPUUID);

ALTER TABLE TSYSTEMSTATE ADD TPUUID VARCHAR(36);
CREATE  INDEX TSYSTEMSTATEINDEX1 ON TSYSTEMSTATE (TPUUID);

ALTER TABLE TCOSTCENTER ADD TPUUID VARCHAR(36);
CREATE  INDEX TCOSTCENTERINDEX1 ON TCOSTCENTER (TPUUID);

ALTER TABLE TMOTD ADD TPUUID VARCHAR(36);
CREATE  INDEX TMOTDINDEX1 ON TMOTD (TPUUID);

ALTER TABLE TDASHBOARDSCREEN ADD TPUUID VARCHAR(36);
CREATE  INDEX TDBSCREENINDEX1 ON TDASHBOARDSCREEN (TPUUID);

ALTER TABLE TDASHBOARDTAB ADD TPUUID VARCHAR(36);
CREATE  INDEX TDBTABINDEX1 ON TDASHBOARDTAB (TPUUID);

ALTER TABLE TDASHBOARDPANEL ADD TPUUID VARCHAR(36);
CREATE  INDEX TDBPANELINDEX1 ON TDASHBOARDPANEL (TPUUID);

ALTER TABLE TDASHBOARDFIELD ADD TPUUID VARCHAR(36);
CREATE  INDEX TDBFIELDINDEX1 ON TDASHBOARDFIELD (TPUUID);

ALTER TABLE TDASHBOARDPARAMETER ADD TPUUID VARCHAR(36);
CREATE  INDEX TDBPARAMINDEX1 ON TDASHBOARDPARAMETER (TPUUID);

ALTER TABLE TVERSIONCONTROLPARAMETER ADD TPUUID VARCHAR(36);
CREATE  INDEX TVCPARAMINDEX1 ON TVERSIONCONTROLPARAMETER (TPUUID);

ALTER TABLE TFIELD ADD TPUUID VARCHAR(36);
CREATE  INDEX TFIELDINDEX1 ON TFIELD (TPUUID);

ALTER TABLE TFIELDCONFIG ADD TPUUID VARCHAR(36);
CREATE  INDEX TFIELDCONFIGINDEX1 ON TFIELDCONFIG (TPUUID);

ALTER TABLE TROLEFIELD ADD TPUUID VARCHAR(36);
CREATE  INDEX TROLEFIELDINDEX1 ON TROLEFIELD (TPUUID);

ALTER TABLE TCONFIGOPTIONSROLE ADD TPUUID VARCHAR(36);
CREATE  INDEX TCONFIGOPTINDEX1 ON TCONFIGOPTIONSROLE (TPUUID);

ALTER TABLE TTEXTBOXSETTINGS ADD TPUUID VARCHAR(36);
CREATE  INDEX TTEXTBOXCONFINDEX1 ON TTEXTBOXSETTINGS (TPUUID);

ALTER TABLE TGENERALSETTINGS ADD TPUUID VARCHAR(36);
CREATE  INDEX TGENERALCONFINDEX1 ON TGENERALSETTINGS (TPUUID);

ALTER TABLE TLIST ADD TPUUID VARCHAR(36);
CREATE  INDEX TLISTINDEX1 ON TLIST (TPUUID);

ALTER TABLE TOPTION ADD TPUUID VARCHAR(36);
CREATE  INDEX TOPTIONINDEX1 ON TOPTION (TPUUID);

ALTER TABLE TOPTIONSETTINGS ADD TPUUID VARCHAR(36);
CREATE  INDEX TOPTIONCONFINDEX1 ON TOPTIONSETTINGS (TPUUID);

ALTER TABLE TATTRIBUTEVALUE ADD TPUUID VARCHAR(36);
CREATE  INDEX TATTVALUEINDEX1 ON TATTRIBUTEVALUE (TPUUID);

ALTER TABLE TSCREEN ADD TPUUID VARCHAR(36);
CREATE  INDEX TSCREENINDEX1 ON TSCREEN (TPUUID);

ALTER TABLE TSCREENTAB ADD TPUUID VARCHAR(36);
CREATE  INDEX TSCREENTABINDEX1 ON TSCREENTAB (TPUUID);

ALTER TABLE TSCREENPANEL ADD TPUUID VARCHAR(36);
CREATE  INDEX TSCREENPANELINDEX1 ON TSCREENPANEL (TPUUID);

ALTER TABLE TSCREENFIELD ADD TPUUID VARCHAR(36);
CREATE  INDEX TSCREENFIELDINDEX1 ON TSCREENFIELD (TPUUID);

ALTER TABLE TACTION ADD TPUUID VARCHAR(36);
CREATE  INDEX TACTIONINDEX1 ON TACTION (TPUUID);

ALTER TABLE TSCREENCONFIG ADD TPUUID VARCHAR(36);
CREATE  INDEX TSCREENCONFINDEX1 ON TSCREENCONFIG (TPUUID);

ALTER TABLE TINITSTATE ADD TPUUID VARCHAR(36);
CREATE  INDEX TINITSTATEINDEX1 ON TINITSTATE (TPUUID);

ALTER TABLE TEVENT ADD TPUUID VARCHAR(36);
CREATE  INDEX TEVENTINDEX1 ON TEVENT (TPUUID);

ALTER TABLE TCLOB ADD TPUUID VARCHAR(36);
CREATE  INDEX TCLOBINDEX1 ON TCLOB (TPUUID);

ALTER TABLE TNOTIFYFIELD ADD TPUUID VARCHAR(36);
CREATE  INDEX TNOTIFYFIELDINDEX1 ON TNOTIFYFIELD (TPUUID);

ALTER TABLE TNOTIFYTRIGGER ADD TPUUID VARCHAR(36);
CREATE  INDEX TNOTIFYTRIGGERINDEX1 ON TNOTIFYTRIGGER (TPUUID);

ALTER TABLE TNOTIFYSETTINGS ADD TPUUID VARCHAR(36);
CREATE  INDEX TNOTIFYCONFINDEX1 ON TNOTIFYSETTINGS (TPUUID);

ALTER TABLE TQUERYREPOSITORY ADD TPUUID VARCHAR(36);
CREATE  INDEX TQUERYREPINDEX1 ON TQUERYREPOSITORY (TPUUID);

ALTER TABLE TLOCALIZEDRESOURCES ADD TPUUID VARCHAR(36);
CREATE  INDEX TLOCALRESINDEX1 ON TLOCALIZEDRESOURCES (TPUUID);

DROP TABLE TWORKITEMLINK;
CREATE TABLE TWORKITEMLINK
(
    OBJECTID INTEGER NOT NULL,
    LINKISCROSSPROJECT CHAR (1) default 'N',
    LINKPRED INTEGER NOT NULL,
    LINKSUCC INTEGER,
    LINKTYPE INTEGER NOT NULL,
    LINKDIRECTION INTEGER,
    LINKLAG DOUBLE PRECISION,
    LINKLAGFORMAT INTEGER,
    STRINGVALUE1 VARCHAR (255),
    STRINGVALUE2 VARCHAR (255),
    STRINGVALUE3 VARCHAR (255),
    INTEGERVALUE1 INTEGER,
    INTEGERVALUE2 INTEGER,
    INTEGERVALUE3 INTEGER,
    DATEVALUE TIMESTAMP,
    DESCRIPTION VARCHAR (8191),
    EXTERNALLINK VARCHAR (255),
	CHANGEDBY INTEGER,
    LASTEDIT TIMESTAMP,
    TPUUID VARCHAR (36),
    PRIMARY KEY(OBJECTID)
);

CREATE  INDEX TWORKITEMLINKINDEX1 ON TWORKITEMLINK (TPUUID);

DROP TABLE TLINKTYPE;
CREATE TABLE TLINKTYPE
(
    OBJECTID INTEGER NOT NULL,
    NAME VARCHAR (255) NOT NULL,
    REVERSENAME VARCHAR (255),
    LEFTTORIGHTFIRST VARCHAR (255),
    LEFTTORIGHTLEVEL VARCHAR (255),
    LEFTTORIGHTALL VARCHAR (255),
    RIGHTTOLEFTFIRST VARCHAR (255),
    RIGHTTOLEFTLEVEL VARCHAR (255),
    RIGHTTOLEFTALL VARCHAR (255),
    LINKDIRECTION INTEGER,
    LINKTYPEPLUGIN VARCHAR (255),
    MOREPROPS VARCHAR (8191),
    TPUUID VARCHAR (36),
    PRIMARY KEY(OBJECTID)
);

CREATE  INDEX TLINKTYPEINDEX1 ON TLINKTYPE (TPUUID);



ALTER TABLE TLOGGINGLEVEL ADD TPUUID VARCHAR(36);
CREATE  INDEX TLOGLEVELINDEX1 ON TLOGGINGLEVEL (TPUUID);

ALTER TABLE TWORKITEMLOCK ADD TPUUID VARCHAR(36);
CREATE  INDEX TWORKITEMLOCKINDEX1 ON TWORKITEMLOCK (TPUUID);

ALTER TABLE TEXPORTTEMPLATE ADD TPUUID VARCHAR(36);
CREATE  INDEX TEXPOPRTTEMPINDEX1 ON TEXPORTTEMPLATE (TPUUID);

ALTER TABLE TEMAILPROCESSED ADD TPUUID VARCHAR(36);
CREATE  INDEX TEMAILPROCINDEX1 ON TEMAILPROCESSED (TPUUID);

CREATE TABLE TAPPLICATIONCONTEXT
(
    OBJECTID INTEGER NOT NULL,
    LOGGEDFULLUSERS INTEGER,
    LOGGEDLIMITEDUSERS INTEGER,
    REFRESHCONFIGURATION INTEGER default 0 NOT NULL,
    FIRSTTIME INTEGER default 0 NOT NULL,
    MOREPROPS VARCHAR (8191),
    PRIMARY KEY(OBJECTID)
);


--------------------------------------------------------------------------
-- TLOGGEDINUSERS
--------------------------------------------------------------------------


CREATE TABLE TLOGGEDINUSERS
(
    OBJECTID INTEGER NOT NULL,
    NODEADDRESS INTEGER,
    SESSIONID VARCHAR (255),
    LOGGEDUSER INTEGER NOT NULL,
    USERLEVEL INTEGER,
    LASTUPDATE TIMESTAMP,
    MOREPROPS VARCHAR (8191),
    PRIMARY KEY(OBJECTID)
);


--------------------------------------------------------------------------
-- CLUSTERNODE
--------------------------------------------------------------------------


CREATE TABLE CLUSTERNODE
(
    OBJECTID INTEGER NOT NULL,
    NODEADDRESS VARCHAR (40),
    NODEURL VARCHAR (255),
    LASTUPDATE TIMESTAMP,
    MASTERNODE INTEGER default 0,
	RELOADCONFIG INTEGER default 0,
    PRIMARY KEY(OBJECTID)
);

--------------------------------------------------------------------------
-- TENTITYCHANGES
--------------------------------------------------------------------------


CREATE TABLE TENTITYCHANGES
(
    OBJECTID INTEGER NOT NULL,
    ENTITYKEY INTEGER NOT NULL,
    ENTITYTYPE INTEGER NOT NULL,
    CLUSTERNODE INTEGER,
    PRIMARY KEY(OBJECTID)
);

CREATE  INDEX ENTITYCHANGESINDEX1 ON TENTITYCHANGES (ENTITYTYPE);
CREATE  INDEX ENTITYCHANGESINDEX2 ON TENTITYCHANGES (CLUSTERNODE);

--------------------------------------------------------------------------
-- TSUMMARYMAIL
--------------------------------------------------------------------------


CREATE TABLE TSUMMARYMAIL
(
    OBJECTID INTEGER NOT NULL,
    WORKITEM INTEGER NOT NULL,
    PERSONFROM INTEGER NOT NULL,
    FROMADDRESS VARCHAR (255),
    MAILSUBJECT VARCHAR (255),
    WORKITEMLINK VARCHAR (255),
    PERSONTO INTEGER NOT NULL,
    LASTEDIT TIMESTAMP,
    TPUUID VARCHAR (36),
    PRIMARY KEY(OBJECTID)
);

CREATE  INDEX TSUMMARYMAILINDEX1 ON TSUMMARYMAIL (WORKITEM);
CREATE  INDEX TSUMMARYMAILINDEX2 ON TSUMMARYMAIL (PERSONFROM);
CREATE  INDEX TSUMMARYMAILINDEX3 ON TSUMMARYMAIL (PERSONTO);
CREATE  INDEX TSUMMARYMAILINDEX4 ON TSUMMARYMAIL (TPUUID);
--------------------------------------------------------------------------
-- TOUTLINECODE
--------------------------------------------------------------------------


CREATE TABLE TOUTLINECODE
(
    OBJECTID INTEGER NOT NULL,
    PARENTID INTEGER,
    LEVELNO INTEGER NOT NULL,
    LEVELCODE VARCHAR (50) NOT NULL,
    FULLCODE VARCHAR (255) NOT NULL,
    ENTITYID INTEGER NOT NULL,
    OUTLINETEMPLATE INTEGER NOT NULL,
    TPUUID VARCHAR (36),
    PRIMARY KEY(OBJECTID)
);

CREATE  INDEX TOUTLINECODEINDEX1 ON TOUTLINECODE (PARENTID);
CREATE  INDEX TOUTLINECODEINDEX2 ON TOUTLINECODE (ENTITYID);
CREATE  INDEX TOUTLINECODEINDEX3 ON TOUTLINECODE (TPUUID);
--------------------------------------------------------------------------
-- TOUTLINETEMPLATEDEF
--------------------------------------------------------------------------


CREATE TABLE TOUTLINETEMPLATEDEF
(
    OBJECTID INTEGER NOT NULL,
    LEVELNO INTEGER NOT NULL,
    SEQUENCETYPE INTEGER NOT NULL,
    LISTID INTEGER,
    SEQUENCELENGTH INTEGER NOT NULL,
    SEPARATORCHAR VARCHAR (10) NOT NULL,
    OUTLINETEMPLATE INTEGER NOT NULL,
    TPUUID VARCHAR (36),
    PRIMARY KEY(OBJECTID)
);

CREATE  INDEX TOUTLINETEMPLATEDEFINDEX1 ON TOUTLINETEMPLATEDEF (TPUUID);
--------------------------------------------------------------------------
-- TOUTLINETEMPLATE
--------------------------------------------------------------------------


CREATE TABLE TOUTLINETEMPLATE
(
    OBJECTID INTEGER NOT NULL,
    LABEL VARCHAR (255) NOT NULL,
    ENTITYTYPE INTEGER NOT NULL,
    TPUUID VARCHAR (36),
    PRIMARY KEY(OBJECTID)
);

CREATE  INDEX TOUTLINETEMPLATEINDEX1 ON TOUTLINETEMPLATE (TPUUID);

--------------------------------------------------------------------------
-- THISTORYTRANSACTION
--------------------------------------------------------------------------


CREATE TABLE THISTORYTRANSACTION
(
    OBJECTID INTEGER NOT NULL,
    WORKITEM INTEGER NOT NULL,
    CHANGEDBY INTEGER NOT NULL,
    LASTEDIT TIMESTAMP,
    TPUUID VARCHAR (36),
    PRIMARY KEY(OBJECTID)
);

CREATE  INDEX THISTORYTRANSINDEX1 ON THISTORYTRANSACTION (WORKITEM);
CREATE  INDEX THISTORYTRANSINDEX2 ON THISTORYTRANSACTION (CHANGEDBY);
CREATE  INDEX THISTORYTRANSINDEX3 ON THISTORYTRANSACTION (TPUUID);
--------------------------------------------------------------------------
-- TFIELDCHANGE
--------------------------------------------------------------------------


CREATE TABLE TFIELDCHANGE
(
    OBJECTID INTEGER NOT NULL,
    FIELDKEY INTEGER NOT NULL,
    HISTORYTRANSACTION INTEGER NOT NULL,
    NEWTEXTVALUE VARCHAR (255),
    OLDTEXTVALUE VARCHAR (255),
    NEWINTEGERVALUE INTEGER,
    OLDINTEGERVALUE INTEGER,
    NEWDOUBLEVALUE DOUBLE PRECISION,
    OLDDOUBLEVALUE DOUBLE PRECISION,
    NEWDATEVALUE TIMESTAMP,
    OLDDATEVALUE TIMESTAMP,
    NEWCHARACTERVALUE CHAR (1),
    OLDCHARACTERVALUE CHAR (1),
    NEWLONGTEXTVALUE VARCHAR (6000),
    OLDLONGTEXTVALUE VARCHAR (6000),
    NEWSYSTEMOPTIONID INTEGER,
    OLDSYSTEMOPTIONID INTEGER,
    SYSTEMOPTIONTYPE INTEGER,
    NEWCUSTOMOPTIONID INTEGER,
    OLDCUSTOMOPTIONID INTEGER,
    PARAMETERCODE INTEGER,
    VALIDVALUE INTEGER,
    PARENTCOMMENT INTEGER,
    TIMESEDITED INTEGER,
    TPUUID VARCHAR (36),
    PRIMARY KEY(OBJECTID)
);

CREATE  INDEX TFIELDCHANGE1 ON TFIELDCHANGE (FIELDKEY);
CREATE  INDEX TFIELDCHANGE2 ON TFIELDCHANGE (HISTORYTRANSACTION);
CREATE  INDEX TFIELDCHANGE3 ON TFIELDCHANGE (VALIDVALUE);
CREATE  INDEX TFIELDCHANGE4 ON TFIELDCHANGE (TPUUID);

--------------------------------------------------------------------------
-- TSCRIPTS
--------------------------------------------------------------------------


CREATE TABLE TSCRIPTS
(
    OBJECTID INTEGER NOT NULL,
    CHANGEDBY INTEGER,
    LASTEDIT TIMESTAMP,
    SCRIPTVERSION INTEGER,
    ORIGINALVERSION INTEGER,
    PROJECTTYPE INTEGER,
    PROJECT INTEGER,
    SCRIPTTYPE INTEGER,
    CLAZZNAME VARCHAR (253),
    SOURCECODE VARCHAR (8191),
    TPUUID VARCHAR (36),
    PRIMARY KEY(OBJECTID)
);

CREATE  INDEX TSCRIPTINDEX1 ON TSCRIPTS (CLAZZNAME);
CREATE  INDEX TSCRIPTINDEX2 ON TSCRIPTS (PROJECTTYPE);
CREATE  INDEX TSCRIPTINDEX3 ON TSCRIPTS (PROJECT);
CREATE  INDEX TSCRIPTINDEX4 ON TSCRIPTS (TPUUID);
--------------------------------------------------------------------------
-- TREVISION
--------------------------------------------------------------------------


CREATE TABLE TREVISION
(
    OBJECTID INTEGER NOT NULL,
    FILENAME VARCHAR (255) NOT NULL,
    AUTHORNAME VARCHAR (255) NOT NULL,
    CHANGEDESCRIPTION VARCHAR (8191),
    REVISIONDATE TIMESTAMP NOT NULL,
    REVISIONNUMBR VARCHAR (255) NOT NULL,
    REPOSITORYKEY INTEGER NOT NULL,
    TPUUID VARCHAR (36),
    PRIMARY KEY(OBJECTID)
);

CREATE  INDEX TREVISIONINDEX1 ON TREVISION (TPUUID);

--------------------------------------------------------------------------
-- TREVISIONWORKITEMS
--------------------------------------------------------------------------


CREATE TABLE TREVISIONWORKITEMS
(
    OBJECTID INTEGER NOT NULL,
    WORKITEMKEY INTEGER NOT NULL,
    REVISIONKEY INTEGER NOT NULL,
    TPUUID VARCHAR (36),
    PRIMARY KEY(OBJECTID)
);

CREATE  INDEX TREVISIONWORKITEMSINDEX1 ON TREVISIONWORKITEMS (WORKITEMKEY);
CREATE  INDEX TREVISIONWORKITEMSINDEX2 ON TREVISIONWORKITEMS (TPUUID);

--------------------------------------------------------------------------
-- TREPOSITORY
--------------------------------------------------------------------------


CREATE TABLE TREPOSITORY
(
    OBJECTID INTEGER NOT NULL,
    REPOSITORYTYPE VARCHAR (255) NOT NULL,
    REPOSITORYURL VARCHAR (255) NOT NULL,
    STARTDATE TIMESTAMP,
    ENDDATE TIMESTAMP,
    STATUSKEY INTEGER NOT NULL,
    TPUUID VARCHAR (36),
    PRIMARY KEY(OBJECTID)
);

CREATE  INDEX TREPOSITORYINDEX1 ON TREPOSITORY (TPUUID);

--------------------------------------------------------------------------
-- TTEMPLATEPERSON
--------------------------------------------------------------------------


CREATE TABLE TTEMPLATEPERSON
(
    OBJECTID INTEGER NOT NULL,
    REPORTTEMPLATE INTEGER NOT NULL,
    PERSON INTEGER NOT NULL,
    RIGHTFLAG INTEGER,
    TPUUID VARCHAR (36),
    PRIMARY KEY(OBJECTID)
);

CREATE  INDEX TTEMPLATEPERSONINDEX1 ON TTEMPLATEPERSON (TPUUID);

ALTER TABLE TWORKITEMLINK
    ADD CONSTRAINT TWORKITEMLINK_FK_1 FOREIGN KEY (LINKPRED)
    REFERENCES TWORKITEM (WORKITEMKEY)
;

ALTER TABLE TWORKITEMLINK
    ADD CONSTRAINT TWORKITEMLINK_FK_2 FOREIGN KEY (LINKSUCC)
    REFERENCES TWORKITEM (WORKITEMKEY)
;

ALTER TABLE TWORKITEMLINK
    ADD CONSTRAINT TWORKITEMLINK_FK_3 FOREIGN KEY (LINKTYPE)
    REFERENCES TLINKTYPE (OBJECTID)
;

ALTER TABLE TWORKITEMLINK
    ADD CONSTRAINT TWORKITEMLINK_FK_4 FOREIGN KEY (CHANGEDBY)
    REFERENCES TPERSON (PKEY)
;

ALTER TABLE TLOGGEDINUSERS
    ADD CONSTRAINT TLOGGEDINUSERS_FK_1 FOREIGN KEY (LOGGEDUSER)
    REFERENCES TPERSON (PKEY);

ALTER TABLE TLOGGEDINUSERS
    ADD CONSTRAINT TLOGGEDINUSERS_FK_2 FOREIGN KEY (NODEADDRESS)
    REFERENCES CLUSTERNODE (OBJECTID);

ALTER TABLE TENTITYCHANGES
    ADD CONSTRAINT TENTITYCHANGES_FK_1 FOREIGN KEY (CLUSTERNODE)
    REFERENCES CLUSTERNODE (OBJECTID);

ALTER TABLE TSUMMARYMAIL
    ADD CONSTRAINT TSUMMARYMAIL_FK_1 FOREIGN KEY (WORKITEM)
    REFERENCES TWORKITEM (WORKITEMKEY);

ALTER TABLE TSUMMARYMAIL
    ADD CONSTRAINT TSUMMARYMAIL_FK_2 FOREIGN KEY (PERSONFROM)
    REFERENCES TPERSON (PKEY);

ALTER TABLE TSUMMARYMAIL
    ADD CONSTRAINT TSUMMARYMAIL_FK_3 FOREIGN KEY (PERSONTO)
    REFERENCES TPERSON (PKEY);

ALTER TABLE TOUTLINECODE
    ADD CONSTRAINT TOUTLINECODE_FK_1 FOREIGN KEY (OUTLINETEMPLATE)
    REFERENCES TOUTLINETEMPLATE (OBJECTID);

ALTER TABLE TOUTLINETEMPLATEDEF
    ADD CONSTRAINT TOUTLINETEMPLATEDEF_FK_1 FOREIGN KEY (OUTLINETEMPLATE)
    REFERENCES TOUTLINETEMPLATE (OBJECTID);

ALTER TABLE THISTORYTRANSACTION
    ADD CONSTRAINT THISTORYTRANSACTION_FK_1 FOREIGN KEY (WORKITEM)
    REFERENCES TWORKITEM (WORKITEMKEY)
;

ALTER TABLE THISTORYTRANSACTION
    ADD CONSTRAINT THISTORYTRANSACTION_FK_2 FOREIGN KEY (CHANGEDBY)
    REFERENCES TPERSON (PKEY)
;

ALTER TABLE TFIELDCHANGE
    ADD CONSTRAINT TFIELDCHANGE_FK_1 FOREIGN KEY (HISTORYTRANSACTION)
    REFERENCES THISTORYTRANSACTION (OBJECTID)
;

ALTER TABLE TFIELDCHANGE
    ADD CONSTRAINT TFIELDCHANGE_FK_2 FOREIGN KEY (PARENTCOMMENT)
    REFERENCES TFIELDCHANGE (OBJECTID)
;

ALTER TABLE TFIELDCHANGE
    ADD CONSTRAINT TFIELDCHANGE_FK_3 FOREIGN KEY (NEWCUSTOMOPTIONID)
    REFERENCES TOPTION (OBJECTID)
;

ALTER TABLE TFIELDCHANGE
    ADD CONSTRAINT TFIELDCHANGE_FK_4 FOREIGN KEY (OLDCUSTOMOPTIONID)
    REFERENCES TOPTION (OBJECTID)
;

ALTER TABLE TSCRIPTS
    ADD CONSTRAINT TSCRIPTS_FK_1 FOREIGN KEY (CHANGEDBY)
    REFERENCES TPERSON (PKEY)
;

ALTER TABLE TSCRIPTS
    ADD CONSTRAINT TSCRIPTS_FK_2 FOREIGN KEY (PROJECTTYPE)
    REFERENCES TPROJECTTYPE (OBJECTID)
;

ALTER TABLE TSCRIPTS
    ADD CONSTRAINT TSCRIPTS_FK_3 FOREIGN KEY (PROJECT)
    REFERENCES TPROJECT (PKEY)
;

ALTER TABLE TREVISION
    ADD CONSTRAINT TREVISION_FK_1 FOREIGN KEY (REPOSITORYKEY)
    REFERENCES TREPOSITORY (OBJECTID)
;

ALTER TABLE TREVISIONWORKITEMS
    ADD CONSTRAINT TREVISIONWORKITEMS_FK_1 FOREIGN KEY (REVISIONKEY)
    REFERENCES TREVISION (OBJECTID)
;

ALTER TABLE TTEMPLATEPERSON
    ADD CONSTRAINT TTEMPLATEPERSON_FK_1 FOREIGN KEY (PERSON)
    REFERENCES TPERSON (PKEY)
;

ALTER TABLE TTEMPLATEPERSON
    ADD CONSTRAINT TTEMPLATEPERSON_FK_2 FOREIGN KEY (REPORTTEMPLATE)
    REFERENCES TEXPORTTEMPLATE (OBJECTID)
;

ALTER TABLE TCATEGORY ADD ICONKEY INTEGER;
ALTER TABLE TPRIORITY ADD ICONKEY INTEGER;
ALTER TABLE TSEVERITY ADD ICONKEY INTEGER;
ALTER TABLE TSTATE ADD ICONKEY INTEGER;
ALTER TABLE TOPTION ADD ICONKEY INTEGER;
ALTER TABLE TLINKTYPE ADD OUTWARDICONKEY INTEGER;
ALTER TABLE TLINKTYPE ADD INWARDICONKEY INTEGER;
--------------------------------------------------------------------------
-- TBLOB
--------------------------------------------------------------------------

CREATE TABLE TBLOB
(
    OBJECTID INTEGER NOT NULL,
    BLOBVALUE BLOB,
    TPUUID VARCHAR (36),
    PRIMARY KEY(OBJECTID)
);

CREATE  INDEX TBLOBINDEX1 ON TBLOB (TPUUID);


ALTER TABLE TCATEGORY
    ADD CONSTRAINT TCATEGORY_FK_1 FOREIGN KEY (ICONKEY)
    REFERENCES TBLOB (OBJECTID)
;

ALTER TABLE TPRIORITY
    ADD CONSTRAINT TPRIORITY_FK_1 FOREIGN KEY (ICONKEY)
    REFERENCES TBLOB (OBJECTID)
;

ALTER TABLE TSEVERITY
    ADD CONSTRAINT TSEVERITY_FK_1 FOREIGN KEY (ICONKEY)
    REFERENCES TBLOB (OBJECTID)
;

ALTER TABLE TSTATE
    ADD CONSTRAINT TSTATE_FK_1 FOREIGN KEY (ICONKEY)
    REFERENCES TBLOB (OBJECTID)
;

ALTER TABLE TOPTION
    ADD CONSTRAINT TOPTION_FK_2 FOREIGN KEY (ICONKEY)
    REFERENCES TBLOB (OBJECTID)
;

ALTER TABLE TLINKTYPE
    ADD CONSTRAINT TLINKTYPE_FK_1 FOREIGN KEY (OUTWARDICONKEY)
    REFERENCES TBLOB (OBJECTID)
;

ALTER TABLE TLINKTYPE
    ADD CONSTRAINT TLINKTYPE_FK_2 FOREIGN KEY (INWARDICONKEY)
    REFERENCES TBLOB (OBJECTID)
;

ALTER TABLE TPROJECT ADD PREFIX VARCHAR (10);
ALTER TABLE TPROJECT ADD LASTID INTEGER;

CREATE  INDEX TPROJECTINDEXIDPF ON TPROJECT (PREFIX);

ALTER TABLE TWORKITEM ADD IDNUMBER INTEGER;

CREATE  INDEX TWIINDEX21 ON TWORKITEM (IDNUMBER);

COMMIT;

INSERT INTO ID_TABLE (ID_TABLE_ID, TABLE_NAME, NEXT_ID, QUANTITY) VALUES(90, 'TAPPLICATIONCONTEXT', 1, 1);
INSERT INTO ID_TABLE (ID_TABLE_ID, TABLE_NAME, NEXT_ID, QUANTITY) VALUES(91, 'TLOGGEDINUSERS', 1, 1);
INSERT INTO ID_TABLE (ID_TABLE_ID, TABLE_NAME, NEXT_ID, QUANTITY) VALUES(92, 'TEMAILCONNECTIONPOINT', 1, 1);
INSERT INTO ID_TABLE (ID_TABLE_ID, TABLE_NAME, NEXT_ID, QUANTITY) VALUES(93, 'CLUSTERNODE', 1, 1);
INSERT INTO ID_TABLE (ID_TABLE_ID, TABLE_NAME, NEXT_ID, QUANTITY) VALUES(94, 'TSUMMARYMAIL', 1, 1);
INSERT INTO ID_TABLE (ID_TABLE_ID, TABLE_NAME, NEXT_ID, QUANTITY) VALUES(95, 'TOUTLINECODE', 1, 1);
INSERT INTO ID_TABLE (ID_TABLE_ID, TABLE_NAME, NEXT_ID, QUANTITY) VALUES(96, 'TOUTLINETEMPLATEDEF', 1, 1);
INSERT INTO ID_TABLE (ID_TABLE_ID, TABLE_NAME, NEXT_ID, QUANTITY) VALUES(97, 'TOUTLINETEMPLATE', 1, 1);
INSERT INTO ID_TABLE (ID_TABLE_ID, TABLE_NAME, NEXT_ID, QUANTITY) VALUES(98, 'THISTORYTRANSACTION', 1, 1);
INSERT INTO ID_TABLE (ID_TABLE_ID, TABLE_NAME, NEXT_ID, QUANTITY) VALUES(99, 'TFIELDCHANGE', 1, 1);
INSERT INTO ID_TABLE (ID_TABLE_ID, TABLE_NAME, NEXT_ID, QUANTITY) VALUES(100, 'TSCRIPTS', 1, 1);
INSERT INTO ID_TABLE (ID_TABLE_ID, TABLE_NAME, NEXT_ID, QUANTITY) VALUES(101, 'TREVISION', 1, 1);
INSERT INTO ID_TABLE (ID_TABLE_ID, TABLE_NAME, NEXT_ID, QUANTITY) VALUES(102, 'TREVISIONWORKITEMS', 1, 1);
INSERT INTO ID_TABLE (ID_TABLE_ID, TABLE_NAME, NEXT_ID, QUANTITY) VALUES(103, 'TREPOSITORY', 1, 1);
INSERT INTO ID_TABLE (ID_TABLE_ID, TABLE_NAME, NEXT_ID, QUANTITY) VALUES(104, 'TTEMPLATEPERSON', 1, 1);
INSERT INTO ID_TABLE (ID_TABLE_ID, TABLE_NAME, NEXT_ID, QUANTITY) VALUES(105, 'TBLOB', 1, 1);

INSERT INTO TFIELD (OBJECTID, NAME, FIELDTYPE, DEPRECATED, ISCUSTOM, REQUIRED)
			VALUES (25, 'ArchiveLevel', 'com.aurel.track.fieldType.types.system.text.SystemArchiveLevel', 'N', 'N', 'N');
INSERT INTO TFIELDCONFIG(OBJECTID, FIELDKEY, LABEL, TOOLTIP, REQUIRED)
			VALUES (25, 25, 'ArchiveLevel', 'ArchiveLevel', 'N');
INSERT INTO TFIELD (OBJECTID, NAME, FIELDTYPE, DEPRECATED, ISCUSTOM, REQUIRED)
			VALUES (26, 'SubmitterEmail', 'com.aurel.track.fieldType.types.system.text.SystemSubmitterEmail', 'N', 'N', 'N');
INSERT INTO TFIELDCONFIG(OBJECTID, FIELDKEY, LABEL, TOOLTIP, REQUIRED)
			VALUES (26, 26, 'SubmitterEmail', 'SubmitterEmail', 'N');

INSERT INTO TLINKTYPE (OBJECTID, NAME, REVERSENAME, LEFTTORIGHTFIRST, RIGHTTOLEFTFIRST, LINKDIRECTION, LINKTYPEPLUGIN) 
	VALUES	(1, 'duplicate of', 'duplicated by', 'duplicates of these issues', 'duplicated by these issues', 3, 'com.aurel.track.linkType.GenericLinkType');
INSERT INTO TLINKTYPE (OBJECTID, NAME, REVERSENAME, LEFTTORIGHTFIRST, RIGHTTOLEFTFIRST, LINKDIRECTION, LINKTYPEPLUGIN) 
	VALUES	(2, 'test case for', 'verified by', 'test cases for these issues', 'verified by these issues', 3, 'com.aurel.track.linkType.GenericLinkType');
commit;