ALTER TABLE TMAILTEMPLATEDEF DROP MAILBODY;
ALTER TABLE TMAILTEMPLATEDEF ADD MAILBODY BLOB SUB_TYPE TEXT;
UPDATE TWORKITEM SET SUPERIORWORKITEM=null WHERE WORKITEMKEY IN 
(SELECT a.WORKITEMKEY FROM TWORKITEM a LEFT JOIN TWORKITEM b ON a.SUPERIORWORKITEM=b.WORKITEMKEY WHERE a.SUPERIORWORKITEM IS NOT NULL and b.WORKITEMKEY IS NULL);
ALTER TABLE TWORKITEM
    ADD CONSTRAINT TWORKITEM_FK_14 FOREIGN KEY (SUPERIORWORKITEM)
    REFERENCES TWORKITEM (WORKITEMKEY);