ALTER TABLE TCATEGORY ADD TYPEFLAG INTEGER;
ALTER TABLE TSTATE ADD PERCENTCOMPLETE INTEGER;
ALTER TABLE TWORKFLOW ADD RESPONSIBLE INTEGER;
ALTER TABLE TREPORTLAYOUT ADD QUERYID INTEGER;
ALTER TABLE TREPORTLAYOUT ADD QUERYTYPE INTEGER;
 
CREATE INDEX TREPORTLAYOUTINDEX4 ON TREPORTLAYOUT (QUERYID);

ALTER TABLE TDASHBOARDSCREEN ADD PROJECT INTEGER;
ALTER TABLE TDASHBOARDSCREEN ADD ENTITYTYPE INTEGER;

CREATE TABLE TRECURRENCEPATTERN
(
    OBJECTID INTEGER NOT NULL,
    RECURRENCEPERIOD INTEGER NOT NULL,
    PARAM1 INTEGER,
    PARAM2 INTEGER,
    PARAM3 INTEGER,
    DAYS VARCHAR(255),
    DATEISABSOLUTE CHAR(1) default 'Y',
    STARTDATE TIMESTAMP,
    ENDDATE TIMESTAMP,
    OCCURENCETYPE INTEGER,
    NOOFOCCURENCES INTEGER,
    TPUUID VARCHAR(36),
    PRIMARY KEY (OBJECTID)
);
CREATE INDEX TRECURRENCEPATTERNINDEX1 ON TRECURRENCEPATTERN (TPUUID);


-----------------------------------------------------------------------------
-- TREPORTPERSONSETTINGS
-----------------------------------------------------------------------------
-- DROP TABLE TREPORTPERSONSETTINGS CASCADE;



CREATE TABLE TREPORTPERSONSETTINGS
(
    OBJECTID INTEGER NOT NULL,
    PERSON INTEGER NOT NULL,
    RECURRENCEPATTERN INTEGER,
    REPORTTEMPLATE INTEGER NOT NULL,
    TPUUID VARCHAR(36),
    PRIMARY KEY (OBJECTID)
);
CREATE INDEX TREPORTPERSONSETTINGSINDEX1 ON TREPORTPERSONSETTINGS (TPUUID);




-----------------------------------------------------------------------------
-- TREPORTPARAMETER
-----------------------------------------------------------------------------
-- DROP TABLE TREPORTPARAMETER CASCADE;



CREATE TABLE TREPORTPARAMETER
(
    OBJECTID INTEGER NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    PARAMVALUE VARCHAR(10000),
    REPORTPERSONSETTINGS INTEGER NOT NULL,
    TPUUID VARCHAR(36),
    PRIMARY KEY (OBJECTID)
);
CREATE INDEX TREPORTPARAMETERINDEX1 ON TREPORTPARAMETER (TPUUID);




-----------------------------------------------------------------------------
-- TMSPROJECTTASK
-----------------------------------------------------------------------------
-- DROP TABLE TMSPROJECTTASK CASCADE;



CREATE TABLE TMSPROJECTTASK
(
    OBJECTID INTEGER NOT NULL,
    WORKITEM INTEGER NOT NULL,
    UNIQUEID INTEGER NOT NULL,
    TASKTYPE INTEGER NOT NULL,
    CONTACT VARCHAR(100),
    WBS VARCHAR(100),
    OUTLINENUMBER VARCHAR(100),
    DURATION VARCHAR(100),
    DURATIONFORMAT INTEGER,
    ESTIMATED CHAR(1) default 'N',
    MILESTONE CHAR(1) default 'N',
    SUMMARY CHAR(1) default 'N',
    ACTUALDURATION VARCHAR(100),
    REMAININGDURATION VARCHAR(100),
    CONSTRAINTTYPE INTEGER,
    CONSTRAINTDATE TIMESTAMP,
    DEADLINE TIMESTAMP,
    TPUUID VARCHAR(36),
    PRIMARY KEY (OBJECTID)
);
CREATE INDEX TMSPROJECTTASKINDEX1 ON TMSPROJECTTASK (TPUUID);




-----------------------------------------------------------------------------
-- TMSPROJECTEXCHANGE
-----------------------------------------------------------------------------
-- DROP TABLE TMSPROJECTEXCHANGE CASCADE;



CREATE TABLE TMSPROJECTEXCHANGE
(
    OBJECTID INTEGER NOT NULL,
    EXCHANGEDIRECTION INTEGER NOT NULL,
    ENTITYID INTEGER NOT NULL,
    ENTITYTYPE INTEGER NOT NULL,
    FILENAME VARCHAR(255),
    FILECONTENT TEXT,
    CHANGEDBY INTEGER,
    LASTEDIT TIMESTAMP,
    TPUUID VARCHAR(36),
    PRIMARY KEY (OBJECTID)
);
CREATE INDEX TMSPROJECTEXCHANGEINDEX1 ON TMSPROJECTEXCHANGE (TPUUID);


----------------------------------------------------------------------
-- TMSPROJECTEXCHANGE
----------------------------------------------------------------------


ALTER TABLE TWORKFLOW
    ADD CONSTRAINT TWORKFLOW_FK_4 FOREIGN KEY (RESPONSIBLE)
    REFERENCES TPERSON (PKEY)
;

ALTER TABLE TDASHBOARDSCREEN
    ADD CONSTRAINT TDASHBOARDSCREEN_FK_2 FOREIGN KEY (PROJECT)
    REFERENCES TPROJECT (PKEY)
;

----------------------------------------------------------------------
-- TRECURRENCEPATTERN
----------------------------------------------------------------------


ALTER TABLE TREPORTPERSONSETTINGS
    ADD CONSTRAINT TREPORTPERSONSETTINGS_FK_1 FOREIGN KEY (PERSON)
    REFERENCES TPERSON (PKEY)
;
ALTER TABLE TREPORTPERSONSETTINGS
    ADD CONSTRAINT TREPORTPERSONSETTINGS_FK_2 FOREIGN KEY (RECURRENCEPATTERN)
    REFERENCES TRECURRENCEPATTERN (OBJECTID)
;
ALTER TABLE TREPORTPERSONSETTINGS
    ADD CONSTRAINT TREPORTPERSONSETTINGS_FK_3 FOREIGN KEY (REPORTTEMPLATE)
    REFERENCES TEXPORTTEMPLATE (OBJECTID)
;

----------------------------------------------------------------------
-- TREPORTPERSONSETTINGS
----------------------------------------------------------------------


ALTER TABLE TREPORTPARAMETER
    ADD CONSTRAINT TREPORTPARAMETER_FK_1 FOREIGN KEY (REPORTPERSONSETTINGS)
    REFERENCES TREPORTPERSONSETTINGS (OBJECTID)
;

----------------------------------------------------------------------
-- TREPORTPARAMETER
----------------------------------------------------------------------


ALTER TABLE TMSPROJECTTASK
    ADD CONSTRAINT TMSPROJECTTASK_FK_1 FOREIGN KEY (WORKITEM)
    REFERENCES TWORKITEM (WORKITEMKEY)
;

----------------------------------------------------------------------
-- TMSPROJECTTASK
----------------------------------------------------------------------


ALTER TABLE TMSPROJECTEXCHANGE
    ADD CONSTRAINT TMSPROJECTEXCHANGE_FK_1 FOREIGN KEY (CHANGEDBY)
    REFERENCES TPERSON (PKEY)
;

INSERT INTO ID_TABLE (ID_TABLE_ID, TABLE_NAME, NEXT_ID, QUANTITY) VALUES(106, 'TRECURRENCEPATTERN', 1, 1);
INSERT INTO ID_TABLE (ID_TABLE_ID, TABLE_NAME, NEXT_ID, QUANTITY) VALUES(107, 'TREPORTPERSONSETTINGS', 1, 1);
INSERT INTO ID_TABLE (ID_TABLE_ID, TABLE_NAME, NEXT_ID, QUANTITY) VALUES(108, 'TREPORTPARAMETER', 1, 1);
INSERT INTO ID_TABLE (ID_TABLE_ID, TABLE_NAME, NEXT_ID, QUANTITY) VALUES(109, 'TMSPROJECTTASK', 1, 1);
INSERT INTO ID_TABLE (ID_TABLE_ID, TABLE_NAME, NEXT_ID, QUANTITY) VALUES(110, 'TMSPROJECTEXCHANGE', 1, 1);

INSERT INTO TCATEGORY (PKEY, LABEL, TYPEFLAG, SORTORDER, SYMBOL, TPUUID) VALUES (-1,'Task',1,-3,'task.gif','8e2216df-370c-446e-9348-a20936854b49');
INSERT INTO TCATEGORY (PKEY, LABEL, TYPEFLAG, SORTORDER, SYMBOL, TPUUID) VALUES (-2,'Sprint',2,-2,'sprint.gif','f150b9e8-55da-4ab7-95bd-0d19e8cceb46');
INSERT INTO TCATEGORY (PKEY, LABEL, TYPEFLAG, SORTORDER, SYMBOL, TPUUID) VALUES (-3,'Meeting',3,-1,'meeting.gif', '9ca87dc7-cf62-41a3-bce1-e13d0f5046e1');
