ALTER TABLE TCATEGORY ALTER COLUMN LABEL TYPE VARCHAR(255);
ALTER TABLE TDEPARTMENT ALTER COLUMN LABEL TYPE VARCHAR(255);
ALTER TABLE TPERSON ADD SUBSTITUTEKEY INTEGER;
ALTER TABLE TPERSON ADD SUBSTITUTEACTIVE CHAR (1) default 'N';
ALTER TABLE TPRIORITY ALTER COLUMN LABEL TYPE VARCHAR(255);
ALTER TABLE TPROJECT ALTER COLUMN LABEL TYPE VARCHAR(255);
ALTER TABLE TRELEASE ALTER COLUMN LABEL TYPE VARCHAR(255);
ALTER TABLE TROLE ALTER COLUMN LABEL TYPE VARCHAR(255);
ALTER TABLE TSEVERITY ALTER COLUMN LABEL TYPE VARCHAR(255);
ALTER TABLE TSTATE ALTER COLUMN LABEL TYPE VARCHAR(255);
ALTER TABLE TWORKITEM ALTER COLUMN PACKAGESYNOPSYS TYPE VARCHAR (255);
ALTER TABLE TPROJECTTYPE ALTER COLUMN LABEL TYPE VARCHAR(255);
ALTER TABLE TSITE DROP COLUMN LICENSEKEY;
ALTER TABLE TSITE DROP COLUMN EXECUTABLE1;
ALTER TABLE TSITE DROP COLUMN EXECUTABLE2;
ALTER TABLE TSITE ALTER COLUMN LICENSEEXT TYPE VARCHAR(512);
ALTER TABLE TSCREENFIELD ADD HIDELABEL CHAR (1) default 'N';
ALTER TABLE TPERSON
    ADD CONSTRAINT TPERSON_FK_4 FOREIGN KEY (SUBSTITUTEKEY)
    REFERENCES TPERSON (PKEY);